### ISSUE TITLE
always signed by gnupg/smime

### ISSUE THREAD

**Issue by supervisitor** [k9mail/k-9#3985] opened 2019-03-26 13:02 UTC
### Expected behavior
Tell us what should happen

with every new mail in K9mail I have to enable "enable sign-only" ... there should be a switch at preferences to do this automatically. this was given in a earlier version. no problem to type in the password every time initially, but a problem to forget signing 

### Actual behavior
Tell us what happens instead

with every mail in K9mail I have to enable at menu "enabled PGP sign-only" from menu, default this is disabled 

### Steps to reproduce
1.go into account with identity with GPG key 
2.press compose new mail
3.there is not signing enabled, you have to do this manually from menu 

### Environment
K-9 Mail version: 5.600

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2019-03-26 23:02
Duplicate of #2375

**Closed by cketti** 2019-03-26 23:02 UTC
