### ISSUE TITLE
Unread count no longer passed to launcher

### ISSUE THREAD

**Issue by OlyAndy** [k9mail/k-9#4445] opened 2020-01-12 23:54 UTC
### Expected behavior
Launcher via tesla unread (nova launcher) displays unread count

### Actual behavior
It doesn't - it does work in 5.6

### Environment
K-9 Mail version: 5.7xx

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2020-01-12 23:56
Duplicate of #4410

**Closed by cketti** 2020-01-12 23:56 UTC
