### ISSUE TITLE
Authentication failed with password which contains _ and -

### ISSUE THREAD

**Issue by Andy1978** [k9mail/k-9#1439] opened 2016-06-05 17:42 UTC
K-9 Mail Version: 5.008 (installed via F-Droid)

logfile: [k9-log.txt](https://github.com/k9mail/k-9/files/299437/k9-log.txt)

Account creation in k9mail fails for some passwords. The password for the account creation attempt from the attached logfile was "noYUW2ipsM_sS-7CQQ4-" without the quotes. If I use a 20 char password without '_' and '-' it works. I also had the same problem with "RPP-5AwqY5sDWdRo_3C7"
### Steps to reproduce

1.) Setup a mail server with postfix and dovecot. Use "doveadm pw -V -s SHA512-CRYPT" and one of the passwords to create hash and add it to your passwords db, reload dovecot. Activate SSL, STARTTLS
2.) Start k9mail on android, create new account, add email adress, imap server, STARTTLS -> Authentication failure
### Environment

K-9 Mail version: 5.008
Android version:4.3.1
Account type IMAP

Please let me know if you need further debugging infos,
Andy

**Comment by philipwhiuk** [comment] 2016-06-06 08:55
Possible duplicate of #1015

**Closed** 2019-02-28 20:09 UTC

**Comment by Andy1978** [comment] 2019-03-01 07:38
Why has this been closed? This is not a duplicate of the possible encoding problem. The chars _ and - are representable in 7bit ASCII (and doesn't have another representation for example in UTF-8)

**Comment by cketti** [comment] 2019-03-01 14:37
We're not doing anything special with those characters. My password contains these and works fine with K-9 Mail. There's most likely something else going on that we might as well track under #1015.

**Comment by Andy1978** [comment] 2019-03-01 16:32
If this is the case you can ask for some additional infos, give some hints, suggest to reduce the password length and not close this after almost 2.5 years without even mentioning why.

**Comment by philipwhiuk** [comment] 2019-03-01 17:07
> Possible duplicate of #1015

Right there.
