### ISSUE TITLE
wrong handling of IMAP (virtual) folders on gmail account

### ISSUE THREAD

**Issue by mpaolo** [k9mail/k-9#2030] opened 2017-01-10 17:00 UTC
I have a number of folders in gmail account, both 'actual' (done e.g. via a MUA like Thunderbird) and 'virtual' (aka labels) defined by filters, thus created on the fly by gmail.
Such are 'custom' folders/labels, beside the 'system' ones.
My gmail UI lang is Italian, if that matters
k9 seems to duplicate both system and custom folders as "[imap]/label"
 
### Expected behavior
no new folders/labels should appear, and e.g. 
- 'trash can' should move email in gmail's 'trash', 
- 'send' should copy in gmail's 'sent' 
- 'save as draft' should save in gmail's 'drafts'
etc rather than create new folders

### Actual behavior
k9 seems to duplicate both system and custom folders as "[imap]/label", e.g. in browser gmail view I get, after using k9:

[Imap]/Bozze
[Imap]/Cestino
[Imap]/Posta inviata
[Imap]/Sent
[Imap]/Trash

beside (below) the 'original' ones, e.g. these 'system' folders:

Posta inviata [= 'sent']
Bozze (67) [= 'drafts']
Cestino [= 'trash']

### Steps to reproduce
just use it - send, receive, trash etc emails 

### Environment
K-9 Mail version: 5.201

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): gmail

**Comment by philipwhiuk** [comment] 2017-01-10 22:30
Duplicate of #752

**Closed by philipwhiuk** 2017-01-10 22:30 UTC
