### ISSUE TITLE
Can't create html signature?

### ISSUE THREAD

**Issue by vasyun** [k9mail/k-9#2942] opened 2017-11-16 15:52 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I create and save signature for new mail. Signature is HTML format. I use html tags <b>,<br>,<p style>,<i> and other....

### Actual behavior
Mail sending with signature like plain-text, not like HTML. Add this feature please!

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.208

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment] 2017-11-16 16:27
Duplicate of #794

**Closed by cketti** 2017-11-16 16:27 UTC
