### ISSUE TITLE
IOException with exchange2013.df.eu

### ISSUE THREAD

**Issue by TRILOS** [k9mail/k-9#2577] opened 2017-06-09 11:35 UTC
### Expected behavior
new account with familiar settings should sync with exchange2013.df.eu of popular provider Domainfactory

### Actual behavior
Error:
"Einrichtung konnte nicht abgeschlossen werden
------
Kann nicht mit dem Server verbinden.
(IOException)

### Steps to reproduce
1. Insert credentiasl, adjust settings as usual, ignored extended settings
2. Verified settings with hotline support of Domainfactory, see also https://www.df.eu/de/support/df-faq/e-mail/managedexchange/mobile-endgeraete/

K9 error mail see below. Note; The server name is correct. Adding https:// (like on Blackberrys) is not possible.

### Environment
K-9 Mail version:
5.206

Android version:
Galaxy S8, Android 7

Account type (IMAP, POP3, WebDAV/Exchange):
Exchange

K9-Mail version: 5.206
Device make: samsung
Device model: SM-G950F
Android version: 7.0

com.fsck.k9.mail.MessagingException: IOException
 at com.fsck.k9.mail.store.webdav.WebDavStore.doInitialConnection(WebDavStore.java:732)
 at com.fsck.k9.mail.store.webdav.WebDavStore.authenticate(WebDavStore.java:631)
 at com.fsck.k9.mail.store.webdav.WebDavStore.sendRequest(WebDavStore.java:999)
 at com.fsck.k9.mail.store.webdav.WebDavStore.processRequest(WebDavStore.java:1091)
 at com.fsck.k9.mail.store.webdav.WebDavStore.processRequest(WebDavStore.java:1066)
 at com.fsck.k9.mail.store.webdav.WebDavFolder.getMessageCount(WebDavFolder.java:159)
 at com.fsck.k9.mail.store.webdav.WebDavFolder.getMessageCount(WebDavFolder.java:173)
 at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:855)
 at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
 at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
 at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
 at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
 at java.lang.Thread.run(Thread.java:762)
Caused by: java.io.IOException: Error with code 404 during request processing: HTTP/1.1 404 Not Found
 at com.fsck.k9.mail.store.webdav.WebDavStore.doInitialConnection(WebDavStore.java:726)
 ... 12 more

**Comment by philipwhiuk** [comment] 2017-06-09 17:15
Exchange 2013 doesn't support WebDAV.

Duplicate of #606

**Closed by philipwhiuk** 2017-06-09 17:15 UTC
