### ISSUE TITLE
long icon press shortcut

### ISSUE THREAD

**Issue by 532910** [k9mail/k-9#3919] opened 2019-02-15 10:15 UTC
Please add support for icon press shortcut
https://developer.android.com/guide/topics/ui/shortcuts/

I'd like to see new letter shortcut in that list.

**Comment by philipwhiuk** [comment] 2019-02-22 14:59
Duplicate of #2145

**Closed by philipwhiuk** 2019-02-22 14:59 UTC

**Comment by 532910** [comment] 2019-02-22 15:04
Sorry!
