### ISSUE TITLE
Closing in PGP messages

### ISSUE THREAD

**Issue by fabianski7** [k9mail/k-9#4624] opened 2020-03-22 21:48 UTC
### Expected behavior
not close?

### Actual behavior
Every time I open an encrypted message the k9 closes.

### Steps to reproduce
1. Unlock openkeychain
2. Go to k-9
3. Open open an encrypted message
4. broken

### Environment
K-9 Mail version: 5.707 (f-droid)
Android version: 10
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

[logs](https://0bin.net/paste/zfCWN4h2lsBDhSp3#27gqpW-yLUniRIsqbb6i9BxNgw/ZMavfioRTQohXJNg)

**Comment by cketti** [comment] 2020-03-23 15:15
K-9 Mail uses Android's `WebView` component to display messages. Your log contains the error "Failed to load WebView provider: No WebView installed".
I fail to see how encrypted messages and/or OpenKeychain could cause this. I would expect displaying any message would lead to this crash.

**Comment by cketti** [comment] 2020-03-31 12:48
Closing because it's not clear what the problem is exactly and there was no additional information provided.

**Closed by cketti** 2020-03-31 12:48 UTC

**Comment by fabianski7** [comment] 2020-03-31 18:37
Hi, sorry for the delay. I really didn't see the notification.

You're right, the problem was with the webview. My rom didn't have any installed.

thanks.
