### ISSUE TITLE
reply causes crash

### ISSUE THREAD

**Issue by schmitzkr** [k9mail/k-9#5121] opened 2021-02-05 16:09 UTC
When I open a message, and click reply, the app crashes.

**To Reproduce**
1. Open app and switch to desired account
2. Open an old read message
3. Click reply icon and then 'reply'
4. App closes/crashes

**Expected behavior**
Expect a new message composition screen, that contains the original message as a reply.

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: 5.726
 - Android version: 11
 - Device: Google Pixel 4
 - Account type: IMAP

**Additional context**
I am using Niagara launcher on Android, I am not sure if this may be causing the issue.

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
[k9-log.txt](https://github.com/k9mail/k-9/files/5934002/k9-log.txt)

**Comment by cketti** [comment] 2021-02-05 16:19
5.718 is quite old. Please try again with the latest beta version.

**Comment by schmitzkr** [comment] 2021-02-05 16:23
that was a typo, it was actually 5.726, updated description.

**Comment by cketti** [comment] 2021-02-06 06:02
Duplicate of #4865

**Closed by cketti** 2021-02-06 06:02 UTC
Labels: bug
