### ISSUE TITLE
Cannet get my Gmail mails

### ISSUE THREAD

**Issue by sebma** [k9mail/k-9#4099] opened 2019-07-06 11:26 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
K-9 should be able to fetch Gmail emails just like Thunderbird does (proposing a first time authentication popup to allow Thunderbird to read the mail).

### Actual behavior
Authentication failed for .....@gmail. Update your server settings.

### Steps to reproduce
1.Setup a Gmail account
2.Read the Gmail Inbox

### Environment
K-9 Mail version: 5.600

Android version: 5.0 on Galaxy Note 3

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

Can you please update your wiki for Android devices that don't have the `pgrep` tool like my Galaxy Note 3 : 
```sh
$ adb shell pgrep k9
/system/bin/sh: pgrep: not found
$ adb shell ps | grep k9
u0_a241   4793  313   2197864 125896 ffffffff 00000000 S com.fsck.k9
```

Here is what log I get : 
```sh
$ adb logcat -d --pid=4793 | tee k9-log_issue#4099.txt
- waiting for device -
```

Therefore, the file `k9-log_issue#4099.txt` is empty : 
```sh
$ du -b k9-log_issue#4099.txt 
0	k9-log_issue#4099.txt
```

**Comment by yoshimo** [comment] 2019-08-04 16:19
Isn't that a duplicate of https://github.com/k9mail/k-9/issues/655 ?

**Closed** 2019-10-12 19:58 UTC
