### ISSUE TITLE
Include sent emails to message chain 

### ISSUE THREAD

**Issue by fedorov-s-n** [k9mail/k-9#1710] opened 2016-10-12 10:32 UTC
There's a possibility to group messages into message chains and display them as a single entry in a list. When user taps on message chain input messages from selected group are shown. It would be more comfortable if sent messages were displayed too, allowing user to look over the whole conversation. Such behavior is already implemented in TypeApp - another Android mail client. 

### Expected behavior
After tap to message chain all emails with selected subject are displayed independent of folder they are placed to. 

### Actual behavior
After tap to message chain only inbox emails with selected subject are displayed. 

### Steps to reproduce
  1. Go to inbox 
  2. Tap to any message chain 
  3. Look for sent emails 

### Environment
K-9 Mail version:
5.010
Android version:
5.1
Account type (IMAP, POP3, WebDAV/Exchange):
Imap

**Comment by philipwhiuk** [comment] 2016-10-12 12:17
Duplicate of #735

**Closed by philipwhiuk** 2016-10-12 12:17 UTC
