### ISSUE TITLE
Please support Multi-Window mode on Android 7.0 +

### ISSUE THREAD

**Issue by jd-boyd** [k9mail/k-9#2594] opened 2017-06-19 18:32 UTC
### Expected behavior

When in k-9 mail, and performing a long press on the Overview button, then selecting a second application to appear next to k-9 mail (such as Chrome) should result in having k-9 mail and that application side by side with no errors or warnings. 

### Actual behavior

When in k-9 mail, and performing a long press on the Overview button, when the screen splits and the option to select the second applcation appears on the right (as expected), there is a warning that appears on k-9 mail "App may not work with split-screen". 

### Steps to reproduce
1. In k-9 mail, built from master (72af527db083327e871d9ef80b02c31ac3b799f1), running on Android 7.0 or newer, perform a long press on the Overview button.
2. See warning appear on k-9 mail.

### Environment
K-9 Mail version: 5.207, also seen in master (72af527db083327e871d9ef80b02c31ac3b799f1)

Android version:7.0 on Nvidia Shield K1, SHIELD tablet software version 5.2 (24.29.303.153)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by jd-boyd** [comment] 2017-06-19 18:33
@lbdroid in issue 2570 stated: "k9mail will work in both split screen and floating window modes that are implemented using the GENUINE multi-display modes built into Android." 

However, it appears that this application attribute isn't set in the manifest, so it should be very simple to fix, I hope.

**Comment by philipwhiuk** [comment] 2017-06-20 00:03
Duplicate of #781

**Closed by philipwhiuk** 2017-06-20 00:03 UTC
