### ISSUE TITLE
[FEATURE REQUEST] Per account quiet time or sync time

### ISSUE THREAD

**Issue by luken-dev** [k9mail/k-9#4187] opened 2019-09-06 06:59 UTC
### Expected behavior
I have multiple email accounts I use K9 for, one of them being work email. For this particular account I would only want to be notified of new emails only during my working hours.

Two ways of approaching this:
- implement per account quiet time, allowing to set notification time, or disabling notifications completely (same options as in global notification settings)
- implement per account syncing time, i.e. email only gets fetched between specified hours

### Actual behavior
At the moment it's all or nothing. All email gets synced, and notifications are shown for all emails regardless of the email account.

### Steps to reproduce
Does not apply

### Environment
K-9 Mail version:
5.6000

Android version:
9

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment] 2019-09-15 13:45
Duplicate of #993

**Closed by cketti** 2019-09-15 13:45 UTC
