### ISSUE TITLE
RuntimeException: Parcel android.os.Parcel@ad26d578: Unmarshalling unknown type code 2131492893 at offset 1352

### ISSUE THREAD

**Issue by lingling-fan** [k9mail/k-9#2755] opened 2017-09-11 06:16 UTC
//package name: com.fsck.k9
//version: 5.205
//target sdk version: android-18
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9.debug/com.fsck.k9.activity.setup.AccountSetupBasics}: java.lang.RuntimeException: Parcel android.os.Parcel@ad26d578: Unmarshalling unknown type code 2131492893 at offset 1352
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@ad26d578: Unmarshalling unknown type code 2131492893 at offset 1352
 	at android.os.Parcel.readValue(Parcel.java:2038)
 	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2284)
 	at android.os.Parcel.readSparseArray(Parcel.java:1693)
 	at android.os.Parcel.readValue(Parcel.java:2028)
 	at android.os.Parcel.readMapInternal(Parcel.java:2255)
 	at android.os.Bundle.unparcel(Bundle.java:223)
 	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1237)
 	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1644)
 	at android.app.Activity.onRestoreInstanceState(Activity.java:938)
 	at com.fsck.k9.activity.setup.AccountSetupBasics.onRestoreInstanceState(AccountSetupBasics.java:124)
 	at android.app.Activity.performRestoreInstanceState(Activity.java:910)
 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)

**Comment by philipwhiuk** [comment] 2017-09-11 09:50
Duplicate of #2380

Released in 5.206, please update.

**Comment by philipwhiuk** [comment] 2017-09-11 09:53
Can you describe what you were doing when this occurred?

**Comment by cketti** [comment] 2017-09-11 13:27
Please check if this error still occurs with v5.208.

**Closed** 2019-03-01 01:15 UTC
