### ISSUE TITLE
Feature Request: Maillist Widget

### ISSUE THREAD

**Issue by tessus** [k9mail/k-9#2680] opened 2017-08-13 04:25 UTC
I've been using MailListWidget for K-9 on my S3 for years, but it won't work on newer devices.
The other widget (Email Widget) listed on the web site does only work to a certain degree.

I'm not an Android/Java developer so I can't write this myself, but a Maillist Widget should be fairly easy to develop. Why not make it part of K-9?

MailListWidget for K-9 was slick and tremendously useful. I hoped something similar could be part of K-9.

**Comment by philipwhiuk** [comment] 2017-08-14 21:42
Duplicate of #1848 

Will be in the next major release.

**Closed by philipwhiuk** 2017-08-14 21:42 UTC

**Comment by tessus** [comment] 2017-08-14 22:13
Thank you for the info. Who's the owner? I'd like to make a few suggestions and maybe the owner could give me some hints where I should start, if I wanted to help coding the widget. I believe I could pick up Android coding fairly quickly.

**Comment by philipwhiuk** [comment] 2017-08-14 22:28
The owner of what? The new widget was built into K-9's codebase (like you suggested) so it's owned by the K-9 mail team. When we next do a release you'll be able to add it.

Feel free to browse the code for the widget and suggest improvements though -
 k9mail/src/java/com/fsck/k9/widget/list

**Comment by tessus** [comment] 2017-08-14 23:44
I meant the owner of the code for the widget. Usually in bigger sw projects, the codebase is divided into components, which in turn have respective owners.

Anyhow, I'll have a look at the code and maybe I can start from there.

I saw the current preview image for the widget and had a few suggestions for options that would make the widget more configurable. IMO a widget should allow for as much overview as possible, but it only really shows 3 mails.
MailListWidget for K-9 on my S3 shows 6 mails in a 4x2 block:

![new](https://user-images.githubusercontent.com/223439/29296539-ee866c18-8128-11e7-85a7-84a01495cf37.png)

**Comment by philipwhiuk** [comment] 2017-08-15 21:39
The problem with owners is it tends to result in problems if the owner is AFK or otherwise unavailable. In general we try and all own and comment on the system - such that any active member can give a reasonable response to an issue/PR. I believe @cketti who was most grumpy about absorbing the functionality reviewed the original PR - that sort of strategy seems to lead to the best code reviews ;)

Regarding the size of the widget I don't really want us to have a million different sizes but if we added another size to better replicate the previous behavior I think that'd be fine. So if you want to look into the work required for that, feel free :)

**Comment by tessus** [comment] 2017-08-15 22:03
Thanks again for the reply. I was not really talking about the size of the widget, but rather the size of the elements in the widget. (The size of the widget can be changed by the launcher anyway.)

As far as I can tell the preview image is also 4x2 size. Anyhow, it would be great, if there were a few options for the widget, like:
- show folder/inbox header (most ppl know that they are looking at their inbox, thus redundant info that only takes away space)
- show only **from**, **subject**, and **date** (the first line of the msg might be nice, but also takes away space. ppl can click on it anyway to read the message.

I guess I will look into 'how to write a widget for android' to familiarize myself with this topic. Cheers.

**Comment by tessus** [comment] 2017-08-20 00:01
@philipwhiuk 2 last questions:
- What will be the next major release and is there an ETA (in the ballpark)?
- Is there a way I can get that widget on top of the current version and compile it myself?

**Comment by philipwhiuk** [comment] 2017-08-20 12:38
I have no idea when @cketti plans to release the current code. Personally I'd rather we release more often than we do.

**Comment by philipwhiuk** [comment] 2017-08-20 12:39
As for getting the current code - you can just checkout the repository and use Android Studio / adb directly to install it.

**Comment by Valodim** [comment] 2017-08-20 14:36
We plan to work on a release in the next two weeks :)

**Comment by tessus** [comment] 2017-08-20 18:18
@Valodim will this be a major release? @philipwhiuk mentioned that the widget will be in the next major release....
What I really want to know is, if this version will include the [widget](https://github.com/k9mail/k-9/tree/master/k9mail/src/main/java/com/fsck/k9/widget/list).

**Comment by tessus** [comment] 2017-08-20 18:23
What I find very odd is that all releases have the following:

`522 commits to master since this release`

How's that even possible?

**Comment by philipwhiuk** [comment] 2017-08-20 21:44
There's way more than 10 releases, so all is definitely not 10.

Because the 5.2x releases all come off a single branch point from master.

Basically how it works is this:

1. We decide we want a new major release.
2. This code gets released as a series of alphas (which we called the 5.10x series).
3. Minor tweaks and bugfixes get merged into the alpha. Eventually we get a release candidate (5.200-RC1). This gets branched off.
4. 5.200 gets released.
5. Any changes that are considered suitable fixes for backporting get merged in as 5.201... 5.209

So the 522+ commits are since December 2016, when we made the split. A few of them GitHub can't recognise as backports. But mostly it's new code which will be first seen in a 5.3x alpha / 5.400 release.

The difference between 5.207 and 5.200 is about 153 commits (101 excluding obvious merge commits).
