### ISSUE TITLE
[Request] Allow custom sender adresses

### ISSUE THREAD

**Issue by malnvenshorn** [k9mail/k-9#3805] opened 2018-12-07 15:19 UTC
At the moment it's only possible to select a sender address from predefined identities. I would like to be able to enter a custom one. The reason is that I use a lot mail extensions and creating/maintain them as separate identities is simply not feasible.

**Comment by knobhead** [comment] 2018-12-15 13:41
I agree, that's a rather advanced feature, but very useful for power users and fans of catch-all e-mail addresses.

**Comment by cketti** [comment] 2018-12-15 16:37
Duplicate of #935

**Closed by cketti** 2018-12-15 16:37 UTC
