### ISSUE TITLE
Some HTML links in text emails no longer recognised and not clickable

### ISSUE THREAD

**Issue by garfieldthecat** [k9mail/k-9#3102] opened 2018-01-17 09:47 UTC
### Expected behavior
HTML links in a text (not HTML) email should be recognised as such.

### Actual behavior
They no longer are, after the update to version 5.403 on 6-Jan-2018. They used to work fine before this update.

### Steps to reproduce
Send yourself a text email with the body containing exactly the following (copy the text verbatim, with the < and > characters):

```
<http://www.google.com>

<www.google.com>

http://www.google.com

www.google.com
```

You will notice only the third link works (i.e. can be clicked on) - the others are not recognised as such.

The links in the format `<http://www.website.com>` come from newsletters I am subscribed to; like I said, they used to work just fine before the 5.403 update.

### Environment
K-9 Mail version: 5.403

Android version: 7.0 running on Samsung Galaxy s7 edge

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (but I don't think it's relevant)

**Comment by philipwhiuk** [comment] 2018-01-17 23:39
Duplicate of #2922

**Closed by philipwhiuk** 2018-01-17 23:39 UTC
