### ISSUE TITLE
Moving account upper make it visible... twice in the list of accounts

### ISSUE THREAD

**Issue by ghsrcgh** [k9mail/k-9#1428] opened 2016-06-05 00:49 UTC
### Expected behaviour
When I moving account up it must move up. Not make a copy upper :)

### Actual behaviour
I got a two copies of the same account.

Was before move up:
Account 1
Account 2

After I used "move up" on account 2, I got:
Account 2
Account 1
Account 2

I tried to open Account 2 (first) and Account 2 (last) -- opened well.
I fixed the case only by totally closing (in task manager) K-9 mail, and restart it.

### Steps to reproduce
1. Setup two POP3 accounts.
2. Try to move up Account 2.

### Environment
K-9 Mail version: 5.0.10

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment] 2016-06-06 08:45
Duplicate of #615

**Closed by philipwhiuk** 2016-06-06 08:45 UTC
