### ISSUE TITLE
Unified Inbox does not update until individual accounts' inboxes refreshed

### ISSUE THREAD

**Issue by dmillins** [k9mail/k-9#1496] opened 2016-07-10 17:09 UTC
### Expected behavior

Unified Inbox should display all accounts' inbox mail
### Actual behavior

Unified Inbox does not update until individual accounts' inboxes refreshed.
### Steps to reproduce
1. Create more than one account, each having mail in its inbox
2. Attempt to refresh Unified Inbox & observe non-updating.
3. Refresh individual accounts' inboxes, return to Unified Inbox and observe it to be updated correctly.
### Environment

K-9 Mail version: 5.010
[k9-log.txt](https://github.com/k9mail/k-9/files/356119/k9-log.txt)

Android version: Android 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2016-07-17 21:14
Works for me.

The log doesn't contain any relevant information.

**Comment by cketti** [comment] 2019-02-28 20:28
Duplicate of #1114

**Closed by cketti** 2019-02-28 20:28 UTC
Labels: needs info
