### ISSUE TITLE
Plus addressing, Subdomain addressing and identities

### ISSUE THREAD

**Issue by saintger** [k9mail/k-9#2185] opened 2017-02-05 00:56 UTC
### Expected behavior
I have currently an account on Fastmail (user@example.com) which allows subdomain addressing (whateveryoulike@user.example.com is automatically forwarded to user@example.com).
Being able to create many emails on the fly is very useful to track how our email is used by companies (for instance I am giving whateveryoulike@user.example.com to the company whateveryoulike).
The same thing can also be achieved through "Plus Adressing" (user+whateveryoulike@example.com).

However on K9mail, we have to manually create identities before being able to use them as sender's email (while composing a new email or while replying to).
It would be nice to have a new feature to handle that automatically.
For instance if I received an email addressed to whateveryoulike@user.example.com, if I click Reply, the sender's address can be populate with whateveryoulike@user.example.com as well instead.

### Actual behavior
if I received an email addressed to whateveryoulike@user.example.com, if I click Reply, the sender's address is filled with the default identity.

### Steps to reproduce
1.Send an email whateveryoulike@user.example.com
2.Email is automatically forwarded to user@example.com
3.Reply to the email within K9
4. Sender's address is the default identity user@example.com instead of whateveryoulike@user.example.com

### Environment
K-9 Mail version:
v5.203
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment] 2017-02-05 01:09
Duplicate of #935

**Closed by cketti** 2017-02-05 01:09 UTC
