### ISSUE TITLE
Syncing stops with Android 7 -- logcat

### ISSUE THREAD

**Issue by Simplenuity** [k9mail/k-9#2618] opened 2017-07-05 14:46 UTC
Sorry, #2357 has been locked. As it might help to have some logcat entries that seem - at least chronologically - be related to the issue I'm opening this one. If not appropriate, please feel free to close and delete.

### Environment
K-9 Mail version: 5.206

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
[logcat_k-9_part.txt](https://github.com/k9mail/k-9/files/1125045/logcat_k-9_part.txt)

**Comment by kairu0** [comment] 2017-07-06 02:32
Also having the issue on a Galaxy S7 since Android 7 upgrade.

**Comment by Simplenuity** [comment] 2017-07-06 14:24
Short update: excluding k-9 from battery optimization has turned out to be a workaround.

**Comment by ghsrcgh** [comment] 2017-07-07 00:23
The same issue on Galaxy S7 since Android 7.0. Battery Optimization ("Do not") and Background Sync ("Always") does not help at all.

**Comment by kairu0** [comment] 2017-07-07 00:31
I enabled:

> Battery Optimization ("Do not", exclude from optimization) and Background Sync ("Always")

about 24 hours. Sync has gone offline twice since then. So, I'm confirming that the workaround doesn't work for me either.

**Comment by kairu0** [comment] 2017-07-20 01:41
Syncing is continuously disabled in spite of excluding k-9 from battery optimization on my Samsung Galaxy G7. This has been the case for a couple weeks now. Just thought I'd share this feedback.

**Comment by philipwhiuk** [comment] 2017-07-30 12:44
Duplicate of #857

**Closed by philipwhiuk** 2017-07-30 12:44 UTC
