### ISSUE TITLE
K9 Syncing disabled or next sync 2 hours AGO

### ISSUE THREAD

**Issue by barneyfife** [k9mail/k-9#2434] opened 2017-03-23 23:31 UTC
Are they going to fix this issue that I see many others are having?

K9 was just updated today and I hoped the fix was in, but no, left the phone alone for about an hour and upon waking up k9 said next sync 2 hours AGO, tried a little later and the old syncing disabled was back.
I have tried everything, from whitelisting K9 from power savings to completely turning off that feature, no luck. I have tried MacroDroid to do things such as keep awake, turn wifi on and off, terminate the k9 process and after a delay open k9, and others all on a repeating 30 minute schedule, it still goes to sleep and k9 says syncing disabled, close and reopen k9 and it works fine. This started with Android 6.01 and got much much worse in 7.0
Thanks

**Comment by philipwhiuk** [comment] 2017-03-23 23:44
Opening duplicate issues just wastes the time of developers.

Closing as duplicate of #857.

**Closed by philipwhiuk** 2017-03-23 23:44 UTC

**Comment by barneyfife** [comment] 2017-03-24 05:35
I already read that, where is the fix?

**Comment by philipwhiuk** [comment] 2017-03-24 08:45
It's not fixed... Hence why the issue is still open.
