### ISSUE TITLE
old icon setting

### ISSUE THREAD

**Issue by treakiandroid** [k9mail/k-9#3259] opened 2018-03-14 08:37 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

I just updated your app from fdroid, i cant see anything has changed, exept the icon which looks nw quite ugly in my eyes...
### Expected behavior
Good old look and feel and icon without asking me me bout it.

### Actual behavior
Horrible looking icon with now way back

### Steps to reproduce
1. Install the update

Could you build in an option to get the old icon back? Thanks

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment] 2018-03-14 10:48
Duplicate of #2998

**Closed by philipwhiuk** 2018-03-14 10:48 UTC
