### ISSUE TITLE
[Oreo] Loss and regain of connection can cause synch to remain disabled. (Not Doze related, but network)

### ISSUE THREAD

**Issue by mandree** [k9mail/k-9#3428] opened 2018-06-04 19:07 UTC
### Expected behavior
Synching should be re-enabled when a network connection (WiFi or mobile) is re-established (after losing it previously).

### Actual behavior
Loss and reacquisition of connection does not re-enable synch. 
Instead, I get a "Synchronisation deaktiviert - kein Netzwerk" (German for "synchronization disabled, no network") display on the "Accounts" front page - which would make this *unrelated* to Doze mode.

Workaround: enable flight mode and disable it again. K9-mail will change back to "next poll in ... minutes"

### Steps to reproduce
1. lose connection on a Sony Xperia XZ1 compact (model code G8441), through bad reception, basement rooms, whatever
2. reacquire connection

### Environment
K-9 Mail version: 5.403 (Google Play Store)

Android version: 8.0.0,  security patch level: 2018 May 1st
(I do not recall having seen this on 6.0 on a Sony Z3 compact)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Random thoughts aka. brainstorming: through what events/messages/... would K9-mail learn that it has UMTS/LTE or WiFi connected when the phone is NOT coming out of flight mode, but going back from "under the rock" to a place where it has reception?

**Comment by itsbrody** [comment] 2018-07-19 15:34
I can confirm this behaviour (and its workaround I read above) for also lower security patch version, I have currently: 8.0.0.122 security patch as of March, 1st. 2018.

and this although I've set synchronisation in k9 to "immer" (always)

I'm sure that I haven't seen this on Android 4.2 or 4.4 I used before with another tablet. Further the other sync setting (i.e. "depend on 'automatic sync' active" or the like) also worked very well and reliably.

**Comment by nailyk-fr** [comment] 2018-07-26 09:17
Same issue here but wondering if it can be oreo related. 
Have it on multiples devices (z3, z3c, zx1c) all custom oreo based. Do not remember having this on my nougats
Alos, here it doesn't seem the problem happens (WIFI/LTE) unless I send a mail. 

Have someone tried to place k9 mail into 'battery optimization exceptions' ?

**Comment by itsbrody** [comment] 2018-07-26 13:14
" Have someone tried to place k9 mail into 'battery optimization exceptions' ?

I'm not sure if this is the case, but I've put k9 into "manual start" with only "running in background" set to on. But before I've had this into automatic mode with same mis-behaviour.
Would you please advice?

**Comment by JuBan1** [comment] 2018-07-28 07:44
I have the same issue on Android 7.0 Nougat. Even with battery optimization disabled for K-9 and every possible setting set to sync as often and aggressively as possible, I still regularly have to open K-9 after coming back home into my WiFi network. Once I manually kick off a sync, K-9 will go back to syncing normally.

**Comment by anotherChristian** [comment] 2018-08-19 13:30
I think I have found the responsible part in the java code.

**Comment by anotherChristian** [comment] 2018-08-20 16:42
Sorry, sorry I was too fast.
it is the responsible function, but not really the problem. 
It seems K9 is not receiving the state of change regarding the connection status or is setting the next poll time in the past.

**Comment by cketti** [comment] 2019-03-08 02:26
Duplicate of #3950

**Closed by cketti** 2019-03-08 02:26 UTC
