### ISSUE TITLE
SMTP-only server support (specific SMTP for specific identity)

### ISSUE THREAD

**Issue by arhayati** [k9mail/k-9#5236] opened 2021-04-08 15:17 UTC
It would be awesome if we could have SMTP server support. I, for example, forward all my emails to another email and need to send emails from that address. Look at this:

emails from me@example.com [gets forwarded to] some@domain.org.
when I want to reply, I need to reply from me@example.com.

Now I can add identities but it raises some problems and many of my emails will end up in junk folder. I need to send emails from that SMTP server on example.com. On Thunderbird, I have no problem because when I add identity in the software (not server), I can set specific SMTP server for it to use but on K-9, there's no feature like this.

Can we please add a feature to set special SMTP server for an identity?

Thank you very much.

**Comment by cketti** [comment] 2021-04-08 15:22
Duplicate of #1117

**Closed by cketti** 2021-04-08 15:22 UTC
