### ISSUE TITLE
Please add text only mode, selectable as default

### ISSUE THREAD

**Issue by hman2** [k9mail/k-9#6025] opened 2022-04-18 20:55 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.916

### Problem you are trying to solve

Today I received (on my desktop) a spam mail that contained nasty stuff in HTML.

This reminds me of the #1 feature I have always missed with K-9. The one that is the first I activate on each and every mail client I use, both in the office and at home: Text only.

HTML can be abused for all kinds of things, most prominently for conceiling bad hyperlinks in counterfeit e-mail that claims to be from your bank etc. In text mode, camouflaged hyperlinks become immediately visible. That is why this feature is desparately needed. It was promised for future addition, but that was several years ago...

Thanks alot.
Yours
hman

### Suggested solution

A text only mode like Thunderbird has it, and add a preset so users can choose whether by default they want to see mails in text or in HTML.

**Comment by ByteHamster** [comment] 2022-04-25 22:03
Duplicate of #906

**Closed by ByteHamster** 2022-04-25 22:03 UTC
Labels: enhancement

**Comment by hman2** [comment] 2024-11-16 10:02
Completed? Now that K-9 and Thunderbird are joined an version is at 8.0, in November 2024 it is still not present in the app. Or was I just unable to find it?
