### ISSUE TITLE
Microsoft Exchange Server format issue

### ISSUE THREAD

**Issue by tigerwoods2k17** [k9mail/k-9#2791] opened 2017-09-25 22:05 UTC
Whenever I encrypt and send message from Outlook where the user is configured as an account on Microsoft Exchange Server, K9 is not able to read the encryption. if i copy and paste the text then encryption is detected

Here is how the Message body is coming up from Microsoft Exchange Server:

```
<html><head><meta name="viewport" content="width=device-width" /><style type="text/css">* { background: black ! important; color: #F3F3F3 !important }:link, :link * { color: #CCFF33 !important }:visited, :visited * { color: #551A8B !important }</style> <style type="text/css"> pre.k9mail {white-space: pre-wrap; word-wrap:break-word; font-family: sans-serif; margin-top: 0px}</style></head><body>
                                                        
                                                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                                                        <meta name="Generator" content="Microsoft Exchange Server" />
                                                        <!-- converted from rtf -->
                                                        <style><!-- .EmailQuote { margin-left: 1pt; padding-left: 4pt; border-left: #800000 2px solid; } --></style>
                                                        
                                                        
                                                        <font face="Arial" size="2"><span style="font-size:9.5pt;">
                                                        <div>-----BEGIN PGP MESSAGE-----</div>
                                                        <div>Version: 10.3.0 (Build 8741)</div>
                                                        <div>Charset: utf-8</div>
                                                        <div>&nbsp;</div>
                                                        <div>qANQR1DBwUwDhu8C6RTZPPwBEACmRmFLqsUfS/qN+ZuH27/RZv7VpAhnNouZpCWr</div>
                                                        <div>fiWk/eUt/zuJ8iTGDxN9dlEcuQNSY3w3zuuvQvjbK0Xa+930r/VHUDGuP10RP9gG</div>
                                                        <div>9botz0Xca4+XzOO1ok7+eUZPOmuPEv+T7NiUXXVCVXRu56S/H7QaDXOM9lQMLRNE</div>
                                                        <div>BC0X90Ee/VQSr8jJ5FY91Ni7lBC6Ac2mr0im0q6QvCLpx+Ub7v9WhlENJc+1sjsJ</div>
                                                        <div>DFkrbpeELMbT9fCivnBhzHKZtc08dNITd+vYzpZ2evhLTlRiwUdW1nttNBjr2afq</div>
                                                        <div>TH98KmSyZT0xQUZFipjzHkUqZnG7GmZdAVatJZdUBW0BXGVsxc7dQszPc4CsoPok</div>
                                                        <div>1JysnEgz+QcWVLEHXALoK2oFK7XFgC1/ourOp1lh5pEHi6UT7ZHS9Cqv15oT7Lbe</div>
                                                        <div>/w5yhQZzNPevKOFYMcfGmfW2B2Y9YXMV1O31GWXSKmJ8ULV70SXHvSJRQJovZIRP</div>
                                                        <div>A9a4dyLzkH6WaztX61KWhV8Hd0hwaxXoZLsltaSHmwsJPYTP7l37LLxU4GiGcTH/</div>
                                                        <div>pEhnKQEjaroYo0ujHrnmfGWPj0lrNA7dYm3tcY1kxo8XbA3RCYQRNDRX85VtcJdu</div>
                                                        <div>bu3WZruCfFxqTOTfeUhFDrO4+OcSxCcqyqHSk2B3er1QKCNg+4TmyvyNi604A8BR</div>
                                                        <div>LurLx8HBTAPJWxZ+rZSaSwEQAInqQErmTDGfoEHxjy+r9VdzximHJBs5MtwuaBLK</div>
                                                        <div>SL2JFrW2f+k7gf/pfiQVh06OoWNlKyEkl63tJtn3XzTLM0KGiVpbya8i27Gzzh7N</div>
                                                        <div>UngIySTJCVwHoAnv9/8uyWgmzsIF2Cvq38VniOBjUAqP275OdjME+S+cr76Q+WCY</div>
                                                        <div>YsB2QJvvJE9Cpb1VW87KYVHG0Q6RpDSB1Tv2y5ZEDs9dpEX131JZeu8IC+8K9tTj</div>
                                                        <div>DahwPeTQnO7IuU+o/rn3WNrAjvPucKXX6KccqCEz20JmlqIErDsWF1AgmGVgwmfo</div>
                                                        <div>fADvZ0ty6wKC9DD5sUL4IaVB4P0oPjSNHVLf2ROKutr4TKwAj4mC2kEboak+t/KS</div>
                                                        <div>ZmwElkFPYA4dCe8/dim5EDWZtTZo09BehFa0PwLEBjBL88/1bSOE0/60E2nTl8QL</div>
                                                        <div>fmUvJidh5hhN+Xgvmnz4eDF53hnT/uRGIZ8MV688dtvzrS0vI/SuQPg4zsPng/e+</div>
                                                        <div>8qvt7k2xWhcl5kovgr66C3W0GVYbL9BNR85q/Dr2oEE9iKUQAB/TRugGwvS4lU4S</div>
                                                        <div>QkYxqwxxmwNLLKfLCmdRtYeF7+OrLz6dDw67breEnu1t9aEyGWhW0njZu9ptAZt9</div>
                                                        <div>Am6hv2MvhwDSVE7MHygZZ4BstskDnhucoQAzjpDjqQdtCXnFaRIWWXV+I2couGuI</div>
                                                        <div>Vot30sGoAXX4kjD6A7udEqVhbbRrWkkF8mWFnUeVaJr2g2Wb6ylaU2AqTJaMmTQx</div>
                                                        <div>SEZH2ae+PKJ9GMSNAYk/lW5Kvaslyiz0pTR4+mf6pRdkoZXMrcNOYWAU0LDjz2mz</div>
                                                        <div>gZUZ/bkY3Rnq6GDEq0e6SgeE+hfS5jzqDtFooaJv0x7fTLbYK7s9fObOL67TGHdF</div>
                                                        <div>9Iz1MZHLR8egsT4C8yw88KrM+QIs9kHfUw7Fp3MMpUPdODhhk6mfKSvuyOeJCM2E</div>
                                                        <div>rRPz4V07pvc49r+yAj80z23DsN3pEdA2Mt2kI5bMMLn/6ISW1k0FAOepMw/50Vrd</div>
                                                        <div>ue/kvBXx9gVdznEPBKbtEC3clT5R0kxZtosSEMoHCkEz9/N6g1l25V76EJALYupa</div>
                                                        <div>kczcTvdmiPtLyjM3dibbpLUaNcbZF9oZp3pGMFj4UcNDSGZSJQX6QP10CBx63xHk</div>
                                                        <div>gZEJEPR1nEUF/6E+n0/+IuRFI2SbXTDs8oQYG4M53fL5Ven/CcbH/+JBbffpE1h7</div>
                                                        <div>p6ItkuUqcwsmpBgfL8UMFrftUfCYBGnqRENUBMxevmtcjrXLPxDc0yJu5ZN5yl65</div>
                                                        <div>OmsrYqBxzyqhLPl7Q2UGClD4KaKJFJCvuyJ2w4uGJpr8akoIBikJKRcpoYuSNhs1</div>
                                                        <div>H16OowwpyLUOLZE7lcOk8IeJUAViZ9uZy0Whw3a6MCZRUEWUjOefDH6wim4WH5hX</div>
                                                        <div>3wdu00vcWYYDA1xJ8IqdJNko4P93vQQn63slVMdQDb9bnTD3A+c2GWp7rdtDrIxa</div>
                                                        <div>AFqmbU4XyuPUd+v7zkocc1cf9h7K4UmdHIa0yARPMpTh3D9Bx0fqIqroag9R6A==</div>
                                                        <div>=cyV1</div>
                                                        <div>-----END PGP MESSAGE-----</div>
                                                        <div>&nbsp;</div>
                                                        <div>&nbsp;</div>
                                                        </span></font>
                                                        
                                                        </body></html>
```

I have deduced the before the message is shown, we can try to change the formatting [here](https://github.com/k9mail/k-9/blob/dcb8587dec0bdd4869139bd952db23a01afab817/k9mail/src/main/java/com/fsck/k9/ui/messageview/MessageViewFragment.java#L240)

**Comment by cketti** [comment] 2019-03-01 01:29
Duplicate of #2422

**Closed by cketti** 2019-03-01 01:29 UTC
