### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by eileenfan** [k9mail/k-9#2754] opened 2017-09-11 06:15 UTC
//package name: com.fsck.k9
//version: 5.205
//target sdk version: android-18
 java.lang.NullPointerException
 	at com.fsck.k9.activity.compose.MessageActions.actionCompose(MessageActions.java:19)
 	at com.fsck.k9.activity.MessageList.onCompose(MessageList.java:1265)
 	at com.fsck.k9.fragment.MessageListFragment.onCompose(MessageListFragment.java:1016)
 	at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.java:800)
 	at android.app.Activity.onMenuItemSelected(Activity.java:2566)
 	at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:986)
 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:742)
 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:881)
 	at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:547)
 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:115)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View$PerformClick.run(View.java:17721)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by philipwhiuk** [comment] 2017-09-11 09:51
Duplicate of #2756

**Closed by philipwhiuk** 2017-09-11 09:51 UTC
