### ISSUE TITLE
Screen redraw regression in 5.202 causes disappearing icons at bottom of message view

### ISSUE THREAD

**Issue by ssb22** [k9mail/k-9#2006] opened 2017-01-07 17:58 UTC
### Expected behaviour
When tapping on a message in the list, the message will take full screen and there are icons at the bottom of the screen for left, right, delete, reply, new, and menu.

### Actual behaviour
These icons are not consistently displayed.  When they are not displayed, it is still possible to tap the empty space where they should be and the icon function will happen (for example, tap where the delete icon should be and the message will be deleted).  Sometimes only the right-most fragment of the icon bar is displayed.

I tried to get a screen-shot of this, but as soon as the screen-shot was triggered, the entire icon bar displayed correctly just in time.  So it seems that Android's screen-shot function triggers a redraw first, and screenshots cannot therefore be used to capture examples of insufficient-redraw artefacts.

### Steps to reproduce
1. Send yourself a blank message, or one with very little content
2. Refresh the message list so your new message appears
3. Open the message
4. Sometimes the icons are displayed OK anyway.  This is an intermittent problem.  You may have to send yourself 4 or 5 messages and open each one to reproduce the issue.

### Environment
K-9 Mail version: 5.202

Android version: 4.4 (on a Sony Xperia Z Ultra)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ssb22** [comment] 2017-01-07 17:59
I called this a 5.202 regression because I have been using K-9 Mail for some time before the update and have never seen this problem before.  However I cannot completely rule out the possibility that the regression actually occurred in the previous (short-lived) update, since I didn't test that version very long.

**Comment by philipwhiuk** [comment] 2017-01-07 18:01
Duplicate of #1984 (and possibly others I'm sure I've seen this raised before that one)

I'd love to fix this one, but my device doesn't reproduce it very often for some reason :( 
I have no idea what's going on here - it's possible it's the way we are using Holo.

**Closed by philipwhiuk** 2017-01-07 18:01 UTC
