### ISSUE TITLE
Unwanted notification on Mailreading (Message is not end to end encrypted)

### ISSUE THREAD

**Issue by Teyro** [k9mail/k-9#2683] opened 2017-08-16 07:17 UTC
### Expected behavior
Click on a mail at the Mainscreen, enter my passpharse and view mail

### Actual behavior
After entering a mail i get this Message displayed every time... Is the a chance to disable that?

### Steps to reproduce
1. Use OpenKeyChain, german mail Provider with Inline PGP Mail enceyption
2. Get a mail :-)
Here is a screenshot: https://cloud.teyro.tech/index.php/s/ZntXAqB3VrICdtn

### Environment
K-9 Mail version: lastest stable 5.207 i think

Android version:

LinaeageOS on OnePlus2 and Stock Android 6.0 on a Samsung Galaxy Tab A 2016

**Comment by philipwhiuk** [comment] 2017-08-17 06:48
Duplicate of #2286

**Closed by philipwhiuk** 2017-08-17 06:48 UTC
