### ISSUE TITLE
Sync disabled over mobile data

### ISSUE THREAD

**Issue by roughnecks** [k9mail/k-9#4597] opened 2020-03-09 20:27 UTC
### Expected behavior
Emails should keep syncing when using mobile data.

### Actual behavior
Every time I open K-9 it tells me that Sync is disabled. When using Wi-Fi everything works fine.
Android Sync is on, battery optimization is set to allow all activities from K-9 and I'm keeping the app locked in recent menu, so it never shuts down.

### Environment
Android version: 5.600
XIAOMI Redmi 6A

Account type: IMAP

**Comment by dhebbeker** [comment] 2020-03-09 21:27
See #3950.

**Comment by roughnecks** [comment] 2020-03-09 21:30
I already saw that but it's not helping.

**Comment by cketti** [comment] 2020-03-10 21:42
Duplicate of #3950

**Closed by cketti** 2020-03-10 21:42 UTC
