### ISSUE TITLE
"Send Later" functionality to schedule the date/time for sending an email.

### ISSUE THREAD

**Issue by KroRob** [k9mail/k-9#1756] opened 2016-10-25 17:07 UTC
Please add "Send Later" functionality to schedule the date/time for sending an email.

**Comment by lbdroid** [comment] 2016-10-31 13:54
It should notify the user clearly if the sending fails.

**Comment by leoj3n** [comment] 2018-10-19 10:28
Personally, I miss the "undo" send feature of Gmail, but would settle for a scheduled send.

Thanks!

**Comment by cketti** [comment] 2019-02-28 21:20
Duplicate of #688

**Closed by cketti** 2019-02-28 21:20 UTC
Labels: enhancement
