### ISSUE TITLE
Snooze Feature like in Google Inbox

### ISSUE THREAD

**Issue by guettli** [k9mail/k-9#1842] opened 2016-12-07 21:14 UTC
### Expected behavior

I would like to have the "snooze" feature like google inbox has.

### Actual behavior

not possible in current k9 app.

### What is "snooze"?

You can move the mail out, and make it reappear N days later.

It's a great productivity tool. Just google for "zero inbox" or "43folders".

**Comment by nicofrand** [comment] 2017-01-06 10:26
I'd really like it to but it appears this won't be realised (unless someones does a PR of course).
This is a duplicate of https://github.com/k9mail/k-9/issues/1549

**Comment by guettli** [comment] 2017-01-06 11:06
@nicofrand Thank you for discovering, that this is a duplicate. I added a comment on the other issue: https://github.com/k9mail/k-9/issues/1549#issuecomment-270880691

**Closed** 2017-01-06 13:26 UTC
Labels: enhancement
