### ISSUE TITLE
Nicer Folder Hierarchy Appearance

### ISSUE THREAD

**Issue by loewexy** [k9mail/k-9#5898] opened 2022-02-06 15:33 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

The folder view in the side drawer does not look very nice. All Subfolders of the inbox are called INBOX.Foo.Bar and so on.

### Suggested solution

Use indentation to build some sort of classic folder view which reflects the hierarchy of the folders.

**Comment by John4266** [comment] 2022-02-14 19:25
I agree.
It would look a bit nicer if it was something like this:
![](https://i.imgur.com/W92IgQL.png)
Instead of this:
![](https://i.imgur.com/C3p5wSM.png)

**Comment by cketti** [comment] 2022-02-21 17:13
Duplicate of #630

**Closed by cketti** 2022-02-21 17:13 UTC
Labels: enhancement
