### ISSUE TITLE
K-9 Mail on Galaxy S10 not working (Glitch)

### ISSUE THREAD

**Issue by gigabyte-ux** [k9mail/k-9#4382] opened 2019-12-15 12:12 UTC
### Expected behavior
K-9 Mail on Samsung Galaxy S10 not working (crash)

### Steps to reproduce
1. Activate flightmode and disable WiFi.
2. Open the K-9 Mail app for the first after installation.
2. Tap next, add email account e.g gmail
3. Tap next, tap next, tap next and enter the name. Tap done.
4. It comes the contact request. Tap allow and the K-9 Mail app is crashed.
5. If want to open the app for the second time, that's not possible. It crashes again and again.

### Environment
K-9 Mail version:
5.702 https://github.com/k9mail/k-9/releases/tag/5.702

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP and POP3

**Comment by ByteHamster** [comment] 2019-12-15 20:41
This is the same as #4352

**Comment by cketti** [comment] 2019-12-17 01:14
Duplicate of #4352

**Closed by cketti** 2019-12-17 01:14 UTC
