### ISSUE TITLE
Feature Request  : No way to see email content source ?

### ISSUE THREAD

**Issue by gitmatt19** [k9mail/k-9#2987] opened 2017-12-26 02:20 UTC
I noticed that when someone sending me email there is no way to look at the HTML source so I can review the URLs etc to see where they are going to pull images from etc. This makes is harder to determine if you are getting phished or if the images are really trackers.

It would be good if we could view the raw / mime decoded email to review its contents like I can with the Alpine email (press H) client.

thanks

Matt

**Comment by philipwhiuk** [comment] 2017-12-28 01:11
This needs to be the original HTML source before we apply our HTML tidy to it. Also we should probably apply some formatting to the HTML rather than render the raw source code which is likely to be hard to read.

**Comment by cketti** [comment] 2017-12-29 05:20
You can long-press links to see the URL.

Duplicate of #1018

**Closed by cketti** 2017-12-29 05:20 UTC
Labels: enhancement

**Comment by gitmatt19** [comment] 2017-12-30 03:33
"You can long-press links to see the URL."

This seems like pulling the trigger half way on a gun to see if it is loaded.
