### ISSUE TITLE
since upgrade to Andoid 8, K9 eats all my battery

### ISSUE THREAD

**Issue by colttt** [k9mail/k-9#2854] opened 2017-10-23 09:16 UTC
### Actual behavior
Since I upgraded to Android 8 (Oreo) k9-mail use more than 75% of my battery everytime, but I didn't change the config.

### Environment
K-9 Mail version: 5.208

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): 2mailaccounts with IMAP, check mail every hour
![screenshot_20171019-163424](https://user-images.githubusercontent.com/10084871/31881329-7ed6fa26-b7e3-11e7-88ea-016539571a61.png)

**Comment by cketti** [comment] 2017-10-25 03:05
Duplicate of #1829

**Closed by cketti** 2017-10-25 03:05 UTC
