### ISSUE TITLE
Feature Request: Easy Delete by SWIPING

### ISSUE THREAD

**Issue by djringjr** [k9mail/k-9#2807] opened 2017-09-30 01:48 UTC
Hi a feature request would be a much faster way of deleting messages.  Often people get advertisements or they have mailing lists and from the subject they know they're not interested in reading the  message.

It would be really nice to swipe a message away.

Toss that around with the devs.

Thanks,

DR

**Comment by f71uday** [comment] 2017-10-11 17:35
I would like to work on this Issue

**Comment by kamil0074** [comment] 2017-11-05 14:46
I there any life in this issue? I would want to contribute to this project by changing ListView of emails to RecyclerView which will allow to easily implement swiping. (In fact I have to contribute somehow to project to pass this semester on university)

**Comment by waldyrious** [comment] 2018-01-22 10:20
This is a duplicate of #1426. @djringjr, would you close it so that discussion is focused in a single place?

**Comment by djringjr** [comment] 2018-01-22 10:29
Closed.

**Closed** 2018-01-22 10:29 UTC
