### ISSUE TITLE
Android 6.0 later Synchronize fail

### ISSUE THREAD

**Issue by li42899974** [k9mail/k-9#1700] opened 2016-10-11 09:05 UTC
Android 6.0 later ,background could be kill, so that do not Synchronize email .

Could you use jobscheduler instead service

**Comment by philipwhiuk** [comment] 2016-10-12 03:30
Doze kills active network connections as well as delaying tasks. Job Scheduler would not solve the problem - the JobScheduler is simply not run during Doze. Moreover we already do use proper scheduling for polling as I recall.

At some point we will add an intent to offer to disable battery optimisation - per the Android whitelisting documentation: https://developer.android.com/training/monitoring-device-state/doze-standby.html#whitelisting-cases.

Closing as duplicate of #857

**Closed by philipwhiuk** 2016-10-12 03:30 UTC
