### ISSUE TITLE
Spam e-mail causes crash

### ISSUE THREAD

**Issue by inthegarage** [k9mail/k-9#1274] opened 2016-04-11 14:37 UTC
### Expected behaviour
Tell us what should happen
Spam e-mail seems to crash K9, it should not.

[Calling_all_TV_lovers!_Samsung_product_testers_required.txt](https://github.com/k9mail/k-9/files/213177/Calling_all_TV_lovers._Samsung_product_testers_required.txt)
### Actual behaviour
Tell us what happens instead
Every time K9 tries to get the message summary from the server this spam causes K9 to crash.
Sending the spam to the spam folder by another program, corrects the behaviour, until the next one is sent.
### Steps to reproduce
1. Send the attachment as an e-mail to your provider.
2. Load K9
3. Get message summary

### Environment
K-9 Mail version: 5.010:

Android version: 5.1.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Please investigate.

**Comment by philipwhiuk** [comment] 2016-04-11 14:57
Duplicate of #1261

**Closed by philipwhiuk** 2016-04-11 14:57 UTC
