### ISSUE TITLE
Reply and Reply All broken

### ISSUE THREAD

**Issue by asaivan** [k9mail/k-9#4752] opened 2020-05-09 22:57 UTC
### Expected behavior
Reply or replay all autofills recipients and subject line

### Actual behavior
Blank email pops up

### Steps to reproduce
1. Reply to an email

### Environment

K-9 Mail version:
Beta 5.712

Android version:
9

Account type:
IMAP

**Comment by cketti** [comment] 2020-05-09 23:04
Duplicate of #4742

**Closed by cketti** 2020-05-09 23:04 UTC
