### ISSUE TITLE
e-mail account deleted by k9-mail without reason

### ISSUE THREAD

**Issue by Rotermila** [k9mail/k-9#4212] opened 2019-10-08 10:09 UTC
Hope this is new - did not find any information about this problem here or by google.

This morning it was the third time (within some month) k9-mail deleted my two e-mail accounts i use with k9. I have no glue why this happens. If there is no possibility to fix this I have to change my e-mail app on my handy. This is really annoing. Because I love k9-mail.

I'm sorry I have no information how this happens. I got a note for a e-mail this morning, that I wiped away. 15 Minutes later I opend k9-mail and it opened with the start screen and asked for a e-mail account. which means both accounts were deleted.

I use a Samsung SM-G800F; Firmware: MMB29K.G800FXXU1CRG3; Version: Marshmallow (6.0.1)

Would be great to get a short response.
Thank you for this great App so far!

**Comment by crazy4chrissi** [comment] 2019-10-10 11:05
This seems to be a duplicate of issue #750

**Comment by cketti** [comment] 2019-10-12 21:20
Duplicate of #750

**Closed by cketti** 2019-10-12 21:20 UTC
