### ISSUE TITLE
Add "Back" button in Compose

### ISSUE THREAD

**Issue by Valodim** [k9mail/k-9#2238] opened 2017-02-14 13:18 UTC
In most of our screens, the k9 icon in the top left is a "back" button. This is not the case in the Compose dialog, but it would be nice if it was :)

The particular action depends on the back stack: If the action was called from the message list, just return there. Otherwise, open up the K9 start screen. This can happen e.g. if the compose dialog is opened from some other app.

(@cketti sanity check please, I'm not entirely sure this is in line with android behavior guidelines? if it is, this can be a `beginner` issue)

**Comment by philipwhiuk** [comment] 2017-02-14 13:26
"Don't use labelled back buttons on action bars" ?

https://developer.android.com/design/patterns/pure-android.html

I don't see a need for a back button that reproduces the physical back button anywhere in the app.

**Comment by Valodim** [comment] 2017-02-14 13:38
Not labeled, and doesn't reproduce the physical back button. From your link:

> Instead, Android uses the main action bar's app icon for hierarchical navigation and the navigation bar's back button for temporal navigation.

Right now we don't have hierarchical navigation in the compose dialog, only temporal.

**Comment by philipwhiuk** [comment] 2017-02-14 22:35
Hmm that makes sense. Also from an aesthetic point of view it makes the app more consistent.

I guess this is a short term thing? I don't know how radical the Material stuff will change all this. Anyway, the stuff I posted is the relevant Android design docs so I think that's the sanity check.

**Comment by Valodim** [comment] 2017-02-14 23:17
Yup, makes sense. And the compose dialog is mo~stly fine, I guess it will be one of the last things to change. So mid term at least ;)

**Comment by cketti** [comment] 2017-02-14 23:21
https://developer.android.com/design/patterns/navigation.html

The "up" button should always go to the same activity. I'd say the message list. Right now it's a bit weird because there are many ways to get to the compose screen, meaning "up" and "back" will lead to different screens.
But things should be better when we have a design similar to Gmail, where the message list is the central part of the app.

**Comment by ployt0** [comment] 2017-02-19 21:15
I was in Account/Global settings just now and was forced to use my back button. I can only hope that option will always be there.
I've heard comments about the "weirdness" of the activity stack on k-9 before; sounds like a perfect opportunity to break it though :/

**Comment by pranavgupta1234** [comment] 2017-02-27 19:39
I would like to work on this :)

**Comment by jvss1996** [comment] 2017-02-28 10:46
I think that I can do work on this feature. Please guide me further.

**Comment by Pritom14** [comment] 2017-02-28 10:48
I would like to work on this #2289

**Comment by Pritom14** [comment] 2017-02-28 11:56
I have added the back button in Compose #2290 . Please guide me further

**Comment by joydeepsaha05** [comment] 2017-02-28 14:39
Please check #2292 for implemetation

**Comment by sanovikov71** [comment] 2017-02-28 14:46
Hi, can you please review the pr #2293?

**Comment by Pritom14** [comment] 2017-02-28 15:33
I have added the back button which depends on the back stack. Please review #2296

**Comment by philipwhiuk** [comment] 2017-02-28 22:04
Hi folks. 

In future if someone's already submitted a PR for an issue that's still open, it's probably more productive to pick a different issue as your changes will more likely to be merged. As it is, I've reviewed most (all?) of them now and suggested changes where relevant. It's likely we'll just pick one (or possibly a combination - the back stack manipulation code is only present in one PR) to merge in but I appreciate the enthusiasm you've all shown.

For additional reference we review all the PRs we get and if you mention the issue in your PR GitHub will link it here automatically so there's typically no need to add a note as well :)

**Comment by cketti** [comment] 2017-03-02 00:28
Please don't create any more pull requests for this. We'll go with a fixed up version of PR #2293.

**Closed** 2017-03-04 08:48 UTC
