### ISSUE TITLE
Replay, Replay to all, forward and forward as attachment of sent mails opens only a new message

### ISSUE THREAD

**Issue by deadletters** [k9mail/k-9#4744] opened 2020-05-08 21:10 UTC
### Actual behavior
Replay, Replay to all, forward and forward as attachment of sent mails opens only a new message

### Steps to reproduce
1. send a mail
2. open sent mails and there a mail
3. try to Replay/Replay to all/forward/forward as attachment

### Environment
K-9 Mail version:
5.712

Android version:
10
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment] 2020-05-08 21:13
Duplicate of #4742

**Closed by cketti** 2020-05-08 21:13 UTC
