### ISSUE TITLE
Duplicate folders

### ISSUE THREAD

**Issue by Cam-Gibb** [k9mail/k-9#1457] opened 2016-06-12 13:06 UTC
### Expected behaviour
Tell us what should happen = obvious.

### Actual behaviour
Tell us what happens instead = obvious.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

Is there way to remove duplicate folders without losing emails. ?? 

I suspect it may be causing issue of polling this account 10 mins instead of set 60 mins.

camgibb59@gmail.com

**Comment by Cam-Gibb** [comment] 2016-06-15 16:46
Fortunately this gmail acct is set to not delete fetched emails. So I was able to refetch after trying your "repopulate folders" option which GOT RID OF DUP'D FOLDERS.

**Comment by cketti** [comment] 2016-06-28 02:50
Duplicate of #1220

**Closed by cketti** 2016-06-28 02:50 UTC
