### ISSUE TITLE
when ignoring / typing into address bar during attempted auto completion suggestions, cursor jumps to signature section

### ISSUE THREAD

**Issue by fsantiago07044** [k9mail/k-9#2887] opened 2017-10-30 19:47 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
k9mail would allow me to simply finish typing in my desired email address and not care that i ignored the auto complete suggestions. 

### Actual behavior
if there is an auto complete suggestion, either from my address book or from sent history, and i keep typing in my custom address, ignoring the auto-complete, it was eventually cause my cursor to jump into the signature section of my email.

### Steps to reproduce
1. start new email
2. start typing in to: address
3. ignore auto-complete suggestion when it appears and continue typing

### Environment
K-9 Mail version: 5.208

Android version: O, 8.0.0, 9/5/2017 patches, on google pixel 2 (note, this also happened on a nexus 6p, and pixel 1 on android N thru now as well)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2017-10-30 19:50
Duplicate of #2829

**Closed by cketti** 2017-10-30 19:50 UTC
