### ISSUE TITLE
Feature request: Add option to delete messages off server once downloaded

### ISSUE THREAD

**Issue by kittenpirate** [k9mail/k-9#2566] opened 2017-06-03 01:11 UTC
### Expected behavior
There should be a way to not leave any messages on the server is one wishes. A check box that could be unchecked that says "Leave messages on server" or a check box that says "delete messages from server once downloaded" that can be checked.

### Actual behavior
There is no option for this at the moment.

### Environment
K-9 Mail version: 5.207

Android version: 7

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment] 2017-06-03 15:04
Duplicate of #580

**Closed by cketti** 2017-06-03 15:04 UTC
