### ISSUE TITLE
Cryptography settings are ambigiuous with multiple private keys

### ISSUE THREAD

**Issue by pshem** [k9mail/k-9#2510] opened 2017-04-22 16:42 UTC
I'd  like to propose an improvement for the settings screen inside Settings>Account Settings>Cryptography

### Expected behavior
"My key" should show the name and email on the chosen key

### Actual behavior
"My key" only shows "Key has been selected"

### Steps to reproduce
This is a problem when you happen to have more than one private key.
1. Create two email accounts
2. Create two PGP keys, one for each
3. Choose the appropriate key for each account

It's far too easy to misclick and choose the wrong key, and there is no way to check which key was chosen. This is simultaneously:
- a technical issue(the email will be signed by the wrong key), 
- a privacy issue(allows the recipient to connect purposefully isolated identities and get to know more email addresses of the sender),
- a UX issue(you only get the information on which key was chosen when encrypting the email, and if you chose wrong, it is very confusing).

A patch would include querying Open Keychain to reveal the identity connected with the chosen key(unless K9 already stores that information) and putting the result of this query into "My key". If doesn't have to be 100% of the identity, just enough to make different identities distinct, as in "last 4 digits of the credit card"

### Environment
K-9 Mail version: 5.206

Android version: Used: 5.1.1, but probably all are affected.

Account type (IMAP, POP3, WebDAV/Exchange): Any
label:enhancment
This ties into [https://github.com/k9mail/k-9/issues/942](url)

**Comment by rugk** [comment] 2017-10-04 19:27
Dupe of https://github.com/k9mail/k-9/issues/942?

**Comment by Valodim** [comment] 2017-10-04 19:38
very related, indeed. this part requires an overhaul anyways, I've been working on that. closing in favor of #942

**Closed by Valodim** 2017-10-04 19:38 UTC
