### ISSUE TITLE
unable to type in an address while creating new mail

### ISSUE THREAD

**Issue by zem** [k9mail/k-9#4662] opened 2020-04-13 14:14 UTC
K9mail 5.600 from F-Droid Store.

Unfortunately I am not able to complete typing an e-mail address in the address field, here is an example: 

You put some.body@example.com into the Addressbook so that lookup works. 

then type:  some.body@o

 and the cursor ends up in the new message field. You are unable to finish typing therdomain.com

You are also unable to fix the Address you have just typed which is annoying. 

Only Workaround is to copy and paste the e-mail Address which is even more annoying.

**Comment by cketti** [comment] 2020-04-13 23:29
Duplicate of #2829

**Closed by cketti** 2020-04-13 23:29 UTC
