### ISSUE TITLE
Move hidden scroll bar to left in folder view

### ISSUE THREAD

**Issue by dannysauer** [k9mail/k-9#2498] opened 2017-04-13 05:46 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

Clicking on unread or starred count next to a folder should display only unread or starred messages. 

### Actual behavior
Tell us what happens instead

List of folders scrolls because super annoying hidden scroll bar activates when clicking near the eight of the screen. 

### Steps to reproduce
1. Try to click on unread messages
2. Express disappointment in Android for not letting me disable the scroll bar that usually doesn't work in the rare instances when I actually want a scroll bar.
3.

### Environment
K-9 Mail version:
5.206
Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
Imap

**Comment by philipwhiuk** [comment] 2017-04-13 07:50
Duplicate of #894

**Closed** 2017-04-13 07:51 UTC
