### ISSUE TITLE
Bar with new/next/previous mails... hard to reach on new theme

### ISSUE THREAD

**Issue by tobiasBora** [k9mail/k-9#5652] opened 2021-09-06 09:36 UTC
**Is your feature request related to a problem? Please describe.**
I recently upgraded K-9 Mail: the new theme is great looking, but not always practical. Notably, the bar containing the buttons to create new emails, or go to the previous/next email has been moved to the top part of the screen. On mobile phones this is quite hard to use with a single hand since I need to stretch my finger to reach the top part of my screen every time I want to write an email or move in a conversation.

**Describe the solution you'd like**
I'd like an option to move this bar to the bottom part of the screen, like before.

**Comment by cketti** [comment] 2021-09-06 17:00
Duplicate of #5447

**Closed by cketti** 2021-09-06 17:00 UTC
Labels: enhancement
