### ISSUE TITLE
No Body Text in quoted or forwardet  Mail after decryption

### ISSUE THREAD

**Issue by webratte** [k9mail/k-9#1400] opened 2016-05-23 19:43 UTC
### Expected behaviour
If I reply or forward a decrypted Mail there should be quoted the whole Mail.

### Actual behaviour
It's only quoted Header and subject
In unencrypted Mails it works fine.

### Steps to reproduce
1. Receive a encrypted Mail
2. Decrypt this Mail
3. Press the Reply or Foward Button.

If you forward a decrypted Mail the quoted Mail will sendet as attachement "encrypted.asc"

### Environment
K-9 Mail version:
5.109
Android version:
5.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Valodim** [comment] 2016-05-23 19:49
this seems like a duplicate of #1225? I have a branch which implements this, so this will be added somewhere down the line. but it's not ready yet and I have other things to finish first.

thanks for the report anyways :+1:

**Closed by Valodim** 2016-05-23 19:49 UTC

**Comment by webratte** [comment] 2016-05-24 15:46
Sounds great 👍

If you fixed and released it, I can remove all other Mail Clients.

Thanks for your work.
