### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by sharddin** [k9mail/k-9#3969] opened 2019-03-16 13:06 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
Very more lags in the job of program and with scrollings. Very bad optimization?

**Comment by sharddin** [comment] 2019-03-16 13:08
Sorry for my over quotting!... I writed: Very more lags in the job of program and with scrollings. Very bad optimization?

**Comment by ByteHamster** [comment] 2019-03-17 08:13
Please edit your first post and fill out the complete template. It's there for a reason. Without filling out, nobody can help you and the issue will be ignored or closed. There are no lags on my device. To find out what is different on your device, we need all the steps you do and information about your device.

Are you talking about the list of messages? Does turning off contact pictures and names of known contacts fix the lag?

**Comment by cketti** [comment] 2019-03-20 15:58
Duplicate of #747

**Closed by cketti** 2019-03-20 15:58 UTC
