### ISSUE TITLE
K-9 doesn't quote when replying

### ISSUE THREAD

**Issue by raibu72428** [k9mail/k-9#3275] opened 2018-03-23 10:05 UTC
**### Expected behavior**
K-9 doesn't quote messages when replying even though Quote message when replying is on.

**### Actual behavior**
Tell us what happens instead

**### Steps to reproduce**
Try to reply to any message sent from another K-9 user.

**### Environment**
K-9 Mail version: 5.403
Device: Xiaomi Mi 6
Android version: 7.1.1 NMF26X
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2018-03-23 16:17
Works fine for me. Please include detailed information on what kind of message you reply to. Also include detailed steps on what you do to reply to a message.

Please also note that tapping the "X" icon on the quoted text will remove the quote, not just hide it in the compose screen. If you're doing that, everything works as intended.

**Comment by Heineken** [comment] 2018-03-26 09:48
Happens for me only when replying to PGP encrypted mails, which is an issue indeed.
Can you confirm @raibu72428 ?

**Comment by klic** [comment] 2018-04-02 09:29
For me also only happening with encrypted mails.

**Comment by cketti** [comment] 2018-04-02 21:55
Can you please test with version 5.503: https://github.com/k9mail/k-9/releases/tag/5.503

**Comment by klic** [comment] 2018-04-03 14:28
This version does quoting correctly

**Comment by Heineken** [comment] 2018-04-09 11:56
I'd try 5.503, but it won't install as an update.

**Comment by cketti** [comment] 2018-04-09 12:00
Our APKs won't install as update if you installed the app from F-Droid. In that case it's best to wait for a new stable version to be available on F-Droid (5.5xx are development snapshots).

Closing this issue as the bug seems to be fixed.

**Closed by cketti** 2018-04-09 12:00 UTC
Labels: needs info
