### ISSUE TITLE
Have option to show both correspondant name and email address in message view

### ISSUE THREAD

**Issue by rancidfrog** [k9mail/k-9#2704] opened 2017-08-25 11:42 UTC
The option at the moment is either one or the other:
![](https://s29.postimg.org/4wbg3x4xj/Screenshot_20170810-163545_01.png)
But as most devices are 5"+ there should be an option to show both, at least when actually reading particular mail, (message view).

**Comment by cketti** [comment] 2017-08-27 21:49
Duplicate of #1119

**Closed by cketti** 2017-08-27 21:49 UTC
