### ISSUE TITLE
K-9 crash by switching to second account

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [k9mail/k-9#4376] opened 2019-12-14 16:35 UTC
I have first reported this here: https://github.com/k9mail/k-9/issues/4359#issuecomment-565692897

I added a second account (IMAP) to K-9 and now, if I try to switch to this account, K-9 crash.

I tried to create a debug log (like described in the K-9 docs), but aLogcat shows me nothing - IDK what I'm doing wrong! But maybe because I haven't rooted this device, yet... (???)

### Environment
K-9 Mail version: 5.702

Android version: Android 9 Stock ROM

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ravvle** [comment] 2020-01-03 04:20
I get this same issue when switching accounts. I can switch to the unified view fine, but i cannot switch to my second account. It might be worth noting that the second account hasn't had any mail sync yet.

Environment:

K-9 Mail version: 5.703
Android version: Android 9 (Samsung Galaxy s8 - stock)
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ravvle** [comment] 2020-01-03 04:55
So it seems like the crash happens if I do a fresh install, import my old settings and then enter the second accounts password wrong.

If i set it up correctly first time and then modify the password to be wrong it does not crash. If I enter everything correctly the first time it seems to all work ok.

**Comment by cketti** [comment] 2020-02-07 14:17
Duplicate of #3691

**Closed by cketti** 2020-02-07 14:17 UTC
