### ISSUE TITLE
White icons with light theme

### ISSUE THREAD

**Issue by dimqua** [k9mail/k-9#4295] opened 2019-11-27 17:47 UTC
When the light theme is enabled (at least, manually), its hard to distinguish toolbar icons, since they're light too. It'd be better to use dark gray icons in this case instead.

![](https://framapic.org/VZnUXas6dUVv/FnpmJTLaw0Vt)

### Environment
K-9 Mail version: 5.700
Android version: LineageOS 17.0

**Comment by cketti** [comment] 2019-11-28 18:29
This is working fine on my test device running "proper" Android. Maybe it's a LineageOS issue.

**Comment by dimqua** [comment] 2019-11-28 19:47
This is probabaly because of my system Android 10 theme is dark.

**Comment by cketti** [comment] 2019-12-01 15:00
I doubt logs will help in this case. Unless someone with development experience tracks down the cause of this on an affected device, I don't think there's anything we can do.

I'm leaving this issue open for a while so users with the same issue can find it. But unless this is also happening on devices not using LineageOS I'll close it in a few weeks.

**Comment by Bubu** [comment] 2019-12-10 22:55
I have this as well on LineageOS 15.1, so it's not related to system theming. 
It's not happening consistently, and always fixed by reopening the k9 activity.

**Comment by dimqua** [comment] 2019-12-11 11:40
It appears to be fixed in the latest version, 5.701.

**Comment by Bubu** [comment] 2019-12-16 14:49
Seems fixed for me as well since 5.701

**Comment by Bubu** [comment] 2019-12-25 12:25
@dimqua want to close this?

**Comment by Bubu** [comment] 2019-12-25 12:30
@dimqua want to close this?

**Closed** 2019-12-25 12:41 UTC
Labels: needs info
