### ISSUE TITLE
Unified Inbox is slow

### ISSUE THREAD

**Issue by sedrubal** [k9mail/k-9#4899] opened 2020-08-03 08:34 UTC
### Expected behavior
When you open the unified inbox, the messages should appear immediately.

### Actual behavior
When I open the unified inbox, the list of messages is empty for about 10 seconds. Then the messages appear.

### Steps to reproduce
1. Set up k-9 mail with >4 IMAP Accounts. Some of them should have >1000 messages
2. Tap on unified inbox

### Environment
K-9 Mail version: 5.717
Android version: 9 (lineage os 16)
Account type: 6 IMAP accounts
*The debug log does imho not contain any useful information.*

**Comment by cketti** [comment] 2020-08-30 18:36
K-9 Mail uses one SQLite database per account. So performance of the Unified Inbox is as bad as it can get.

The more general issue is that we load all available messages into the list view and don't do any kind of lazy loading.

Duplicate of #3472

**Closed by cketti** 2020-08-30 18:36 UTC
