### ISSUE TITLE
support modern authentication SAML

### ISSUE THREAD

**Issue by zez3** [k9mail/k-9#6046] opened 2022-04-29 17:46 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.912

### Problem you are trying to solve

Since more and more mail Servers are now using SAML for authentication, there's a need to implement it in K9.
More concrete, I could test with Exchange Online.
To push this forward I am also open to discuss a form of sponsorship(more than ☕ donation) to have this implemented with MFA

### Suggested solution

Implement SAML authentication with MFA via client default local Browser(Cookie)

### Screenshots / Drawings / Technical details

TBD

**Comment by cketti** [comment] 2022-05-01 17:08
Duplicate of #1753

**Closed by cketti** 2022-05-01 17:08 UTC
Labels: enhancement
