### ISSUE TITLE
Feature request: Mark email as read before deleting it

### ISSUE THREAD

**Issue by mythran** [k9mail/k-9#3298] opened 2018-04-03 01:40 UTC
It would be usefull if a setting could exist which causes that a to delete email is marked as read before deleting it via the notification on the lock screen or home screen or via the context menu, so that this email does not appear as unread with in other email clients which accessing the same IMAP account.

**Comment by ByteHamster** [comment] 2018-04-03 08:43
That option is already available:

- Settings
- Global Settings
- General 
- Delete marks as read

**Comment by cketti** [comment] 2018-04-03 12:01
Duplicate of #591

**Closed by cketti** 2018-04-03 12:01 UTC
