### ISSUE TITLE
Feature request: Only download big messages over wifi

### ISSUE THREAD

**Issue by felagund** [k9mail/k-9#3457] opened 2018-06-21 08:08 UTC
Currently ,there is a setting in Account>Fetching mail>Fetch messages up to that sets a limit for messages to be fetched. I would like that limit be conditioned on connection, so it would only apply on cellular connection (that is metered for some user like me). 

Use case: I have a 300 MB monthly plan at the moment and I do not want 1/15th of if to be eaten by a 20 MB attachment.

**Comment by cketti** [comment] 2019-03-08 02:54
Duplicate of #1184

**Closed by cketti** 2019-03-08 02:54 UTC
