### ISSUE TITLE
Add ability to export/import existing email data.

### ISSUE THREAD

**Issue by zellchristensen** [k9mail/k-9#5875] opened 2022-01-20 16:48 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.806

### Problem you are trying to solve

When using the Export settings feature, existing messages on the device are not exported, and thus not imported when importing again.  Any messages would have to be re-downloaded from the server after removing an account and importing it again.

### Suggested solution

It would be great if all saved data on the device could be exported and imported including offline drafts that may not be synced to the server yet.  

### Screenshots / Drawings / Technical details

Perhaps a checkbox option in the Export and Import settings menus under General Settings and above the first account such as "Include email data" that is unchecked by default.

**Comment by cketti** [comment] 2022-01-20 16:58
Duplicate of #3627

**Closed by cketti** 2022-01-20 16:58 UTC
Labels: enhancement
