### ISSUE TITLE
Pinch to zoom within email body

### ISSUE THREAD

**Issue by Chris-Pa** [k9mail/k-9#2064] opened 2017-01-16 12:14 UTC
Following latest update, pinch to zoom no longer works as expected

### Expected behavior
Should behave as you'd expect in any typical android - any pinch gesture zooming in and out as expected

### Actual behavior
Tell us what happens instead

Pinch to zoom only seems to work when doing a horizontal pinch - if your fingers aren't aligned left to right relative to the screen then it won't zoom.

Also, once zoomed, can't scroll back to the top of the email

### Steps to reproduce
1. Open email
2. Try pinching to zoom
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by Chris-Pa** [comment] 2017-01-16 12:16
Sorry, caught the submit button by accident

K9 mail version
5.202

**Comment by Chris-Pa** [comment] 2017-01-16 12:19
Android 6.0.1
Sony xperia z5
IMAP

**Comment by philipwhiuk** [comment] 2017-01-16 12:37
Duplicate of about a dozen existing issues e.g. #1886

**Closed by philipwhiuk** 2017-01-16 12:37 UTC

**Comment by Chris-Pa** [comment] 2017-01-16 12:54
Hello thanks for the swift response

Sorry for creating a duplicate bug report. The problem is that all of the previous bug reports are closed, so if you're looking at *open* issues - particularly using the mobile interface into Github - then it appears that this has't been reported.

I'd have thought that the issues were closed once the fix was in released/available code and it's new behaviour could be confirmed.

**Comment by philipwhiuk** [comment] 2017-01-16 15:40
No we close issues when the issue is fixed.

I would agree that GitHub's issue system isn't particularly good. The problem is the merge-close PR behaviour GitHub exhibits doesn't account for the need for a release.
