### ISSUE TITLE
Sync only during specified intervals

### ISSUE THREAD

**Issue by asarubbo** [k9mail/k-9#2617] opened 2017-07-05 11:07 UTC
The fetch for the imap accounts configured on k-9 happens 24/7.
Since from the 09:00 to 18:00 I'm in the office, and I have configured the work's email, k-9 fetches them even if I'm reading the email from the pc.
While I'm using the silent notify option I notice that every time I see the phone it is always fetching something.
I'd like to fetch the email in some intervals instead of "Never/always/when autosync is active"

### Expected behavior
I'd like to fetch the email in some intervals instead of "Never/always/when autosync is active"
### Actual behavior
It fetches 24/7

### Steps to reproduce
1. Just add an imap account and it will fetch continuously.

### Environment
K-9 Mail version: 5.206

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2019-03-01 00:27
Duplicate of #1610

**Closed by cketti** 2019-03-01 00:27 UTC
Labels: enhancement
