### ISSUE TITLE
Notificatons not removed after reading mails on 5.1.1 Android

### ISSUE THREAD

**Issue by iloveeclipse** [k9mail/k-9#1216] opened 2016-03-25 22:54 UTC
### Expected behaviour
Tell us what should happen
K9 shows a notification about new mail, user clicks this to read mail, after reading the mail notificaton is removed. 
### Actual behaviour
Tell us what happens instead
Notificatons stay in the system tray. The only way to remove them is to manually swipe them away. 
### Steps to reproduce
Can reproduce with latest K9 version on Galaxy A3 2016. Uses 5.1.1 Android, default Samsung UI.
Can NOT reproduce on Galaxy Tab S2. Uses 5.0.2 Android, default Samsung UI. 
In both cases same settings and same account was used, it is IMAP Gmx.de account. 

### Environment
K-9 Mail version:
5.0.0.8
Android version:
5.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment] 2016-03-26 03:16
This is already fixed in the current alpha version. The next major stable version will also include this fix.

Duplicate of #1110

**Closed by cketti** 2016-03-26 03:16 UTC
