### ISSUE TITLE
Can't connect to IMAP server with SSL on port 993 - no error given

### ISSUE THREAD

**Issue by nathanzachary** [k9mail/k-9#3141] opened 2018-01-26 19:57 UTC
### Expected behavior
K-9 mail should connect to the IMAP server with SSL enabled

### Actual behavior
K-9 mail simply states that it cannot connect to the server (no further information provided)

### Steps to reproduce
1. Enter account details (IMAP with SSL, port 993)
2. Hit next
3. It fails to connect to the server

### Environment
K-9 Mail version: 5.403

Android version: Tried with 4.4.2 on an old tablet, on 7.0 on a Motorola G5, and on 7.1.1.

Account type (IMAP, POP3, WebDAV/Exchange): IMAP with SSL on port 993 for incoming

Some information about the incoming server:

>>>>>
nmap --script ssl-enum-ciphers -p 993 mail.$SERVER.com

Starting Nmap 7.60 ( https://nmap.org ) at 2018-01-26 13:03 CST
Nmap scan report for mail.$SERVER.com ($IP)
Host is up (0.070s latency).

PORT    STATE SERVICE
993/tcp open  imaps
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp384r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp384r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp384r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp384r1) - A
|     compressors: 
|       NULL
|     cipher preference: client
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 3.51 seconds
>>>>>

I removed the server name and IP, but the nmap scan shows the available ciphers.  I'm wondering if that is the problem.  The odd part is that the same settings work in Thunderbird without problem.

IMAP server
Port 993
SSL/TLS
Normal Password

I didn't see anything obvious when I dumped the log information via adb.

**Comment by philipwhiuk** [comment] 2018-01-27 02:25
> I didn't see anything obvious when I dumped the log information via adb.

There ought to be a stack trace showing the connection failure at minimum. This would be extremely useful

**Comment by nathanzachary** [comment] 2018-01-27 02:31
Hello Philip,

Thanks for your response.  When I used the adb command listed here: https://k9mail.github.io/documentation/debugging.html

I basically got an empty log file.  When I just shortened it to:
adb logcat -d -v time

I was able to see more on stdout, but nothing showing the connection failure.  Do you have a suggestion on a modification that will provide you with the information you need in the log file?

Thanks!

Cheers,
Nathan Zachary

**Comment by philipwhiuk** [comment] 2018-01-27 03:22
I've just updated the documentation to correct the commands you need.

Thanks!

**Comment by uj** [comment] 2018-01-28 15:21
I have the same issue.  I can connect with no encryption, but if I use SSL/TLS or STARTTLS, it does not connect.  It simply says it cannot connect.  However, I can connect with other android email clients and  can connect with other PC clients.

What I did to fix it for now was change the ciphers used on the dovecot mailserver, and it works.

This does NOT work with K-9, but works with everything else:
ssl_cipher_list = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256

This works with everything:
ssl_cipher_list =  ECDHE-RSA-ES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA

**Comment by philipwhiuk** [comment] 2018-01-28 15:36
Most likely your phone doesn't have any of the new ciphers.

You shouldn't need the CBCs, the NULLs and MD5 ciphers.

**Comment by nathanzachary** [comment] 2018-01-29 17:29
[k9log.txt](https://github.com/k9mail/k-9/files/1674594/k9log.txt)

I couldn't get the new command to work because apparently my version of logcat doesn't support the pid option.  However, I just went through and grepped out the pid into a new log (attached here, but scrubbed the domain and IP of the mail server).

My guess is that the relevant stack trace is this portion:
`I/ActivityManager(  483): START u0 {cmp=com.fsck.k9/.activity.setup.AccountSetupCheckSettings (has extras)} from pid 23327
D/ImapConnection(23327): Connecting to mail.DOMAIN.COM as mail.DOMAIN.COM/IP_ADDRESS
D/InputMethodManagerService(  483): --- calledFromForegroundUserOrSystemProcess ? calling uid = 10099 system uid = 1000 calling userId = 0, foreground user id = 0, calling pid = 23327com.android.server.InputMethodManagerService.windowGainedFocus(InputMethodManagerService.java:1882)
E/ImapConnection(23327): Failed to login, closing connection for conn568406216
E/AccountSetupCheckSettin(23327): Error while testing settings
E/AccountSetupCheckSettin(23327): com.fsck.k9.mail.MessagingException: Unable to connect
E/AccountSetupCheckSettin(23327):       at com.fsck.k9.mail.store.imap.ImapStore.checkSettings(ImapStore.java:308)
E/AccountSetupCheckSettin(23327):       at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkIncoming(AccountSetupCheckSettings.java:497)
E/AccountSetupCheckSettin(23327):       at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkServerSettings(AccountSetupCheckSettings.java:467)
E/AccountSetupCheckSettin(23327):       at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:424)
E/AccountSetupCheckSettin(23327):       at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.doInBackground(AccountSetupCheckSettings.java:402)
E/AccountSetupCheckSettin(23327):       at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AccountSetupCheckSettin(23327):       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AccountSetupCheckSettin(23327):       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AccountSetupCheckSettin(23327):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AccountSetupCheckSettin(23327):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AccountSetupCheckSettin(23327):       at java.lang.Thread.run(Thread.java:841)
E/AccountSetupCheckSettin(23327): Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x64c18910: Failure in SSL library, usually a protocol error
E/AccountSetupCheckSettin(23327): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5fe68cb0:0x00000000)
E/AccountSetupCheckSettin(23327):       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
E/AccountSetupCheckSettin(23327):       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:661)
E/AccountSetupCheckSettin(23327):       at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:632)
E/AccountSetupCheckSettin(23327):       at com.fsck.k9.mail.store.imap.ImapConnection.setUpStreamsAndParserFromSocket(ImapConnection.java:236)
E/AccountSetupCheckSettin(23327):       at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:120)
E/AccountSetupCheckSettin(23327):       at com.fsck.k9.mail.store.imap.ImapStore.checkSettings(ImapStore.java:304)
E/AccountSetupCheckSettin(23327):       ... 10 more
E/AccountSetupCheckSettin(23327): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x64c18910: Failure in SSL library, usually a protocol error
E/AccountSetupCheckSettin(23327): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5fe68cb0:0x00000000)
E/AccountSetupCheckSettin(23327):       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/AccountSetupCheckSettin(23327):       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
E/AccountSetupCheckSettin(23327):       ... 15 more
`

In particular, this seems to be the SSL error:
`E/AccountSetupCheckSettin(23327): Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x64c18910: Failure in SSL library, usually a protocol error
E/AccountSetupCheckSettin(23327): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5fe68cb0:0x00000000)
`

Cheers,
Nathan Zachary

**Comment by nathanzachary** [comment] 2018-01-29 17:33
I should also mention that this log is from an old tablet that I was using for debugging (running Android 4.4.2).  Seeing similar connection failures from a Motorola G5 running Android 7.0, so I don't think that it is limited to Android 4.4.2.

It does seem like a problem with the available ciphers.

**Comment by philipwhiuk** [comment] 2018-01-29 18:54
Closing as duplicate of #893 given debug log.

**Closed by philipwhiuk** 2018-01-29 18:54 UTC
Labels: needs info
