### ISSUE TITLE
feature request: print a mail

### ISSUE THREAD

**Issue by treakiandroid** [k9mail/k-9#3260] opened 2018-03-14 08:47 UTC
Since some time now android supports printing and with some fiddeling around with ipp ou can even print on not officially supported printers using a cups server on some computer im the netzwerk.

But one of the most important features, quick printing out a mail, still requires to open a mail programm on desktop. So it would be very nice if you could use th android WebKit/ pdf /whatever nterface to send some mails to the printer directly without loading the k9mail apk withcany big libs (not more ten 720 k filesize increase i would think or build an addon to print mails if it needs tons of binarys to convert mails to print format.

Or maybe just make some fake views in the background with reasonable high dpi, set some text fiels in the op and bottom (top subject, date, bottom page number, total number of page) and put some big webview in the middlecof it,bigger then size, againcandcagaim while scrolling and counting line numbers, do a screenshot and send that to the printer. If thats eseyer, would be ugly to render a bitmap on device but if android doesn't gives you library on default its imho better then a much bigger apk

Thanks

**Comment by philipwhiuk** [comment] 2018-03-14 10:48
Duplicate of #1062

**Closed by philipwhiuk** 2018-03-14 10:48 UTC
