### ISSUE TITLE
Load images when WLAN active

### ISSUE THREAD

**Issue by THausherr** [k9mail/k-9#5535] opened 2021-08-06 15:18 UTC
**Is your feature request related to a problem? Please describe.**
I have disabled the loading of images because mobile bandwidth is expensive in Germany. So I download images manually (tap the "show pictures" button), e.g. when getting ebay search result lists. However I have to do this at home too, although this shouldn't be needed.

**Describe the solution you'd like**
I'd like to have an additional setting in the dialog below "[x] always load pictures when WLAN active"

**Describe alternatives you've considered**
Changing the settings each time when leaving home / returning home.

**Additional context**
![grafik](https://user-images.githubusercontent.com/6665575/128532290-0bd2407e-dd59-4267-bace-16a55ccaa4ac.png)

Both twitter and instagram have settings related to mobile bandwidth, so my idea isn't that wild.

**Comment by cketti** [comment] 2021-08-06 15:25
Duplicate of #1502

Note: Not automatically loading images is mainly a privacy feature. Many email senders use images to track who has read their emails and when.

**Closed by cketti** 2021-08-06 15:25 UTC
Labels: enhancement
