### ISSUE TITLE
Signing into yahoo fails

### ISSUE THREAD

**Issue by handyj** [k9mail/k-9#1742] opened 2016-10-22 01:52 UTC
### Expected behavior
Enter/change password and connect to yahoo email

### Actual behavior
Valid user and password configured on fetch and send. Error saying invalid I'd or password.

### Steps to reproduce
1.settings
2.a account settings
3.fetching mail
4. Incoming server
5. Accept all defaults for yahoo
6. Enter password
7. Receive I'd/ password error
Authenticate plain; response#1#no, authenticationfailed,mbr1212

### Environment
K-9 Mail version: 4.3

Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP.

Uninstall k-9 / install k-9, issue remains. Id and password are valid and have been verified on yahoo web page. App works without fail on similar phone, all versions the same.

**Comment by philipwhiuk** [comment] 2016-10-23 03:20
Yahoo added XOAUTH and deprecated older methods of sign-in, without warning, probably to detract from their terrible security practices recently.

Duplicate of #1698

**Closed by philipwhiuk** 2016-10-23 03:20 UTC
