### ISSUE TITLE
Opening links does not open browser

### ISSUE THREAD

**Issue by FliegendeWurst** [k9mail/k-9#4521] opened 2020-02-08 17:10 UTC
Existing issues: #587 #673 but it occurs in newer versions.

### Expected behavior
Opening a link should open a new browser tab.

### Actual behavior
The link is opened in the mail view.

### Steps to reproduce
1. View (HTML) mail with link.
2. Open link.

### Environment
K-9 Mail version: 5.704
Android version: 6.0
Account type (IMAP, POP3, WebDAV/Exchange): IMAP
Logs: probably not relevant for this issue

**Comment by cketti** [comment] 2020-02-08 18:19
Duplicate of #4498

**Closed by cketti** 2020-02-08 18:19 UTC
