### ISSUE TITLE
Addressie name appears instead of email address

### ISSUE THREAD

**Issue by dabear2** [k9mail/k-9#1970] opened 2017-01-05 00:18 UTC
### Expected behavior
When composing an email and adding an email address (TO, CC, or BCC) of an email that is in the contact list and I tap the address as it pops up and the address should then be displayed on the TO (or whichever) line I put it on.
This is how it worked in 5.010

### Actual behavior
In the 5.020 it lets you select the found email address associated with the contact, but then the **contact name** is what is placed on the TO line, not the email address. 

### Steps to reproduce
1.   Go to Main menu, Settings, Display;  ensure that "show Correspondent names" is UNChecked
2.   Compose an email by typing the email address of at least one contact in your contacts
3.    When it finds the email address, tap it and you'll see only the contact name.

### Environment
K-9 Mail version:5.020

Android version:6.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by philipwhiuk** [comment] 2017-01-05 10:08
Duplicate of #1892

**Closed by philipwhiuk** 2017-01-05 10:08 UTC
