### ISSUE TITLE
Ability to select monospaced font for composing messages

### ISSUE THREAD

**Issue by AlainKnaff** [k9mail/k-9#3008] opened 2017-12-30 19:19 UTC
### Expected behavior
Letters should line up under each other properly, so that users can flag words by using ^^^^ on the line beneath, so that Ascii graphics can be entered, or to make it easier to see when to break a line.

### Actual behavior
Letters don't line up under each other

### Steps to reproduce
1. Compose a mail with the following contents:

mmmmmmmm
.....

2. Watch how the m's and the dots don't line up...

... or, if for some reason this can't be made the default, it should at least be configurable, like it is for reading incoming mails.

### Environment
K-9 Mail version:
5.400

Android version:
4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
any (tested with IMAP)

**Comment by cketti** [comment] 2018-01-19 03:19
Duplicate of #907

**Closed by cketti** 2018-01-19 03:19 UTC
Labels: enhancement
