### ISSUE TITLE
IMAP IDLE - Closing connection after 30 seconds

### ISSUE THREAD

**Issue by N-ik05** [k9mail/k-9#1701] opened 2016-10-11 09:36 UTC
### Expected behavior
Expecting to correctly setup a connection for IMAP PUSH/IDLE to work.

### Actual behavior
In the logs I can see an exception is thrown while idling, resulting in the pusher being disabled because of too many errors. I have attached the log file (adb logcat -v time k9:V '*:S' AndroidRuntime:E).
[k9-log2.txt](https://github.com/k9mail/k-9/files/521455/k9-log2.txt)

### Steps to reproduce
1. Setup IMAP account, with polling disabled.
2. Boot phone
3. Watch the logs...
4. Maybe, have my email provider

### Environment
K-9 Mail version: Had it in 5.113, reinstalled 5.010 which also has the problem

Android version: CM 13 nightly bacon

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Doze: inactive timeout = 24h, k-9 mail is in battery optimization ignore

### Question

Could this be the result of a bug in K-9 mail or is this my provider not handling IMAP IDLE connections correctly?

Thank you very much for looking into this.

**Comment by philipwhiuk** [comment] 2016-10-11 11:28
I am (fairly slowly) looking into not disabling PUSH for certain errors (and adding functionality to easily restart push) to solve Doze related issues. But the issue here is your provider basically doesn't support IDLE to be honest.

Snippet:

```
10-10 22:48:47.772 I/k9      (17158): About to IDLE for NAME:INBOX/Thread-145/conn186973973
10-10 22:48:47.772 V/k9      (17158): conn186973973>>> 3 IDLE
10-10 22:48:47.792 V/k9      (17158): Got async response: #+# [idling]
10-10 22:48:47.792 D/k9      (17158): Idling NAME:INBOX/Thread-145/conn186973973
.....
10-10 22:49:18.145 E/k9      (17158): Got exception while idling for NAME:INBOX/Thread-145
10-10 22:49:18.145 E/k9      (17158): java.io.IOException: readStringUntil(): end of stream reached
```

They're closing the stream 30 seconds after we send IDLE. That's just not correct.

The IDLE spec says we should send a heartbeat every 30 **minutes**. Heartbeating every 30 seconds is silly - you may as well just poll.

**Comment by N-ik05** [comment] 2016-10-11 18:15
Thank you very much for looking into it @philipwhiuk.  I will contact my provider with this information. Hopefully they can fix this soon.

Isn't the heartbeat already configurable? At Account settings, Fetching mail, advanced, Refresh IDLE connection; you can already change it to refresh every minute.

**Comment by philipwhiuk** [comment] 2016-10-12 16:18
Closing as issue not caused by K-9

**Closed by philipwhiuk** 2016-10-12 16:18 UTC
Labels: invalid
