### ISSUE TITLE
Option: place replies in the folder of the message being replied to

### ISSUE THREAD

**Issue by cbrace** [k9mail/k-9#1767] opened 2016-10-31 11:42 UTC
This is a standard option many email clients, such as Thunderbird and Roundcube. It would be very convenient to have this option in K9 as well.  Thanks for considering it.

**Comment by zvoniimiir** [comment] 2016-11-15 16:34
Also would like this feature.

**Comment by cketti** [comment] 2019-02-28 22:48
Duplicate of #2266

**Closed by cketti** 2019-02-28 22:48 UTC
Labels: enhancement
