### ISSUE TITLE
cannot connect to IMAP outgoing server (incoming works)

### ISSUE THREAD

**Issue by cast-away** [k9mail/k-9#3316] opened 2018-04-08 23:29 UTC
### Expected behavior
"Cannot connect to server. (Unable to connect)" error should be more specific, probably related to #3141

### Actual behavior
connecting to imap server after updating ssl certificate not working (k9 only, no issues with thunderbird) and error does not provide any information on why. Oddly enough same settings for outgoing server work fine.

### Steps to reproduce
1. change ssl certificate + smtp url on site
2. update details on k9

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP with SSL on port 993 for incoming

**Comment by philipwhiuk** [comment] 2018-04-15 23:07
Duplicate of #1789

**Closed by philipwhiuk** 2018-04-15 23:07 UTC
