### ISSUE TITLE
Auto Sync hit or miss on Galaxy S9+

### ISSUE THREAD

**Issue by dlathem** [k9mail/k-9#3430] opened 2018-06-06 18:06 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
K-9 should check for new mail at the intervals I have set for each account.

### Actual behavior
Sometimes K-9 will check the mail at the intervals set and sometimes it does not.  I have 4 email accounts set up on my S9+ just like I had them on my Note 4.  The Note 4 works perfectly, the S9+ does not.  I have to constantly manually check email to make sure I do not miss something.  It will so hours without check mail.  I have background sync on always.

### Steps to reproduce
1. have the device turned on
2.
3.

### Environment
K-9 Mail version: 5.403

Android version:8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): POP

**Comment by tvlovers** [comment] 2018-06-08 22:12
I'm using Note8 on Android 7, but Galaxy 9 should be very similar.

Try the following:
settings ->device maintenance -> battery and then:
1. unmonitored apps -> add K-9 -> go back to battery sub menu
2. battery usage -> 3 dots -> optimize battery usage -> change "apps not optimized"  to "all apps" view -> turn K-9 off
3. restart your phone

**Comment by dlathem** [comment] 2018-06-12 02:05
Thanks for the suggesstion.  I saw the settings shown in step #1.  I could not find the menu options under step #2 on my phone.  I made the changesbgg under 1 and rebooted, but K-9 still does not sync.

**Comment by dlathem** [comment] 2018-06-12 02:33
I went back in to the menus and finally found step #2.  I made the changes an rebooted.  I have done several test and it now appears to work.  Thank you for the help..I hope it lasts.

**Comment by madfmy** [comment] 2018-08-14 16:11
dlathem - where did you find step 2

**Comment by dkowis** [comment] 2019-02-13 22:13
I haven't been able to keep synching enabled on my Note 9

I have attempted to do the steps, and I'll plop screenshots showing.
I went to bettery and device maintenance. At the bottom is "Unmonitored apps"
![screenshot_20190213-160901_device maintenance](https://user-images.githubusercontent.com/28048/52747687-0c5edc80-2faa-11e9-94e9-08dcf5084cc5.jpg)

I added k9mail to that list:
![screenshot_20190213-160906_device maintenance](https://user-images.githubusercontent.com/28048/52747732-2d273200-2faa-11e9-87cd-087f7c60e7dc.jpg)

Then I disabled the "put apps to sleep in the background" setting under 3-dots advanced:
![screenshot_20190213-160959_device maintenance](https://user-images.githubusercontent.com/28048/52747752-3d3f1180-2faa-11e9-8732-c0992bd624e2.jpg)


Despite this, synching gets disabled pretty quickly :(

**Comment by cketti** [comment] 2019-03-08 02:27
Duplicate of #3950

**Closed by cketti** 2019-03-08 02:27 UTC
