### ISSUE TITLE
[feature request] add an option to ask for a password on each k9 opening

### ISSUE THREAD

**Issue by dcaillibaud** [k9mail/k-9#4796] opened 2020-05-29 12:13 UTC
Hi,

I don't want to lock my phone (password or gesture are easy to stole if you need to do it all the time), the only thing I want to lock is my mail access (a lot of 2 way authentication with mail for important purposes).

An option to set a global password to open k9 will be great (or an option "allways ask for password" on each mail account, but in my case I prefer a global pass to all accounts).

It could also be usefull for people who often lend their phone to husband/wife/children/… but doesn't want to give mail access, with a lock access to the phone or not (these people who borrow the phone usually know the unlock code).

Thanks a lot

**Comment by cketti** [comment] 2020-05-29 15:01
Duplicate of #753

**Closed by cketti** 2020-05-29 15:01 UTC
