### ISSUE TITLE
important-icon not clickable

### ISSUE THREAD

**Issue by theCalcaholic** [k9mail/k-9#1957] opened 2017-01-04 07:01 UTC
### Expected behavior
In the email list view there is a star icon which appears to be supposed to be clickable. So expectedly, when I click on it the according message should be marked or unmarked (toggle) important. 

### Actual behavior
Instead once I click on the icon the scroll bar appears and I'm immediately taken to the position on the scrollbar I was (unknowingly) clicking. The same obviously happens when clicking on the star icon while the scroll bar is visible already. 

### Steps to reproduce
1. Open the message overview for any email account. 
2. Try to click on the star icon (might possibly work on some phones - doesn't on mine). 

### Environment
K-9 Mail version: 5.201

Android version: 7.1.1 (Cyanogenmod 14.1-20161225-NIGHTLY) 
Phone Model: Oneplus3

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (Though probably not relevant)

**Comment by dschuermann** [comment] 2017-01-04 09:52
duplicate of #894

**Closed** 2017-01-04 10:07 UTC
Labels: duplicate
