### ISSUE TITLE
Notifications about NOT new messages for one specific box

### ISSUE THREAD

**Issue by AFract** [k9mail/k-9#3039] opened 2018-01-04 16:03 UTC
Hello, 

I am using K9 mail since a long time on my **Android 6.0** phone **Huawei Honor 7**.

I use it against a few different mailboxes, but for one of them (an **IMAP** box on port 993, at Yahoo) I have a little annoying bug everytime I click on the refresh button for New messages, while retrieving the INBOX messages :
- If I have one or more new messages, no problem, a notification is displayed accordly about the new messages which are successfully downloaded.
- But if there are NO new messages on the server, **I also receive a notification about one random message I have already received before in this box** (I recognize the Title of the message in the notification). From time to time, the offending message will change, maybe depending of real new messages actually retrieved.
If I click on the notification, it displays an empty message with a warning like "An error has occurred". Sometimes instead of referring to only one message, I got a notification for two or three messages.

This only happens to this specific box, never for any of the others (including another Yahoo box), and I encounter this problem since many MONTHS now, so it's **not related to any recent version**.
Normally the messages for which I got the message (at least the messages from the beginning of the problem) have already been definitely removed from the web server.

Thanks for your advices, and for K9 which is really a nice mail tool.

**Comment by cketti** [comment] 2019-03-01 04:27
Duplicate of #2092

**Closed by cketti** 2019-03-01 04:27 UTC
