### ISSUE TITLE
Misbehaviour when trying to correct typed address after suggestions 

### ISSUE THREAD

**Issue by rogers1106** [k9mail/k-9#3671] opened 2018-10-20 19:11 UTC
There is some kind of error when the user tries to edit a typed address.

### Steps to reproduce
1. Start a new mail.
2. Start typing the name of a contact in your address book. An address will be suggested.
3. Now enter a wrong char. The suggestion will disappear.
4. Now try to remove the wrong char with the backspace key.
5. Instead of deleting in address field chars in the signature field be be deleted.

100% reproducible on my device Nexus 5x with LineageOS 15.1

### Environment
K-9 Mail version: 5.600

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2018-10-20 20:28
Duplicate of #2829

**Closed by cketti** 2018-10-20 20:28 UTC
