### ISSUE TITLE
Email completions

### ISSUE THREAD

**Issue by liar666** [k9mail/k-9#2946] opened 2017-11-22 10:45 UTC
Context: I do not have data on my Mobile subscription, I only access internet through Wifi at home or at work. But I often write & (attempt to) send emails while not connected. They are just put in the "sent mail" queue with an error and actually sent when I connect.

What I do:
1. Create a new email
2. Start typing an address 

What happens is that a list of emails _from the contacts of the phone_ is presented

What I would like is that either previously typed emails or emails in the sent/received emails would be proposed. What is strange is that I had this bezhaviour before flushing K9's App cache, but now I cannot find any config to make it work again. Has it been removed? Why? How to get back a similar behaviour?

For more details, see my erroneous entry here (sorry): https://github.com/k9mail/k9mail.github.io/issues/60#issuecomment-346298354  (BTW which has nothing to do with the proposed issue)

### Environment
K-9 Mail version: 5.208
Android version: 4.4.2
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2017-11-22 22:49
Duplicate of #1006

**Closed by cketti** 2017-11-22 22:49 UTC

**Comment by liar666** [comment] 2017-12-06 22:46
The main difference with #1006 is that *I had* such a feature previously, so I'm not asking for a new feature like #1006, but how to get an existing feature back...

**Comment by cketti** [comment] 2017-12-21 04:18
K-9 Mail never had this feature.
