### ISSUE TITLE
Search - Edit - Delete , Previous-Next buttons moved to the bottom

### ISSUE THREAD

**Issue by a123xxsp** [k9mail/k-9#5219] opened 2021-03-26 08:00 UTC
up to 5.6 these buttons message actions (all in the same bar ) were located at the bottom,
for larger phones, it is better to have them down there because it is easier to navigate through e-mails and delete.

perhaps this could be an option in settings. or maybe part of a custom theme?

**Comment by cketti** [comment] 2021-03-26 12:09
Duplicate of #4725

**Closed by cketti** 2021-03-26 12:09 UTC
Labels: enhancement
