### ISSUE TITLE
"Mark all as read" doesn't from "Unread messages" when message is in "Spam" folder

### ISSUE THREAD

**Issue by boskamp** [k9mail/k-9#2230] opened 2017-02-13 11:21 UTC
### Expected behavior
Have two unread messages in your account: one in IMAP folder 'INBOX', one in IMAP folder 'Spam'. Open k-9 "Accounts" page, and click on the "Unread" count (solid blue circle) of that account to open the "Unread messages" view. A list of all unread messages (two, in my case) is displayed. Click the Android menu button, and select "Mark all as read". Both unread messages should be marked as read, and hence disappear from this list.

### Actual behavior
Only the message from 'INBOX' is marked as read and disappears. The message in 'Spam' remains unread and hence stays in the list. Only when I select the check box to the left of the unread message in 'Spam', and then use the "Mark as read" button in the icon bar at the bottom, it works as expected.

### Steps to reproduce
See "Expected behavior". It should be noted that this problem only occurs when the unread message is anywhere else than in the INBOX folder. When it's in INBOX, everything works fine. If it's in "Spam", "Mark all as read" doesn't work. I have attached a debug log.
[k9-log.txt](https://github.com/k9mail/k-9/files/770862/k9-log.txt)

### Environment
K-9 Mail version: 5.010 (sorry, I can't update due to #1961)

Android version: 4.4.4 (CM 11-20141115-SNAPSHOT-M12-i9100)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2017-02-13 20:40
Duplicate of #1194

**Closed by cketti** 2017-02-13 20:40 UTC
