### ISSUE TITLE
Configurable notification actions

### ISSUE THREAD

**Issue by shtrom** [k9mail/k-9#2659] opened 2017-08-04 11:38 UTC
Currently, K9 only shows 2 or 3 actions on notifications:
* Reply
* Mark Read
* Delete (if enabled)

It would be good to also allow to add (as a configuration option) Spam, Archive (and mark read) and move to other folders as per #2635.

### Environment
K-9 Mail version: 5.207

Android version: 7.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2017-08-08 12:17
Duplicate of #943

**Closed by cketti** 2017-08-08 12:17 UTC
