### ISSUE TITLE
Printing Missing

### ISSUE THREAD

**Issue by BushTrocity** [k9mail/k-9#3185] opened 2018-02-16 19:50 UTC
App version 5.403

Android Version 8.1.0

I seen many posts about the print option is in the sub send menu (2 left arrows). But i only see Reply, Reply all, Forward and Share. Print is not in the share options either. Not sure if just my OS or it is not yet implemented.

**Comment by cketti** [comment] 2018-02-17 04:08
Duplicate of #1062

**Closed by cketti** 2018-02-17 04:08 UTC
