### ISSUE TITLE
[ 5.701 ] after import settings, unfortunately, k-9 mail has stopped

### ISSUE THREAD

**Issue by leela52452** [k9mail/k-9#4339] opened 2019-12-04 06:17 UTC
### Expected behavior
Tell us what should happen
open app

### Actual behavior
displays message unfortunately, k-9 mail has stopped

### Steps to reproduce
1. open app
2. tap import setting
3. tap later

### Environment
K-9 Mail version: 5.701

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
dont have access to desktop or laptop

**Comment by ouafnico** [comment] 2019-12-07 10:34
Same on Pixel 2 / Android 10.

**Comment by HagenTronje** [comment] 2019-12-07 13:32
Same here

K-9 Mail version: 5.701

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by leela52452** [comment] 2019-12-09 17:03
@HagenTronje @ouafnico 

if you have access to desktop or laptop, please [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors)

**Comment by ouafnico** [comment] 2019-12-09 19:12
I didn't reproduice the bug after upgrade 5.600 to 5.701.
I only had when starting a fresh 5.701 install.
Unfortunatly I can not retrieve logs right now but I will try on another impacted phone.

**Comment by docfuz** [comment] 2019-12-09 19:36
I had a similar (same?!) issue when upgrading from 5.700 to 5.701. I'm attaching the relevant logs.

It happened **only** when displaying the **Gmail** account. As it was my default account, I could not start K9 from the drawer. I had to create a widget and launch it to another account's inbox.

I deleted my Gmail account, **manually** added it back, now everything works. As it worked in 5.700 and I didn't change anything in the Gmail account myself, maybe this can point others in the right direction.

[k9-log.txt](https://github.com/k9mail/k-9/files/3941389/k9-log.txt)

**Comment by HagenTronje** [comment] 2019-12-10 16:26
> @HagenTronje @ouafnico
> 
> if you have access to desktop or laptop, please [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors)

Sorry!
I am dependent on a working MUA on my phone so i re-installed k-9 V5.6 immediately after i recognized that V5.701 failed to work.

**Comment by cketti** [comment] 2020-05-05 13:25
Duplicate of #3691

**Closed by cketti** 2020-05-05 13:25 UTC
