### ISSUE TITLE
Idea: Swiping the messages to delete or answer mails even faster

### ISSUE THREAD

**Issue by ShadowBr0ther** [k9mail/k-9#3494] opened 2018-07-09 09:03 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Swipe to the left: message will be deleted.
Swipe to the right: answer message.

### Actual behavior
Nothing

### Environment
K-9 Mail version: 5.700

Android version: 7.1.1 Nougat (API 25)

**Comment by cketti** [comment] 2018-07-12 11:45
Duplicate of #1426

**Closed by cketti** 2018-07-12 11:45 UTC
