### ISSUE TITLE
Double entries of folders

### ISSUE THREAD

**Issue by PetziAt** [k9mail/k-9#3328] opened 2018-04-11 11:33 UTC
Double entries of folders in a IMAP Account.

The double entries are gone if I clear local data on phone. After few hours they are back again.

### Environment
K-9 Mail version: 5.503 (beta)
Android version: 7

![screenshot_20180411-131053](https://user-images.githubusercontent.com/4418572/38614237-ab314ce6-3d8c-11e8-917e-accd7aab0e23.png)

**Comment by philipwhiuk** [comment] 2018-04-15 22:58
Duplicate of #1220

**Closed by philipwhiuk** 2018-04-15 22:58 UTC
