### ISSUE TITLE
insert photo in signature k9-mail

### ISSUE THREAD

**Issue by ruspantini** [k9mail/k-9#5067] opened 2020-12-07 11:55 UTC
Hi please help. I have tried all sorts of ways to insert a logo in my signature and can't find the way to do it.

Here is to start.

Thanks in advance
Luca Ruspantini 

https://www.instagram.com/p/CIfceZJMGQ87KYN3jGM1AF-lHLnrhX7QH5x-Aw0/?igshid=16yhgxtoxxn5y

http://architectes.pro/wp-content/uploads/2015/01/log-RA_Logo_fdBleu.png
--
<!DOCTYPE html>
<html>
<head>
  <title>Page Title</title>
</head>
<p body style="font-family:roboto"; style="color:#6666CC"></p>
<body style="font-family:roboto">
  <h3 style="color:#10069F"><strong>Luca Ruspantini</strong></h3>

Envoyé de mon appareil téléphone. Veuillez excuser ma brièveté..

**Comment by ruspantini** [comment] 2020-12-08 13:33
Up

**Comment by cketti** [comment] 2020-12-09 12:46
Duplicate of #794

**Closed by cketti** 2020-12-09 12:46 UTC

**Comment by ruspantini** [comment] 2020-12-10 12:08
Up

**Comment by ruspantini** [comment] 2020-12-10 12:14
Thanks @cketti for your help. I checked #794 and it seems I have to change email manager. Any suggestions ?
Luca Ruspantini
