### ISSUE TITLE
Right to left layout for rtl languages

### ISSUE THREAD

**Issue by iriman** [k9mail/k-9#3391] opened 2018-05-15 20:23 UTC
Hi, Please implement the rtl layout for when we choose a rtl language like Persian, Arabic, etc. 
This is needed for the general UI of the app and also header and body sections of the emails.
I think it's better (specially for header and body of emails) that position of elements (rtl/ltr, right align/left align) to be detected like what android does by default, i.e. rtl direction when the string starts with a strong right-aligned character or ltr for left-aligned chars.

**Comment by eladhen** [comment] 2018-05-20 09:46
I've seen this issue opened and then closed several times. At the moment it's the only reason I can't us K-9 mail and resort to AOSP mail client, which is much more bare-bones, but can handle RTL and BIDI text.

**Comment by mehdisadeghi** [comment] 2020-06-09 20:27
Hi @cketti, I have similar issues as described here and would very much like to contribute a PR to fix them. I hope you can help me understand the current state of the things first.

There are [two](https://github.com/k9mail/k-9/issues/2506) other [PRs](https://github.com/k9mail/k-9/issues/1166) which are already closed, however it is still broken on my Android 9 with latest K-9 from Google Play store. Here is a picture of some dummy text with Arabic alphabet.:

![Screenshot_20200608-083623_K-9 Mail resized resized](https://user-images.githubusercontent.com/3101557/84195709-50c79300-aa9f-11ea-9319-4c52874ead04.jpg)

I read on other PRs that some simple html `dir="auto"` tagging could have fixed it. There are [merged PRs](https://github.com/k9mail/k-9/pull/3080) and [more closed](https://github.com/k9mail/k-9/issues/3265) [issues](https://github.com/k9mail/k-9/issues/3076). It would be very helpful if you could let me know whether this is a mere technical problem before I dive in. Was this issue once solved and reappeared? Is this a regression bug?

Any info is very much appreciated. Then I can work on a fix.

Thanks

**Comment by cketti** [comment] 2020-06-16 21:09
> Was this issue once solved and reappeared? Is this a regression bug?

I don't know. Personally, I never send or receive emails that contain text in a right-to-left language. If it doesn't work now, it's a bug. 
Any help with this is welcome. There are three major areas that need to be looked at:
1. Sending messages. Do we include `dir="auto"` in the HTML part of the message we send?
2. Displaying `text/plain` part of received messages. Do we include `dir="auto"` in the HTML that is generated to display the message in the WebView widget?
3. Displaying `text/html` part of received messages. Should we add a `dir="auto"` if it's missing or display the message as is? Also, if there's a `dir` attribute in the original message make sure it survives our HTML sanitization step.

**Comment by mehdisadeghi** [comment] 2020-06-19 11:24
> 1. Sending messages. Do we include dir="auto" in the HTML part of the message we send?

HTML messages work fine (if the html source contains proper tags). The issue is only with text messages.

> 2. Displaying text/plain part of received messages. Do we include dir="auto" in the HTML that is generated to display the message in the WebView widget?

No. The PR fixes that.

> 3. Displaying text/html part of received messages. Should we add a dir="auto" if it's missing or display the message as is?

I thought about this but didn't touch it. It is the responsibility of the sender to add necessary tags to their html message. No need to implement hacks in K-9, IMO.

> Also, if there's a dir attribute in the original message make sure it survives our HTML sanitization step.

I checked, `dir` attribute is already excluded during sanitization.

Please see the PR. Thanks!

**Closed** 2020-06-19 14:38 UTC
Labels: enhancement, help wanted
