### ISSUE TITLE
Crash after reloading a .k9s backup into k9 5.708 f-droid

### ISSUE THREAD

**Issue by Massedil** [k9mail/k-9#4676] opened 2020-04-19 17:31 UTC
Crash after reloading a backup `<k9settings version="65" format="1">` into a fresh install of K9 5.708 from f-droid.

After import, at each start, K9 crashes and is unusable.

Here is the log :

```
04-19 18:58:37.330  3465  3465 D AndroidRuntime: Shutting down VM
04-19 18:58:37.331  3465  3465 E AndroidRuntime: FATAL EXCEPTION: main
04-19 18:58:37.331  3465  3465 E AndroidRuntime: Process: com.fsck.k9, PID: 3465
04-19 18:58:37.331  3465  3465 E AndroidRuntime: java.lang.RuntimeException: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:530)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.fragment.MessageListFragment.decodeArguments(MessageListFragment.java:471)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.fragment.MessageListFragment.onCreate(MessageListFragment.java:320)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:200)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.activity.MessageList.onStart(MessageList.java:556)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7165)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: Caused by: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:193)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:172)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:273)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.mailstore.LocalFolder.open(LocalFolder.java:172)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.fragment.MlfUtils.getOpenFolder(MlfUtils.java:28)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:527)
04-19 18:58:37.331  3465  3465 E AndroidRuntime: 	... 31 more
04-19 18:58:37.335  1570  5607 W ActivityManager:   Force finishing activity com.fsck.k9/.activity.MessageList
```

**Comment by Chartman123** [comment] 2020-04-23 08:46
Same in 5.709 from Google Play.

**Comment by cketti** [comment] 2020-05-05 13:25
Duplicate of #3691

**Closed by cketti** 2020-05-05 13:25 UTC
