### ISSUE TITLE
e-mail not shown correctly (valid tags/attributes filtered by sanitizing?)

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#3122] opened 2018-01-22 12:15 UTC
Hi, it's me again.

I got another mail as an example:
[[LEDE Project Forum] Summary.zip](https://github.com/k9mail/k-9/files/1651751/LEDE.Project.Forum.Summary.zip)
This time from a discourse forum (LEDE).

Thunderbird:
![thunderbird_2018-01-22_12-33-33](https://user-images.githubusercontent.com/5685512/35219051-342d8212-ff71-11e7-8fbd-8373740b4507.png)
![thunderbird_2018-01-22_12-34-11](https://user-images.githubusercontent.com/5685512/35219053-36122524-ff71-11e7-8294-27f9cc788606.png)

K9:
![screenshot_20180122-123307](https://user-images.githubusercontent.com/5685512/35219121-91075d14-ff71-11e7-8808-6489356957ac.png)
![screenshot_20180122-122547](https://user-images.githubusercontent.com/5685512/35219122-92410bda-ff71-11e7-8743-120f598549fa.png)
There are white lines left and right of the blue box (because some part of the table layout is missing after sanitizing, I guess)

Some headlines are black and too small instead of white and not centered (sanitizing, too?)
(Taking a look at the code, this might be fixed by whitelisting ```<center>``` ^^)

The link at the end should be broken up into multiple lines like thunderbird does it.

And there should be more grey background instead white background overall (maybe it's enough to break the link into several lines, though).

Regards,
Djfe

**Comment by philipwhiuk** [comment] 2018-01-22 12:48
`<center>` was fixed in #3051 as well as bumping JSoup to fix the behaviour when stuff is removed.
`table background` in #3037
other `table` stuff in #3036 

Closing as duplicate of #3052

**Closed by philipwhiuk** 2018-01-22 12:48 UTC

**Comment by Djfe** [comment] 2018-01-22 12:55
I'm using 5.403 so the table related fixes are already included. so there seems to be missing something else that's causing the white lines to appear

**Comment by philipwhiuk** [comment] 2018-01-22 13:24
#3051 isn't in, nor is the JSoup update.

**Comment by Djfe** [comment] 2018-01-22 13:29
ok, I'll update this in-case the update doesn't fix everything (once it's out)
:)

**Comment by Djfe** [comment] 2018-01-23 06:30
one thing I forgot: updating jsoup won't make the link-text being broken up into several lines, right?

**Comment by philipwhiuk** [comment] 2018-01-23 09:00
I'm not sure what you mean by that.

**Comment by Djfe** [comment] 2018-01-23 09:22
no problem
the last arrow on my last Screenshot points to a link, that makes the whole e-mail body width wider. it should be split over several lines, so everything else can use the full display (the blue container at the top) should stretch over the full width of the screen

I hope, this makes it clearer to you :)

**Comment by philipwhiuk** [comment] 2018-01-23 11:08
Hmm that might be due to #3117
