### ISSUE TITLE
Folders View

### ISSUE THREAD

**Issue by gene-git** [k9mail/k-9#3982] opened 2019-03-25 14:33 UTC
Folders 
   a) Viewing
    b) Selecting class

In my other email clients (e.g. thunderbird) i see folders in a hierarchy.
e.g. 
F1
    -> sub11
     -> sub12
     .... -> Sub123
     -> Sub13
F2
    -> sub21
### Expected behavior
a) The view should be hierarchical tree view - with toggle to show/not show sub-folders.
b) Class selection should be able to picked for entire suite of subfolders of a given follder

### Actual behavior
a) Folders are shown flattened.
     F1
     F1.sub12
     F1.sub12
     F1.sub12.sub123
     F1.sub13
     F2
     F2.sub21

b) no ability to assign class other than individual flattened folders rather than for each sub tree - e..g. ability to set all F1.xxx as 2nd class.

### Environment
K-9 Mail version: 5.6.0

Android version: Android 9 Pie

Account type (IMAP, POP3, WebDAV/Exchange): imap (dovecot server)

Thanks!!

**Comment by cketti** [comment] 2019-03-26 22:42
Duplicate of #630

**Closed by cketti** 2019-03-26 22:42 UTC
