### ISSUE TITLE
Some TLDs are not converted to links when using plain text

### ISSUE THREAD

**Issue by skolarianer** [k9mail/k-9#1497] opened 2016-07-11 12:46 UTC
### Expected behavior
when receiving plain text emails with URLs containing TLDs like "link" or "online" the URL should be converted into a link.

### Actual behavior
www.whatever.link or www.whatever.online are NOT converted into a link. It's just plain text. Not clickable.

### Steps to reproduce
1. receive a plain text email containing an URL with a TLD like "link" or "online"

### Environment
K-9 Mail version: 5.010

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2016-07-14 15:29
Duplicate of #1223

**Closed by philipwhiuk** 2016-07-14 15:29 UTC
