### ISSUE TITLE
Add setting for archive per year/month

### ISSUE THREAD

**Issue by svbergerem** [k9mail/k-9#2157] opened 2017-01-30 23:38 UTC
### Expected behavior
It would be great if one could use archive folders per year or per month like Thunderbird does, e.g.

Archives/2015
Archives/2016
Archives/2017

K-9 Mail should use the correct folder based on the date of the messages.

### Actual behavior
K-9 Mail uses a single archive folder and has no setting to change this behavior.

### Environment
K-9 Mail version: 5.203

Android version: CM13 / 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2017-01-30 23:50
Duplicate of #900

**Closed by philipwhiuk** 2017-01-30 23:50 UTC
