### ISSUE TITLE
Crash when reporting issue by email

### ISSUE THREAD

**Issue by agilob** [k9mail/k-9#1542] opened 2016-08-04 07:09 UTC
### Expected behavior
Should not crash :)

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1. OsmAnd~ crashed and asked me to send report. I selected send by email with k-9, new draft email was created and in a second k9mail crashed. Draft of the OsmAnd bug was saved in remote folder, but incomplete.

### Environment
K-9 Mail version: 5.010 F-droid

Android version: 4.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

```
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:299)
    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.ExceptionInInitializerError
    at de.cketti.safecontentresolver.SafeContentResolverApi14.getFileUidOrThrow(SafeContentResolverApi14.java:36)
    at de.cketti.safecontentresolver.SafeContentResolver.openInputStream(SafeContentResolver.java:114)
    at com.fsck.k9.activity.loader.AttachmentContentLoader.loadInBackground(AttachmentContentLoader.java:58)
    at com.fsck.k9.activity.loader.AttachmentContentLoader.loadInBackground(AttachmentContentLoader.java:24)
    at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
    at android.os.AsyncTask$2.call(AsyncTask.java:287)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load os-compat: findLibrary returned null
    at java.lang.Runtime.loadLibrary(Runtime.java:365)
    at java.lang.System.loadLibrary(System.java:535)
    at de.cketti.safecontentresolver.Os.<clinit>(Os.java:21)
    at de.cketti.safecontentresolver.SafeContentResolverApi14.getFileUidOrThrow(SafeContentResolverApi14.java:36)
    at de.cketti.safecontentresolver.SafeContentResolver.openInputStream(SafeContentResolver.java:114)
    at com.fsck.k9.activity.loader.AttachmentContentLoader.loadInBackground(AttachmentContentLoader.java:58)
    at com.fsck.k9.activity.loader.AttachmentContentLoader.loadInBackground(AttachmentContentLoader.java:24)
    at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
    at android.os.AsyncTask$2.call(AsyncTask.java:287)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
```

I am able to reproduce it by opening file manager, long tap on osmand exception file -> share -> K9 -> opens view -> crashes, not able to reproduce on images.

**Comment by Valodim** [comment] 2016-08-04 18:42
duplicate of #1394. this one seems to be difficult to debug :(

**Closed by Valodim** 2016-08-04 18:42 UTC

**Comment by agilob** [comment] 2016-08-05 05:41
In my case it crashes when I try to create email from "Crasher" (Xposed module), content of the crash - stack trace is not an attachment, but content of email. It looks like it's a duplicate.
