### ISSUE TITLE
Notifications ringtones

### ISSUE THREAD

**Issue by Jose92** [k9mail/k-9#4826] opened 2020-06-05 12:18 UTC
Sorry for my bad english I use google traduction

### Expected behavior
When I receive several emails I should have a notification and only one ringtone.

### Actual behavior
When I receive several emails I have a notification and several ringtones.

### Steps to reproduce
Launch K9Mail, receive several emails.

### Environment
K-9 Mail version: 5.716 ( and 5.715 )

Android version: android 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

2020-06-05 13:59:18.336 11624-11651/com.fsck.k9 V/MessagingController$ControllerSyncListener: Creating notification for message INBOX:30532
2020-06-05 13:59:18.667 11624-11651/com.fsck.k9 V/MessagingController$ControllerSyncListener: Creating notification for message INBOX:30531
2020-06-05 13:59:18.892 11624-11651/com.fsck.k9 V/MessagingController$ControllerSyncListener: Creating notification for message INBOX:30530
2020-06-05 13:59:19.131 11624-11651/com.fsck.k9 V/MessagingController$ControllerSyncListener: Creating notification for message INBOX:30529

Here I had 4 rings

**Comment by cketti** [comment] 2020-06-05 13:13
Duplicate of #4559

**Closed by cketti** 2020-06-05 13:13 UTC
