### ISSUE TITLE
feature request: debugging sanitization

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#3140] opened 2018-01-26 17:04 UTC
It would be nice, if I could activate some sort of debugging in the settings, so that the ... menu of every e-mail has another option, that allows me to take a look at all the html in the e-mail that got removed by sanitization.
This way we all have an easier time adjusting the whitelist for html e-mails until no more elements are missing :)

**Comment by philipwhiuk** [comment] 2018-01-27 02:23
Duplicate of #1018

**Closed by philipwhiuk** 2018-01-27 02:23 UTC
