### ISSUE TITLE
Red envelope on k-9 icon looks now "evil"

### ISSUE THREAD

**Issue by hertell** [k9mail/k-9#3048] opened 2018-01-05 17:58 UTC
Since the december update, the red colour on the k-9 icon has changed to a scary, "evil" colour. First i thought it had to do with x-mas, but after a new update since then, the colour is still awful.

This occurs on android 4.4.4
K-9 5.402

**Comment by ArchangeGabriel** [comment] 2018-01-05 17:59
Dupe of #2998.

**Closed** 2018-01-05 18:05 UTC
