### ISSUE TITLE
K9 stopping and crashing when deleting

### ISSUE THREAD

**Issue by Cindy62707** [k9mail/k-9#3325] opened 2018-04-10 18:00 UTC
For months now I've been reporting that K9 is crashing when I delete emails most of the time on one of my mediacom accounts. It is also starting this on my other mediacom accounts too.  Apparently the developers do not read their feedback reports or else this would have been fixed by now.  Has anyone else been having this happening when deleting emails?

Also, at the top it always says "Sync Disabled - no network" even though I do have a great network connection.  If I manually sync it will work some of the time. Other times, I go all day without being able to get new emails even though I keep trying to manually sync.

### Expected behavior
Tell us what should happen - I should be able to delete emails without crashing K9

### Actual behavior
Tell us what happens instead - crashes when I delete an email or multiple emails most of the time, occasionally it will not crash but that is rare.  Emails will not sync every 15 minutes as checked.  Emails will not always sync when I try to do it manually.

### Steps to reproduce
1. deleting emails are crashing the program
2. sync does not work normally as described above
3.

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by Sprinterfreak** [comment] 2018-04-25 07:34
I can confirm, that K-9 has issues while deleting emails.
I let K-9 group my conversations in inbox-view. If I then open a conversation group wich lists all related emails to this thread and select multiple emails in that thread-list, K-9 crashes with the click on the trashbin.
The mails get removed from the server of course.

**Comment by TKLCZ** [comment] 2019-01-29 17:13
In my case when I have more than 2500 e-mails in a folder K9Mail is unable to delete or move one or multiple e-mails and hangs. After restart the deleted mails seems to be deleted (sometime) but they still exists in a folder on server.
After archiving old e-mails everything works normally.
Android 9 on Xiaomi A1, only one e-mail account, IMAPS.

**Comment by cketti** [comment] 2019-03-07 17:11
Duplicate of #2604

**Closed by cketti** 2019-03-07 17:11 UTC

**Comment by TKLCZ** [comment] 2019-03-07 17:24
Hello, this is not a duplicate.
I don't use a threads.


7. března 2019 18:11:54 SEČ, cketti <notifications@github.com> napsal:
>Duplicate of #2604

-- 
Tomáš Klos
tkl@tkl.cz
https://www.tkl.cz

**Comment by Cindy62707** [comment] 2019-03-07 18:13
I don't use threads either so the issue is not a duplicate.

**Comment by Cindy62707** [comment] 2019-03-07 18:17
The issue still exists so was there ever a fix?  I got tired of constantly reporting and getting ignored so I stopped using K9 for my main email accounts and switched to Aqua Mail.  I still use K9 for some of my other accounts where I don't get as many emails so the problem isn't as big a deal if it happens.  I'd switch back to K9 if bugs like this weren't ignored constantly.

**Comment by cketti** [comment] 2019-03-08 01:40
It's likely the same issue whether you use threads or not.

**Comment by Cindy62707** [comment] 2019-03-08 22:47
So did it ever get fixed? I don't see a fix listed in the other topic either.
