### ISSUE TITLE
IMAP authentication fails on new Yahoo! Mail secure sign in method

### ISSUE THREAD

**Issue by phoenixx2** [k9mail/k-9#1853] opened 2016-12-15 02:47 UTC
### Expected behavior
As per this article:
https://help.yahoo.com/kb/account/SLN27791.html
Once enabled, K-9 cannot be used to check Yahoo! Mail.

### Actual behavior
You receive the following error:
"Server doesn't support encrypted passwords using CRAM-MD5."

### Steps to reproduce
1. Turn on secure sign in on Yahoo! Mail (which will become the norm soon, apparently).
2. Attempt to sign in with "Encrypted password".
3. Error.

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2016-12-15 09:38
Duplicate of #1698

**Closed** 2016-12-15 09:38 UTC
Labels: duplicate

**Comment by TheTechGuy100** [comment] 2017-07-31 23:50
https://github.com/k9mail/k-9/issues/2653 might address your issue

**Comment by philipwhiuk** [comment] 2017-08-01 05:12
Encrypted password is not the same as OAuth. That's the users mistake. Nothing to do with the server URL
