### ISSUE TITLE
Start folder none not working

### ISSUE THREAD

**Issue by stoecker** [k9mail/k-9#4736] opened 2020-05-07 17:51 UTC
### Expected behavior
When start folder is set to none (Keine in German) it should display folders instead of contents of a folder.

### Actual behavior
Option is still there but INBOX is shown

### Steps to reproduce
1. Set start folder to Keine

### Environment
K-9 Mail version:

5.709 via fdroid in German

Android version:

7.0

Account type (IMAP, POP3, WebDAV/Exchange):

IMAP

**Comment by cketti** [comment] 2020-05-07 23:34
Duplicate of #4471

**Closed by cketti** 2020-05-07 23:34 UTC
