### ISSUE TITLE
Lost all account data after installing update of 29th

### ISSUE THREAD

**Issue by JatGitHub** [k9mail/k-9#3016] opened 2017-12-31 09:54 UTC
After the last update of December 29 I lost all my account settings. Hadn't come to export them. 

Android 6.0
Levono b

**Comment by ayekaramba** [comment] 2017-12-31 12:13
I can partly confirm this issue.
I had to assign the folders of the IMAP account to the named folders in K9 again.
The other settings seem to be fine so far.

**Comment by cketti** [comment] 2018-01-02 15:15
Duplicate of #750

**Closed by cketti** 2018-01-02 15:15 UTC
