### ISSUE TITLE
Start in unified inbox doesn't work in 5.700

### ISSUE THREAD

**Issue by adolfintel** [k9mail/k-9#4332] opened 2019-12-03 21:12 UTC
I just updated K9 to version 5.700 via F-Droid, and I noticed that the "Start in Unified Inbox" option doesn't work, the app always starts with the inbox of your first account.

### Expected behavior
App starts in unified inbox

### Actual behavior
App ignores the setting and always starts in the inbox of the first account

### Environment
K-9 Mail version: 5.700 F-Droid

Android version: Android 9 (LineageOS 16.0)

Account type (IMAP, POP3, WebDAV/Exchange): various

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2019-12-03 21:18
Duplicate of #4287

**Closed by cketti** 2019-12-03 21:18 UTC

**Comment by adolfintel** [comment] 2019-12-04 05:28
Sorry, I didn't see the other issue
