### ISSUE TITLE
Continue a long message 

### ISSUE THREAD

**Issue by muessjoeh** [k9mail/k-9#4416] opened 2019-12-31 13:19 UTC
When a long message is displayed, it is interrupted and there is a button labeled "Gesamte Nachricht herunterladen" (in German). When you press it, it loads the rest, but starts to display with line no 1. I would prefer if it started right there to display, because now you have to scroll and watch very much.

**Comment by cketti** [comment] 2020-01-02 14:45
Duplicate of #2810

**Closed by cketti** 2020-01-02 14:45 UTC
