### ISSUE TITLE
Focus shifts to message body while typing addresses

### ISSUE THREAD

**Issue by peterjanes** [k9mail/k-9#3235] opened 2018-03-04 22:53 UTC
### Expected behavior
It should be possible to type an entire email address.

### Actual behavior
When typing certain addresses, focus is switched to the message body.

### Steps to reproduce
1. Start typing peter.janes. Notice that after the "j" focus is on the message body in a random location, and the rest of the characters are entered there.

I've seen this behaviour regardless of the keyboard I use (Swype, Gboard).

### Environment
K-9 Mail version: 5.501 (installed via beta program on Play Store). Noticed in a previous version as well.

Android version: 8.1.0, February 5 security patches applied

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2018-03-05 03:37
Duplicate of #2829

**Closed by cketti** 2018-03-05 03:37 UTC
