### ISSUE TITLE
WEBDAV is broken on Android Nougat with K-9 Mail v5.010 (stable)

### ISSUE THREAD

**Issue by markusb68** [k9mail/k-9#1785] opened 2016-11-08 18:31 UTC
Went from Nexus 10 (Android 5.1.1 Build LMY49J) to NEXUS 9 (7.0.0 Build NRD91N, Nov 2016))
Both were routed so I used Titanium Backup and moved K-9 Mail v5.010.
I have 3 mail acounts 2x IMAP and one WEB-DAV using exchange (with a self signed cert)
The IMAP accounts are OK, but the WEBDAV account just reports Java exceptions.
Can't fetch new mails, nor can't change something in the mailserver settings.
Are there any known incompatibilities with Android 7 and webdav support?
Also tried the latest v5.114 (alpha). isn't better at all.

Deleted K9 Data, uninstalled APP, reinstalled app and tried setting up just the webdav account completely new but this also gives the same result.: Can't connect to server.

See attached log:
[k9-log.zip](https://github.com/k9mail/k-9/files/579014/k9-log.zip)
And here's a log with DEBUG Mode ON:
[k9-log_debug.zip](https://github.com/k9mail/k-9/files/579060/k9-log_debug.zip)

BR

Markus

**Comment by philipwhiuk** [comment] 2016-11-08 20:55
Thanks for the debug log. 

Caused by: javax.net.ssl.SSLHandshakeException: Connection closed by peer 
at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)

So the other side, i.e. the server is closing the connection. Note also this is not our code it's Android code. 

The change here is the Android version. Newer Android versions ship newer SSL implementations which change what crypto protocols are available for us to use.

What algorithms does your server support? You can find this out by running OpenSSL from the terminal or by connecting via a web browser and looking what the browser uses to connect.

**Comment by philipwhiuk** [comment] 2016-11-08 21:07
I looked at your server based on the debug log

You're using 3DES_EDE_CBC. 

By memory 3DES was declared broken several years ago and Google has probably removed it from the default crypto built into Android. Chrome calls it obsolete and throws warning.

It's self signed anyway so just reissue a stronger cert.

**Closed** 2016-11-08 21:07 UTC
