### ISSUE TITLE
Removing all Default Accounts should land you in a view listing the accounts

### ISSUE THREAD

**Issue by NickJH** [k9mail/k-9#5464] opened 2021-07-28 12:20 UTC
If you have no account set as default you should be able to open k-9 mail without landing in an account and should just be presented with a list of accounts. Similarly if you are in an account inbox, hitting the back button should then take you to the list of accounts.

**Comment by AndySchroder** [comment] 2021-08-05 03:41
Seems to be a duplicate of https://github.com/k9mail/k-9/issues/5452 .

**Comment by cketti** [comment] 2021-08-13 15:54
See #5570

**Closed by cketti** 2021-08-13 15:54 UTC
Labels: enhancement
