### ISSUE TITLE
Add black theme for OLED devices

### ISSUE THREAD

**Issue by Lynnesbian** [k9mail/k-9#3993] opened 2019-03-29 06:10 UTC
OLED devices use less battery when displaying pure black pixels, as the pixel is able to turn off. The current dark theme has a grey gradient, which means that many of the pixels are still on. Some apps implement this by having light, dark, and black themes.

![Dark theme example](https://i.imgur.com/FN6aYPS.jpg)

**Comment by cketti** [comment] 2019-03-29 14:46
Duplicate of #2353

**Closed by cketti** 2019-03-29 14:46 UTC
