### ISSUE TITLE
No IMAP push sync in/after doze in Android 7.1

### ISSUE THREAD

**Issue by djdookie** [k9mail/k-9#1830] opened 2016-12-05 09:12 UTC
### Expected behavior
If my smartphone is in doze, I should immediately receive notifications about incoming mails via IMAP and push connection with syncing enabled.

### Actual behavior
Tell us what happens instead
After some time I see the words "syncing disabled", although it is "always enabled".

### Steps to reproduce
1. use imap with push, syncing enabled
2. close all apps, put phone to doze
3. send yourself an email
4. you don't receive any notifications of incoming mails anymore

I found out, that push syncing in doze mode seems to still work on my newest android 7.1 (cm14.1) if you set your auto email-request interval to say 30 minutes. This seems to keep the push connection open which is a good workaround until this gets fixed. Another thing I tried before is excluding k-9 mail from android battery optimizations, but this unfortunately didn't make a difference.

### Environment
K-9 Mail version:
v5.010

Android version:
Andoid 7.1 on Samsung Galaxy S5 (SM-G900F)
Cyanogenmod 14.1-20161201-NIGHTLY-klte

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by djdookie** [comment] 2016-12-05 17:08
Ok I have to correct my observations:
This workaround doesn't help also.
It says "synchronisation disabled" after some time, which is wrong.

**Comment by philipwhiuk** [comment] 2016-12-05 21:02
Duplicate of #857

**Closed by philipwhiuk** 2016-12-05 21:02 UTC
