### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by hecsa** [k9mail/k-9#2241] opened 2017-02-16 01:37 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When an email contains bullets, or numbering, the text that follows those bullets or numbers needs to appear.

### Actual behavior
When an email contains bullets or numbers, sometimes the text after that numbers and/or bullets cannot be seen. 
If the message is replied, that text appears.
If the text had some modification, for example highlighting, the text appears too, but only the highlighted part.

### Steps to reproduce
1. Send using, for example, M$ Outlook, and email containing bullets or numbers, and some text after the bullets or numbers. Maybe to highlight part of the text, but not the numbers or bullets, could be a better first step.
2. Receive the email on the cell phone, using K-9. Check the issue.
3. Reply that email, checking that there the text appears.

### Environment
K-9 Mail version:
5.203

Android version:
5.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment] 2017-02-16 10:51
Duplicate of #2015. Caused by our attempt to clean-up the mess that Microsoft Office claims is HTML.

**Closed by philipwhiuk** 2017-02-16 10:51 UTC
