### ISSUE TITLE
Add support for composing PGP/MIME messages

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#572] opened 2015-03-15 00:59 UTC
We also require some form of UI so the user can select whether to use inline PGP or PGP/MIME.

**Comment by Diagoras** [comment] 2015-05-31 02:29
I'll pick this one up, if that's alright.

**Comment by fnielson1** [comment] 2015-06-03 16:34
That would be great! Also, I assume that you would help to have it so that k9 could read PGP/MIME emails

**Comment by Diagoras** [comment] 2015-06-05 15:52
@fnielson1 The weird thing is, my debug build of K9 seems like it can read PGP/MIME emails just fine! I'm guessing that's a feature which is in the codebase but not yet released.

**Comment by fnielson1** [comment] 2015-06-05 16:53
Really? That's awesome! I'm going to have to just use that on my phone instead.

**Comment by knoy** [comment] 2015-06-30 00:24
@Diagoras how long do you think you will need to implement this? I'm willing to sponsor $150 USD to anyone who can get this done in the next 7 days.

**Comment by knoy** [comment] 2015-06-30 00:29
Signed PGP/MIME messages are very important to prevent spoofing and various social engineering attacks against K9 users

**Comment by knoy** [comment] 2015-07-31 01:31
Sgning is supported but not enabled for some unknown reason. For anyone interested the fix is adding android:checked="true" to cb_crypto_signature in the message_compose.xml layout

**Comment by fnielson1** [comment] 2015-07-31 03:16
Thanks for the tip! That's awesome!

**Comment by denim2x** [comment] 2015-08-05 19:10
Duplicate of [issue 5864](https://code.google.com/p/k9mail/issues/detail?id=5864)

**Comment by alexandre75** [comment] 2015-11-07 11:43
RFC1847 is implemented (#576). Should this (from RFC2015) be also implemented along this issue? 

> 6.2  Combined method
>
>   Versions 2.x of PGP also allow data to be signed and encrypted in one
>   operation.  This method is an acceptable shortcut, and has the
>   benefit of less overhead.  The resulting data should be formed as a
>   "multipart/encrypted" object as described above.
>
>   Messages which are encrypted and signed in this combined fashion are
>   REQUIRED to follow the same canonicalization rules as for
>   multipart/signed objects.
>
>   It is explicitly allowed for an agent to decrypt a combined message
>   and rewrite it as a multipart/signed object using the signature data
>   embedded in the encrypted version.

**Comment by alexandre75** [comment] 2015-12-02 14:21
Pull request https://github.com/k9mail/k-9/pull/884 fixes this issue.
Commits
https://github.com/alexandre75/k-9/commit/7e4488081061bf611986ce3a203953e9378233f0

**Comment by Valodim** [comment] 2016-01-27 23:58
solved with #924 and #962. polish, bugs and missing features will be handled in different issues.

**Closed by Valodim** 2016-01-27 23:58 UTC
