### ISSUE TITLE
Composing message to address not in contacts jumps to message text

### ISSUE THREAD

**Issue by mhoran** [k9mail/k-9#3150] opened 2018-01-28 19:53 UTC
### Expected behavior
When composing a message to an address not in contacts, I'd expect to be able to enter the address.

### Actual behavior
When composing a message to an address not in contacts, the contact dropdown shows until there are no matches, then disappears. When typing a subsequent letter (for example, if entering "not", which doesn't correspond to a contact), the cursor will jump to the message text field.

This seems similar to one of the issues reported in #2836.

### Steps to reproduce
1. Open compose view
2. Begin typing the address of a contact not in contacts
3. Upon typing a subsequent letter after the contact dropdown disappears, the cursor will jump to message text.

### Environment
K-9 Mail version: 5.403

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Thunderhawk2001** [comment] 2018-02-26 14:31
Got the exact same issue.
When entering a new mail adress, it jumps to the message field, after the last entry disappears from the dropdown menu.

Pixel XL, Android 8.1.0, k9 V5.501

**Comment by cketti** [comment] 2018-07-12 12:18
Duplicate of #2829

**Closed by cketti** 2018-07-12 12:18 UTC
