### ISSUE TITLE
dark theme background has slight gradient...

### ISSUE THREAD

**Issue by fake-fur** [k9mail/k-9#3479] opened 2018-06-30 12:30 UTC
hi guys

i did ask another person to check to make sure i'm not going crazy but the dark theme background appears to have a gradient that makes it lighter toward the bottom of the screen ... i have looked on several devices and they all show it to some degree or other

is there any way to get a really black background theme for amoled users?

thanks much again
:)

**Comment by cketti** [comment] 2018-07-12 11:54
Duplicate of #2353

**Closed by cketti** 2018-07-12 11:54 UTC
