### ISSUE TITLE
Feature Request: Pin when opening app

### ISSUE THREAD

**Issue by lprc** [k9mail/k-9#1352] opened 2016-05-04 09:13 UTC
I think a feature for setting a pin for opening the app would be really awesome so that when you lose your phone and someone manages to unlock it he can't directly view your e-mails and  e-mail-account related data (e.g. the dropbox app has this feature).

**Comment by cketti** [comment] 2017-02-08 03:43
Duplicate of #753

**Closed by cketti** 2017-02-08 03:43 UTC
