### ISSUE TITLE
allow server based searches for body

### ISSUE THREAD

**Issue by fezie** [k9mail/k-9#4141] opened 2019-08-04 09:03 UTC
It seems like the server based search is limited to from and subject headers.
I use dovecot with fts-xapian plugin and search mail bodies in evolution is very fast and successfull.
But K-9 Mail doesn't show any mails where the search string is just in the body and not in the subject or the from address.

### Expected behavior
server based search for "foo" should returrn mails with "foo" in the body

### Actual behavior
Only mails where "foo" is in from or subject header gets shown.

### Steps to reproduce
1.  Enable server based searching
2. Search for sth. which is just in a mail body but not in the subject or from line.
3.

### Environment
K-9 Mail version: 5.600

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP on dovecot 2.3.4.1 with fts-xapian plugin

**Comment by cketti** [comment] 2019-10-12 20:06
Duplicate of #699

**Closed by cketti** 2019-10-12 20:06 UTC
