### ISSUE TITLE
POP3 - App hangs when polling email

### ISSUE THREAD

**Issue by stevem99999** [k9mail/k-9#3923] opened 2019-02-21 22:45 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Poll of email account causes app to hang

### Actual behavior
App hangs, phone freezes - some partial error message seen on folder list 'socket exception rea' is all I can see. Never seen before, app has always performed well. No changes to settings made.

### Steps to reproduce
1. Open K9, click on account name
2. Poll email address - see 'fetching headers' and then app hangs
3. Also hangs in background as app is set to poll email every 15 mins.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by philipwhiuk** [comment] 2019-02-22 14:53
Duplicate of #2270

**Comment by stevem99999** [comment] 2019-02-22 15:03
Thanks, it's not a duplicate as the thread referred to is about IMAP, and I use POP3 but whatever. Did complete reinstall and rebuild and seems to be working again.

**Comment by philipwhiuk** [comment] 2019-02-27 13:10
I couldn't tell that because you didn't fill in the template.

**Comment by cketti** [comment] 2019-03-01 14:54
If there's no debug log we could use to track down the cause we might as well close this issue.

**Closed by cketti** 2019-03-01 14:54 UTC
