### ISSUE TITLE
Redirect/Bounce Mails

### ISSUE THREAD

**Issue by heimatruhr** [k9mail/k-9#2794] opened 2017-09-26 16:58 UTC
Hi,
I missed the Plugin to redirect/Bounce Mails Like in the Thunderbird Plugin 'Mail Redirect'.
It's very important for me as administrator.

Thanks 

Malte

**Comment by kwenzig** [comment] 2018-08-23 05:27
Seems to be duplicate of #622

**Comment by cketti** [comment] 2018-08-26 21:55
Duplicate of #622

**Closed by cketti** 2018-08-26 21:55 UTC
