### ISSUE TITLE
Notification-LED not working anymore

### ISSUE THREAD

**Issue by Buntbart** [k9mail/k-9#4596] opened 2020-03-09 18:05 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
LED blinks when new E-Mail arrived. K9-Mail up to v.5.600 (F-Droid) had this feature.

### Actual behavior
LED doesn't lit.

### Steps to reproduce
1. Get new E-Mail
2.
3.

### Environment
K-9 Mail version: 5.705 (from F-Droid)

Android version: 9 (LineageOS 16)

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2020-03-10 21:41
Duplicate of #4299

**Closed by cketti** 2020-03-10 21:41 UTC
