### ISSUE TITLE
Offline Drafts + Sync = Loss

### ISSUE THREAD

**Issue by alooshu** [k9mail/k-9#3031] opened 2018-01-03 20:28 UTC
### Expected behavior
Drafts written/edited offline after the particular client synced the Drafts folder last, on next sync are synced *to* the server first thing, and hence become available on all devices

### Actual behavior
when the Drafts folder syncs, it happens that it is put into a state identical to server, resulting in drafts written offline to disappear.

### Steps to reproduce
not yet systematically tested - this may or may not depend on whether other clients have synced in the meantime.  In any case: a) the Drafts folder has special sync requirements b) the relevant last sync timestamp would be the local, per-client one, not the global server one.

### Environment
K-9 Mail version: various 4.804 to 5.208

Android version:gingerbread, ice cream sandwich

Account type (IMAP, POP3, WebDAV/Exchange):imap

**Comment by alooshu** [comment] 2018-01-09 19:10
I have now tested the following: writing, still offline, an original draft and a mail reply each in 4.804 under gingerbread and 5.208 under ics, then letting the gingerbread client sync, and after that, the ics client, all went as it should: both original drafts got uploaded to server, and both replies to the same mail were kept as independent drafts in the same thread.
So I have not been able at all to reproduce the error yet, but it definitely happens despite not encrypting mails, merely using ssl to connect to the gmail imap server.
Maybe it would make sense to make the server, not only protocol, a part of the issue report template, since in theory , the server behaviour could be significant, too.
For an idea of possible scenarios: I'm using a phone to pass on a mobile connection to a tablet per ad-hoc wifi, thus it may happen that clients from 2 devices attempt syncing near-simultaneously from the same ip address, resulting in a 'too many simultaneaous connections' server response from google/gmail.
Maybe this could also point to different threads performing duplicate tasks, or even a buggy implemention of ics erroneously allowing multiple instances of k9.
Feel free to suggest additional tests for me to do, bearing in mind that I cannot compile or run specific debug environments, but I have root and busybox on ics, and on all devices, a shell emulator,

**Comment by cketti** [comment] 2018-02-10 18:25
Duplicate of #2164

**Closed by cketti** 2018-02-10 18:25 UTC
