### ISSUE TITLE
Losing emails during submission upon disconnectin

### ISSUE THREAD

**Issue by dilyanpalauzov** [k9mail/k-9#3550] opened 2018-08-11 03:12 UTC
With k9 5.403 when I try to send an email, that is in Outbox, if the connection breaks during sending, the email disappears - it is neither in Sent, nor in Outbox and likely it is also not sent.

**Comment by cketti** [comment] 2019-03-08 03:23
Duplicate of #2616

**Closed by cketti** 2019-03-08 03:23 UTC
