### ISSUE TITLE
Draft message disappears on sync if cryptography is set to OpenKeyChain

### ISSUE THREAD

**Issue by Heineken** [k9mail/k-9#2687] opened 2017-08-18 09:44 UTC
See caption.

### Expected behavior
The drafted message should appear on the server.

### Actual behavior
The message goes to a better place.

### Steps to reproduce
1. Compose message for IMAP-account which has encryption activated as OpenKeyChain 4.5
2. Save message as draft
3. Sync draft folder

### Workaround
Deactivate encryption for that account.

### Environment
K-9 Mail version: 5.207

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP-account hostet at posteo.de

**Comment by philipwhiuk** [comment] 2017-08-18 10:31
This is expected behaviour right now.

Ideally we would save encrypted drafts but that's not the current behaviour.

@Valodim I thought we had a warning for this - do we not? Should we?

**Comment by ghostrider72** [comment] 2017-08-19 07:49
I had to revrite a long long email three times before discover it was an issue. They did not solve the forced encryption and added this issue too... Sometimes I wonder if the developers use this app at all.

**Comment by spi43984** [comment] 2017-08-23 16:48
I stumbled across the same issue on two different Android devices. Had OpenKeyChain enabled but still no keys configured. Draft mails got saved and immediately deleted without any prior warning. That's not an expected behaviour.

Rather than just deleting the message I'd appreciate some warning and the choice to either delete the message, store it unencrypted or encrypted with the sender's key only (I'd expect everybody to also encrypt message with their own keys, so that could be used in case of saving draft mails).

**Comment by Valodim** [comment] 2017-08-23 18:36
Yeah that behavior is far from ideal, sorry about that. This will change in an upcoming version to at least be less surprising.

**Comment by DorKeinath** [comment] 2017-10-17 18:58
I'm looking forward for it :-)
Thank you in advanced for your ingenious work!

**Comment by cketti** [comment] 2018-02-10 18:23
Duplicate of #2164

**Closed by cketti** 2018-02-10 18:23 UTC
