### ISSUE TITLE
Can't zoom messages 

### ISSUE THREAD

**Issue by MickLG1965** [k9mail/k-9#2056] opened 2017-01-14 18:01 UTC
### Expected behavior
Tell us what should happen

When using two fingers to zoom into text or image. Image or text should enlarge making it easy to read. 

### Actual behavior
Tell us what happens instead

Text or image may zoom a small amount,and then sticks, not allowing any more zoom 
This started happening since the last upgrade or last but one. 

### Steps to reproduce
1. Example : daily cartoon email from dilbert.com
2. Download full email and click show images. 
3. Try to zoom into cartoon 

### Environment
K-9 Mail version:
5.202
Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
Pop3

**Comment by philipwhiuk** [comment] 2017-01-14 22:43
Duplicate of many bugs e.g. #2020

**Closed by philipwhiuk** 2017-01-14 22:43 UTC
