### ISSUE TITLE
Dark Text in Reply with Dark Theme 

### ISSUE THREAD

**Issue by ITGeekMonkeys** [k9mail/k-9#2012] opened 2017-01-08 02:31 UTC
### Steps to reproduce
1. Open message and reply. 

### Environment

K-9 Mail version: v5.502 

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2017-01-08 02:34
In the quote, right? If so it's a duplicate of #1930

**Closed by philipwhiuk** 2017-01-08 02:34 UTC
