### ISSUE TITLE
Feature request: Display folders using nested structure

### ISSUE THREAD

**Issue by mrBussy** [k9mail/k-9#2350] opened 2017-03-06 12:28 UTC
### Expected behavior
I have a lot of folders in a nested structure. I would like K9 to support this structure in such A way that I can dive into child folders or go back to parent folders without looking at the entire folder list. this makes searching a lot more usefull. Also prevents a lot of elipses in the list of folders.

For example:
- INBOX
- SUBJECT 1
-- SUBSUBJECT 1
--- Even lower 1
--- Even lower 2
-- SUBSUBJECT 2
- SUBJECT 2

### Actual behavior
Currently when you look at the list of folders you get a long list of folders where the entire path is combined to a long string.

INBOX
SUBJECT 1
SUBJECT 1/SUBSUBJECT 1
...1/SUBSUBJECT 1/Even Lower 1
...1/SUBSUBJECT 1/Even Lower 2
...1/SUBSUBJECT 1/Even Lower 3
SUBJECT 1/SUBJECT 2
SUBJECT 2

### Steps to reproduce
Open a IMAP mailbox with a lot of folders and subfolders

### Environment
K-9 Mail version: K-9 Mail v5.205
Android version: 6.0
Account type (IMAP, POP3, WebDAV/Exchange): IMAP/Exchange

**Comment by cketti** [comment] 2017-03-06 12:40
Duplicate of #630

**Closed by cketti** 2017-03-06 12:40 UTC
