### ISSUE TITLE
Show accout list in app home screen. (or option to set it as default behaviour)

### ISSUE THREAD

**Issue by andrixnet** [k9mail/k-9#5518] opened 2021-08-04 08:18 UTC
Everytime an app is updated and I read "UI changed" in the "what's new" it makes me cringe. This means too often loss of functionality, usage hassle/difficulties (unrelated to learning curve), loss of productivity and too little actual gains. 
Sadly K9 updating to 5.8 followed this same pattern.

I manage multiple email accounts. 
More often I need to work with a different account when I open K9 then the account I used last time. Up to now K9 was the perfect and high performance choice and with PGP integration. 
With version 5.8 however the changed UI follows concepts used by many other email apps, concepts which made those apps very hard to use and thus poor choices for such multiple account management.

**Desired behaviour**
- when I open K9 app (first open), show me the account list and let me choose which one I want to manage right now.

I have nothing against the current behaviour, personally. There may be sound rationale behind UI redesigns and some users benefit from them. 
I wouldn't recommend however alienating existing users (including supporters and advocates) by brutally removing key features that made this app their app of choice.

While keeping the new behaviour as default, showing account list in app home behaviour could be made available to users really needing it via a checkbox in settings/display.

**Current behaviour:**
- 5.8 displays by default the inbox of the first account in the account list and forces the user to perform at least 3 taps, maybe additional scrolling (depending on screen size and number of accounts), to get to use any of the other accounts.
This is only viable to the user if the there is overwhelming focus on the first account ONLY and the others are seldom used. 
This is horrible when managing multiple accounts with balanced focus among them.

Alternatives?
- none viable found in app settings
- unified inbox may be of use for some users, but not for a well ordered and structured mind.
- downgrading for now
- eagerly waiting for positive K9 development response

For now, the only viable (for me, at least short term) solution was to downgrade to v5.6 according to this https://forum.k9mail.app/t/how-to-downgrade-to-an-earlier-version/1432 

As I read further in the forum, there are quite a number of users seriously affected by this UI loss of function in v5.8 and other issues as well. Not talking about disgruntled persons not liking the changed UI.

**Comment by jult** [comment] 2021-08-04 09:18
Please someone fork K-9 Mail v5.741 and rename it all, so we can continue where k9 was still usable. I mean, come on, why would anyone push such ridiculous change onto all its users? Even for OSS this is not the way to do it. You make changes like this optional, at the very least.

**Comment by AndySchroder** [comment] 2021-08-05 03:37
Seems to be a duplicate of https://github.com/k9mail/k-9/issues/5452

**Comment by andrixnet** [comment] 2021-08-05 15:51
Partially. While #5452 complains about the new UI being broken (ie a bug).

This issue treats the problem in the spirit of K9 evolving, while the new UI changes things, perhaps the new UI could integrate similar functionality to the old app home in the future. 

Also I hope I described the situation in more detail, in a more technically competent way and respectfully (while the forums are red hot with flames). 

Perhaps the similarity/duplication could be considered the other way around.

Thank you.

**Comment by Swyter** [comment] 2021-08-13 09:45
As a (recent) K-9 Spanish translation contributor, I agree. Some people are expressing it in a mean way, but there are nuggets of truth in there and losing some functionality or workflow we've been using for many-many years is not fun.

For most of us it's part of our daily routine.

So at least letting people discuss it here instead of burying the dissidence in other places seems like a good idea. Keeping a semblance of civility is important, so let's try being constructive. Hopefully the main developer is open to improving the situation instead of losing what makes the program unique and worthwhile over other solutions and keeps the spirit of the UI.

Reminds me a bit of Mozilla killing arbitrary extensions and configurability on Android, the only thing that puts it above the rest.

**Comment by cketti** [comment] 2021-08-13 15:47
See #5570

**Closed by cketti** 2021-08-13 15:47 UTC
Labels: enhancement
