### ISSUE TITLE
corrupted mail headers when To/Cc longer than 1024 characters

### ISSUE THREAD

**Issue by evgeni** [k9mail/k-9#2709] opened 2017-08-27 12:56 UTC
### Expected behavior
When answering an email with the following `To` line:

    To: test1@broken.k9mail.example.com, test2@broken.k9mail.example.com, test3@broken.k9mail.example.com, test4@broken.k9mail.example.com, test5@broken.k9mail.example.com, test6@broken.k9mail.example.com, test7@broken.k9mail.example.com, test8@broken.k9mail.example.com, test9@broken.k9mail.example.com, test10@broken.k9mail.example.com, test11@broken.k9mail.example.com, test12@broken.k9mail.example.com, test13@broken.k9mail.example.com, test14@broken.k9mail.example.com, test15@broken.k9mail.example.com, test16@broken.k9mail.example.com, test17@broken.k9mail.example.com, test18@broken.k9mail.example.com, test19@broken.k9mail.example.com, test20@broken.k9mail.example.com, test21@broken.k9mail.example.com, test22@broken.k9mail.example.com, test23@broken.k9mail.example.com, test24@broken.k9mail.example.com, test25@broken.k9mail.example.com, test26@broken.k9mail.example.com, test27@broken.k9mail.example.com, test28@broken.k9mail.example.com, test29@broken.k9mail.example.com, test30@broken.k9mail.example.com, test31@broken.k9mail.example.com, test32@broken.k9mail.example.com

I expect that the answer has correctly formatted headers.

### Actual behavior
The mail K9 generates looks like this:

```
<other headers>
To:

test1@broken.k9mail.example.com,test2@broken.k9mail.example.com,test3@broken.k9mail.example.com,test4@broken.k9mail.example.com,test5@broken.k9mail.example.com,test6@broken.k9mail.example.com,test7@broken.k9mail.example.com,test8@broken.k9mail.example.com,test9@broken.k9mail.example.com,test10@broken.k9mail.example.com,test11@broken.k9mail.example.com,test12@broken.k9mail.example.com,test13@broken.k9mail.example.com,test14@broken.k9mail.example.com,test15@broken.k9mail.example.com,test16@broken.k9mail.example.com,test17@broken.k9mail.example.com,test18@broken.k9mail.example.com,test19@broken.k9mail.example.com,test20@broken.k9mail.example.com,test21@broken.k9mail.example.com,test22@broken.k9mail.example.com,test23@broken.k9mail.example.com,test24@broken.k9mail.example.com,test25@broken.k9mail.example.com,test26@broken.k9mail.example.com,test27@broken.k9mail.example.com,test28@broken.k9mail.example.com,test29@broken.k9mail.example.com,test30@broken.k9mail.example.com,test31@broken.k9mail.example.com,test32@broken.k9mail.example.com
From: Evgeni Golov <evgeni@golov.de>
Message-ID: <1ED16679-4CF3-45FF-B55F-F879AB5564BD@golov.de>

<the real message body>
```

Due to the empty line between `To:` and the address list, the addresses and the `From` is not considered to be headers anymore, but message body. Thus the mail looks like it has neither a recipient nor a sender (and that triggers spam filters).

### Steps to reproduce
1. Answer (or write?, did not test that) an E-Mail which has a `To` or `Cc` field longer than 1024 characters

### Environment
K-9 Mail version:
5.207

Android version:
* Android 7.1.1  (OxygenOS 4.1.7) on OnePlus 3
* also observed on other Android versions

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (should not matter)

**Comment by cketti** [comment] 2017-08-27 15:01
Duplicate of #822

**Closed by cketti** 2017-08-27 15:01 UTC
