### ISSUE TITLE
K9 hangs up if connection goes unused for around a minute

### ISSUE THREAD

**Issue by z28cueball** [k9mail/k-9#989] opened 2016-01-01 15:58 UTC
This problem is happening on a Samsung running OS 4.4.4, and a Droid Turbo running OS 5.1.
This problem occurs using IMAP with EITHER polling or IDLE.
This problem occurs on 3G, 4G, and multiple internet connections.
This problem occurs with multiple e-mail providers.

If the connection is used every minute (either via e-mails coming in, going out, etc., or by a poll  or IDLE refresh), the connection is fine.  If the polling or IDLE refresh is set to anything longer than a minute, and no e-mails come in or go out, the connection stops working.

Once the connection has gone unused for over a minute, any attempt to do anything with the connection (poll, send e-mail, delete an existing email) will cause K9 mail to hang up (the application still responds, but it is stuck trying to communicate with the server).

I did force close K9 after waiting 25 minutes for it to give up trying to communicate with the server and/or throw an error.  Once it was force stopped and re-opened, the following error was in the error folder:

java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
    at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
    at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
    at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
    at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
    at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
    at java.io.InputStream.read(InputStream.java:162)
    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
    at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
    at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:42)
    at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
    at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
    at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2925)
    at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:862)
    at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3151)
    at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
    at libcore.io.Posix.recvfromBytes(Native Method)
    at libcore.io.Posix.recvfrom(Posix.java:185)
    at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
    at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
    ... 14 more

**Comment by z28cueball** [comment] 2016-01-01 21:12
The logcat is showing a bunch of StrictMode policy violations in regards to K9
[k9-log.txt](https://github.com/k9mail/k-9/files/76033/k9-log.txt)

**Comment by z28cueball** [comment] 2016-01-01 21:17
The log is also showing this line
01-01 16:08:08.165 I/ActivityManager(  884): Waited long enough for: ServiceRecord{cf6d64a u0 com.fsck.k9/.service.PollService}
Not sure if either of these entries have anything to do with the problem I'm experiencing.

**Comment by z28cueball** [comment] 2016-01-01 21:38
I also ran a logcat with no filters while triggering a poll in K9 after no e-mail activity for 3 minutes, which caused it to hang up, and saw the following in that log:

I/Choreographer(17377): Skipped 30 frames!  The application may be doing too much work on its main thread.
W/Resources(17377): Converting to int: TypedValue{t=0x3/d=0x9e8 "0" a=2 r=0x7f090262}
I/ConversationCursor(17377): ConversationCursor pre-loading took 2ms n=1
W/ResourceType( 1541): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1541): Failure retrieving resources for com.fsck.k9: Resource ID #0x0

**Comment by cketti** [comment] 2016-01-01 22:14
Currently, K-9 Mail is not closing connections after performing an operation. For the next operation one of the existing connections is reused. If a gateway has dropped the TCP connection in the meantime, all further packets sent for this TCP connection will never reach the destination. Since K-9 Mail waits for a response the connection will run into the read timeout eventually and the dead connection will be discarded. The failed operation will be retried eventually and then a another connection from the pool is used or a new connection opened in case there are none left in the pool. So operations should complete eventually. 

Always closing connections after a completed operation would probably alleviate your problem. But it would also mean having to constantly create new connections and authenticating to the server. Since the current way works for the vast majority of users changing this behavior is very low priority.

Not being able to send data after 1 minute is an exceptional case and has nothing to do with K-9 Mail. It might be because of a home router, mobile gateway or firewall that drops idle connections.

**Closed by cketti** 2016-01-01 22:14 UTC

**Comment by z28cueball** [comment] 2016-01-01 23:10
I really wish you would stop closing my issues.  Clearly something is wrong here.  I've spent weeks troubleshooting it to rule out the mail server, internet connection/mobile data connection, etc.
As I stated in my original post, it is happening on multiple internet providers as well as on mobile data.  None of the internet connections in question had a firewall.  Other phones work just fine with K9, the same email servers, and the same internet connections.
As far as you saying it "eventually" times out, it can take half an hour for it to time out.

**Comment by z28cueball** [comment] 2016-01-01 23:20
Also, this behavior does NOT occur using a computer and telnet, so the issue is NOT with the mail server OR the internet connection / network setup.

**Comment by cketti** [comment] 2016-01-01 23:26
Sorry, maybe I should have been more explicit. I'm closing this issue because nobody will be looking into it.
Without being able to reproduce the behavior on a developer's device, tracking down what's causing this issue would require a large amount of time and communication. Given that there are a lot of other bugs and you appear to be the only affected user it doesn't make sense for a developer to look into your issue.
If you manage to find out what must be changed in K-9 Mail to make it work in your environment, we'd be happy to accept a pull request.

**Comment by z28cueball** [comment] 2016-01-01 23:29
Ok, well thanks for the clarification :-)  I was hoping that maybe someone a little smarter than me would be able to look at the logs I posted and see right away what was wrong.
There are other people affected by it, I spent weeks trying to find a solution and ruling things out before posting, and during that time I found plenty of postings around the net of people experiencing similar issues.

**Comment by z28cueball** [comment] 2016-01-01 23:31
You mentioned being unable to duplicate it on a developer's device.  What if I sent you a device that was having the issue?

**Comment by jgrosseo** [comment] 2017-08-04 08:19
Same issue here using imap, android 6.0.1, kmail 5.207.
Occurs over both wireless at work and home, and 3g.
