### ISSUE TITLE
Database storage

### ISSUE THREAD

**Issue by Goodingn** [k9mail/k-9#863] opened 2015-10-24 12:44 UTC
Even though I have the Account Storage set to SDcard, it stores the data on internal storage. Kitkit/Lollipop

**Comment by cketti** [comment] 2015-11-02 18:59
It's working as originally intended. However, due to changes in what Android considers "external storage" the wording is no longer correct.
This has been "broken" for a while now and it seems nobody with the skills to fix it cares. So I'm inclined to drop the feature altogether.

**Comment by johnnybaloney** [comment] 2015-12-10 11:30
My phone runs **Android 4.3.1 (Jelly Beans)**. Which Android version broke the current k9 implementation?

Would it be possible for the user to decide the database storage path by himself? Just as it's done in the `Settings -> Global Settings -> Miscellaneous -> Save attachments to...` which works fine and saves attachments to the actual SD card. I have always been confused by the storage area naming in Android.

----
I understand that the maintainers are aware of the issue but just a bit more description for users like me who are puzzled with what's going on. The [wiki page](https://github.com/k9mail/k-9/wiki/Storage#mail-databases) does not mention this problem.

This is what I see:

```
                       | internal       | SD card
--------------------------------------------------------
fresh installation     | 0.5 MB         | 0
--------------------------------------------------------
importing settings (all accounts storage set to SD card)
--------------------------------------------------------
first sync             | 33 MB          | 0
--------------------------------------------------------
changed one account    | 22 MB          | 0
storage to internal    |                |
--------------------------------------------------------
changed the account    | 33 MB          | 0
storage back to SD     |                |
```
It turns out that **External storage (SD card)** means `/sdcard/Android/data/com.fsck.k9` (which is in fact internal) and **Regular internal storage** means `/data/data/com.fsck.k9` (which is also internal). That's why it's always 0 on the right hand side in the table above, k9 just shifts the databases from one directory in the internal storage to another.

**Comment by gappleto97** [comment] 2015-12-12 00:31
Part of the problem is that OEMs will often change the mount point for external storage. I don't know how K-9 handles it, but on the devices in front of me I have:

|Device|Internal|External|
-------------------------------
|NVidia Shield|/sdcard0|/sdcard1|
|Galaxy S5\*|/sdcard|/extSdCard|

\*From memory, it's at home

**Comment by denim2x** [comment] 2015-12-18 01:09
@Goodingn @johnnybaloney Please consider backing this issue at ![Bountysource](https://api.bountysource.com/badge/issue?issue_id=27664598)

**Comment by philipwhiuk** [comment] 2016-04-06 23:16
**Transcribing my comments on the mailing list:**

From Android's perspective /storage/emulated/0 is considered external storage. Basically the device manufacturer gets to decide what external storage really is. It's better classified as "typically fixed on device storage logically separated from the normal storage"

The very fact that the Nexus line doesn't contain removable storage options tells you how much Google care about this.

See https://commonsware.com/blog/2014/04/08/storage-situation-external-storage.html for the completely insane tortured logic that gets you there.

Also: https://commonsware.com/blog/2014/04/09/storage-situation-removable-storage.html

What and end user thinks of 'external storage' is better named 'removable storage'.

And for Android 4.4 the problem is (again quoting):

"... apps cannot write to or otherwise modify such removable storage. Note that device manufacturers themselves may have ways of dealing with this, but ordinary app developers do not."

For Android 5.0 there is a solution documented here:

https://metactrl.com/docs/sdcard-on-lollipop/

We need to implement this if we want to support SD card support.

This also does need careful design as we probably want to avoid:

* Other apps reading our files (which you don't get in 'internal storage')
* Storing unencrypted copies of encrypted content
* The app crashing without explanation if an SD card with all the settings and stuff on being removed

I also think that asking users to provide the path for 'external storage' is bad UX anyway. Using a file browser would be better. This whole setting needs ripping out and improving in a backward compatible manner.

There's lots of related improvements to do in this sort of area, like the ability to inspect where K-9 is actually using storage (big messages etc).

**Comment by Goodingn** [comment] 2016-04-07 06:54
Have a look at Locus Map Free for a good example of handling SDcard access. It's not the only app that manages this, but it has the best UI for managing it too. It's the 'Locus root folder' setting.

In a nutshell, apps like this started by creating a simple folder, like 'Locus' on the SDcard and storing large ammounts of data there. Then when Android brought the storage changes, this folder was then located on internal storage.

Most apps then offered a workable solution by using a folder in the Android/data/app.name/files folder on the SDcard. This offered the large storage available to the SDcard, but the data didn't persist between installs. This sounds best for K9.

Another solution was to offer access to the SDcard via the /storage/sdcard1/ path. Most apps tell me this will be read only, but it works fine on my phone. I suspect it's a manufacturer thing.

I wonder if all of /sdcard1/ is usually read-only, except for each app's folder in /sdcard1/data/android/ ?

I've also seen the granting access feature, but I've not seen it in any of my most used apps and it's tricky to use.

It all smells like Windows Vista, doesn't it ;)

N

On 7 April 2016 00:16:44 BST, Philip <notifications@github.com> wrote:
>**Transcribing my comments on the mailing list:**
>
>From Android's perspective /storage/emulated/0 is considered external
>storage. Basically the device manufacturer gets to decide what external
>storage really is. It's better classified as "typically fixed on device
>storage logically separated from the normal storage"
>
>The very fact that the Nexus line doesn't contain removable storage
>options tells you how much Google care about this.
>
>See
>https://commonsware.com/blog/2014/04/08/storage-situation-external-storage.html
>for the completely insane tortured logic that gets you there.
>
>Also:
>https://commonsware.com/blog/2014/04/09/storage-situation-removable-storage.html
>
>What and end user thinks of 'external storage' is better named
>'removable storage'.
>
>And for Android 4.4 the problem is (again quoting):
>
>"... apps cannot write to or otherwise modify such removable storage.
>Note that device manufacturers themselves may have ways of dealing with
>this, but ordinary app developers do not."
>
>For Android 5.0 there is a solution documented here:
>
>https://metactrl.com/docs/sdcard-on-lollipop/
>
>We need to implement this if we want to support SD card support.
>
>This also does need careful design as we probably want to avoid:
>
>* Other apps reading our files (which you don't get in 'internal
>storage')
>* Storing unencrypted copies of encrypted content
>* The app crashing without explanation if an SD card with all the
>settings and stuff on being removed
>
>I also think that asking users to provide the path for 'external
>storage' is bad UX anyway. Using a file browser would be better. This
>whole setting needs ripping out and improving in a backward compatible
>manner.
>
>There's lots of related improvements to do in this sort of area, like
>the ability to inspect where K-9 is actually using storage (big
>messages etc).
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/863#issuecomment-206616235

-- 
Neil Gooding

**Comment by jimktrains** [comment] 2016-09-11 22:06
Would the simplest solution be to allow the user to enter a path for the database ? While it's unfortunate that Google has made the decisions it has, I would wage that users interested in changing the storage location would be OK with specifying that location.  I believe this is what OsmAnd does.

**Comment by philipwhiuk** [comment] 2016-09-12 14:14
No because:

a) It would be horribly hacky.
b) It would likely result in more obscure issues being raised as bugs taking up developer time.
c) It would not work on newer versions of Android where permission has to be granted
d) It would do odd things if the removable storage was removed mid-poll.

I'm absolutely against replacing one ugly setting that few change, with more ugly settings that few change and exposing more of Android's ugly internals.

We should do it properly or not all. Supporting removable storage is a new enhancement - there is no justification for hacking it in badly.

**Comment by Goodingn** [comment] 2016-09-14 11:33
"We should do it properly or not all. Supporting removable storage is a new enhancement - there is no justification for hacking it in badly."

Doing it properly sounds ideal.  When does this start?

**Comment by cketti** [comment] 2016-09-14 11:36
@Goodingn: Please use the [mailing list](http://groups.google.com/group/k-9-mail) for questions or comments that don't add anything to the technical issue.

**Comment by hako1** [comment] 2017-08-20 05:00
I have about 3 GB email storage on my Note 3 eating up my internal memory. Since there does not seem a way to store the emails on ext SD card, K9 is no longer usable for me.
The devs are not willing to solve the problem. Need to find an alternative...

**Comment by 3j9fkyahunqoxwqu** [comment] 2019-08-26 18:15
I also have this problem. 
Please fix it if may.

**Comment by 3j9fkyahunqoxwqu** [comment] 2019-08-26 18:17
I also have this problem. 
Please fix it if may. 
I also think adding a advanced option with caution to user that it may breaks app will be gteat and you can for ex. in it let user set path themselves or...

**Closed** 2019-11-22 03:03 UTC
Labels: enhancement, help wanted
