### ISSUE TITLE
Feedback for 5.702 version UI with multiple accounts

### ISSUE THREAD

**Issue by chrkuhlmann** [k9mail/k-9#4395] opened 2019-12-20 09:14 UTC
Hi,
here are a few issues I noticed with the new UI of 5.702 compared to 5.6 when using multiple mail accounts.
In essence I suggest to bring back the option for some kind of overview page that lists all accounts, since this gives much better overview and more direct access to the accounts. It should be displayed whenever the back button is pressed inside the top hierarchy of an account or the combined inbox.
I do appreciate the new UI for navigating within accounts but the overview page still has a useful place.

Advantages:
* Direct access by using the back button, no need to open the burger menu, scroll up, and use a dropdown to select the account (1 button press instead of 4 complex actions)
* Direct navigation to unread **and** marked messages **and** folderlist
* Fast overview of new and starred messages without a combined inbox

Thanks for considering this. Keep up the great work.

### Environment
K-9 Mail version:
5.702 
Android version:
9
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by rkoe** [comment] 2020-01-08 08:57
+1

Please also bring back the "manually sync all"-button on the overview-page:
In 5.600, it was possible to manually sync all folders with one click on the overview-page;
in 5.70x, every folder has to be synced separately, which is really tedious.

**Comment by cketti** [comment] 2020-02-07 17:17
Duplicate of #4405

**Closed by cketti** 2020-02-07 17:17 UTC
