### ISSUE TITLE
doesn't display clickable links

### ISSUE THREAD

**Issue by nico239** [k9mail/k-9#2922] opened 2017-11-08 23:15 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
click on link into mail

### Actual behavior
Tell us what happens instead
impossible to click on link into mail

### Environment
K-9 Mail version: last

Android version: 4:4:2

Account type (IMAP, POP3, WebDAV/Exchange):
imap

**Comment by philipwhiuk** [comment] 2018-01-15 22:51
Without the source of the email it's hard to tell the problem - though we have done some HTML parsing improvements since last release.

**Comment by njeyaakili** [comment] 2018-01-15 23:17
If a text-part only message has the url as:

  <https://github.com/k9mail/k-9/releases>

i.e., with the angle brackets - which is a fairly standard form (my desktop email client puts them in by default on a paste) - version 5.403 doesn't hyperlink it, version 5.107 does -- don't know where the change happened.

@nico239 -- when giving your K-9 version it would be helpful to give the explicit number. "last" isn't very meaningful.

**Comment by nico239** [comment] 2018-01-15 23:43
﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ 
Hi Philip

Try with this forum

https://www.econologie.com/forums/?sid=7c08437b123d9853ac6e90a9ec5f403a 

And tell me if the links of the mail subscriptions are clickable?





Adrien
envoyé avec Foxmail 7.0.93


De: Philip
Date: 2018-01-15 23:51
Pour: k9mail/k-9
Cc: nico239; Author
Sujet: Re: [k9mail/k-9] doesn't display clickable links (#2922)

Without the source of the email it's hard to tell the problem - though we have done some HTML parsing improvements since last release.

**Comment by nico239** [comment] 2018-01-16 00:27
﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ 
Hi Philip

Look at these 2 screenshots

- K9 forum éconologique : no link KO
- Old Samsung email client, forum éconologique : link OK

Why???




Adrien
envoyé avec Foxmail 7.0.93


De: Philip
Date: 2018-01-15 23:51
Pour: k9mail/k-9
Cc: nico239; Author
Sujet: Re: [k9mail/k-9] doesn't display clickable links (#2922)

Without the source of the email it's hard to tell the problem - though we have done some HTML parsing improvements since last release.

**Comment by garfieldthecat** [comment] 2018-01-17 23:48
To reproduce the error, send yourself a text email with the body containing exactly the following (copy the text verbatim, with the < and > characters):

```
<http://www.google.com>

<www.google.com>

http://www.google.com

www.google.com
```


You will notice only the third link works (i.e. can be clicked on) - the others are not recognised as such.

The links in the format `<http://www.website.com>` come from newsletters I am subscribed to; from memory, they used to work just fine before the 5.403 update.

**Comment by garfieldthecat** [comment] 2018-01-18 14:51
Can 'needs info' be removed now that examples to reproduce the error have been provided?

**Comment by nico239** [comment] 2018-01-18 14:56
﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ 
if you try k@mail there are no errors




Adrien
envoyé avec Foxmail 7.0.93


De: garfieldthecat
Date: 2018-01-18 00:48
Pour: k9mail/k-9
Cc: nico239; Mention
Sujet: Re: [k9mail/k-9] doesn't display clickable links (#2922)

To reproduce the error, send yourself a text email with the body containing exactly the following (copy the text verbatim, with the < and > characters):
<http://www.google.com>

<www.google.com>

http://www.google.com

www.google.com

You will notice only the third link works (i.e. can be clicked on) - the others are not recognised as such.
The links in the format <http://www.website.com> come from newsletters I am subscribed to; from memory, they used to work just fine before the 5.403 update.

**Comment by nico239** [comment] 2018-01-18 14:56
﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ ﻿ 
the error is in k9 but not in Samsung client or in k@




Adrien
envoyé avec Foxmail 7.0.93


De: garfieldthecat
Date: 2018-01-18 15:51
Pour: k9mail/k-9
Cc: nico239; Mention
Sujet: Re: [k9mail/k-9] doesn't display clickable links (#2922)

Can 'needs info' be removed now that examples to reproduce the error have been provided?

**Comment by stoecker** [comment] 2018-01-18 15:05
Not. Also other brackets like [], not only <> are affected.

**Comment by Djfe** [comment] 2018-02-08 07:57
an example from a trac server
[trac.zip](https://github.com/k9mail/k-9/files/1706141/trac.zip)

Thunderbird for example makes the links in text e-mails clickable.
K9 should do so as well :)

**Comment by philipwhiuk** [comment] 2018-02-08 13:21
Probably a duplicate of #913

**Comment by Djfe** [comment] 2018-02-08 13:28
not a duplicate but related
but since you're already working on this ^^ w/e

**Closed** 2019-03-01 02:09 UTC
