### ISSUE TITLE
Mail not marked as read

### ISSUE THREAD

**Issue by kenmak** [k9mail/k-9#671] opened 2015-06-04 01:44 UTC
What's going wrong?

Read email not marked as read in the server

What steps will reproduce the problem?
1. Read mail
2. Mail marked as read on K9
3. When new mail arrives, the previous email is marked unread

What do you expect to have happen?

1. After reading mail on K9, mail is marked as read on server

What do you see instead?

1. After reading mail on K9, mail is not marked read on server.
2. on next sync, mail marked unread at K9

What version of K-9 are you using?

5.005

What is your device and what version of Android are you using?

Asus Zenfone 2 
Android version 5.0

Is your email account a POP account, Exchange Account or an IMAP account?

IMAP account

**Comment by cketti** [comment] 2015-06-07 20:55
This is most likely not a bug in K-9 Mail, but an issue with your setup. Without a debug log it's impossible to tell what's happening.

**Comment by DreamR-Heart** [comment] 2015-09-06 18:34
Cketti, I have k9-mail v 5.006 on my 2nd gen Moto X and have seen it develop the same problem. 

Messages are no longer being marked as read from more than once instance. 

What logs, rather, how would I get the data to share?

**Comment by DreamR-Heart** [comment] 2015-09-06 19:37
I am seeing SSLException: Write errors

http://node02.com/wErrors.txt

**Comment by philipwhiuk** [comment] 2016-03-30 17:01
"Connection reset by peer" means either a timeout that we should be retrying over or the phone lost it's internet connection.

**Closed** 2016-07-17 22:11 UTC
Labels: needs info
