### ISSUE TITLE
Modify View

### ISSUE THREAD

**Issue by werano** [k9mail/k-9#5039] opened 2020-11-02 10:29 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I still miss the View modifying subject. In the actual 5.60 version I have the startup scree will the tree of all my accounts. In the 5.7xx versions that subject is still missing.

**Comment by cketti** [comment] 2020-11-04 13:38
Duplicate of #4405

**Closed by cketti** 2020-11-04 13:38 UTC
Labels: enhancement
