### ISSUE TITLE
When Deleting Emails older Emails notify as if they are new in IMAP configuration

### ISSUE THREAD

**Issue by daviwph** [k9mail/k-9#3448] opened 2018-06-16 02:41 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When deleting Email from the inbox, older Emails that fill in at the end of the list should not send a notification.

### Actual behavior
When deleting Email from the inbox, older unread Emails will send a notification as if they are new Emails.

### Steps to reproduce
1.  Go to the inbox and make sure the specified number of Emails are loaded.  In my case, the number is 50.
2.  Make sure that there are more the 50 emails in the IMAP inbox
3.  Delete one of the 50 emails and wait for K9 to fetch.  An older unread email will send a notification.

### Environment
K-9 Mail version:  5,503  (however, this is not related to the latest version)

Android version: 4.1.2

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by cketti** [comment] 2019-03-08 02:48
Duplicate of #2092

**Closed by cketti** 2019-03-08 02:48 UTC
