### ISSUE TITLE
Can't authenticate outgoing server on WiFi

### ISSUE THREAD

**Issue by HickoryHollowUpland** [k9mail/k-9#3976] opened 2019-03-20 18:47 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
The email should send to recipients as normal, whether on WiFi or mobile data.

### Actual behavior
If connected to WiFi, the sent message sits in the Outbox because a connection to the server cannot be made and then I get periodic messages that the email was not sent. If I disconnect from WiFi, the email is sent as expected and doesn't sit in the Outbox. 

### Steps to reproduce
1. Turn on WiFi
2. Write email and then send
3. Check outbox folder, message never gets sent.
4. Turn off WiFi
5. Write email and then send
6. Check outbox, message is gone and is now in the Sent messages folder

You can also verify the outgoing server in the Account Settings. When WiFi is off (phone is using mobile data) it authenticates normally, but when WiFi is on, the connection to the outgoing server times out. 

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2019-03-21 00:26
Duplicate of #3977

**Closed by cketti** 2019-03-21 00:26 UTC
