### ISSUE TITLE
[Feature request] Change order of accounts

### ISSUE THREAD

**Issue by Christian-Git01** [k9mail/k-9#4875] opened 2020-07-14 10:16 UTC
As far as I know the accounts appear in the order they were added. It would be great if one can manually change the order.

**Comment by cketti** [comment] 2021-01-24 01:52
I'd like us to support this feature by changing the settings screen to allow accounts to be reordered via drag and drop. The material design guidelines contain an example on how that should look like: https://material.io/components/lists#behavior (second example under the heading "Gestures")

The relevant class in K-9 Mail's code base is [`SettingsListFragment`](https://github.com/k9mail/k-9/blob/main/app/ui/legacy/src/main/java/com/fsck/k9/ui/settings/SettingsListFragment.kt).
We use the [FastAdapter](https://github.com/mikepenz/FastAdapter) library for the list. The sample app for the library contains an example for reordering a list using drag and drop: [`SimpleItemListActivity`](https://github.com/mikepenz/FastAdapter/blob/525a261372e80fe62804ab1812f5925d8a9ddbfc/app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.kt) (the UX is slightly different, though; so the approach probably can't be copied as-is)

There is some left-over code to reorder the account list from the previous implementation of this feature: [`Preferences.move()`](https://github.com/k9mail/k-9/blob/ac95fe9e33e25e29711a47165d2bb976ef9ec48c/app/core/src/main/java/com/fsck/k9/Preferences.java#L305)
It probably needs adjusting and shouldn't be used as-is. But it should illustrate what needs to be done.

Things to consider:
- the "drag area" should be limited to the sub-list of accounts, i.e. we don't want users to be able to drag an account above the "Accounts" section header or below the "Add account" list item
- when there's only one account the functionality should be disabled; there's no point in showing a drag handle when there's nothing useful you can do with it
- saving the new account order must not happen in the main/UI thread

**Comment by poldi171254** [comment] 2021-02-23 07:19
I noticed that the issue was closed. I'm still working on a fix

**Comment by cketti** [comment] 2021-02-23 11:06
> I noticed that the issue was closed. I'm still working on a fix. While you may think this is a trivial fix it took me a while to get up to speed on a few things:-)

This issue is still open. Another issue that mentioned this one was closed.

**Comment by poldi171254** [comment] 2021-02-25 05:00
I have a small working example based on Mike's demo. Issue is that it uses FastAdapter (and extensions) version 5.1.3. When I try to compile k-9 with the latest version I get quite a few compiler errors similar to

`Inherited platform declarations clash: The following declarations have the same JVM signature (bindView(Lcom/fsck/k9/ui/settings/import/ImportCheckBoxViewHolder;Ljava/util/List;)V): fun bindView(holder: ImportCheckBoxViewHolder, payloads: List<Any>): Unit defined in com.fsck.k9.ui.settings.import.GeneralSettingsItem fun bindView(holder: ImportCheckBoxViewHolder, payloads: MutableList<Any>): Unit defined in com.fsck.k9.ui.settings.import.GeneralSettingsItem`

Not sure how to proceed as the older version of FastTrack lacks the functionality needed for this.

**Comment by cketti** [comment] 2021-02-25 13:41
I'll have a look at how much work it is to upgrade to the latest version of FastAdapter.

**Comment by cketti** [comment] 2021-02-26 02:33
Turns out: quite a bit. After PR #5169 is merged you'll be able to use the latest `FastAdapter` version.

**Comment by poldi171254** [comment] 2021-02-26 03:41
ok. Will wait.
Anything else you'd like me to work on in the meantime?

**Comment by cketti** [comment] 2021-02-26 17:33
Apologies. What I meant was that it took me all day yesterday to get it done. The change is now merged and the app uses FastAdapter 5.3.4.

**Comment by poldi171254** [comment] 2021-03-01 02:08
I think I've got this working. One thing I found is that the first account  (in the attached Test2) should be the 'default/first' account to be displayed, but it stays with Test1

![Mail-2](https://user-images.githubusercontent.com/43848359/109443566-fb993a80-7a8e-11eb-916e-875b68d06013.png)
![Mail Account](https://user-images.githubusercontent.com/43848359/109443575-018f1b80-7a8f-11eb-91e0-28ddff7b01fc.png)


![Mail](https://user-images.githubusercontent.com/43848359/109443446-abba7380-7a8e-11eb-9448-1dfa0e63396b.png)

**Comment by cketti** [comment] 2021-03-01 13:55
It's hard to guess the cause of a problem when all you have is a couple of screenshots. Please open a draft pull request with what you have so far.

**Comment by cketti** [comment] 2021-03-03 13:57
The default account is independent from the order of accounts. It can be configured under `Settings > [Account] > General settings > Default account`. I forgot about this. It feels unnecessary to have this kind of flexibility. We'll probably get rid of it in the future and make the first account the default account. But changing this is out of scope for this issue.

**Closed** 2021-04-12 16:15 UTC
Labels: enhancement
