### ISSUE TITLE
Manual email recipient entry jumps after typing 3 characters

### ISSUE THREAD

**Issue by NunovYurbiz** [k9mail/k-9#3474] opened 2018-06-29 07:16 UTC
### Expected behavior
While creating a new email message to send, I should be able to manually type the full email address of any recipient who is NOT already in my contacts. (No one has the entire world's email addresses in their phone's address book.)

The expected behavior is to enable the user to manually type the entire email address without interruption or jumping the cursor to another field in the middle of typing the address. The app should automatically dismiss the contact suggestion pop-up if the user continues to type without selecting it.

The app prevents this under the entry sequence detailed below.

### Actual behavior
After typing only 2 characters into the To: or Cc: or Bcc: fields, the auto-suggest pop-up appears (for matches found in my contacts list). Since this address is NOT in that list, I continue typing the desired email address manually like a normal user would likely do in an email client.

However, upon typing the 4th character in the new email address, that 4th character is ignored and the input cursor immediately jumps down into the message field somewhere in the middle of my predefined signature block text.  The precise location of the cursor after it jumps is seemingly random in the signature block below. (I haven't been able to find a pattern on the exact jump location, just that it's always several lines down.)

This causes the user to have the email address split with the first 3 characters displayed in the To: or Cc: or Bcc: field, the 4th character completely skipped, and the remainder of the manually-typed address wedged somewhere in the middle of the signature block text.

Also the To: or Cc: or Bcc:  field displays the red exclamation symbol with this error message displayed: "Error parsing address!".  Which is a mess! This creates many errors in the entry process and wastes time!

### Steps to reproduce
1. Select an account to view emails
2. Tap the Compose icon at bottom of screen.
3. Begin manually typing an email address that is NOT stored in your contacts/address book, but which shares the two-letter pattern of one or more existing contacts. For example: The manual email adress begins with 'bobbi' but that contact does not exist. Typing 'bo' (w/o quotes) will generate a pop-up with all matches of those two characters in your existing contacts (like Bob Smith or Mary Peterbo for example - fictitious names for illustration purposes).
4. Do NOT select or dismiss that pop-up list, but continue to type the email address as a user would expect it to continue accepting characters.
5. The third letter will appear in that same To: or Cc: or Bcc: field.
6. As soon as you type the 4th character, it immediately jumps the cursor down into the body/message field, where subsequent typing of the address is inserted somewhere several lines down in a multi-line signature block.

After much experimentation, the only workaround I discovered is below which is disruptive to the expected entry flow:

1. After typing the first 2 characters of the email address, the suggestive pop-up list appears if there is a pattern match. (This happens very frequently for me, nearly every time.)

2. You MUST then EITHER:
A.  Manually tap in the white space in that same To: or Cc: or Bcc: field (to the right of the 2 characters you just typed), OR
B. Press the Android back button at the bottom.

3. Either of these two actions has the effect of dismissing the suggestion pop-up list, and then you can continue typing the remainder of the desired email recipient's address.

Again, very frustrating, it took a while to figure out why it was happening most times, but not always.

### Environment
K-9 Mail version: 5.403 (just newly installed this week from the Play store).

Android version: 8.1.0 on newly activated Google Pixel 2 XL (current with June 5th, 2018 security update).

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by SandorDobos** [comment] 2018-07-04 15:57
Hi

Same here.
K9: 5.403
Android: 8.0.0
MIUI 9.6.1.0

Tried to change gboard keyboard input to other (hacker's kb), but same effect so this is not
a google magic I suppose.

**Comment by SandorDobos** [comment] 2018-07-04 16:03
possible duplicate: #3150

**Comment by cketti** [comment] 2018-07-12 12:19
Duplicate of #2829

**Closed by cketti** 2018-07-12 12:19 UTC
