### ISSUE TITLE
Accounts sorting

### ISSUE THREAD

**Issue by gjf** [k9mail/k-9#4943] opened 2020-09-14 16:37 UTC
**Is your feature request related to a problem? Please describe.**
I am using a number of different accounts and I'd like to sort them in a proper order. But the order is the only adding accounts time.

**Describe the solution you'd like**
I would like to have a possibility to move accounts up and down.

**Describe alternatives you've considered**
Grouping accounts alphabetically.

**Additional context**
None, I think it is quite self-explaining but please let me know if more information is needed.

**Comment by cketti** [comment] 2020-09-14 16:51
Duplicate of #4875

**Closed by cketti** 2020-09-14 16:51 UTC
Labels: enhancement
