### ISSUE TITLE
[5.205] CertPathValidatorException

### ISSUE THREAD

**Issue by michaelof** [k9mail/k-9#2355] opened 2017-03-07 12:18 UTC
### Expected behavior
Receive Email without error. E.g. Thunderbird on Linux does not throw any exceptions for same imap server.

### Actual behavior
Starting with 5.205, K9 throws an CertPathValidatorException for email provider freenet.de (see screenshot appended)

### Steps to reproduce
1. (create freemail account, if not exist)
2.  add mx.freenet.de as IMAP server, port 143/starttls
3. sync

### Environment
K-9 Mail version: 5.205

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP
![screenshot_2017-03-07-13-09-46](https://cloud.githubusercontent.com/assets/15951622/23656058/5cef30aa-0338-11e7-87ac-6493f5032c14.png)

**Comment by philipwhiuk** [comment] 2017-03-07 12:35
Your phone is probably missing the root certificate. I'm not sure how these get rolled out to old Android devices.

**Comment by michaelof** [comment] 2017-03-07 13:03
Hi Philip,

do you have an idea why this was "introduced" with 5.205? 
I'm using K9 for several releases now, and I've never got this error message before when using this IMAP account on this server with K9 before 5.205.

**Comment by cketti** [comment] 2017-03-07 14:59
The certificate of "mx.freenet.de" is valid from March 3 2017. So this was more likely caused by a change on the server rather than a change in K-9 Mail.

**Comment by bambam4654** [comment] 2017-03-07 23:12
So is it safe to accept the certificate?

**Comment by philipwhiuk** [comment] 2017-03-08 01:53
I expect so yes @bambam4654.

We've already got issue(s) open for re-working this dialog so it gives you a lot better information about what's wrong. Closing this.

**Closed by philipwhiuk** 2017-03-08 01:53 UTC
