### ISSUE TITLE
Reproducible RecipientSelectView bug introduces extraneous chars into text

### ISSUE THREAD

**Issue by markcapella** [k9mail/k-9#3257] opened 2018-03-14 07:46 UTC
See: https://www.dropbox.com/s/4mtyhzxdjzsb6gi/fix%20IMM%20issue.mp4?dl=0

During entry of To/Cc/Bcc fields, after completion of a recipient by tapping a suggested Icon from the contacts list, subsequent typing will re-add text from the previous typing that led to the selection of the Icon/Token in the dropdown.

See the video I've attached. The K9 with the RED ICON exhibits the issue. The K9 with the PURPLE ICON, exhibits the fix.

This probably needs to get posted to the com.splitwise:tokenautocomplete:2.0.7 GITHUB also, but I started out trying to fix you, so here's an override of one of their methods.

You can recreate the issue, by typing THREE CHARS of a contact in your list with a valid email entry, then selecting the Icon/Token by tapping. The next char typed will re-generate the three previous chars in the internal buffer.

Three chars is important as during the token substitution, it leaves the View selection length as is, tricking the IMM into avoiding an internal reset.

**Comment by cketti** [comment] 2018-03-18 10:27
I can't reproduce the issue you're seeing. What Android version and keyboard are you using?

**Comment by Valodim** [comment] 2018-03-18 16:34
I also experience it, and it's extremely annoying. Thanks for looking into this

**Comment by cketti** [comment] 2018-03-22 04:43
Fixed by #3258

**Closed by cketti** 2018-03-22 04:43 UTC
