### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by HendrikF** [k9mail/k-9#1258] opened 2016-04-04 13:51 UTC
### Expected behaviour
When changing language in settings, it should display in the set language.

### Actual behaviour
K9 Mail is still in English. Even when selecting 'system default', which is German for me.

### Steps to reproduce
1. Open K9-Mail
2. Open Settings
3. Set Language e.g. to 'Deutsch' under Display > Language

### Environment
K-9 Mail version: 5.009

Android version: 4.1.1 (HTC Desire X)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP, but should not matter

**Comment by philipwhiuk** [comment] 2016-04-04 13:56
Duplicate of #1254

**Closed by philipwhiuk** 2016-04-04 13:56 UTC
