### ISSUE TITLE
When answering an email identity isn't selected any more

### ISSUE THREAD

**Issue by renky** [k9mail/k-9#3077] opened 2018-01-10 20:58 UTC
### Expected behavior
When answering an email that came in over an additional identity this identity shall be selected automatically. 

### Actual behavior
Standard identity is selected - this is a new behaviour since the version with the new icon!! in older versions the identity was selected correctly, after the update it doesn't work any more.

### Environment
K-9 Mail version: 5.403

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2018-01-11 00:12
Probably a duplicate of #3011

**Comment by renky** [comment] 2018-01-13 11:54
Hmmm... I'm not sure if this is really a duplicate - in #3011 there is mentioned that "X-Original-To" was used instead of "To" - but in my Emails there was no X-Original-To set... But what I know see is, that in my emails there is set a "Delivered-To:" where the Emailadress of the Mailbox is used instead of one of the aliases... And when answering this Emailadress is selected. But I don't see if k9 uses this Identity because it is the Standrad-Identity, or because it is the first Identity, or the Identities email fits to the Delivered-To: 
Nevertheless I think if an email comes in with To: alias@email, and there exists an Identity with alias@email than this one should be used... And really: it worked for me the last years (without changing anything in the settings) like I think it should be - until the new versions.. so there must be changed anything in the software?! From one day to the other I used only my standard-identity when answering...

**Comment by philipwhiuk** [comment] 2018-01-14 00:02
Yeah, we've added more possibilities, including Delivered-To. The PR I've made re-prioritises the To: header to the top of the list.

**Comment by philipwhiuk** [comment] 2018-01-21 20:10
Fixed in #3079.

**Closed by philipwhiuk** 2018-01-21 20:10 UTC
Labels: being worked on, needs info, next stable
