### ISSUE TITLE
Account mailbox size

### ISSUE THREAD

**Issue by rsakanashi** [k9mail/k-9#2167] opened 2017-02-02 18:28 UTC
Hello,

The size of my account mailboxes is not decreasing when I delete messages. I have tried clearing local messages and compacting account but the size of the mailbox does not decrease, they keep getting larger. Removing and re-adding email accounts does not make a difference.

Before recent K-9 Mail updates, clearing local messages in each folder after deleting messages and emptying trash would reduce the size of the account mailbox to around 100KB or less.

There is a thread in the general purpose mailing list that began in early January.
https://groups.google.com/forum/#!topic/k-9-mail/OEpBHFCtxBo

### Environment
K-9 Mail version: 5.203

Android version: 5.0.2

Account type (IMAP, POP3, WebDAV/Exchange): POP 3 and IMAP

Your help will be appreciated.
Regards,
Richard Sakanashi

**Comment by philipwhiuk** [comment] 2017-02-03 01:34
Duplicate of #2103

Will be fixed in the next release.

**Closed** 2017-02-03 01:34 UTC

**Comment by rsakanashi** [comment] 2017-02-03 13:01
Thanks Philip
