### ISSUE TITLE
K9mail can't  find public keys of recipients

### ISSUE THREAD

**Issue by MaxLanar** [k9mail/k-9#2147] opened 2017-01-28 17:11 UTC
### Expected behavior
Successfully encrypt messages for recipients with an associated key in Openkeychain (OKC).

### Actual behavior
When I try to send encrypted messages to recipients with a public key in OKC I get this :

`"private mode is enabled but some recipients don't have keys."` and the dots of the lock icon don't become green anymore.

I've triple-checked the crypto settings of the account and the recipient address of course.

It used to work before but not anymore, I don't know what triggered that behavior.

### Steps to reproduce
1. create a new mail, fill recipient
2. Select Encrypt
3. Tap on the send icon

### Environment
K-9 Mail version: 5.203 from fdroid

Android version: cm-13

Account type : POP3

**Comment by MaxLanar** [comment] 2017-01-28 17:31
OK, seems to be a duplicate of https://github.com/k9mail/k-9/issues/942 (for my defense it's hard to text-search images... ^^)

If I do select 'encrypt if possible' the email is indeed send encrypted. I know it is encrypted because I sent an email to myself, but nothing lead me to think the email was sent encrypted (lock icon with on red dot).

**Comment by Valodim** [comment] 2017-01-28 19:53
It's it possible this is a capitalization issue? The private mode thing sucks as it is, I'm just not sure how best to do this and didn't want to trial and error iterate here too much

**Comment by MaxLanar** [comment] 2017-01-28 21:21
A capitalization issue ? You mean if I entered an address like this mAiL@servEr.com ? Then it's not, I checked and re-re-check the recipient field each time and tested with different address, the issue always comes up .

**Comment by softgenix** [comment] 2017-01-29 22:21
I have the same issue, as described.
Setting lock to "Encrypt" fails to send the message and gives the error, "Private mode is enabled but some recipients don't have keys!."   

But, using "Encrypt if possible," successfully encrypts and sends the messages.

I have K9 v 5.203,  imap, Android 6

**Comment by dschuermann** [comment] 2017-01-30 16:45
For every email address in K-9 Mail's recipients, is there a key in OpenKeychain **that contains a User ID with that email address**?

**Comment by MaxLanar** [comment] 2017-01-30 17:59
I don't know if it's what you're talking about, but the corresponding public keys  for every address I tested have the email address under "Advanced -> Identities" (words translated from french) In OpenKeychain.

**Comment by dschuermann** [comment] 2017-01-30 18:05
@MaxLanar yup I meant that. Sry for my technical words. Can you try to identity which recipient actually results in the error you described in the bug report by adding them one by one and testing? Maybe disable internet connection before so that the emails are send and then removing them from outbox.

Another idea: Is any of these keys revoked or expired?

**Comment by MaxLanar** [comment] 2017-01-30 18:20
What do you mean by "by adding them one by one and testing" ? I don't understand what you exactly want me to do.

None of the keys are expired or revoked.

**Comment by MaxLanar** [comment] 2017-01-30 21:21
@dschuermann In fact the testing I did was already with one recipient at a time (only one recipient in the 'to' field).

**Comment by rugk** [comment] 2017-01-31 22:38
Dupe of https://github.com/k9mail/k-9/issues/1655 I think.

**Comment by richfirst** [comment] 2017-02-05 16:23
I had to revert to 5.0.1 as have nothing but issues relayed to encryption/decryption,

First, I'd like to say, a great number of people, myself included, have red/green color blind issues, and to try to relay info by these, or even other colors will not work for me, I can't tell the difference. Until I read these bug reports, I didn't even know there were different colors.
Please change to something that works for color impaired purple.

Second, I can no longer decrypt any received messages: I use open key chain, I an promoted to enter my password, and then I an shown the encrypted pgp gibberish with old k9,i see the gibberish behind the prompt to enter my password, and then when it's in I see the decoded message.
The new k9 is unusable.

**Comment by rugk** [comment] 2017-02-05 18:05
> Please change to something that works for color impaired purple.

Good idea. I'd suggest to open a new issue for this though.
And as a suggestion how to fix it: The lock could be open (when it is orange). It already displays a cross when it is red, so it should just also be an "open lock".

Also for your other problem open a new issue. It does not seem as if this would have anything to do with this issue. (public keys do not seem to be the problem)

**Comment by philipwhiuk** [comment] 2017-02-05 18:27
#2189 for the colour impaired issue.

As for the other one @richfirst's description of the actual issue is too vague - it doesn't say why they can't be decrypted. But yes - if it's different please open a new issue.

**Comment by dschuermann** [comment] 2017-02-07 19:17
@MaxLanar @softgenix Can you try OpenKeychain 4.2.4 I just pushed to Google Play? We recently fixed a problem regarding the selection of public keys.

**Comment by MaxLanar** [comment] 2017-02-12 12:49
Hello,
@dschuermann Still exactly the same behavior with OpenKeychain 4.2.4 (from fdroid) for me. Nothing changed.

**Comment by madpsy** [comment] 2017-04-04 16:34
> Please change to something that works for color impaired purple.

Probably one of the best typos I've seen all day.

**Comment by rugk** [comment] 2017-10-04 19:44
Related: https://github.com/k9mail/k-9/issues/1655 (?)

**Closed** 2019-02-28 22:31 UTC
Labels: bug
