### ISSUE TITLE
Importance/Priority

### ISSUE THREAD

**Issue by nowo84** [k9mail/k-9#4033] opened 2019-04-25 08:07 UTC
please add option in compose Mail / send Mail to set Importance/Priority like "Read receipt":

*** Read receipt (already implemented in K9 Mail) ***

X-Confirm-Reading-To: (own Mail adress)
Return-Receipt-To: (own Mail adress)

*** Importance/Priority (ToDo) ***

Importance: high
X-Priority: 1

Importance: low
X-Priority: 5

Thanks

For Example:

![K9 Mail](https://user-images.githubusercontent.com/49975818/56719765-b2188f80-6741-11e9-83a1-7241149a5cba.jpg)

**Comment by cketti** [comment] 2019-05-11 01:42
Duplicate of #2329

**Closed by cketti** 2019-05-11 01:42 UTC
