### ISSUE TITLE
accounts view

### ISSUE THREAD

**Issue by plaszczy** [k9mail/k-9#5276] opened 2021-04-25 11:30 UTC
hi there,
I recently witched to a version (5.733?) where there is no more an accounts view, the app directly starts in the last viewed inbox. To change account (under parameters now) one has to perform many clicks (3 or 4 to get to the new inbox). I think it is a pity for users like myself who several accounts and not a prefered one.
So I would suggest to add the possibility to start the app in an "account" view way as it used to be.
Anyway it is still a great app, congrat for your work!
stephane

**Comment by ByteHamster** [comment] 2021-04-26 16:46
Duplicate of #4405

**Closed by ByteHamster** 2021-04-26 16:46 UTC
Labels: enhancement
