### ISSUE TITLE
Clicking notification does not go to inbox

### ISSUE THREAD

**Issue by evitalis** [k9mail/k-9#2097] opened 2017-01-20 01:44 UTC
### Expected behavior
Clicking the notification of new mail should automatically open the inbox of the applicable account.

### Actual behavior
Folder list is displayed including drafts and spam.
Might be user error or a missing setting but older versions did not have this issue.

### Steps to reproduce
1. Receive mail
2. Click notification
3. End up at folder list instead of inbox where the new message likely is
4. Click inbox to see new message

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): GMail

**Comment by ArchangeGabriel** [comment] 2017-01-20 09:15
Dupe of #1885.

**Closed** 2017-01-20 09:20 UTC
