### ISSUE TITLE
Feature request: Support for IMAP "public folders"

### ISSUE THREAD

**Issue by sgofferj** [k9mail/k-9#4093] opened 2019-06-25 09:39 UTC
At the moment, K9 seems to only show folders under the user.<username> IMAP subtree, i.e. the user's mailbox.

Public folders are folders above the IMAP user.* subtree to which users may have access to or not. Additionally, it's not uncommon that users have access to other users' mailboxes, role accounts like "webmaster", "postmaster", "root", etc. being some common examples.

It would be quite nice and useful if every folder a user has access rights to would show up in the folder list in K9.

**Comment by cketti** [comment] 2019-06-29 14:22
Duplicate of #1342

**Closed by cketti** 2019-06-29 14:22 UTC
