### ISSUE TITLE
unable to extract email address from To, Cc, or Bcc fields 

### ISSUE THREAD

**Issue by tvlovers** [k9mail/k-9#3435] opened 2018-06-08 21:57 UTC
### Expected behavior
When hitting "reply to all" I should be able to see individual email addresses as plain text like in K-9 4.804 so I could copy and paste as desired

### Actual behavior
When hitting "reply to all" I see each individual email address represented as "gif" where email "john@email.com" is represented as square box with letter "J" then "john@email.com" with no way to copy and paste that particular email address so I could add it to address book

### Steps to reproduce
1. open email
2. hit reply to all
3. expand "to" or "cc"
4. try to copy email individual email address - no go

### Environment
K-9 Mail version:
5.503
Android version:
7.1.1
Account type (IMAP, Exchange):
IMAP
Exchange

**Comment by rob-stewart** [comment] 2018-11-30 15:40
I've hit this, too. I don't mind the graphical addresses, but I'd like to be able to copy the email addresses from the pop-up *and* I'd like to be able to drag them between To:, CC:, and BCC:.

**Comment by cketti** [comment] 2019-03-08 02:37
Duplicate of #1602

**Closed by cketti** 2019-03-08 02:37 UTC
