### ISSUE TITLE
Add option to show BOTH correspondent name AND email address.

### ISSUE THREAD

**Issue by DavidGriffith** [k9mail/k-9#3378] opened 2018-05-08 02:51 UTC
### Expected behavior
In Global_Settings->Display is this single checkbox option: "Show correspondent names: Show correspondent names rather than their email addresses".  I would like to have the option of being shown BOTH the name and address, particularly when I want to quickly check if the sender is trying something dishonest.

### Actual behavior
There's just a single option for correspondent name XOR email address.

### Steps to reproduce
1. Start K9mail.
2. Press the 3 vertical dots to expose the Settings menu.
3. Press "Settings".
4. Press "Global settings".
5. Press "Display".
6. Scroll down to the "MESSAGE LISTS" section.
7. See the single option described above.

### Environment
K-9 Mail version: 5.403

Android version: 7.1.2, LineageOS 14.1 (May 4, 2018 nightly)

Account type: IMAP

**Comment by cketti** [comment] 2018-05-10 15:21
Duplicate of #1119

**Closed by cketti** 2018-05-10 15:21 UTC
