### ISSUE TITLE
reply quotes encryptes text

### ISSUE THREAD

**Issue by andrixnet** [k9mail/k-9#1080] opened 2016-02-10 08:12 UTC
Using k9 with openkeychain has a problem.
Viewing and encrypted email (which is shown as decrypted in view mail screen) and replyingto that mail results in k9 quoting the encrypted version of the original mail instead of the decrypted text.

This is wrong.

**Comment by mawiegand** [comment] 2016-02-10 15:05
Duplicate of #663

**Closed** 2016-02-10 16:07 UTC
Labels: duplicate
