### ISSUE TITLE
Search for a string crashes K-9 and returns to Accounts page

### ISSUE THREAD

**Issue by gbrtrac** [k9mail/k-9#2094] opened 2017-01-19 16:21 UTC
[adb_log.txt](https://github.com/k9mail/k-9/files/717150/adb_log.txt)
### Expected behavior
press the magnifying glass, enter a string, it should find messages with the string (worked in all previous versions except recent updates)

### Actual behavior
blank screen, back to Accounts page

### Steps to reproduce
1. see above
2.
3.

### Environment
K-9 Mail version:  5.203

Android version: 4.2.2

Account type (IMAP, POP3, WebDAV/Exchange):  imap

**Comment by Valodim** [comment] 2017-01-19 17:12
Hi, thanks for your report! Unfortunately, that debug log is empty. :(

Did you follow the steps on [Logging Errors](https://github.com/k9mail/k-9/wiki/LoggingErrors) to record it? otherwise, if it's a crash and you installed the app via google play, you can just hit "Report" to send the crash report to us.

**Comment by gbrtrac** [comment] 2017-01-19 17:43
Yes, same steps as when I submitted the last bug on this issue

[adb_log.txt](https://github.com/k9mail/k-9/files/717315/adb_log.txt)

**Comment by gbrtrac** [comment] 2017-01-19 17:44
[k9-log.txt](https://github.com/k9mail/k-9/files/717321/k9-log.txt)

**Comment by philipwhiuk** [comment] 2017-01-21 18:53
The adb_logs are virtually empty and contains no K-9 logs at all. The k-9 logs contain no search errors or crash, only indications of difficulty connecting to the email server.

**Comment by philipwhiuk** [comment] 2017-01-21 21:23
Same user, closing as duplicate of #1985

**Closed by philipwhiuk** 2017-01-21 21:23 UTC
Labels: needs info
