### ISSUE TITLE
K9-Mail invokes too many connection when it is set to display "All Folders"

### ISSUE THREAD

**Issue by SarenT** [k9mail/k-9#1694] opened 2016-10-08 16:46 UTC
### Expected behavior
I should be able to see all folders and also use other e-mail clients to access my account.

### Actual behavior
When I use the "Show all folders" action, I am being banned by my e-mail server due to "too many connections".

### Steps to reproduce
(I am writing this in a generalized way and I am putting specific circumstances in soft brackets.
1. Access/Configure to an IMAP server (Microsoft Server (OWA) at workplace) with K9-Mail.
2. Access/Configure to the same account with Thunderbird.
3. Create some folders under main INBOX in Thunderbird.
4. Change K9 settings to show "All Folders" instead of only 1st or 2nd class folders.
5. Try to access e-mails via Thunderbird again and fail due to "wrong password".

### Environment
K-9 Mail version: 5.010

Android version: 5.1.1 CyanogenMod 12.1/LG G3 D855

Account type (IMAP, POP3, WebDAV/Exchange): IMAP on Exchange Server.

### Additional Info
The Thunderbird error turns out to be insufficient. The error message "wrong password" is not true. Nothing has changed with my password. The problem turns out to be the maximum allowed connections! And the problem always starts with "Show all folders" in K9-Mail. By allowing more connections on the server side resolves the issue temporarily/shortly.

I guess, K9-Mail invokes too many connections, presumably one for each folder, without closing these. On a mail server where this number of connections exceeds, other clients cannot access anymore. Same password, which used be working and still is working with K9-Mail and Webmail, stops working for other clients (Thunderbird in this case). But the problem isn't Thunderbird or the password.

I think solution would be to tightly limit outgoing IMAP connections by default. I didn't find any option to this in the settings.

**Comment by philipwhiuk** [comment] 2016-10-08 19:49
K-9 uses N+1 connections where N is the number of folders you have configured to use PUSH email.

PUSH email by design requires one connection per folder. You can configure which folders are set to use PUSH. If you set more to PUSH than you are allowed, then you will run out. Unfortunately there is no deployed 'PUSH FOR SELECTED FOLDERS' behaviour in IMAP.

All other operations use a single connection.

**Comment by philipwhiuk** [comment] 2016-10-08 19:51
Closing as no evidence is suggested for us breaking the model - if you got a debug log of us opening lots of connections to do stuff other than IDLE for messages we could re-open this.

**Closed by philipwhiuk** 2016-10-08 19:51 UTC
