### ISSUE TITLE
K9 search failure in folder Sent?

### ISSUE THREAD

**Issue by oniter** [k9mail/k-9#1486] opened 2016-07-06 07:57 UTC
### Actual and Expected behavior

In the INBOX when I'm looking for more mails from a special sender (option[in German_language]:"Mehr von diesem Absender") all is like expected.
Example: If I got a mail from Alice - do a long press on this mail and choose the option "more from this sender" - I got all mails from Alice. Just fine!
BUT in the folder SENT when I'm looking for more mails send to a special person, I expect that the search function is looking for recipients and not for senders. 
Example: If I answered once a mail from Alice and my name is Bob, I have this mail in the folder SENT. Long press on this mail and choose the option "more from this sender" - I got all mails from Bob he was sending what is the whole content of SENT. Corresponding to the name of the option the result is just fine too, BUT not expected! If I have only one mail-address sending mails from, everytime I will search for mails send to Alice or someone else the result is always the same: all messages sent from Bob.

Question: Is there a possibility to at a search option named "more from this recipient"?
Or give us the freedom of search over a keyword like From:  and To: to specify our search.
There are people who uses more than one mail address getting and sending mails from/to.
So, the option "more from this recipient" would be appreciate a lot. THX.
### Steps to reproduce
1. Go to folder SENT
2. Long press to a mail sent to someone, but not you, till options are shown.
3. Choose option "More from this sender (Mehr von diesem Absender)"
4. Always got the whole content of folder SENT (only if you use one mail address sending mails from)
5. Expected as result are the mails to the recipient.
### Environment

K-9 Mail version:5.010

Android version:4.2.2

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment] 2019-02-28 20:26
Duplicate of #1103

**Closed by cketti** 2019-02-28 20:26 UTC
Labels: enhancement
