### ISSUE TITLE
portrait vs landscape doesn't work right, buttons go missing

### ISSUE THREAD

**Issue by whatttup22g** [k9mail/k-9#2487] opened 2017-04-05 22:19 UTC
[k9_port-vs-land](https://cloud.githubusercontent.com/assets/26942380/24729292/5fa8eb42-1a12-11e7-95bf-6b9009ec6a7e.png)

pic above I hope..

### Expected behavior
Tell us what should happen

Buttons in bottom row (like reply) should remain no matter how you orient phone or device.

### Actual behavior
Tell us what happens instead

Buttons appear when phone is upright (portrait) but not when sideways (landscape).

### Steps to reproduce
1. open K9
2. view an email
3. turn your device from upright to sideways, notice buttons on bottom row disappear and reappear by changing the orientation.

### Environment
K-9 Mail version: 5.206

Android version: Marshmallow 6

Account type (IMAP, POP3, WebDAV/Exchange): several IMAP accts

(works great otherwise, IMAP is awesome)

**Comment by cketti** [comment] 2017-04-05 23:34
Duplicate of #727

**Closed by cketti** 2017-04-05 23:34 UTC

**Comment by whatttup22g** [comment] 2017-04-06 00:20
The "duplicate" mentioned is a year old. It wasn't fixed then, still isn't now.
