### ISSUE TITLE
notifications only in working hours

### ISSUE THREAD

**Issue by ristein** [k9mail/k-9#5053] opened 2020-11-14 10:23 UTC
Would be nice to optionally have notifications of specific accounts only from 8 to 5 on working days.

Solution: Fetch mails but dont notify until its working time again.

Alternative: only fetch specific account in working hours.

**Comment by cketti** [comment] 2020-11-14 19:13
Duplicate of #993

**Closed by cketti** 2020-11-14 19:13 UTC
Labels: enhancement
