### ISSUE TITLE
New Message notification doesnt refresh after message delete (occasionally)

### ISSUE THREAD

**Issue by jimimaseye** [k9mail/k-9#2201] opened 2017-02-07 13:54 UTC
Occasionally (without obvious reason or method to reproduce), tapping on DELETE and deleting messages from the notification area results in the message being deleted but the notification does not refresh or remove from the notification area (leaving it in place and still responsive to processing by further tapping).  The only way to remove it from notification is to swipe it away to clear it.  This happens frequently but not always.  (Ive noticed a frequency with Facebook notifications but I would think thats coincidence rather than cause). 

This behaviour did not occur prior to 5.202.

### Expected behavior
Tap DELETE within notifications, confirm delete (and have the message removed within the app), and the notification is updated accordingly (the messages no longer appear in the notification area).

### Actual behavior
The notification remains and doesnt refresh to reflect the deletion thats been applied.

### Steps to reproduce

This screenshot shows the initial notification of 2x new messages (although in reality there are 5 - but thats another problem and already logged).

![image](https://cloud.githubusercontent.com/assets/15649182/22693315/ac1a2432-ed3a-11e6-9308-f3741b7b74c3.png)

This screen shots shows me actually clicking and confirming DELETE of the 2 messages from the notification 'delete' button:

![image](https://cloud.githubusercontent.com/assets/15649182/22693185/15ab291a-ed3a-11e6-906b-ef383d7bc277.png)

This next shot shows that in the notifications there are the same messages still there (note the time of 7:59 is after I performed the delete for them - they have not been removed from notification area):

![image](https://cloud.githubusercontent.com/assets/15649182/22693368/ebd1519a-ed3a-11e6-93b2-aa7f66175abf.png)

If I tap on the notification to view the messages you see that they are not actually there resulting in :

![image](https://cloud.githubusercontent.com/assets/15649182/22693483/63b8aadc-ed3b-11e6-8fb9-91eab6dcfb2b.png)

And the summary list view of the Inbox indeed shows that they are no longer there (but show the other 3 that should have also been included in the notification - again this relates to the other problem already logged).

![image](https://cloud.githubusercontent.com/assets/15649182/22693603/d6e9a402-ed3b-11e6-8365-99767ab3a66b.png)

### Environment
K-9 Mail version:  5.203

Android version:   4.2.1

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by philipwhiuk** [comment] 2017-02-07 15:43
Duplicate of #1588

**Closed by philipwhiuk** 2017-02-07 15:43 UTC
