### ISSUE TITLE
No function to search for subfolders after recent update

### ISSUE THREAD

**Issue by Tsloth** [k9mail/k-9#5682] opened 2021-09-19 09:09 UTC
After recent update, the much appreciated function to search for folders is gone? In my inbox I have app 500 subfolders, and in order to find any email, I need to search and find relevant subfolder.
Please re-introduce the 'search folder' function, eg. next to "setttings"
Thanks for an otherwise great app.

**Comment by cketti** [comment] 2021-09-20 13:53
Duplicate of #4961

**Closed by cketti** 2021-09-20 13:53 UTC
Labels: enhancement
