### ISSUE TITLE
Last used target folder not directly accessible in folder list when moving mails

### ISSUE THREAD

**Issue by TheNitek** [k9mail/k-9#3053] opened 2018-01-06 08:14 UTC
### Expected behavior
When I move multiple mails, mail by mail, the last used target folder should be in the visible area of the folder list when moving the next mail

### Actual behavior
The folder list keeps its position but the last used folder is on the very top of the "visible" are, which is hidden by the header bar.

### Steps to reproduce
1. move one mail into an folder (there need to be more folders after this target folder than fit on the screen)
2. try to move another mail

### Environment
K-9 Mail version:
v5.402 and earlier

Android version:
7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment] 2018-01-06 15:01
Duplicate of #1493

**Closed by philipwhiuk** 2018-01-06 15:01 UTC
