### ISSUE TITLE
Can't send mail: "Cannot connect to crypto provider"

### ISSUE THREAD

**Issue by dsgiigh** [k9mail/k-9#4194] opened 2019-09-10 00:22 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Can send mail

### Actual behavior
A red lock icon with an X through it appears in upper left of composing screen (on the From: line). Attempting to send shows: "Cannot connect to crypto provider, check your settings or click crypto icon to retry!"

I don't have Open Keychain installed.

### Steps to reproduce
1. Open K9
2. Try to send email.
3.

### Environment
K-9 Mail version: 5.600

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors
[k9-log.txt]) and attach them here:
(https://github.com/k9mail/k-9/files/3593094/k9-log.txt)

**Comment by ei-ke** [comment] 2019-10-02 16:22
@dsgiigh What is your OpenPGP provider / app? This can be selected in the global settings > cryptography.

I had this Issue with OpenKeychain enabled. In my case the energy management suspended OpenKeychain after a while and then K-9 went mad :)

**Comment by dsgiigh** [comment] 2019-10-02 19:34
Same, OpenKeychain...




--


from mobile, sorry for typoes







On Wed, Oct 2, 2019 at 9:22 AM -0700, "Eike" <notifications@github.com> wrote:












@dsgiigh What is your OpenPGP provider / app? This can be selected in the global settings > cryptography.


I had this Issue with OpenKeychain enabled. In my case the energy management suspended OpenKeychain after a while and then K-9 went mad :)

**Comment by ei-ke** [comment] 2019-10-02 20:08
@dsgiigh Okay, in your first post you said you don't have OpenKeychain installed. Have you tried opening OpenKeychain and then K-9? If that solves the issue your have to change the energy management setting on yout mobile phone to not suspend OpenKeychain.

**Comment by dsgiigh** [comment] 2019-10-02 20:24
It fails with and without it installed...




--


from mobile, sorry for typoes







On Wed, Oct 2, 2019 at 1:08 PM -0700, "Eike" <notifications@github.com> wrote:












@dsgiigh Okay, in your first post you said you don't have OpenKeychain installed. Have you tried opening OpenKeychain and then K-9? If that solves the issue your have to change the energy management setting on yout mobile phone to not suspend OpenKeychain.

**Comment by cketti** [comment] 2019-10-12 20:36
Duplicate of #3420

**Closed by cketti** 2019-10-12 20:36 UTC
