### ISSUE TITLE
Allow quoted replies/forwards to be edited without changing to plain text 

### ISSUE THREAD

**Issue by PatrickB** [k9mail/k-9#2600] opened 2017-06-23 01:34 UTC
### Expected behavior
When I forward an email I would like to edit the quoted portion so that some of the original text is removed. Specifically, the original is an email to me from an email list. I would like to remove the automatic "Unsubscribe" button so that some on the forward chain does not mistakenly unsubscribe me. 

Unfortunately, when I select to edit the quoted text, all of the pictures and formatting are removed. That makes sharing the original less useful and less readable. 

For my purposes, simply removing the "Unsubscribe" link from the original message would be sufficient. 

### Actual behavior
Unfortunately, when I select to edit the quoted text, all of the pictures and formatting are removed. That makes sharing the original less useful and less readable. 

### Steps to reproduce
1. Select option to forward 
2. Observe Unsubscribe link in original email 
3. Select option to edit original email, then observe that formatting is gone

### Environment
K-9 Mail version: 5.206

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP & POP3

**Comment by philipwhiuk** [comment] 2017-06-27 10:53
Duplicate of #1745

**Closed by philipwhiuk** 2017-06-27 10:53 UTC
