### ISSUE TITLE
Add ability to print an email

### ISSUE THREAD

**Issue by WebSpider** [k9mail/k-9#4074] opened 2019-05-29 09:03 UTC
The current release seems to lack support to print an e-mail.

This is a feature request to add this ability, either in the way this has been implemented in Firefox (hamburger menu > Print when looking at a page) or by sending an email to a print app

**Comment by cketti** [comment] 2019-05-29 11:42
Duplicate of #1062

**Closed by cketti** 2019-05-29 11:42 UTC
