### ISSUE TITLE
Spam filter based on text in summary or body

### ISSUE THREAD

**Issue by johan974** [k9mail/k-9#2002] opened 2017-01-07 11:06 UTC
### Expected behavior
It would be very nice that while reading the e-mails from the email provider that any mail matching spam filter rules are put in a separate folder. 

### Actual behavior
As far as I understand, you can only filter on 

### Steps to reproduce
1. You cannot set an additional filter on texts. OR ... is this possible via a plug-in? 

### Environment
K-9 Mail version: any

Android version: any

Account type (IMAP, POP3, WebDAV/Exchange): any

**Comment by philipwhiuk** [comment] 2017-01-07 15:05
Duplicate of #908

**Closed** 2017-01-07 15:05 UTC
