### ISSUE TITLE
HTML list not parsed correctly when sender has pasted from MS Word

### ISSUE THREAD

**Issue by rasos** [k9mail/k-9#2199] opened 2017-02-06 17:56 UTC
### Expected behavior
Render text correctly in e-mail message enumerations
1. text1
2. text2
3. text3.

### Actual behavior
Shows only numbers:
1.
2.
3.

### Steps to reproduce
1. Paste numbered list from MS Word in Outlook and send to k9mail

### Environment
K-9 Mail version: 5.203
Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Message is sent both in
Content-Type: text/plain; charset="iso-8859-1"
Content-Type: text/html; charset="iso-8859-1"

Here is the beginning of the ugly MS Word paste code: http://pastebin.com/RY5z0nW8
Maybe a won't fix.

![screenshot_20170206-181942](https://cloud.githubusercontent.com/assets/485723/22659427/e1c0f270-ec9d-11e6-8af3-926cda2e9802.png)

**Comment by philipwhiuk** [comment] 2017-02-06 18:33
Please search 

Duplicate of #2015

**Closed by philipwhiuk** 2017-02-06 18:33 UTC
