### ISSUE TITLE
Copy Paste eMail, Move Email, Mark Email as Spam disappeared since Update

### ISSUE THREAD

**Issue by vee-k** [k9mail/k-9#5609] opened 2021-08-23 14:57 UTC
Since the recent update to v5.803 ,  Move and Copy crash the app.
Also, marking Email as Spam is not available, even when turned on in Settings.

This is a real setback for efficient mail administration.

Using Firefox on Android, latest versions respectively.

Hope these issues can be solved soon.
Thanks a lot!

**Comment by cketti** [comment] 2021-08-23 15:19
Please provide the information asked for in the issue template: https://github.com/k9mail/k-9/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

Please create one GitHub issue per problem (feel free to create two new ones and close this one). It's important that you provide details. For example: "Also, marking Email as Spam is not available, even when turned on in Settings" doesn't tell us a) where you expect to find the "mark as spam" functionality exactly and b) how you configured K-9 Mail exactly.

---
How did you create this GitHub issue? Users should end up on this page to select an issue type: https://github.com/k9mail/k-9/issues/new/choose. However, the cases where this doesn't seem to work are increasing. I'm curious to find out why that is.

**Comment by spaetz** [comment] 2021-08-25 05:11
I am pretty sure this is a duplicate of  #5448.

**Closed** 2021-09-22 11:44 UTC

**Comment by vee-k** [comment] 2021-09-22 15:01
Hi chketti

The issue has been closed, but is not resolved.
Si CE I'm not savvy with3 GitHub and posting and checking on issues, just 
reminding you this way that 
the App is not functioning well anymore on Android.

The "Spam" button has disappeared from the menu, ( screenshot attached ) , 

and moving or copying email from one folder to another is crashing the app.

The same I've noticed with download of files: the app just crashes and there are only ".part" files to be found.

So, maybe these basic functions don't seem important, or maybe something is not right with my Galaxy phone, but all m other apps work fine .


And since I read the app is maintained by volunteers, I can imagi6 everyone is busy and it will take time.

I do hope you will have time to look at the issues and maybe have another update.

It used to be the best email pp I found, and was very happy for a few years,but now it doesn't work as it's supposed to.
 At least not on latest Android.

Thank you for your time and work,
Have a pleasant rest of the week!

Viktoriana Kostov

**Comment by spaetz** [comment] 2021-09-22 15:30
Hi Viktoriana,

the issue has been closed, but not because it is invalid.
Issue #5448 and others have been filed and are describing the same ui issue. If moving mails crashes k9, this is a diffderent issue for sure and should be filed separately as a new bug.

**Comment by vee-k** [comment] 2021-09-22 16:33
Ah, great!
 Thanks for the heads-up! :)
