### ISSUE TITLE
notifications are not being dismissed after hitting delete

### ISSUE THREAD

**Issue by Soboku** [k9mail/k-9#1780] opened 2016-11-07 20:16 UTC
### Expected behavior
When tapping on the delete button on a mail in the notification bar it should dismissed the notification. 

### Actual behavior
Notifications are not being dismissed. 

### Steps to reproduce
1 . when notification comes in tap delete on it. 
2.
3.

### Environment
K-9 Mail version:
5.114
Android version:
7.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
imap.

screen cast of what is happening. Link> http://bit.ly/2egaRWu

Would be nice if I could have pasted this link. Firefox might be stopping me from doing so are your site don't allow pasting

**Comment by philipwhiuk** [comment] 2016-11-07 23:21
Duplicate of #1588 amongst others

**Closed by philipwhiuk** 2016-11-07 23:21 UTC

**Comment by Soboku** [comment] 2016-11-08 00:32
Thanks
