### ISSUE TITLE
Duplicate folders in fodler list

### ISSUE THREAD

**Issue by PCZeroNet** [k9mail/k-9#3238] opened 2018-03-05 20:58 UTC
### Expected behavior
When I tap an account it should open and show a list of folders in that account

### Actual behavior
On many accounts there are duplicate folders listed example:

Inbox
Inbox
Sent (Sent)
Sent (Sent)
Drafts (Drafts)
Spam (Spam)
Trash (Trash) 

is the folder list on one of my accounts.

### Steps to reproduce
use teh program normally.

### Environment
K-9 Mail version: 5.403

Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
POP3 SSL/TLS 995

This happens randomly.  I can delete an account that is having the issue and re-add it.  The duplicates go away.  Then after a period of time of fetching and sending mail the duplicates re-appear.

**Comment by philipwhiuk** [comment] 2018-03-06 15:35
Ironically or not this a duplicate of #1220

**Closed by philipwhiuk** 2018-03-06 15:35 UTC
