### ISSUE TITLE
Targeting above API 25 not running Background services like Checking Mail

### ISSUE THREAD

**Issue by Krammig** [k9mail/k-9#4245] opened 2019-11-10 06:24 UTC
### Expected behavior
It should sync messages and automatically check for messages in background as it used to do.  

Should also check for messages automatically as set in Foreground.

### Actual behavior
It seems that Targeting above API 25 the Background services do not run. 

It is not even checking for messages in "Foreground" - the user must Manually check which is Bad

### Why it is an Issue
a) K9 will not operate as an email app should in checking messages etc if targeted above API 25
b) Google Play Store will not accept any apps that target below API 26 

### Steps to reproduce
Simple, just build and target say 27 or 28 and you will see that background services do not run. 

### Question
What broadcast receivers are involved in this issue ?

### Notes
https://developer.android.com/about/versions/oreo/background

### Environment
K-9 Mail version:  Build # 4242

Android version:  5.1  7.1  8.1  9

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment] 2019-11-10 13:50
Duplicate of #3375

**Closed by cketti** 2019-11-10 13:50 UTC
