### ISSUE TITLE
forwarding e-mail (attachments) download full message prompt

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#3162] opened 2018-02-01 15:40 UTC
K9 should ask you, whether you want to download missing e-mail attachments to be able to forward them as well.
Right now, K9 just opens the send dialogue and only adds attachments, that are available without mentioning it. (except if you downloaded the full message before)

In general it should also ask you to download the full message before forwarding (so the text/html is fully forwarded as well)

EDIT:
the prompt could offer 3 answers:
Always, once, not now)

**Comment by philipwhiuk** [comment] 2018-02-01 21:13
Duplicate of #3028

**Closed by philipwhiuk** 2018-02-01 21:13 UTC
