### ISSUE TITLE
Font size become too small when receive email with many quotes

### ISSUE THREAD

**Issue by hanchiran** [k9mail/k-9#3384] opened 2018-05-14 02:44 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Font size is normal when receive email with many quotes

### Actual behavior
Font size become too small when receive email with many quotes

### Steps to reproduce
1. forward email with many quotes in k9-mail 
2. open k9-mail
3. read email

### Environment
K-9 Mail version:
K-9 Mail v5.503
Android version:
android 6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment] 2019-03-07 17:39
Duplicate of #3172

**Closed by cketti** 2019-03-07 17:39 UTC
