### ISSUE TITLE
Folder search 

### ISSUE THREAD

**Issue by DieterB61** [k9mail/k-9#5605] opened 2021-08-23 07:40 UTC
**Is your feature request related to a problem? Please describe.**
In the new version it is not possible to search for a folder with a part of the name **and change into that folder** to see emails within that folder. This is an important feature if you have hundreds of folders in an IMAP account. It was possible in the old version.

**Describe the solution you'd like**
There is already the possibility to search for folders in the manage folder ("Ordner Verwalten" in German version) menu. But after selecting the searched folder one can only change the settings of the folder. If there would be an additional possibility to "change to the folder", it would be fine.

**Describe alternatives you've considered**
Scrolling through hundreds of folders where sometimes not all the path is visible (long folder names) is not a good alternative ... 

**Additional context**
see: https://forum.k9mail.app/t/search-for-folders/2001

**Comment by sfadschm** [comment] 2021-08-23 09:22
Possibly something that could be integrated in the button bar introduced in #5498.

**Comment by cketti** [comment] 2021-08-23 13:33
Duplicate of #4961

**Closed by cketti** 2021-08-23 13:33 UTC
Labels: enhancement
