### ISSUE TITLE
Feature request: send via any address

### ISSUE THREAD

**Issue by dandart** [k9mail/k-9#957] opened 2015-12-15 12:29 UTC
I have a catch all email address and would really like to send as anybody custom at the time of creating the message. And then when receiving a new message to a new address I'd like to reply from that address. I'd imagine it would just be cloning an identity.

Cheers

**Comment by cketti** [comment] 2015-12-15 13:03
Duplicate of #935

**Closed by cketti** 2015-12-15 13:03 UTC
