### ISSUE TITLE
At the first sync with a YahooMail! account K9 will see the "DraftS" folder but not what's inside of it. K9 gives essential a error of [Command: Examine "Drafts"] 

### ISSUE THREAD

**Issue by Locash** [k9mail/k-9#3069] opened 2018-01-09 13:00 UTC
### Expected behavior
Tell us what should happen
Upon first account setup and syncing. K9 should sync(poll) with yahoo's "Drafts(Drafts)" folder. 

### Actual behavior
Tell us what happens instead
At first account sync up K9 does not poll the yahoo created "Drafts(Drafts)" folder. Everything else is fine
Under the folder name Drafts(Drafts) it says [Command: Examine "Drafts";] Then k9 creates a new folder named "Draft" on its own. That folder is then created on yahoo's server. Then that error below the Drafts(Drafts) folders name disappears but the original Drafts(Drafts) folder still will not poll. 

In a nut shell: At the first sync with a YahooMail! account K9 will see the "DraftS" folder but not what's inside of it. K9 gives essential a error of [Command: Examine "Drafts"] 

### Steps to reproduce
1.Make sure a draft already exists in the YahooMail original Draft folder on yahoo mails website. 
2. Setup YahooMail with k9
3.view the error [Command: Examine "Drafts"] below the Drafts(Drafts)folder and folder does not sync.
3. Sync a few times a see the new "Draft* folder created

### Environment
K-9 Mail version:
5.402

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
Yahoo Mail  IMAP

**Comment by philipwhiuk** [comment] 2018-01-09 15:40
Duplicate of #633

**Closed by philipwhiuk** 2018-01-09 15:40 UTC
