### ISSUE TITLE
Notifications during silence mode

### ISSUE THREAD

**Issue by marktiptop** [k9mail/k-9#3452] opened 2018-06-19 08:48 UTC
### Expected behavior
No notifications at all during silence mode.

### Actual behavior
When the silence mode starts at the set time, I still get notifications in my notification bar. The only difference is that the notification sound is turned off, but I don't want any notifications anymore, inclusing visual ones.

### Steps to reproduce
1. Open general settings
2. Select 'warnings' (my K9 is in Dutch, so I am not sure if this is the right translation)
3. Check the boxes behind 'silence period' and 'turn off notifications'.
4. Select when the silence period should start and stop.

### Environment
K-9 Mail version: 5.403

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Phone: OnePlus2 OxygenOS version 3.6.1

**Comment by hichamboushaba** [comment] 2018-06-20 12:42
Duplicate of: #3303

**Closed** 2019-03-08 02:53 UTC
