### ISSUE TITLE
cancel set up a new account, reopen the app will cause app crash

### ISSUE THREAD

**Issue by lich1011** [k9mail/k-9#3527] opened 2018-07-25 10:52 UTC
### Expected behavior
App should open Welcome Activity.

### Actual behavior
App crashed at first time, then reopen it, it will show Welcome Activity.

### Steps to reproduce
1.Set up email account.
2.Cancel progress will checking incoming server.
3.Exit the app.
4.Reopen app, then app crashed.
5.Reopen app, show Welcome Activity

### Environment
K-9 Mail version: master brach

Android version: API LEVEL 27

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by ar-jan** [comment] 2018-08-08 20:44
Similar problem here (I suppose same issue?): installed K-9 (v 5.403) from F-Droid, set up account (IMAP) via wizard using default options. As soon as I click "Done" after filling out my name for outgoing messages, the app crashes. Restarting, I get "K-9 Mail keeps stopping". This is a new install on a new Android 8.0.0 phone.

**Comment by cketti** [comment] 2019-03-08 03:11
Duplicate of #922

**Closed by cketti** 2019-03-08 03:11 UTC
