### ISSUE TITLE
I would like to be able to have subfolders - my imap server allows it after all

### ISSUE THREAD

**Issue by lemmy04** [k9mail/k-9#5562] opened 2021-08-12 10:46 UTC
**Is your feature request related to a problem? Please describe.**
On my imap server I have my mails organized in folders and subfolders, for example
Archiv/Games/CSGO
Archiv/Games/BDO
Archiv/Games/Other

and so on, and so on. In pretty much every mail client I see that folder structure as ... well, a folder structure.
In K9 what I see of the above example is:
Archiv.Games.CSGO
Archiv.Games.BDO
Archiv.Games.Other

I believe that is because my imap server which is a cyrus imap sends a period as the folder separator, and K9 doesn't understand it.

**Describe the solution you'd like**
Please add the period to what K9 considers a folder separator for imap subfolders - possibly as a per-server configurable setting.

**Describe alternatives you've considered**
This might actually be a bug, not a feature request...

**Comment by cketti** [comment] 2021-08-12 10:48
Duplicate of #630

**Closed by cketti** 2021-08-12 10:48 UTC
Labels: enhancement
