### ISSUE TITLE
Show sender's address in mail view

### ISSUE THREAD

**Issue by ashegoulding** [k9mail/k-9#5924] opened 2022-02-16 01:09 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

When viewing an email, there's no direct way to see or copy sender's address. It only shows the sender's name. I understand that there are ways to get senders' address (by press and holding the sender's name, looking at the original and so on), but what I don't understand is why it's trying to "hide" the sender's address particular whilst showing the full address of the recipient, which the user already know in most cases. This should have been other way around, at least. It would made sense to me that it just showed both sender's and recipient addresses in the complete form.

### Suggested solution

Show the sender's address in the form of: **Name** &lt;address@example.com&gt;

I'm trying to see if anyone's on the same page. I'll make a patch if I get enough approval from other users.

**Comment by ashegoulding** [comment] 2022-02-16 01:12
"Show correspondent names" setting does not solve this issue.

**Comment by cketti** [comment] 2022-02-21 15:39
Duplicate of #1119

**Closed by cketti** 2022-02-21 15:39 UTC
Labels: enhancement
