### ISSUE TITLE
Show the sending progress to the user / option to compress images

### ISSUE THREAD

**Issue by schorschii** [k9mail/k-9#5763] opened 2021-10-30 21:33 UTC
**Is your feature request related to a problem? Please describe.**
When sending images (~ 6 MB) with enabled PGP encryption, it takes a while until the mail is sent (tested on Fairphone 3), but no progress is reported to the user. This can be misleading to the user, as nothing happens until the email has been sent.

**Describe the solution you'd like**
- A progress bar or informational text ("please wait") should be shown if sending the mail takes longer than 1 second.

- When attaching larger images, the app could ask the user to compress the images as the iOS mail app does:
![Screenshot of iOS mail app](https://cdn.osxdaily.com/wp-content/uploads/2014/04/resize-photo-from-iphone.jpg)

**Comment by mbeko** [comment] 2021-12-02 09:03
I would also be interested in that. One of the biggest problems I have with e-mail is that image compression options are often missing in my experience while it is standard in all the chat apps that I use.

**Comment by cketti** [comment] 2021-12-12 19:49
Duplicate of #1758

**Closed by cketti** 2021-12-12 19:49 UTC
Labels: enhancement

**Comment by mbeko** [comment] 2021-12-12 20:58
Thank you, I didn't notice the other issue!
