### ISSUE TITLE
Bad scrolling performances in messages list

### ISSUE THREAD

**Issue by dewi-ny-je** [k9mail/k-9#691] opened 2015-06-18 23:04 UTC
Scrolling the list of mails is extremely sluggish on my LG G2 (IMAP inbox, not unified or unified, 10 emails!), at least an order of magnitude slower than is the scrolling on most other apps, including complex web pages in Chrome. Scrolling the content of emails is however perfect. This makes the experience very poor and makes difficult to scroll exactly to the desired email.

**Comment by cketti** [comment] 2015-06-18 23:08
Seems to be a duplicate of #643

**Closed by cketti** 2015-06-18 23:08 UTC
Labels: duplicate
