### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by mbest** [k9mail/k-9#1792] opened 2016-11-11 21:00 UTC
### Expected behavior
normal CPU usage

### Actual behavior
High CPU usage. I noticed my phone was hot in my pocket. Checked CPU usage. Found K-9 as the culprit.

### Environment
K-9 Mail version: 5.0101

Android version: 5.0.2

Account type (IMAP, POP3, WebDAV/Exchange): 3 IMAP accounts. Two are set to poll every 15 minutes. The other is set to use push.

![_20161111_124859](https://cloud.githubusercontent.com/assets/1230364/20230069/b0c4dfa2-a80e-11e6-889d-f865e9b2714e.JPG)

**Comment by Valodim** [comment] 2016-11-12 00:05
If this is a bug in K-9, it seems to be triggered on very specific conditions only, otherwise we would be getting many more reports of this. Without more info it's impossible to track though. Does this happen persistently to you? If so, we might be able to see something from a debug log. If this was a freak occurrence, I'm afraid there is not much we can do.

**Comment by mbest** [comment] 2016-11-12 00:45
It's the second time I've noticed this.

**Comment by konturger** [comment] 2016-11-21 04:43
I can reproduce it, after install k9 didnt want to go to sleep. Will observe it further more. Rebooted my device and will see...
K9 Version 5.115, on CR Droid marshmellow, on Galaxy s4 phone

![screenshot_20161121-042407](https://cloud.githubusercontent.com/assets/10417066/20470871/ec11d236-afac-11e6-9309-8b1011e09037.png)

**Comment by konturger** [comment] 2016-11-21 17:13
After reboot it kept fixed on my s4, too. Strange, whatever it was.

![screenshot_20161121-180932](https://cloud.githubusercontent.com/assets/10417066/20492714/21bb859e-b016-11e6-8e02-cfceda573d7e.png)

**Comment by WGH-** [comment] 2017-03-10 08:48
I'm also having this on K-9 5.203. I'm pretty sure this appeared relatively recently. K-9 sometimes consumes 100% CPU, warming up the phone rather fast. The conditions for this to appear are unknown. Force stopping the application helps.

I've just updated to 5.205, and I'll tell if the bug's still here.

**Closed** 2019-02-28 21:24 UTC
Labels: needs info, performance
