### ISSUE TITLE
All settings gone after update to 5.207

### ISSUE THREAD

**Issue by martin3000** [k9mail/k-9#2657] opened 2017-08-03 21:32 UTC
Phone: LG Leon with Android 6.0
In google play store, I manually started the update for K9.
But my phone gave me a message that the update did not work.
But I have 5.207 now installed.
I started K9 mail, but all settings were gone, i.e. my 2 mail accounts are gone, K9 looks like after a fresh install.

**Comment by cketti** [comment] 2017-10-28 16:38
Duplicate of #750

**Closed by cketti** 2017-10-28 16:38 UTC
