### ISSUE TITLE
Use "to" address as "from" address when replying

### ISSUE THREAD

**Issue by thrdroom** [k9mail/k-9#6101] opened 2022-06-06 13:49 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

There should be a usersetting inside k9 to use the "to" address as "from" address when replying.

This would be useful for users who use catch all addresses and use different addresses for different services. When I reply to an email it always changes to my default address (myname@mydomain.com). When I receive an email to servicename@mydomain.com I want to reply with the from address being servicename@mydomain.com, not myname@mydomain.com. I can edit the address manually, but sometimes I forget and I end up sending replies with myname@mydomain.com. servicename can be variable per email.

Current problematic situation:

1. Receive email incoming to servicename@mydomain.com
2. Reply from address should be myname@mydomain.com

New wanted situation:

1. Receive email incoming to servicename@mydomain.com
2. Reply from address should be servicename@mydomain.com

### Suggested solution

For reference, this option for example is built into thunderbird for a while now.

![065RFJJ](https://user-images.githubusercontent.com/5912061/172173607-938bf33f-7d2d-4341-8e0c-9a04a7be9bab.png)

1. Go to Account Settings
2. Enable Reply from this identity when delivery headers match
3. Enter your domain prefixed by a wildcard (*), for example *@yourdomain.com
4. Close/confirm all your changes
5. Open an email that was sent to one of your catch-all addresses and click the reply button.
6. The FROM field should be the catch-all address and not your general address.

**Comment by cketti** [comment] 2022-06-06 14:00
Duplicate of #935

**Closed as completed by cketti** 2022-06-06 14:00 UTC
Labels: type: enhancement
