### ISSUE TITLE
No notifications about new mail when Quiet Time is ON (K-9 v5.401)

### ISSUE THREAD

**Issue by emc2peer** [k9mail/k-9#3029] opened 2018-01-03 15:39 UTC
### Problem
After some actualization after new ugly icon (5.300 - 5.401) there is no notification about new mail.

### Reason
I have diagnosted that the reason is Quiet Time ON regardless what time is set.

### Steps to reproduce
1. IMAP account
2. Synchronize Always
3. Quiet Time: ON , Start: 22:00 , End: 7:00
4. Current time: 7:01 - 21:59
5. New mail is indicated only as notification icon, no LED, no beeping
6. Quiet Time: OFF
7. New mail is indicated as notification icon, LED is blinking and repro is beeping

### Environment
K-9 Mail version: 5.401
Android version: 6.0 (Jun 12, 2017)
Account type: IMAP

**Comment by gitfve** [comment] 2018-01-03 16:45
**Same here no indication at all! Random working...

->K9 V5.401 / Android 7.0 Huawei P10

**Comment by hfinp** [comment] 2018-01-03 20:07
See #2999, duplicate issue.

**Comment by nathanzachary** [comment] 2018-01-03 20:57
Issue #2610 may be the same problem as well.

**Comment by emc2peer** [comment] 2018-01-03 21:36
nathanzachary,
this is new issue, Dec 2017 - Jan 2018. I use K-9 for a long time. A didn't have this problem before.

gitfve,
yes, $2999 is the same issue, thanks. I appologize for duplicate.

**Comment by cketti** [comment] 2018-01-04 03:19
Duplicate of #2999

**Closed by cketti** 2018-01-04 03:19 UTC
