### ISSUE TITLE
Never checks for new mail

### ISSUE THREAD

**Issue by Melab** [k9mail/k-9#3918] opened 2019-02-14 03:28 UTC
I've been using K-9 Mail for five years, on both Android 4.4 and 9.0. I've never gotten it to automatically check for new mail in the background like every other e-mail client does. I've looked through all ofthe settings and none of the settings I've adjusted fix this. The only time it actually checks for mail is when I have it open and click the sync button. Why isn't it checking for e-mail on its own?

**Comment by philipwhiuk** [comment] 2019-02-22 15:01
Please follow the issue template.

**Comment by cketti** [comment] 2019-03-08 05:22
Duplicate of #3950

**Closed by cketti** 2019-03-08 05:22 UTC
Labels: needs info
