### ISSUE TITLE
Existing draft messages shouldn't be touched if the user hasn't edited them

### ISSUE THREAD

**Issue by birdie-github** [k9mail/k-9#4837] opened 2020-06-16 06:18 UTC
If I open an already existing draft message in the IMAP drafts folder, do nothing with and click the Android back/return button, probably it should be worth not doing anything at all, instead of showing a dialog with "Discard" / "Save as draft".

And then image a situation: you created a draft message in a different application altogether (e.g. Thunderbird) or via the web interface: these two alternatives make even less sense.

**Comment by cketti** [comment] 2020-06-27 21:53
Duplicate of #2485

See also #4163

**Closed by cketti** 2020-06-27 21:53 UTC
