### ISSUE TITLE
sharing a file to k9 should automatically attach file to email

### ISSUE THREAD

**Issue by tusch001** [k9mail/k-9#4910] opened 2020-08-14 08:26 UTC
Please search to check for an existing issue (I did with [https://github.com/k9mail/k-9/issues?q=share](https://github.com/k9mail/k-9/issues?q=share))

### Expected behavior
When sharing a file from another application to k9 the user expects that the file is automatically attached to a new email (at least I would expect this - other email apps behave like this).

### Actual behavior
Although opening a new email in k9 by using the share to menu of another app the user has to manually attach the file. This involves tapping the button to append a file and using the crappy Android file manager to navigate the file system. This could be lots of taps if the file is located somewhere on the external sd card deep in the file system.

### Steps to reproduce
1. Open file manager of your choice
2. Share file to k9 that you want to send with email. This opens k9 correctly.
3. No attachment with email - you have to do it yourself.

### Environment
K-9 Mail version: 5.717

Android version: 6.0.1 

Account type (IMAP, POP3, WebDAV/Exchange): don't think it matters - I have IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
Nothing in the logs
```
---- 14.08.2020 10:12:53 vorm. ----

08-14 10:12:23.170  1255  1266 I ActivityManager: START u0 {act=android.intent.action.SEND typ=text/plain flg=0xb080001 cmp=com.fsck.k9/.activity.MessageCompose clip={text/plain U:file:///storage/8900-7EE7/.Backups/file_list.txt} (has extras)} from uid 10209 on display 0

08-14 10:12:23.464  1255  1273 I ActivityManager: Displayed com.fsck.k9/.activity.MessageCompose: +259ms

---- 14.08.2020 10:12:53 vorm. ----
```

**Comment by cketti** [comment] 2020-08-14 10:54
Duplicate of #4399

**Closed by cketti** 2020-08-14 10:54 UTC
