### ISSUE TITLE
K9 and Android 7 - syncing disabled

### ISSUE THREAD

**Issue by efenjay** [k9mail/k-9#2432] opened 2017-03-23 13:23 UTC
Samsung S7 Phone updated to Android 7.0 yesterday.

K9 v5.206

Following that K9 continues to download when syncing manually, but I am unable to change "syncing disabled" even though "Background sync" is set to "Always" in the global settings and all the accounts are set to poll regularly (between 1 and 30 minutes)

**Comment by philipwhiuk** [comment] 2017-03-23 15:02
Duplicate of #857 - Doze is more aggressive on Android 7.

**Closed by philipwhiuk** 2017-03-23 15:02 UTC
