### ISSUE TITLE
Attachement get lost by forwarding a (encrypted but not signed) Mail

### ISSUE THREAD

**Issue by webratte** [k9mail/k-9#3460] opened 2018-06-21 21:12 UTC
### Expected behavior
If I forward a Mail, the whole mail including Attachments should be forwarded

### Actual behavior
The Content is correct in the forward mail but Attachments are missed

### Steps to reproduce
1. Receive a **encrypted but not signed** Mail with Attachment (e.g. test.pdf)
2. Press the Button to forward this Mail
3. Thats ist, the Attachment is missing

### Environment
K-9 Mail version: 5.502

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by webratte** [comment] 2018-07-22 13:51
This is very important for me because I use the option in my mail account to encrypt all incoming mails.
And this mails are not signed.

And very often I have to forward this mails.

Currently I use a workaround. I save the attachment, forward the mail and attach the saved  file before I send the mail.

This is really stupid. Especially if I forget to attach the file....

**Comment by webratte** [comment] 2018-09-24 19:04
Hi,
could anybody reproduce this?

This is a really annoying bug.

I would like you could take a look on this.

Thank you.

**Comment by Rima-S** [comment] 2018-10-15 08:59
Hello, I am facing the same problem (version 5.600).  Forwarding a non-encrypted e-mail I lose the attachment. Do you have any updates regarding a possible fix?

**Comment by zeratul2099** [comment] 2018-11-26 21:38
Same problem here. Version 5.600, Android 8.0.0
When I forward former encrypted (and now decrypted) mails, the attachment is lost.

**Comment by cketti** [comment] 2019-03-08 02:58
Duplicate of #3028

**Comment by webratte** [comment] 2019-08-16 10:43
You have marked and closed this issue as a duplicat of https://github.com/k9mail/k-9/issues/3028

I'm sure it's not the same because I always download the whole mail including attachments.
In the other case I would not decrypt the mail.

Remember:
My issue means attachments get lost by forwarding encrypted but not signet mails.
I use the "verschlüsseltes Postfach" of mailbox.org.
There will mails encrypted after they reach the inbox (unencrypted). And of course, this mails are only encrypted and not signet.

**Comment by webratte** [comment] 2020-05-27 17:34
I just test Version 5.715
But this issue is still NOT FIXED.

Issue https://github.com/k9mail/k-9/issues/3028 

Please keep this in mind. This issue is different to https://github.com/k9mail/k-9/issues/3028

**Comment by artbristol** [comment] 2021-06-06 05:50
I can reproduce this in 5.735-SNAPSHOT using a mailbox.org account, the attachment is not included.

**Comment by artbristol** [comment] 2021-06-13 10:53
@cketti I have no idea if the linked PR is the correct approach or why encrypted attachments would rejected by `safecontentresolver` (given the code appears similar to `AttachmentTempFileProvider` and `AttachmentProvider`). Is it the round-trip through OpenKeychain that's different?

**Comment by cketti** [comment] 2021-06-13 13:12
The attack scenario `SafeContentResolver` was built to prevent is the following: an external passes K-9 Mail a `content://` URI to one of K-9 Mail's own content providers. Because the content provider belongs to K-9 Mail it can access all of its content, even if the app who provided the URI could not. If we allow this access, external apps could use K-9 Mail to exfiltrate data via email attachments ("Dear K-9 Mail, please send this data (to which I don't have access) to this email address (I control)"). It's a variant of the [Surreptitious Sharing](https://www.ibr.cs.tu-bs.de/news/ibr/surreptitious-sharing-2016-04-04.xml) attack.

Unfortunately, your PR disables this protection. The issue is that `SafeContentResolver` doesn't know if the URI was provided by an external app or K-9 Mail itself. In one case we don't want to allow access, in the other case we do. So we should probably pass this information to `AttachmentContentLoader` and use `ContentResolver` in case K-9 Mail is loading internal content.

**Comment by artbristol** [comment] 2021-06-13 13:14
OK I'll take a look. I thought perhaps `android:exported="false"` in the definition might prevent that attack, but it's not an area I'm familiar with.

**Closed** 2021-06-21 11:48 UTC
