### ISSUE TITLE
Large white bar for K9 statuses after latest Sprint S8 firmware update 

### ISSUE THREAD

**Issue by dcigary** [k9mail/k-9#4150] opened 2019-08-10 08:36 UTC
### Expected behavior
When new mail arrives status line should show info about latest email in a single line

### Actual behavior
Displays double or triple line status in white box, with no info about email. 

### Steps to reproduce
1. Upgrade phone to Sprint kernel 4.4.153-16125356 #2 Jul 4 23:06:25 KST 2019  (Samsung Galaxy S8) 
2. Receive new mail
3. Swipe down from top to view statuses, large white entries appear for new mail

### Environment
K-9 Mail version:
5.600

Android version:
See screen captures

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

![Screenshot_20190810-030614_One UI Home](https://user-images.githubusercontent.com/5402429/62819750-4eaf4380-bb1f-11e9-81c4-e327b64bd200.jpg)

![Screenshot_20190810-030721_Settings](https://user-images.githubusercontent.com/5402429/62819764-6a1a4e80-bb1f-11e9-853b-eefc06ed9703.jpg)

![Screenshot_20190810-030739_Settings](https://user-images.githubusercontent.com/5402429/62819767-7c948800-bb1f-11e9-9f68-aac4e8238129.jpg)

**Comment by cketti** [comment] 2019-08-10 13:36
Duplicate of #4079

**Closed by cketti** 2019-08-10 13:36 UTC
