### ISSUE TITLE
Feature Request: autocomplete previously used email addresses

### ISSUE THREAD

**Issue by droidonfire** [k9mail/k-9#2746] opened 2017-09-09 13:41 UTC
I am missing the autocomplete function for email addresses that are not stored in the android addressbook (as the basic android app does). Please add an internal database, that stores such addresses (e.g. after having sent a mail to it). I do not want to save every new address in my addressbook.

**Comment by cketti** [comment] 2017-09-09 14:11
Duplicate of #1006

**Closed by cketti** 2017-09-09 14:11 UTC
