### ISSUE TITLE
K9mail becomes very slow 

### ISSUE THREAD

**Issue by muessjoeh** [k9mail/k-9#4927] opened 2020-08-30 13:49 UTC
I have K9mail 5.718 on my Android 10 smartphone. The current uptime is 66 hours.
The K9mail app becomes very slow with increasing uptime. When I activate it, it first shows an empty screen, then after 6 seconds the common folder of new messages. When I then swipe down to fetch new mail, it takes another 6 seconds until it changes the status line to indicate that it is actually fetching mail. Then, when I actually have one, which is indicated by a sound signal, it takes 10 seconds until it appears on this list.
Going to this mail and then going back with the 'back' button is very slow, too.
The other apps behave normal, so K9mail is the only app that shows this behavior.

**Comment by muessjoeh** [comment] 2020-08-30 15:25
I just restarted my phone, but unfortunately this app still is slow. So it has nothing to do with the uptime.

**Comment by justinacolmena** [comment] 2020-08-30 16:16
Just curious… What are the memory and processor specs on your phone/device?

On August 30, 2020 7:26:20 AM AKDT, muessjoeh <notifications@github.com> wrote:
>I just restarted my phone, but unfortunately this app still is slow. So
>it has nothing to do with the uptime. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/4927#issuecomment-683433774

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by muessjoeh** [comment] 2020-08-30 16:25
It has a Qualcomm 450 1.8GHz and has 2786MB RAM.

**Comment by cketti** [comment] 2020-08-30 17:49
@muessjoeh: In cases like this please post to the [support forum](https://forum.k9mail.app/) instead. Without being able to reproduce this issue there's little chance developers can fix any of the bugs that might cause this.

Posting to the support forum will reach more people. Maybe someone has experienced the same problem and is able to offer some advice. It's also a chance for more people to ask questions that will hopefully narrow down the cause.

In cases like this the question that should be asked is: what changed between the app working as expected and the app stopping to work as expected? You speculated that the device uptime might be involved, but ruled that out later. What else has changed? Did you download a lot of messages to your device? Did you change K-9 Mail's settings? The important thing is that only you can test this (e.g. start with a fresh install and download more and more messages, check whether the app becomes slower).

Feel free to create a forum post to update us about your investigation. But please don't create bug reports in this issue tracker that are not actionable.

I'm closing this issue. Once you can reliably reproduce the issue (app is fast, do XYZ, app is slow) on your device feel free to create a new bug report.

**Closed by cketti** 2020-08-30 17:49 UTC

**Comment by muessjoeh** [comment] 2020-08-30 19:15
One more investigation should be possible: When you have the log file, you could determine the steps that take extraordinarily long.
