### ISSUE TITLE
Separate PGP keys for multiple identies under the same account.

### ISSUE THREAD

**Issue by jlamothe** [k9mail/k-9#5316] opened 2021-05-31 05:31 UTC
I have an email solution set up where I have a single account, and multiple forwarding only addresses set up so that I can use filtering rules to sort my mail based on the address the sender has been given. Because I do not want all these addresses to be visible to the public, they have separate PGP keys, not all of which are available on the public keyservers.

Because of this, it would be nice if I could set a separate PGP key for each identity on a single email account.

**Comment by cketti** [comment] 2021-05-31 07:25
Duplicate of #942

**Closed** 2021-05-31 07:25 UTC
Labels: enhancement
