### ISSUE TITLE
Search in all folders

### ISSUE THREAD

**Issue by Virgyxx** [k9mail/k-9#4754] opened 2020-05-10 11:43 UTC
Hello
I just installed the latest release of K-9 mail 5.713 on my Android phone. 
I configured an old hotmail account and I received all my emails. This account has many folders. When I use the search function, it doesn't found the emails containing the keywords if I'm not already in the correct opened folder. 
Is this normal ? In the settings I chose that I want to search in any folder.
In my previous K-9 version 5.6 (which is the latest version available in the Play Store), it would give results regardless of the location of the emails.

### Expected behavior
Show all searched emails regardless of the opened folder/email location.

### Actual behavior
I find the searched emails only if I'm already in the correct folder. 

### Environment
K-9 Mail version: 5.713

Android phone. 

Account type (IMAP, POP3, WebDAV/Exchange):IMAP (Hotmail)

**Comment by Virgyxx** [comment] 2020-06-21 22:09
I've found a workaround:
Search for the mail when the general inbox is selected (the mailbox containing all the emails from all accounts)

**Comment by cketti** [comment] 2020-06-27 22:34
Duplicate of #4514

**Closed by cketti** 2020-06-27 22:34 UTC
Labels: enhancement
