### ISSUE TITLE
Proxy support 

### ISSUE THREAD

**Issue by tuliogit** [k9mail/k-9#736] opened 2015-08-05 13:05 UTC
We need a possibility to connect to the mail server via a proxy server. At the moment, there is no possibility to get the mails in networks that are set to use a proxy (e.g. many networks at University,  Tor etc).
I would add that proxy support should be added in a "per account" basis.

**Comment by cketti** [comment] 2015-08-05 14:01
Duplicate of #704

Also, it's not good form to start a feature request with "we need" unless you follow it up with an offer to implement that feature.

**Closed by cketti** 2015-08-05 14:01 UTC
Labels: duplicate
