### ISSUE TITLE
Recipient name doesn't show up automatically while sending 

### ISSUE THREAD

**Issue by SeriousHoax** [k9mail/k-9#3310] opened 2018-04-06 17:00 UTC
When I'm typing an email address in the "To" section, the name of the recipient to whom I previously sent any email should come up automatically. It comes up in other email apps. 

So, is there any way to enable that from the settings? Or it's not available in K-9 Mail yet!!!

**Comment by cketti** [comment] 2019-03-07 17:06
Duplicate of #1006

**Closed by cketti** 2019-03-07 17:06 UTC
