### ISSUE TITLE
The new email icon disappears from the status bar (the clock bar)

### ISSUE THREAD

**Issue by xmiseggs** [k9mail/k-9#3596] opened 2018-09-04 07:44 UTC
### Expected behavior
The new email icon in the status bar should be kept without disappearing

### Actual behavior
I leave my phone in airplane mode all night long and without mobile data, when I wake up I remove the airplane mode and activate data, K9 automatically checks new email, informs me with an icon in the status bar of a new email and after 2 seconds, without doing anything, the new email icon disappears from the status bar.

### Steps to reproduce
1. I have described it in: Actual behavior 

### Environment
K-9 Mail version: v5.503 and v5.600

Android version: 8.1.0 (OxygenOS 5.1.5 OnePlus 5T)

Account type (IMAP, POP3, WebDAV/Exchange): It's with a Gmail account

**Comment by Joreel** [comment] 2018-09-21 10:29
I'm having the exact same issue. 

### **Environment**

K-9 Mail version: v5.600

Android version: 7.1.1 (Moto G Play)

Account type (IMAP, POP3, WebDAV/Exchange): It's with a Gmail account

**Comment by beerisgood** [comment] 2018-11-19 15:18
Can confirm this under LineageOS 15.1 (Android 8.1)

Also sometimes no icon is displayed at all

**Comment by djfun** [comment] 2019-01-27 11:00
I ran a git-bisect and found that for my test case (IMAP), I could not reproduce the issue before this pull request was merged: https://github.com/k9mail/k-9/pull/3059

**Comment by cketti** [comment] 2019-03-08 03:35
Duplicate of #3809

**Closed by cketti** 2019-03-08 03:35 UTC
