### ISSUE TITLE
Unable to successfully display decrypted plain text emails

### ISSUE THREAD

**Issue by craftyguy** [k9mail/k-9#1338] opened 2016-04-28 18:44 UTC
### Expected behaviour
Plain text emails, when decrypted, should display the original text.

### Actual behaviour
When decrypted, plain text email display all sorts of crazy symbols. It looks like some data is preserved (i.e. length of message) but the message itself is totally unreadable. 

This does not happen if the email format is html or rich text. This also does not happen with other clients (like mutt), they are able to read the decrypted plain text emails.

The message in the attached screenshot should say "This is a test! If you can read this in k-9 then something else is wrong!"
![screenshot_4](https://cloud.githubusercontent.com/assets/1474209/14897374/9fb487a8-0d36-11e6-9e5f-4868084ab17f.png)

Here's the email when viewed in mutt:

```
[-- PGP output follows (current time: Thu 28 Apr 2016 11:55:50 AM PDT) --]
[-- End of PGP output --]

[-- The following data is PGP/MIME encrypted --]

[-- Attachment #1 --]
[-- Type: text/plain, Encoding: base64, Size: 0.1K --]

This is a test! If you can read this in k-9 then something else is wrong!


[-- End of PGP/MIME encrypted data --]
```

### Steps to reproduce
1. Compose email in plain text
2. Encrypt with opengpg
3. Decrypt/view in K9

### Environment
K-9 Mail version: 5.108

Android version: 6.0.1 - Cyanogenmod 13.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2016-04-28 19:03
Duplicate of #1252

**Closed by philipwhiuk** 2016-04-28 19:03 UTC
