### ISSUE TITLE
killed due to SQL lock after/while 'Background concurrent copying'

### ISSUE THREAD

**Issue by traumschule** [k9mail/k-9#4680] opened 2020-04-21 14:32 UTC
### Expected behavior
No crash.

### Actual behavior
k9 got killed while 'Background concurrent copying' and main thread was waiting for SQL connection

### Steps to reproduce
1. Delete message in INBOX

### Environment
K-9 Mail version: 5.6
Android version: 9
Account type: IMAP

```
04-21 10:42:33.290 22684 22704 V ImapResponseParser: conn98369622<<<#14# [OK, Search completed (0.002 + 0.000 + 0.001 secs).]
04-21 10:42:33.344 22684 22704 V ImapSync: SYNC: Got 558 messages for folder INBOX
04-21 10:42:33.894 22684 22694 I com.fsck.k9: Background concurrent copying GC freed 298559(14MB) AllocSpace objects, 0(0B) LOS objects, 72% free, 6MB/24MB, paused 258us total 132.618ms
04-21 10:42:35.083 22684 22694 I com.fsck.k9: Background concurrent copying GC freed 190825(15MB) AllocSpace objects, 5(108KB) LOS objects, 62% free, 10MB/28MB, paused 233us total 177.446ms
04-21 10:42:36.292 22684 22694 I com.fsck.k9: Background concurrent copying GC freed 199191(16MB) AllocSpace objects, 5(104KB) LOS objects, 54% free, 14MB/32MB, paused 1.303ms total 211.579ms
04-21 10:42:37.511 22684 22694 I com.fsck.k9: Background concurrent copying GC freed 207412(17MB) AllocSpace objects, 1(16KB) LOS objects, 49% free, 18MB/37MB, paused 232us total 251.119ms
04-21 10:42:38.818 22684 22694 I com.fsck.k9: Background concurrent copying GC freed 225419(18MB) AllocSpace objects, 3(56KB) LOS objects, 50% free, 23MB/46MB, paused 239us total 297.274ms
04-21 10:42:48.082 22684 22777 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 55344 (AsyncTask #2) with flags 0x1 for 4.038 seconds.
04-21 10:42:48.082 22684 22777 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:42:48.082 22684 22777 W SQLiteConnectionPool: 
04-21 10:42:48.082 22684 22777 W SQLiteConnectionPool: Requests in progress:
04-21 10:42:48.082 22684 22777 W SQLiteConnectionPool:   executeForCursorWindow started 132ms ago - running, sql="SELECT id FROM message_parts WHERE root = ? AND data_location = 2"
04-21 10:42:52.121 22684 22777 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 55344 (AsyncTask #2) with flags 0x1 for 8.078 seconds.
04-21 10:42:52.121 22684 22777 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:42:52.121 22684 22777 W SQLiteConnectionPool: 
04-21 10:42:52.121 22684 22777 W SQLiteConnectionPool: Requests in progress:
04-21 10:42:52.121 22684 22777 W SQLiteConnectionPool:   executeForChangedRowCount started 7ms ago - running, sql="DELETE FROM messages WHERE id = ?"
04-21 10:42:56.161 22684 22777 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 55344 (AsyncTask #2) with flags 0x1 for 12.118001 seconds.
04-21 10:42:56.161 22684 22777 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:42:56.161 22684 22777 W SQLiteConnectionPool: 
04-21 10:42:56.161 22684 22777 W SQLiteConnectionPool: Requests in progress:
04-21 10:42:56.161 22684 22777 W SQLiteConnectionPool:   executeForChangedRowCount started 41ms ago - running, sql="DELETE FROM message_parts WHERE root = ?"
04-21 10:42:59.433 22684 22684 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 2 (main) with flags 0x5 for 4.0 seconds.
04-21 10:42:59.433 22684 22684 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:42:59.433 22684 22684 W SQLiteConnectionPool: 
04-21 10:42:59.433 22684 22684 W SQLiteConnectionPool: Requests in progress:
04-21 10:42:59.433 22684 22684 W SQLiteConnectionPool:   executeForCursorWindow started 39ms ago - running, sql="SELECT id FROM message_parts WHERE root = ? AND data_location = 2"
04-21 10:43:00.201 22684 22777 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 55344 (AsyncTask #2) with flags 0x1 for 16.158 seconds.
04-21 10:43:00.201 22684 22777 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:43:00.201 22684 22777 W SQLiteConnectionPool: 
04-21 10:43:00.201 22684 22777 W SQLiteConnectionPool: Requests in progress:
04-21 10:43:00.201 22684 22777 W SQLiteConnectionPool:   executeForCursorWindow started 58ms ago - running, sql="SELECT id FROM message_parts WHERE root = ? AND data_location = 2"
04-21 10:43:03.436 22684 22684 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 2 (main) with flags 0x5 for 8.001 seconds.
04-21 10:43:03.436 22684 22684 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:43:03.436 22684 22684 W SQLiteConnectionPool: 
04-21 10:43:03.436 22684 22684 W SQLiteConnectionPool: Requests in progress:
04-21 10:43:03.436 22684 22684 W SQLiteConnectionPool:   executeForChangedRowCount started 16ms ago - running, sql="DELETE FROM messages WHERE id = ?"
04-21 10:43:15.438 22684 22684 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 2 (main) with flags 0x5 for 20.005001 seconds.
04-21 10:43:15.438 22684 22684 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:43:15.438 22684 22684 W SQLiteConnectionPool: 
04-21 10:43:15.438 22684 22684 W SQLiteConnectionPool: Requests in progress:
04-21 10:43:15.438 22684 22684 W SQLiteConnectionPool:   executeForChangedRowCount started 298ms ago - running, sql="DELETE FROM message_parts WHERE root = ?"
04-21 10:43:16.361 22684 22777 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 55344 (AsyncTask #2) with flags 0x1 for 32.318 seconds.
04-21 10:43:16.361 22684 22777 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:43:16.361 22684 22777 W SQLiteConnectionPool: 
04-21 10:43:16.361 22684 22777 W SQLiteConnectionPool: Requests in progress:
04-21 10:43:16.361 22684 22777 W SQLiteConnectionPool:   executeForChangedRowCount started 99ms ago - running, sql="DELETE FROM message_parts WHERE root = ?"
04-21 10:43:19.450 22684 22684 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 2 (main) with flags 0x5 for 24.006 seconds.
04-21 10:43:19.450 22684 22684 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:43:19.450 22684 22684 W SQLiteConnectionPool: 
04-21 10:43:19.450 22684 22684 W SQLiteConnectionPool: Requests in progress:
04-21 10:43:19.450 22684 22684 W SQLiteConnectionPool:   executeForCursorWindow started 134ms ago - running, sql="SELECT id FROM message_parts WHERE root = ? AND data_location = 2"
04-21 10:43:20.401 22684 22777 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 55344 (AsyncTask #2) with flags 0x1 for 36.358 seconds.
04-21 10:43:20.401 22684 22777 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:43:20.401 22684 22777 W SQLiteConnectionPool: 
04-21 10:43:20.401 22684 22777 W SQLiteConnectionPool: Requests in progress:
04-21 10:43:20.401 22684 22777 W SQLiteConnectionPool:   executeForChangedRowCount started 34ms ago - running, sql="DELETE FROM message_parts WHERE root = ?"
04-21 10:43:23.452 22684 22684 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 2 (main) with flags 0x5 for 28.019001 seconds.
04-21 10:43:23.452 22684 22684 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:43:23.452 22684 22684 W SQLiteConnectionPool: 
04-21 10:43:23.452 22684 22684 W SQLiteConnectionPool: Requests in progress:
04-21 10:43:23.452 22684 22684 W SQLiteConnectionPool:   executeForChangedRowCount started 26ms ago - running, sql="DELETE FROM message_parts WHERE root = ?"
04-21 10:43:24.443 22684 22777 W SQLiteConnectionPool: The connection pool for database '+data+user+0+com_fsck_k9+databases+740abd79-f9a8-46b6-9428-93595d70e367_db' has been unable to grant a connection to thread 55344 (AsyncTask #2) with flags 0x1 for 40.398003 seconds.
04-21 10:43:24.443 22684 22777 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
04-21 10:43:24.443 22684 22777 W SQLiteConnectionPool: 
04-21 10:43:24.443 22684 22777 W SQLiteConnectionPool: Requests in progress:
04-21 10:43:24.443 22684 22777 W SQLiteConnectionPool:   executeForChangedRowCount started 102ms ago - running, sql="DELETE FROM message_parts WHERE root = ?"
04-21 10:43:26.259  1266  1287 I ActivityManager: Killing 22684:com.fsck.k9/u0a186 (adj 900): user request after error
04-21 10:43:26.342  1266  1289 W libprocessgroup: kill(-22684, 9) failed: No such process
```

**Comment by cketti** [comment] 2020-04-21 16:42
From the log it sounds like the app was killed by the user: `Killing 22684:com.fsck.k9/u0a186 (adj 900): user request after error`

I'm guessing the app wasn't responding because a database query was performed on the main thread and it was blocked by a slow delete operation. In those cases the OS usually offers the user to either wait or kill the app.
If that's the case the issue is not so much the crash but the database operation that is performed in the main thread.

**Comment by traumschule** [comment] 2020-04-21 18:03
you are right, i was a bit impatient and i agree db operations shouldn't be performed on the main thread. cheers!

**Comment by cketti** [comment] 2020-04-23 18:18
This is a known problem that requires a lot of internal changes to be fixed. It's an ongoing process.
Closing this issue because it's not necessary as a reminder.

**Closed by cketti** 2020-04-23 18:18 UTC
