### ISSUE TITLE
Please make the From email addresses appear beside the name, and not just the name 

### ISSUE THREAD

**Issue by life777eternal** [k9mail/k-9#5688] opened 2021-09-21 12:50 UTC
**Describe the solution you'd like**
When an email sender has a name with their email address, the name only shows in the From field without the actual email address. Additionally the from Name has a link 🔗 that opens a popover with "Add to contacts."  Would rather see the actual email address there as well.  

**Describe alternatives you've considered**
The Gmail app has an option to expand the top section to show more information. 

**Additional context**
Have compared a version of the Gmail app, and it shows more information than just the senders name. 

Thank you.

**Comment by cketti** [comment] 2021-09-21 12:52
Duplicate of #1119

**Closed by cketti** 2021-09-21 12:52 UTC
Labels: enhancement
