### ISSUE TITLE
Sent messages often lost during poor Internet connectivity

### ISSUE THREAD

**Issue by jgoerzen** [k9mail/k-9#3921] opened 2019-02-19 16:51 UTC
### Expected behavior

A sent message should be copied to the Sent folder when it is transmitted.  During times of good Internet connectivity (3G/4G/wifi), this is fine.

### Actual behavior

During times of poor Internet connectivity, the message is sometimes transmitted but not saved into Sent, leaving no record for the sender.  I experienced this numerous times during a recent trip into areas with dodgy signal.  My theory is that the signal was good enough for K-9 to transmit the message with SMTP, but failed before it could completely APPEND with IMAP, and it therefore discarded the message.  In some cases, I was able to resurrect most of it from the Drafts folder.

I suspect there needs to be a state in the state machine for outgoing messages: sent via SMTP, appended via IMAP, complete.

### Steps to reproduce
1. Send a message while the signal is dodgy (not so bad that Android thinks you have no Internet, just bad enough.)  Attaching a photo will probably help with reproduction.
2. If K-9 is able to send via SMTP but not complete via IMAP, the sent message is lost.
3.

### Environment
K-9 Mail version: 5.600

Android version: 9, patch level 2019-02-05

Account type (IMAP, POP3, WebDAV/Exchange): IMAP with SMTP

**Comment by yoshimo** [comment] 2019-02-20 06:29
https://tools.ietf.org/html/rfc4468 might help here.
If the message is received by the server, it will be copied into the sent folder  by the server.

**Comment by cketti** [comment] 2019-03-08 05:22
Duplicate of #2616

**Closed by cketti** 2019-03-08 05:22 UTC
