### ISSUE TITLE
sync/push broken with android 7.0

### ISSUE THREAD

**Issue by rexdwilson** [k9mail/k-9#2441] opened 2017-03-25 14:00 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
i should get notified of new emails

### Actual behavior
k-9 seems to go to sleep. Note that i have used the battery monitor advanced settings to tell it to not monitor k-9

### Steps to reproduce
1. wait for a little while
2. have new emails appear in my inbox
3. notice that k-9 doesn't see them and doesn't alert me

### Environment
K-9 Mail version:
5.206

Android version:
7.0
Account type (IMAP, POP3, WebDAV/Exchange):
imap

**Comment by philipwhiuk** [comment] 2017-03-25 14:05
Duplicate of #857

**Closed by philipwhiuk** 2017-03-25 14:05 UTC
