### ISSUE TITLE
Print capability

### ISSUE THREAD

**Issue by Silventar** [k9mail/k-9#2773] opened 2017-09-16 18:40 UTC
K9 does  OT seem to possess a print capability or even a share capability like many other email programs.

**Comment by cketti** [comment] 2017-09-16 18:53
Please don't use this issue tracker for support requests. If you want to request a feature make sure to formulate it as such. But search first (including closed issues) to make sure the feature hasn't been requested before.

The share action can be found in the "Send…" sub menu (might be displayed as two left pointing arrows).

Duplicate of #1062

**Closed by cketti** 2017-09-16 18:53 UTC
