### ISSUE TITLE
Can't Scroll with Keyboard Open

### ISSUE THREAD

**Issue by johnyradio** [k9mail/k-9#4401] opened 2019-12-23 17:16 UTC
existing issue?
This is a new problem with yesterday's release. 

### Expected behavior
Ability to scroll within message while composing. 

### Actual behavior
Can't scroll. Message is stuck in a tiny frame. My extra long signature (which I'm NOT trying to edit) monopolizes the screen, and can't be scrolled out of view. 

### Steps to reproduce
1. Compose a reply

### Environment
K-9 Mail version: 5.703

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

 logs
Not a crash or bug.

**Comment by cketti** [comment] 2019-12-23 17:20
Duplicate of #4342

**Closed by cketti** 2019-12-23 17:20 UTC
