### ISSUE TITLE
K-9 shouldn't "discard" a draft completely, just the changes done

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [k9mail/k-9#4372] opened 2019-12-14 08:18 UTC
If you open an existing draft in K-9 to e.g. copy some text out of it, and you e.g. press a key by mistake, even if you have un-done your changes, K-9 will ask you for save or discard when you leaf the draft.
At least I will think in this moment, that K-9 should discard (the changes), because I don't want to save them! But "discard" deletes the whole draft instead with this function! I think this behavior is wrong!

Also: If you discard a draft, K-9 jumps into the inbox. I think K-9 should instead go back into the drafts folder!

### Environment
K-9 Mail version:
5.703

Android version:
Android 9 Stock ROM

**Comment by cketti** [comment] 2019-12-14 14:01
Duplicate of #2485

**Closed by cketti** 2019-12-14 14:01 UTC

**Comment by gloschtla** [comment] 2019-12-16 08:45
Thank you for reporting this issue. It's sad to see that still nothing has been improved.
