### ISSUE TITLE
Timestamps are from when mail is checked, not from when message was recieved

### ISSUE THREAD

**Issue by Viss** [k9mail/k-9#4806] opened 2020-06-01 21:53 UTC
The timestamps visible on the right hand side which indicate the time of message arrival do not actually reflect the time the message arrived, they are the timestamp of when the email was checked. I have dozens of emails that look like they "were sent moments ago", when the timestamp in the actual email was from hours ago. 
This is with version 5.714

**Comment by cketti** [comment] 2020-06-04 01:52
This is probably related to issue #1356.

**Comment by cketti** [comment] 2020-06-04 02:07
Can you provide a Date header of an affected message?

**Comment by Viss** [comment] 2020-06-04 05:24
certainly

`Return-Path: <camera@atenlabs.com>
X-Original-To: viss@mail.atenlabs.com
Delivered-To: viss@mail.atenlabs.com
Received: from localhost (localhost [127.0.0.1])
    by mail.atenlabs.com (Postfix) with ESMTP id 3BAFC10A22C9
    for <viss@mail.atenlabs.com>; Sat, 30 May 2020 16:12:03 -0700 (PDT)
X-Virus-Scanned: Debian amavisd-new at mail.atenlabs.com
Received: from mail.atenlabs.com ([127.0.0.1])
    by localhost (localhost [127.0.0.1]) (amavisd-new, port 10024)
    with ESMTP id NG2C7SvD14KN for <viss@mail.atenlabs.com>;
    Sat, 30 May 2020 16:11:51 -0700 (PDT)
Received-SPF: Softfail (mailfrom) identity=mailfrom; client-ip=10.0.0.8; helo=garagecam; envelope-from=camera@atenlabs.com; receiver=<UNKNOWN>
Received: from garagecam (unknown [10.0.0.8])
    by mail.atenlabs.com (Postfix) with ESMTP id A6C9610A26A4
    for <dan@atenlabs.com>; Sat, 30 May 2020 16:11:42 -0700 (PDT)
To: =?utf-8?B?ZGFuQGF0ZW5sYWJzLmNvbQ==?= <dan@atenlabs.com>
From: =?utf-8?B?Y2FtZXJhQGF0ZW5sYWJzLmNvbQ==?= <camera@atenlabs.com>
Subject: =?utf-8?B?R2FyYWdlY2FtIHdhcyB0cmlnZ2VyZWQhICB6b25l?=
Date: Sat May 30 23:03:14 2020 +0000
MIME-version: 1.0
Content-Type: multipart/mixed; boundary=curlsink-boundary
Message-Id: <20200530231203.3BAFC10A22C9@mail.atenlabs.com>`

**Comment by cketti** [comment] 2020-06-04 11:20
`Sat May 30 23:03:14 2020 +0000` is not a properly formatted date.

That makes this issue a duplicate of #1356.

**Closed by cketti** 2020-06-04 11:20 UTC
Labels: needs info

**Comment by cketti** [comment] 2020-06-04 11:53
I've tracked down the likely culprit for this and submitted a fix: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1317

**Comment by Virgyxx** [comment] 2020-06-21 22:06
I don't understand
Has this been solved?
Will it be fixed in a future release
