### ISSUE TITLE
The mail has shown without content

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#1631] opened 2016-09-24 03:56 UTC
### Expected behavior
Subject display as "no subject" and the details of body display as "no text"

### Actual behavior
Actually this mail I have ever seen it

### Steps to reproduce
1.Open a mail
2.The title and body is all blank
3.Back to message list and find the mail is display as no subject

### Environment
K-9 Mail version:how to view?

Android version:HUAWEI TAG-AL00

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by philipwhiuk** [comment] 2016-09-24 13:02
Closing as duplicate of #1541

**Closed by philipwhiuk** 2016-09-24 13:02 UTC
Labels: duplicate
