### ISSUE TITLE
Standard IMAP folders should not be created without user consent

### ISSUE THREAD

**Issue by d-tamm** [k9mail/k-9#2928] opened 2017-11-10 21:41 UTC
### Expected behavior
When connecting to an IMAP account, K9 should look for existing standard folders for Trash, Sent, Drafts, Junk on the server and respect those even if called differently. It should not create new standard folders on the server just because they do not exist under the (localized) name. If K9 cannot identify those existing folders, the user should be asked which action to take.

### Actual behavior
When creating a new IMAP account in a localized K9 (e.g. German), it will look for standard folders on the server using localized names (e.g. Papierkorb for the trash bin). If folders with those names do not exists, they are silently created, even if there already is a folder for that purpose but with a different name. E.g. there may be a folder called Trash, but anyway K9 creates another one called Papierkorb. This ends up with K9 moving deleted mails to "Papierkorb", while any other application using the same IMAP account would move them to "Trash".

The same bug has been reported in issue #881 which has been closed, but should not. It is an old bug and still exists.

**Comment by philipwhiuk** [comment] 2017-11-10 22:01
Duplicate of #633

**Closed by philipwhiuk** 2017-11-10 22:01 UTC
