### ISSUE TITLE
Enhancement: schedule email sending of a particular draft

### ISSUE THREAD

**Issue by xtingu** [k9mail/k-9#1195] opened 2016-03-21 09:01 UTC
### Expected behaviour
Type an email, save it in your Drafts folder, with the ability to schedule a "Send Later" date and time. (Sometimes I don't want my clients knowing I was up working at 3:30am, so I'd love to go to sleep knowing my email will auto-send at, say, 8:30am.)

### Actual behaviour
This functionality currently does not exist. Must hit "send" when you want to send you email. 

### Environment
K-9 Mail version: Current

Android version: Any (Lollipop. 5.1.1)

Account type (IMAP, POP3, WebDAV/Exchange):
All account types, but IMAP is probably easiest

**Comment by philipwhiuk** [comment] 2016-03-21 12:45
Duplicate of #688

**Closed by philipwhiuk** 2016-03-21 12:45 UTC
Labels: enhancement
