### ISSUE TITLE
Notifications don't disappear

### ISSUE THREAD

**Issue by jmlobert** [k9mail/k-9#2132] opened 2017-01-24 23:05 UTC
Notifications for new mails in Android's notification bar (at the top of the screen) do not consistently disappear when checking mail directly, only when following those notifications

### Expected behavior
Android notification bar: one icon per email account for new emails. When following these, the notification disappears. When going into the mail client and checking the accounts individually, the notifications disappear also. 

### Actual behavior
Notifications only disappear when following them from the notification bar, but not when checking and reading new emails directly. This is not consistent.

### Steps to reproduce
1. Get new mail, have notifications in notification bar (top of Android screen)
2. Do not tap on those, but go directly into mail client, check and read emails 
3. Notifications at top may or may not disappear.

### Environment
K-9 Mail version: latest 5.203

Android version: 6.0.1, Google Nexus 5

Account type: POP3

**Comment by AndromedaXP** [comment] 2017-01-26 08:42
Same here with an OnePlusOne, same version. I have configured multiple IMAP accounts and when I try to delete them directly in the status bar, sometimes they disappear but most of the time not, especially when I have new mails from more than one account.

**Comment by cketti** [comment] 2017-01-26 09:29
Duplicate of #1921

**Closed by cketti** 2017-01-26 09:29 UTC
