### ISSUE TITLE
Can't connect to IMAP server via SSL/TLS on port 993, no error detail given

### ISSUE THREAD

**Issue by Pazu** [k9mail/k-9#3329] opened 2018-04-11 14:59 UTC
This is likely related to or a duplicate of issue #3141 or #893.

### Expected behavior
Connection should be made to my host via SSL/TLS on port 993.

### Actual behavior
An error message "Setup could not finish / Cannot connect to server. (Unable to connect)" is shown without further details.

### Steps to reproduce
1. Enter hostname, select SSL/TLS, port 993, enter username and password, and click Done.

### Environment
K-9 Mail version: 5.403

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Ciphers supported by server: 0xc027, 0xc028, 0xc02f, and 0xc030.

Ciphers supported by client: According to SSLLabs client test:

* 0xcc14
* 0xcc13
* 0xcc15
* 0xc014
* 0xc00a
* 0x39
* 0x38
* 0x35
* 0xc012
* 0xc008
* 0x16
* 0x13
* 0xa
* 0xc02f
* 0xc02b
* 0xc013
* 0xc009
* 0xa2
* 0x9e
* 0x33
* 0x32
* 0x9c
* 0x2f
* 0xc011
* 0xc007
* 0x5
* 0x4
* 0xff

[k9-log.txt](https://github.com/k9mail/k-9/files/1899345/k9-log.txt)
![screenshot_2018-04-11-16-20-57](https://user-images.githubusercontent.com/2777268/38624970-abffc810-3da9-11e8-813b-4a9ed95c052a.png)

**Comment by philipwhiuk** [comment] 2018-04-15 23:04
Nothing in the logs. Unfortunately there's not much we can do about this - we don't get told why the connection is closed.

**Comment by philipwhiuk** [comment] 2018-04-15 23:05
Closing as duplicate of #1789

**Closed by philipwhiuk** 2018-04-15 23:05 UTC
