### ISSUE TITLE
K9-Mail not restarting after Reboot on Oro

### ISSUE THREAD

**Issue by gleichda** [k9mail/k-9#3433] opened 2018-06-07 08:48 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
After Rebooting the Phone K9-Mail should start in Background and notify about new Mails.

### Actual behavior
K9-Mail is not doing anything before it was opened manually.
Background Activity allowed and No Battery Optimisation

### Steps to reproduce
1. Reboot Phone and DO NOT open K9-Mail
2. Send a mail to K9-Mail configured Account

### Environment
K-9 Mail version: 5.403 (from F-Droid)

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by itsbrody** [comment] 2018-07-16 20:08
can confirm same behaviour on OREO 8.0.0
Further sometimes the sync settings switch to off (also its setup says either anytime or on ‘automatic synchronisstion‘

**Comment by cketti** [comment] 2019-03-08 02:32
Duplicate of #3950

**Closed by cketti** 2019-03-08 02:32 UTC
