### ISSUE TITLE
Remember Show Pictures setting per sender

### ISSUE THREAD

**Issue by linucksrox** [k9mail/k-9#5883] opened 2022-01-25 20:49 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.909

### Problem you are trying to solve

I would like an option to tell K-9 Mail to save the show pictures setting per sender, like I can do in the Gmail app. I don't mind clicking the Show Pictures button for random emails, but it would be nice to have the option to "always show pictures" based on the sender.

### Suggested solution

After clicking Show Pictures, change the button into Always Show pictures (not sure on the exact wording). Gmail says "always show pictures from this sender"

**Comment by cketti** [comment] 2022-01-25 20:52
Duplicate of #1035

**Closed by cketti** 2022-01-25 20:52 UTC
Labels: enhancement
