### ISSUE TITLE
Allow for account mail (not settings) backup

### ISSUE THREAD

**Issue by bovergaauw** [k9mail/k-9#3885] opened 2019-01-21 00:16 UTC
I need to migrate to a new phone, but cannot find any way to backup the messages of my accounts. For IMAP accounts this is not an issue as all mail is stored on the IMAP server. However, this is not the case with POP mail. Consequently, even if I can re-download all messages that are still stored on the POP server with my new phone, I will lose all outgoing messages as well as the messages in the other special folders (including Drafts and Trash). Losing messages in Trash are an issue since there seems to be no way to move accidentally deleted message back to the Inbox.

**Comment by cketti** [comment] 2019-03-08 03:58
Duplicate of #3627

**Closed by cketti** 2019-03-08 03:58 UTC
