### ISSUE TITLE
"Unrecognized Certificate" error after upgrading from K9 v5.600 to v5.800

### ISSUE THREAD

**Issue by atc0005** [k9mail/k-9#5491] opened 2021-07-31 16:10 UTC
**Describe the bug**

After upgrading to K9 v5.800, I've been unable to connect seamlessly to an IMAP server mail server which uses a private CA to sign certificates. In the prior version, as long as the root CA was trusted by Android then K9 would validate the certificate and connect without issue.

**To Reproduce**

1. Install K9 v5.600
2. Connect to private IMAP server
    - *which uses certificate signed by custom CA already trusted by the device*
3. Upgrade to K9 v5.800
4. "Unrecognized Certificate" error is displayed when attempting to refresh the Inbox contents

**Expected behavior**

I expected the trusted CA certificate on the device (untouched and not expired) to be used to verify the IMAPS connection (certificate) and allow the connection without errors/warnings.

**Environment (please complete the following information):**

 - K-9 Mail version: v5.800 (now), v5.600 (before)
 - Android version: 10
 - Device: LG V40
 - Account type: IMAP

**Comment by cketti** [comment] 2021-07-31 16:14
Duplicate of #5473.

Fixed in K-9 Mail 5.801. https://forum.k9mail.app/t/new-beta-release-k-9-mail-5-801/2214

**Closed by cketti** 2021-07-31 16:14 UTC
Labels: bug

**Comment by atc0005** [comment] 2021-07-31 16:26
> @cketti: Duplicate of #5473.
> 
> Fixed in K-9 Mail 5.801. https://forum.k9mail.app/t/new-beta-release-k-9-mail-5-801/2214

Sorry for the noise (I looked, but completely missed the existing GH issue). Thanks for the app!
