### ISSUE TITLE
Mails shown twice

### ISSUE THREAD

**Issue by rkoe** [k9mail/k-9#4403] opened 2019-12-24 16:30 UTC
With some mails, K-9 Mail shows the mail twice; and selecting one of these messages also selects the other. The message-count is correct.

This seems to be a GUI error.

Maybe #981 was the same error.

### Expected behavior
Every message should only be shown once.

### Actual behavior
Some messages are shown twice by K-9 Mail.

Example (GUI output approximated in ASCII) with two messages (each shown twice):
- Message list: 2 Messages
   ```
   [ ] To: test@example.com, "TEST 2"
   [ ] To: test@example.com, "TEST 2"
   [ ] To: test@example.com, "TEST 1"
   [ ] To: test@example.com, "TEST 1"
   ```
- select 1st message -> duplicate is automatically selected, too
   ```
   [X] To: test@example.com, "TEST 2"
   [X] To: test@example.com, "TEST 2"
   [ ] To: test@example.com, "TEST 1"
   [ ] To: test@example.com, "TEST 1"
   ```
- moving/deleting the message, also moves/deletes the duplicate
- after moving the message to an other folder, it is then shown 3 times, after moving again to an other folder, it is shown 5 times, after then moving back it is shown 9 times, then 17 times, then 33 times ...
  So, after each move, the "duplicates" increase.

- there's also only one entry in the messages-table of the SQL database

### Environment
K-9 Mail version: 5.600

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by realmain** [comment] 2020-01-06 08:38
You're using an over 1 year old version of K9 (from 2018). Try using 5.700 which was released in Nov 2019, or the new 5.703

**Comment by realmain** [comment] 2020-01-06 08:53
Please update your app to v5.703 and see if the issue is still there.

**Comment by filipiff** [comment] 2020-04-10 15:59
I'have a similar problem that I get duplicated mails but only recently received and new mails. Old mails are shown correctly. With a different email's client mails aren't shown duplicated. Version is v5.707

**Comment by cketti** [comment] 2020-04-23 17:59
Duplicate of #2705

**Closed by cketti** 2020-04-23 17:59 UTC
