### ISSUE TITLE
auto complete of recipients broken?

### ISSUE THREAD

**Issue by himpierre** [k9mail/k-9#3557] opened 2018-08-16 15:32 UTC
### Expected behavior
When i try to enter a recipients address k9 mail stops completion one character after the @ sign.
Example: I wanna sent an email to hr@mydomain.xxx
I would expect to be able to type this email address.

### Actual behavior
Auto completion seems to catch ht@m. After that i cannot type any longer.

### Steps to reproduce
1. Enter in the to field hr@mydomain.xxx
2. auto completion jumps in at hr@m
3. no further input possible

### Environment
K-9 Mail version: 5.403 / 5.503

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by himpierre** [comment] 2018-08-16 15:34
Uh i should mention this error only occurs on email addresses which are *not* in the carddav address book. auto completion for existing entries work fine.

**Comment by cketti** [comment] 2018-08-16 15:37
Duplicate of #2829

**Closed by cketti** 2018-08-16 15:37 UTC
