### ISSUE TITLE
search message text

### ISSUE THREAD

**Issue by Djfe** [k9mail/k-9#5156] opened 2021-02-18 21:06 UTC
**Describe the solution you'd like**
A search function for mails (like STRG + F on desktop mail apps).
I want to search the content of a mail (mostly the text)

Like in a Webbrowser.
You could probably rely on functionality of chrome/webview (the engine you use already).

**Comment by Djfe** [comment] 2021-02-18 21:08
This is related to #586
even though it's not about the headers

**Comment by cketti** [comment] 2021-02-18 21:24
Duplicate of #3644

**Closed by cketti** 2021-02-18 21:24 UTC
Labels: enhancement
