### ISSUE TITLE
per identity sent folder

### ISSUE THREAD

**Issue by 532910** [k9mail/k-9#3914] opened 2019-02-11 23:41 UTC
Thunderbird has the setting "Place a copy in" with following options: "Sent folder" | "Other". And additional flag "Place replies in the folder of the message being replied to"

These settings are per identity.

![image](https://user-images.githubusercontent.com/14617699/52601205-0d3f2380-2e6f-11e9-9cef-93cb28197d81.png)

I have multiple identities with a separate folder for each. It will be very nice to have same functional in k9.

**Comment by jrd** [comment] 2019-02-21 08:06
In the same idea, I would like to choose the folder to save an outgoing message (per message) rather than to save it in the send folder

**Comment by cketti** [comment] 2019-03-08 03:04
Duplicate of #904

**Closed by cketti** 2019-03-08 03:04 UTC
