### ISSUE TITLE
Draft emails losing message contents randomly

### ISSUE THREAD

**Issue by GedMiller** [k9mail/k-9#3359] opened 2018-04-24 20:20 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by GedMiller** [comment] 2018-04-24 20:25
Create a new email. Type in lots of text in message body but with no recipient details.
Click on the save a draft option.
It closes the email and returns you to the folders.
You've now got less than 50% chance that when you reopen the draft email the message body is still there.

Using imap mailbox

**Comment by cketti** [comment] 2019-03-07 17:24
Duplicate of #2581

**Closed by cketti** 2019-03-07 17:24 UTC
