### ISSUE TITLE
TO, CC and BCC address fields user experience bad; no copy&paste; no paste of comma seperated emails

### ISSUE THREAD

**Issue by christianmenkens** [k9mail/k-9#2553] opened 2017-05-28 16:38 UTC
### Expected behavior

When I have one or many emails addresses in TO, CC or BCC I should be able to mark them and copy them and paste them to any other text field or other app.

When I have a text file with comma seperated email addresses, I should be able to copy this list from any text edit app and paste into TO, CC or BCC and emails should be parsed and accepted.

### Actual behavior

When I mark, copy and paste from TO, CC or BCC to any text field or other app only some commas get copied, not emails.

When I copy a list of comma seperated emails into TO, CC, BCC then it says email parsing error.

### Steps to reproduce
1. mark emails in TO, CC, BCC and copy
2. paste to any text field or any other app that accepts text

1. create a comma seperated list of emails in any text edit app
2. copy and paste to TO, CC or BCC

### Environment
K-9 Mail version: 5.206

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): does not make any difference, all of them

**Comment by 5t0rmr1d3r** [comment] 2017-11-17 09:45
I would also love to have that functionality!

**Comment by cketti** [comment] 2019-02-28 23:53
Duplicate of #1602

**Closed by cketti** 2019-02-28 23:53 UTC
