### ISSUE TITLE
Move message to folder in other email account

### ISSUE THREAD

**Issue by jroldroyd** [k9mail/k-9#2960] opened 2017-12-01 23:17 UTC
This is a feature request.

I'd like to be able to use the Refile/Move menu to move a message to a folder in another email account than the message is currently.

Right now, the Move menu only shows folders from the email's current account.   Would it be possible to add a General Setting to show all accounts' folders in the Move folder list, with some indication of each folder's account, perhaps the account's color code, to distinguish folders with the same names on different accounts?  Then to add code to support a move of messages in that way?

Thanks.

PS: If this is somehow already possible, I'm sorry that I failed to see how in both looking through the settings and in reading the docs!

**Comment by cketti** [comment] 2017-12-21 04:22
Duplicate of #760

**Closed by cketti** 2017-12-21 04:22 UTC
