### ISSUE TITLE
Have "Spam/Archive"-buttons in notification

### ISSUE THREAD

**Issue by amette** [k9mail/k-9#5778] opened 2021-11-17 17:41 UTC
Many e-mails can be immediately recognized as spam just by reading the Android notification. It is quite annoying to still have to open the mail and then tap twice more to put it into the spam folder.

There is a feature to show a delete button in the notification. I would suggest adding a similar feature for a spam button:

> global settings > notifications > show “Spam” button

Similar thing applies to an "Archive"-button. Some e-mails are just notifications that tell me everything in their subject. I would like to send them to archive right from the Android notification.

> global settings > notifications > show “Archive" button

**Comment by cketti** [comment] 2021-11-20 13:53
Duplicate of #3530

**Closed by cketti** 2021-11-20 13:53 UTC
Labels: enhancement
