### ISSUE TITLE
Old messages keep coming up as unread.

### ISSUE THREAD

**Issue by djreiswig** [k9mail/k-9#3641] opened 2018-10-03 14:25 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Once a message is marked as read it should stay that way.

### Actual behavior
Random messages show back up as unread.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
Latest update
Android version:
NDQ 26.69-64-9
Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by cketti** [comment] 2019-03-08 04:07
Duplicate of #1454

**Closed by cketti** 2019-03-08 04:07 UTC
