### ISSUE TITLE
Configure message actions visible in notification box

### ISSUE THREAD

**Issue by amiryal** [k9mail/k-9#1281] opened 2016-04-13 09:00 UTC
### Feature request
Currently, it’s possible to configure Visible message actions under Display settings, where my personal preference is to show only the Archive action.  Similarly, I would like to be able to configure the action inside new message notifications, and replace Mark read with Archive as well.

Thanks.

### Environment
K-9 Mail version: 5.008, F-Droid build

Android version: 6.0.1

Account type: IMAP

**Comment by cketti** [comment] 2016-04-13 10:29
Duplicate of #943

**Closed by cketti** 2016-04-13 10:29 UTC
