### ISSUE TITLE
New User Login(2 step Verification)

### ISSUE THREAD

**Issue by AshwinChandlapur** [k9mail/k-9#2362] opened 2017-03-08 18:33 UTC
With the raise of One time Password(OTP), 2 step Verification is a common thing that many users enable. But k9mail cannot be setup account if the user has enabled 2 step verification.

### Expected behavior
The app should help user login without much fuss.

Or

The app should inform user to check about 2 step verification. 

### Actual behavior
The app displays a Dialog Box saying:

Setup Could Not be finish.
Username or password incorrect.
(Command:*sensitive*;
response:#3#[NO,
[AUTHENTICATIONFAILED], Invalid 
credentials(Failure)])

### Steps to reproduce
1. Enable 2 step verification in your gmail account.
2. Try logging in through k9-Mail.

### Environment
K-9 Mail version:5.115

Android version:6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by philipwhiuk** [comment] 2017-03-08 19:45
Duplicate of #655

**Closed** 2017-03-08 19:45 UTC
