### ISSUE TITLE
'Unfortunately, chrome has stopped' every time I open this email

### ISSUE THREAD

**Issue by DanielHeath** [k9mail/k-9#674] opened 2015-06-08 23:37 UTC
App Version: 5.005
Chrome version: Samsung build, 42.0.2311.111

Raw email: https://gist.github.com/DanielHeath/b1ce95e25fa7b0aa5d8d
Every time I open this email I get the message "Unfortunately, Chrome has stopped"

The chrome logs indicate there's a `java.lang.SecurityException` in `readException:1472`, file `Parcel.java`.

Exception message is 'Unable to start activity ComponentInfo' ... ChromeLauncherActivity ... `Uid 10021 does not have permission to uri content://com.fsck.k9.attachmentprovider/<guid>/1415/RAW`

**Comment by cketti** [comment] 2015-06-10 02:19
I can't reproduce this. But I'm guessing it's because of the `<iframe>` element.

**Comment by philipwhiuk** [comment] 2016-03-30 19:54
It's trying to load the attachment content as the source of the iframe. `src=3D"cid:external_0"`

There's no way we'd want to support this at email open. We should be stripping iframes on privacy grounds at any rate. If it's crashing Chrome/WebView that would be a Chrome bug to my mind. Maybe it was fixed on @cketti's device?

**Closed** 2017-02-08 03:13 UTC
