### ISSUE TITLE
New IMAP Folder could not sync / download

### ISSUE THREAD

**Issue by magicWF** [k9mail/k-9#4370] opened 2019-12-13 20:26 UTC
Create outside of k-9 an IMAP folder and store emails. 
Refresh in k-9 the folder list.
Open the new folder, at start manually to load mails.

### Expected behavior
=> listen mails in this folder

### Actual behavior
nothing!  no mail are shown in this folder. With Tunderbird or Webmail I can see the mails, but k-9 show me no mails.  Also the text "load 25 more mail" is not shown.

### Steps to reproduce
1. Create outside of k-9 an IMAP folder
2. Refresh in k-9 the folder list
3. watch mails...

### Environment
K-9 Mail version: 5.701

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (Dovcote)

[k9-log.txt](https://github.com/k9mail/k-9/files/3962607/k9-log.txt)

I attached a logfile. The problem folder called "vz"

Best regards
Maik

**Comment by cketti** [comment] 2019-12-14 01:51
Try 5.702. We fixed a bug that could lead to the behavior you described.

**Comment by mruwek** [comment] 2019-12-14 13:49
@magicWF 
I've looked through the log and this looks definitely like a duplicate of #4364 (which is fixed in 5.702)

**Comment by cketti** [comment] 2019-12-14 13:56
Duplicate of #4364

**Closed by cketti** 2019-12-14 13:56 UTC

**Comment by magicWF** [comment] 2019-12-15 22:25
With the version 5.702 it seems to work. The problematic folders were synchronized without errors.
