### ISSUE TITLE
Feature request: Add email to contacts

### ISSUE THREAD

**Issue by KopiasCsaba** [k9mail/k-9#1365] opened 2016-05-09 15:41 UTC
Hello!

It would be good to have an easy to use feature that could add the email addresses in  To, Cc, From, etc headers to the contacts list.

It should search for an existing contact (to append the email for that), but give an option to make a new one with that address.

Thanks:)

**Comment by philipwhiuk** [comment] 2016-05-09 16:39
Duplicate of #1120

**Closed by philipwhiuk** 2016-05-09 16:39 UTC
