### ISSUE TITLE
Option to get transmission confirmation (DSN)

### ISSUE THREAD

**Issue by BuZZ-dEE** [k9mail/k-9#4220] opened 2019-10-15 11:51 UTC
Option to get transmission confirmation (DSN)
Please see for example the following user interfaces from Roundcube and Rainloop.

![roundcube](https://user-images.githubusercontent.com/125954/66829043-c8fea880-ef52-11e9-8db5-99ab1dd0e045.png)

![rainloop](https://user-images.githubusercontent.com/125954/66829055-cef48980-ef52-11e9-8ee7-930a6c52ad98.png)

**Comment by cketti** [comment] 2019-10-15 11:55
Duplicate of #3901

**Closed by cketti** 2019-10-15 11:55 UTC
