### ISSUE TITLE
Special tags like <![if mso]> are shown in a mail body

### ISSUE THREAD

**Issue by msvec** [k9mail/k-9#2948] opened 2017-11-23 09:52 UTC
### Expected behavior
Mail is shown without tags.

### Actual behavior
There are tags shown inside of the mail body, specifically <![if mso]> and <![endif]>.
I am not sure if they follow any standard, but otherwise mail clients apparently ignore them.
(I could bounce that mail if needed)

### Environment
K-9 Mail version:
5.208

Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Djfe** [comment] 2017-11-24 09:35
I'm seeing the same behaviour.

They are similar to the tags people use to add special code for IE9.

the comments are displayed as text and therefore break up the e-mail (looks ugly)

**Comment by philipwhiuk** [comment] 2017-11-27 03:24
Duplicate of #2148. Fixed in 5.300 and later.

**Closed by philipwhiuk** 2017-11-27 03:24 UTC
