### ISSUE TITLE
write debug logs to text file

### ISSUE THREAD

**Issue by gbjbaanb** [k9mail/k-9#4505] opened 2020-02-05 21:10 UTC
Its a real PITA to get debug logs to send to the K9 team, install adb etc.

When you think about what the logs are required, simply writing to a text file would be more than sufficient. So the app should stop using the system log provider and, if the debugging checkbox is checked, write logs to something much easier and simpler to find. 

if that's too hard due to permissions, then write the debug logs to memory and send it as a email, or store it internally and display it as an email that the user can then send.

**Comment by cketti** [comment] 2020-02-06 12:18
Duplicate of #1732

**Closed by cketti** 2020-02-06 12:18 UTC
