### ISSUE TITLE
Show both sender name and email address at the same time

### ISSUE THREAD

**Issue by cnmicha** [k9mail/k-9#6092] opened 2022-06-01 12:54 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

When clicking on an email to read it, I want to see from whom the email comes from.
Currently, it is only possible to either display the sender name (which can easily be faked) or the sender email address (which might be misleading without seeing the sender name).
Users can select which of these two options they want to see in the app settings.

### Suggested solution

I would welcome if both the sender name and the sender email address could be shown at the same time.
Proposed format "sender name <sender-mail-address@example.com>"

**Comment by cketti** [comment] 2022-06-01 12:58
Duplicate of #1119

**Closed as completed by cketti** 2022-06-01 12:58 UTC
Labels: type: enhancement
