### ISSUE TITLE
After importing accounts and settings  no mails can be received or sent

### ISSUE THREAD

**Issue by wolkenschieber** [k9mail/k-9#4203] opened 2019-09-26 10:47 UTC
When importing accounts and settings into an new K9 instance, no mails can be received or sent, if the mail server operates with self-signed certificates. The app doesn't report an error, but seems to do nothing. Some certificate warnings would be helpful.

I'm using K-9 Mail Version 5.600 (Fdroid) for both export and import.

**Comment by cketti** [comment] 2019-09-26 11:04
Duplicate of #3459

**Closed by cketti** 2019-09-26 11:04 UTC
