### ISSUE TITLE
Notification does not clear

### ISSUE THREAD

**Issue by kolchose80** [k9mail/k-9#4833] opened 2020-06-12 17:58 UTC
Let me say something about the small bug.
I would have it also in the version before 5.716.

Sometimes when I receive a email, and I extend the notification. There is a option (button right) "löschen" After I click on it the notification does not clear. After that when I click direct on the email  only it opens a white page (looks at a empty email)
For me looks like the email is deleted but the notification is not gone.

I hope you can understand my report.
My English is not the best.

It is my first report on GitHub.

### Environment
K-9 Mail version:5.716

Android version:9

Account type (IMAP, POP3, WebDAV/Exchange):imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2020-06-27 22:09
There's [a lot of issues](https://github.com/k9mail/k-9/milestone/13) with notifications. We'll make this a priority after the next stable version is released.

Closing this issue because it doesn't contain information on how to reproduce it. Chances are it's a duplicate of another issue anyway.

**Closed by cketti** 2020-06-27 22:09 UTC

**Comment by MisterY** [comment] 2021-01-17 10:16
Well, he kinda said that he taps "Delete" option in the notification. The email is deleted after the confirmation but the notification remains.
Anyways, I'm sure it's gonna get fixed once the focus is on notifications.
Cheers
