### ISSUE TITLE
Save As Draft no longer works properly as of latest update 5.600

### ISSUE THREAD

**Issue by HerborenInVlammen** [k9mail/k-9#3610] opened 2018-09-12 19:35 UTC
Save As Draft no longer works properly as of latest update 5.600.

Expected behavior:  You click 'Save as Draft" and K-9 saves your message in the draft folder.  It saves subject, and message body.

Actual behavior:  If the message body is more than a few words, NONE of the message body is saved; only the subject is saved.  The preview of the saved draft shows the message body, but opening the draft results in all the body being deleted.  Thus rendering Save As Draft useless.

This is a GO TO feature guys!  When it is broken K-9 is useless as a serious email client.  As a user who handles scores of emails a day, this needs attention yesterday!!

Confirmed on Lollipop (ASUS Zenfone 2), Nougat (Xiomi Redmi Note 4), and Oreo (Oneplus6)

**Comment by cketti** [comment] 2018-09-12 20:01
Duplicate of #3611

**Closed by cketti** 2018-09-12 20:01 UTC
