### ISSUE TITLE
Mail read/unread icon (envelope) indication inverted.

### ISSUE THREAD

**Issue by fuelflo** [k9mail/k-9#4387] opened 2019-12-17 16:14 UTC
### Expected behavior
When opening an unread email the mail status should change to 'read' and the envelope icon in the top navigation bar should change to 'open'. Then when trying to mark the message as unread by clicking on the envelope icon, the envelope should change to 'closed'

### Actual behavior
When opening an unread email, its status changes to 'read', but the envelope icon remains 'unread' (closed). When returning to to message folder or overview, the message is clearely marked as read but even when going back into the message, the envelope icon is still closed.

Now when marking the message as unread via the envelope icon, the message status correctly changes to unread, but the envelope icon opens!

### Steps to reproduce
1. open unread email
2. go back to inbox and check mail got marked as read
3. open the same (now read) email again
(step 2 & 3 are optional)
4. click on envelope icon
5. return to inbox and check read/unread status

### Environment
K-9 Mail version: 5.702

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: -

**Comment by violoncelloCH** [comment] 2019-12-17 16:22
I guess the envelope simply represents the action and not the actual state...

**Comment by cketti** [comment] 2019-12-17 16:37
All the icons in the toolbar represent actions. If you long-press the envelope icon you'll also see "Mark unread" or "Mark as read" depending on the current state of the message. That's the action that will be performed when you press the icon.

Closing this issue because it's working as intended.

**Comment by fuelflo** [comment] 2019-12-17 16:38
Was this different in versions <5.700 or why is this confusing the hell out of me?

The thing is, when clicking on it and the icon opens/closes it seems like a status indicator.
I've checked and in Gmail it actually has the same behavior as currently in k9 5.702. But the avoid confusion by automatically going back to the inbox when marking the mail as read from within the email.

**Closed by cketti** 2019-12-17 16:37 UTC

**Comment by cketti** [comment] 2019-12-17 16:40
The behavior hasn't changed from 5.600.
