### ISSUE TITLE
Make option to show full correspondent name and address

### ISSUE THREAD

**Issue by ghsrcgh** [k9mail/k-9#1429] opened 2016-06-05 01:02 UTC
### Expected behaviour

I need to see full information in "From: " field, like
From: Vasiliy Pupkin &lt;vasilek@pupkin.com&gt;
### Actual behaviour

There are only to ways to see:
1) If option "Show correspondent names" is enabled, you will see
From: Vasiliy Pupkin
2) If option "Show correspondent names" is disabled, you will see
From: vasilek@pupkin.com

But you will unable to see normal view with all information available:
From: Vasiliy Pupkin &lt;vasilek@pupkin.com&gt;
### Steps to reproduce
1. Just try to see any email message
### Environment

K-9 Mail version: 5.0.10

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment] 2019-02-28 20:07
Duplicate of #1119

**Closed by cketti** 2019-02-28 20:07 UTC
Labels: enhancement
