### ISSUE TITLE
With no email in outbox: Failed to send some messages. Negative SMTP reply 501 5.1.3 Bad recipient address syntax

### ISSUE THREAD

**Issue by eschamp** [k9mail/k-9#1286] opened 2016-04-14 23:23 UTC
Persistent error message

Failed to send some messages.
Negative SMTP reply 501 5.1.3 Bad recipient address syntax
### Environment

K-9 Mail version:5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Ex
[k9-log.txt](https://github.com/k9mail/k-9/files/220106/k9-log.txt)
change):Not sure which account has the problem so it could be POP3 or IMAP.

**Comment by philipwhiuk** [comment] 2016-04-14 23:54
There's a crash reported in the log but it's nothing to do with SMTP - it looks like the app crashed while updating the list of emails.... 

Still at a loss on this one. Looking at the code I can't see a way to get this error without having a bad email in an Outbox

**Comment by eschamp** [comment] 2016-04-15 00:10
Thanks for looking.

Well, the bad email is gone. Why do the error messages recur?

Anything I can do to stop them?

Philip wrote on 4/14/2016 7:55 PM:

**Comment by philipwhiuk** [comment] 2016-04-15 00:18
Yes, that's the puzzling thing. Because I've not found a way of doing it. What you can do to fix it is select the 'clear pending actions' option from tapping and holding on each account in the accounts page.

**Comment by eschamp** [comment] 2016-04-15 01:57
OK. Just did that. Will keep you posted.

**Comment by Demel75** [comment] 2016-04-23 02:59
k9-Mail version: 5.008
Device make: samsung
Device model: SM-T520
Android version: 5.1.1

com.fsck.k9.mail.MessagingException: Unable to send message
at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:539)
at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:495)
at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3563)
at com.fsck.k9.controller.MessagingController$20.run(MessagingController.java:3314)
at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
at java.lang.Thread.run(Thread.java:818)
Caused by: com.fsck.k9.mail.transport.SmtpTransport$NegativeSmtpReplyException: Negative SMTP reply: 501 5.1.3 Bad recipient address syntax
at com.fsck.k9.mail.transport.SmtpTransport.checkLine(SmtpTransport.java:649)
at com.fsck.k9.mail.transport.SmtpTransport.executeSimpleCommand(SmtpTransport.java:690)
at com.fsck.k9.mail.transport.SmtpTransport.executeSimpleCommand(SmtpTransport.java:654)
at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:524)
... 5 more


I think there's is a problem with german mutated vowel (äöü..) in Email-adress.

Other recipient without mutated vowel work fine.

**Comment by philipwhiuk** [comment] 2016-04-23 12:37
In this case you actually wrote an e-mail and your mail server rejected it. That's not a bug in K-9, it's a problem with your mail server.

In @eschamp's case, they claim to get the Exception without any e-mail being sent.

**Comment by eschamp** [comment] 2016-04-23 19:56
philipwhiuk, I don't understand "In @eschamp's case, they claim to get the Exception without any e-mail being sent."

Who is they? 

Error message was "Negative SMTP reply 501 5.1.3 Bad recipient address syntax" Still persists. Somehow, a message with "bad recipient address syntax" is still on my system. I've deleted the account that I believe is causing this, and then recreated it. Still getting the same error message.

**Comment by philipwhiuk** [comment] 2016-04-24 00:10
That was my point. Demel had an email in their outbox. You apparently do not. 

For your issue we still need a debug log.

**Comment by Demel75** [comment] 2016-04-24 03:43
Last question:

But why did it work with Thunderbird on a Desktop PC?

**Comment by eschamp** [comment] 2016-04-24 05:36
Philip wrote on 4/23/2016 8:10 PM:
>
> That was my point. Demel had an email in their outbox. You apparently
> do not.
>
> For your issue we still need a debug log.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/k9mail/k-9/issues/1286#issuecomment-213856618>
>

I believe I already posted one.

**Comment by mario-d-s** [comment] 2018-09-17 11:11
@eschamp, @Demel75 do either of you still have this issue? If not, maybe best to close this?

**Comment by cketti** [comment] 2019-02-28 19:20
Please create a new issue if this is still a problem.

**Closed by cketti** 2019-02-28 19:20 UTC
