### ISSUE TITLE
Pinch-out stopped working on K-9 probably at the last update.

### ISSUE THREAD

**Issue by 3chakko** [k9mail/k-9#2052] opened 2017-01-13 23:58 UTC
### Expected behavior
Mail should expand on pinch-out

### Actual behavior
Nothing happens. Or it moves recognizing the pinch-out as just a swipe.

### Steps to reproduce
1. Open an e-mail
2. Pinch it out.
3. Nothing happens.

### Environment
K-9 Mail version: 5.202

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): Either with IMAP or POP3

**Comment by philipwhiuk** [comment] 2017-01-14 01:20
Please search before raising a new issue. This will be fixed in the next release.

Duplicate of #1908, #1886, #2020, #2029, #2042, etc

**Closed by philipwhiuk** 2017-01-14 01:20 UTC
