### ISSUE TITLE
Can't MOVE messages across email accounts

### ISSUE THREAD

**Issue by kejriwals** [k9mail/k-9#1313] opened 2016-04-20 14:48 UTC
### Expected behaviour
First, congrats for the brilliant App! I have multiple IMAP accounts. Often there is a need to move emails to folders in some other email account. This is a standard feature in Samsung's native email app, Apple's IOS email app, and all desktop email clients. 

### Actual behaviour
Your app does not allow me to Move emails to other accounts. The Move feature is restricted to the folders within the same IMAP account where the incoming message originally lands. 

### Steps to reproduce
1. Create two IMAP accounts. 
2. Try to MOVE email from inbox of one account into the inbox of other account. 

### Environment
K-9 Mail version: 5.010

Android version: Lollipop

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2016-04-20 15:19
Duplicate of #760

**Closed by cketti** 2016-04-20 15:19 UTC
