### ISSUE TITLE
Feature request: show e-mail address next to contact name when viewing sent emails

### ISSUE THREAD

**Issue by giovi321** [k9mail/k-9#2257] opened 2017-02-18 11:24 UTC
When viewing sent emails, in the "To:" line is showed only the name of the contact but not the email address. It makes it difficult to understand to which email address the email has been sent.

**Comment by karishnu** [comment] 2017-03-02 07:03
Can I work on this?

**Comment by cketti** [comment] 2017-03-02 10:39
This is something that should be done during the design overhaul. Adding the functionality now will most likely only clutter the existing UI even more.

**Comment by duncan-SF** [comment] 2017-05-12 21:13
This behavior is a step backwards from the behavior of K-9 version 5.010, which showed the address only and omitted the "real name" field configured in the Identity or arriving from the sender.

I really dislike the new contact card thing, which now shows neither the address nor the name from the From line but instead the name under which I've filed the person in my contacts list.  

I hope to see a return to something like RFC822 in the displayed format on the address lines.

**Comment by Meteor0id** [comment] 2018-05-12 13:25
Very similar to and possibly duplicate of: https://github.com/k9mail/k-9/issues/1119

**Comment by cketti** [comment] 2018-05-12 15:34
Duplicate of #1119

**Closed by cketti** 2018-05-12 15:34 UTC
