### ISSUE TITLE
Long URL on mobile phone screens

### ISSUE THREAD

**Issue by xuhdev** [k9mail/k-9#3658] opened 2018-10-12 05:48 UTC
(This issue can be important for many users since some email servers, such as institutional servers, have set up URL filters to encode all normal URLs into very long URLs with fraud/virus detectors.)

### Expected behavior

When there is a long URL in a mail, the long URL should either break or be truncated such that the user can slide to the right to read the full URL.

### Actual behavior

The whole message was zoomed out to fit long URLs within the screen width. This makes the whole text look tiny.

### Steps to reproduce
Open a message with a long URL.

### Environment
K-9 Mail version: 5.600

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2019-03-08 04:15
Duplicate of #3172

**Closed by cketti** 2019-03-08 04:15 UTC
