### ISSUE TITLE
[Feature Request] Allow to edit the from field

### ISSUE THREAD

**Issue by robsdedude** [k9mail/k-9#3436] opened 2018-06-10 07:44 UTC
I know, that I can add identities. But I'd like to be able to edit the `from` address right on the fly. The reason is that I own a domain an I use unique mail addresses for all kind of stuff (so I have many > 100). Adding all these identities would make the list explode an basically unusable (it would also take way too much time to add all of them).
I know this behavior from Thunderbird an it's really helpful.

**Comment by cketti** [comment] 2019-03-08 02:39
Duplicate of #935

**Closed by cketti** 2019-03-08 02:39 UTC

**Comment by pjvleeuwen** [comment] 2019-08-28 18:53
@cketti Please reconsider closing this feature request.

This feature request is simple and gives precisely what I (really really really) would like to have in my Android mail client. Feature request #935 is a big grab bag of related features. Many contributors seem to agree that they want _something_ but seem to have different idea's on what they want precisely.

Most notably not in scope of this feature request are:
* the whole automatic selection of identities (and the associated discussion about which headers to base this on)
* the discussion whether it should be possible to distinguish between Sender and From
* the suggestion to automatically select different SMTP servers

I expect that this scope creep is the exact reason that #935 is dragging on for years without resulting in an actual feature for end users. So please somebody reopen this feature request and somebody please consider implementing it. I believe there are many users that would appreciate being able to use this.
