### ISSUE TITLE
Synch off with my new Galaxy S10 plus

### ISSUE THREAD

**Issue by pipodug** [k9mail/k-9#4087] opened 2019-06-19 15:28 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Synch every 5 minutes.

### Actual behavior
With my new galaxy S10 plus, I have a sync problem with k9 mail.
I configured it exactly like my old galaxy S8 but I have a message "sync off".
I have the parameter "synchronization in the background" on "always".
Sometimes, when I go from a wifi network to a 4g network, I find sync every 5 minutes as before, but after a while, I have "sync down again" and I have to retrieve the mails manually.
I did not have this problem with the S8.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.6

Android version: 9

4 POP account
1 IMAP account

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2019-06-29 16:11
Duplicate of #3950

**Closed by cketti** 2019-06-29 16:11 UTC
