### ISSUE TITLE
Extreme lag and "Not responding" in unified inbox with thousands of messages

### ISSUE THREAD

**Issue by IAMtheIAM** [k9mail/k-9#3979] opened 2019-03-21 17:58 UTC
### Expected behavior
Smooth infinite scrolling, immediately opens tapped messages

### Actual behavior
Lags, stutters, "not responding" prompt appears repeatedly when opening app, scrolling, or viewing any messages

### Steps to reproduce
1. Set up 5 accounts with thousands of message in history each
2. Set fetch to "all mail" with "any size" for limit
3. Sync all messages
4. Try to use the app once they are all synced.

### Environment
K-9 Mail version:
5.600
Android version:
9.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
All IMAP

I have about 24,000 messages in my unified inbox. The app barely works. It worked fine when I set it to "25" fetch limit foe each account, but if I want all my emails, it is unusable.

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2019-10-12 17:44
Duplicate of #3472

**Closed by cketti** 2019-10-12 17:44 UTC
