### ISSUE TITLE
Bad UI when No Mails found with Search Query - No option to Edit Query and Re-Search for Mails.

### ISSUE THREAD

**Issue by meghalagrawal** [k9mail/k-9#2385] opened 2017-03-12 23:42 UTC
### Expected behavior
1.While searching for a query to find an Email if we are not getting any results then we should show user that No Results found with this query and at the same we should provide them an option to edit the query and re-search for mail.

2.Suppose a user accidently put a wrong spelling then they should have an option to edit the query in the same page and Re-Search.

### Actual behavior

![whatsapp image 2017-03-13 at 05 08 08 1](https://cloud.githubusercontent.com/assets/18400951/23837262/67b31264-07ab-11e7-93fb-a65dccd74cdc.jpeg)
![whatsapp image 2017-03-13 at 05 08 08](https://cloud.githubusercontent.com/assets/18400951/23837261/67b0a826-07ab-11e7-80f6-476dc960336c.jpeg)

While search if we are not getting any result then we are showing an Empty Page and user only have an option of going back and then selecting Search option again to search for a query with correct Spelling or so.

It involves 3 Steps for Re-Searching -

1. Go back to mail list .
2. Select Search Again
3. Type Query and Search

This can be reduced to a single step - 

Just edit query and Re-Search on Same Fragment.

### Steps to reproduce
1.We Should give Edit text in the Top of Search Fragment to Edit Query or Re-Search if No Results Found.
2.We should show to user via a Png or just text that No Results found for your Query "TestQuery".

### Environment
K-9 Mail version:
5.203

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
All

**Comment by cketti** [comment] 2017-03-12 23:48
Duplicate of #1980

**Closed by cketti** 2017-03-12 23:48 UTC

**Comment by meghalagrawal** [comment] 2017-03-12 23:52
I am sorry.

I want to work on this.

Can you please assign this issue to me?
