### ISSUE TITLE
App no longer goes to Inbox after phone notification

### ISSUE THREAD

**Issue by roccol5** [k9mail/k-9#1946] opened 2017-01-03 20:27 UTC
### Expected behavior
After your phone notifies you that you have new mail you tap the notification and it goes to the Inbox so you can read your new messages.

### Actual behavior
After your phone notifies you that you have new mail you tap the notification and it goes to the folder list.  You then have to tap on the Inbox to read your new messages.

### Steps to reproduce
1. Wait for a new mail notification.
2. Tap the notification.
3. Observe the app go to the folder list instead of the Inbox.

### Environment
K-9 Mail version:
5.201
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
POP3 and IMAP

**Comment by cketti** [comment] 2017-01-03 20:30
We're tracking this under #1885. What do you think opening another duplicate of this issue will accomplish?

On a side note: every issue you open takes away from the time we have to fix bugs.

**Closed by cketti** 2017-01-03 20:30 UTC

**Comment by roccol5** [comment] 2017-01-04 14:20
I added this again because about 2 minutes after I saved the original issue it was gone from the issue list so I thought that the original did not save.  My apologies.  Also, how do I see issue that were removed from the list (presumably because they were closed?).  Thanks.

**Comment by ArchangeGabriel** [comment] 2017-01-04 14:31
Go to bottom of the issue list. Realise they are pages. Go to next page. Find the issue. ;)

Or use search, sort by most recently updated…

**Comment by cketti** [comment] 2017-01-04 18:30
Click the "X Closed" link or manually remove the "is:open" from the filter.

**Comment by roccol5** [comment] 2017-01-04 21:00
Thank you.
