### ISSUE TITLE
Bug since 5.200: New mail opens in folder view, not inbox

### ISSUE THREAD

**Issue by jmlobert** [k9mail/k-9#2027] opened 2017-01-10 16:49 UTC
### Expected behavior
Following a new mail notification, the app used to go straight to the inbox and show all messages. 

### Actual behavior
Since the latest update, the app opens the folder list and forces me to tap on the inbox to go there. One unnecessary tap and I can't find any options for that behavior

### Steps to reproduce
1. Get new mail
2. Follow the new mail notification
3. App opens in folder view, not inbox
This is almost consistent, not 100%. I tried to make sure to leave the app in Inbox view to be remembered, but to no avail.

### Environment
K-9 Mail version: 5.200

Android version:
6.0.1, Google Nexus 5

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by Valodim** [comment] 2017-01-10 17:12
Duplicate of #1885. Please check if issues already exist before opening new ones.

**Closed by Valodim** 2017-01-10 17:12 UTC
