### ISSUE TITLE
Replying to an encrypted Mail quotes the encrypted Mail still encrypted

### ISSUE THREAD

**Issue by Olf0** [k9mail/k-9#994] opened 2016-01-06 00:42 UTC
This was tested with K9-Mail v5.007 under AlienDalvik / AOSP 4.1.2:

Replying to an encrypted Mail quotes the encrypted Mail still encrypted.

I always wondered why K9-Mail only offers the menu entry "Reply" in the mail list view inside a folder, but not when viewing an individual email.   This does not really matter (it is merely an inconvenience), as long as the intent is to reply to an unencrypted email.  But for encrypted emails that results in the email's content being quoted encrypted, effectively rendering replies to encrypted emails useless.  
Or is this just either an oversight by me or the fact, that I run K9-Mail in SailfishOS's AlienDalvik (based on AOSP 4.1.2)?

Kudos for your excellent work,
Olf0

**Comment by dschuermann** [comment] 2016-01-06 00:47
duplicate of https://github.com/k9mail/k-9/issues/663

**Closed by dschuermann** 2016-01-06 00:47 UTC
