### ISSUE TITLE
Showing unread message count

### ISSUE THREAD

**Issue by duracher** [k9mail/k-9#4831] opened 2020-06-10 06:50 UTC
I have multiple e Mail accounts. 
There is no way, to get an overview of the unread messages, i dont want to use the cumulated (?) mail entry
### Expected behavior (gemeinsamer Posteingang)

Tell us what should happen

### Actual behavior
Mostly i would like an overview of the mail accounts similar to the old version. An other option would be, if the count of unread messages is shown in the account drop down list

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version: du 10

Account type (IMAP, POP3, WebDAV/Exchange): imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2020-06-10 11:41
Duplicate of #4515

**Closed by cketti** 2020-06-10 11:41 UTC
