### ISSUE TITLE
Can't send mail: RuntimeException: Nope

### ISSUE THREAD

**Issue by iloveeclipse** [k9mail/k-9#1218] opened 2016-03-26 16:14 UTC
### Expected behaviour
Tell us what should happen
Create Mail and send
### Actual behaviour
Tell us what happens instead
RuntimeException: Nope message shown in the system status line
### Steps to reproduce
1. Use Alpha 5.108 built from https://github.com/k9mail/k-9/commit/b586522ca11b190717c24e4abea2583be7ff9043
2. On 5.1.1 Android, try to send mail using gmx.de IMAP account. 

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment] 2016-03-26 16:15
Please provide the stack trace. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by iloveeclipse** [comment] 2016-03-26 16:41
I have no plans to use adb and I also have not rooted my device, so I see no way to access the logs.

But why so complicated? I wonder if K9 could automatically store stack traces from errors as mails to the dedicated mail folder. The only thing one would need is to send that mails / copy/paste to the big report.

**Comment by njeyaakili** [comment] 2016-03-26 17:22
As .108 is being used, this looks like the bug I reported in #1206.

You can get a log of the type I posted by turning on debugging, as indicated in the document that cketti referenced, trigger the error, and then look at your "K9mail-errors" folder.

**Comment by gunterkoenigsmann** [comment] 2016-03-30 10:38
[k9-log.txt](https://github.com/k9mail/k-9/files/195314/k9-log.txt)

**Comment by gunterkoenigsmann** [comment] 2016-03-30 10:43
Seems like the current alpha-release solves issue #814 and possibly #783, too. So as soon as this bug is fixed I am completely happy with K9 again. Keep up your good work!

**Comment by philipwhiuk** [comment] 2016-03-30 10:44
Closing. Duplicate of #1026 as suggested.

**Closed by philipwhiuk** 2016-03-30 10:44 UTC
