### ISSUE TITLE
Icon for read/unread is reversed

### ISSUE THREAD

**Issue by J-J-Chiarella** [k9mail/k-9#5949] opened 2022-03-07 21:36 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

Android 11 (Samsung One Core UI version)

### Device model

SM-A015M

### Steps to reproduce

1. Click on a mail message.

### Expected behavior

1. Click on a mail message.
2. Look at the envelope icon near the top.
3. Notice that the letter envelope icon is opened when read, and when you set the message to be unread (because you don't have time to read it all now and wish to leave it unread to remind yourself that you haven't read it all yet) the letter will become envelope is sealed and unopened to show that the message is "unread." This is because in real life an unopened envelope with the letter still inside and the seal unbroken is an indication that you have not yet read the contents of that piece of mail.

### Actual behavior

1. Click on a mail message.
2. Look at the envelope icon near the top.
3. Notice that the letter envelope icon is opened when unread and the letter envelope is sealed and unopened when the message is read, which is the reverse of what one expects.

**Comment by cketti** [comment] 2022-03-07 21:48
Duplicate of #5142

**Closed by cketti** 2022-03-07 21:48 UTC
Labels: bug

**Comment by J-J-Chiarella** [comment] 2022-03-07 21:50
Ah, that bug title made me think it was about some updating feature to do with synchronization or IMAP or something. I see how it's related now.
