### ISSUE TITLE
K9 does not reject expired SSL certs / warnings could be more user-friendly.

### ISSUE THREAD

**Issue by vext01** [k9mail/k-9#2467] opened 2017-03-30 20:58 UTC
Hi,

I think k9 is failing to reject expired (self-signed) SSL certificates, **and/or** the warnings have not been clear enough. 

I noticed this when I installed claws-mail on my laptop:

![ssl](https://cloud.githubusercontent.com/assets/604955/24524465/8605edae-158e-11e7-9408-7af770c844cf.png)

At first I didn't believe what I was seeing, as `mbsync` (an IMAP synchroniser I am using) was not complaining, but then I went to the server:

```
$ openssl x509 -text -in dovecotcert.pem -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: XXX
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=XXX, ST=XXX, L=XXX, O=XXX, OU=IMAP server, CN=XXX/emailAddress=XXX
        Validity
            Not Before: Dec 27 00:42:30 2014 GMT
            Not After : Dec 26 00:42:30 2016 GMT
...
```

It has indeed expired! (so we have a side issue for `mbsync` here too, I'll be raising a bug)

I don't recall ever seeing K9 warn me that the certificate has expired. 

I've just deleted the account from K9 and re-added it. This is what I see:

![k9](https://cloud.githubusercontent.com/assets/604955/24525213/642927f2-1591-11e7-8b90-618aec41130a.png)

There's a subtle issue here. I expect to see a warning about the certificate being invalid due to it being self signed. People self sign all the time, and it's generally OK as long as you check the fingerprint matches. However, if the certificate is expired, that's another arguably more severe matter. I wonder if K9 should make a distinction.

A question I can't yet answer is: what happens if the user initially sets up an IMAP account, accepts a self-signed but current (unexpired) SSL cert, then later the cert expires. This must have happened to me at some point, yet I don't recall K9 warning me (that's not to say it didn't but perhaps it wasn't explicit enough)? Does it just accept a cert forever more?

### Expected behavior

When making an account:

 * Explicitly warn the user if the signer is invalid.
 * Give a separate explicit error message if the certificate has expired.
 * If the user dismisses the warning that the cert is expired, warn again later (say once a day)? Maybe too extreme?

After setting up an account:

 * Warn explicitly when a previously accepted certificate expires (sorry if it turns out K9 does do this, but I missed the warning. Arguably, if I missed it, it wasn't clear enough)

### Environment
K-9 Mail version: 5.206

Android version:66.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

The server side is dovecot.

Thanks

**Comment by philipwhiuk** [comment] 2017-03-30 21:41
Most of this is a duplicate of #893 / #1789 and hopefully covered in #1818 but it was worth raising to make sure we consider the expired case. I agree we should probably warn independently for self-sign vs expired.

Of course if we opt for #2361 it becomes a moot point.

**Closed by philipwhiuk** 2017-03-30 21:41 UTC

**Comment by vext01** [comment] 2017-03-30 21:53
Thanks, glad it's being thought about.
