### ISSUE TITLE
Client bandwidth usage suddenly surged to hundreds of MBs for no apparent reason

### ISSUE THREAD

**Issue by vladsl** [k9mail/k-9#1217] opened 2016-03-26 12:04 UTC
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Steps to reproduce

1.
2.
3.
### Environment

K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by vladsl** [comment] 2016-03-26 12:08
Using IMAP accounts, Android version 5.1 
K9 5.008

**Comment by vladsl** [comment] 2016-03-26 12:12
And I meant data usage

**Comment by philipwhiuk** [comment] 2016-03-26 12:54
Please edit your original post to provide some details. Otherwise we may as well just close this as there's absolutely nothing to go on. Are you downloading entire emails by default - is there a massive on in your inbox?

**Comment by vladsl** [comment] 2016-03-26 22:14
I noticed under mobile data applications usage that k9 used over 4gb of mobile data in just one day. Nothing even remotly large are in my inboxes so I assume app went into ensless data loop. At this point I diasabled background data. I can provide logs if you tell me how

**Comment by amennini** [comment] 2016-03-29 09:04
Me too.
I'm using K-9 5.008 with two accounts: one is pop3, one is imap.

If I configure only the pop3 one all seems ok.

If I try to configure the imap one, K-9 usually crashes. If I can configure it, then data usage skyrockets and kill my monthly platfond.

BTW, I've been using K-9 from three years with the same accounts without any problem.
POP3 is configured on port 110 in input
IMAP is configured on port 143 with no security.

What can we do to stop this mess?

**Comment by philipwhiuk** [comment] 2016-03-29 09:16
If it crashes we should have PlayStore crash reports. Debug logs might be useful, as would account settings like push vs polling and polling frequency and whether the phone is running CM or something.

**Comment by amennini** [comment] 2016-03-29 10:35
I have sent a crash report via play store right now. The phone told me K-9 has crashed and gave m e two choiches: ok or report. I did the second one

**Comment by philipwhiuk** [comment] 2016-03-29 10:39
I think @cketti is the only person who can see those so we shall have to wait for his feedback.

**Comment by cketti** [comment] 2016-03-29 14:12
It's almost impossible to find individual crash reports in the Google Play Developer Console. Anyway, a crash is different from high bandwidth usage. Let's try to keep issues on track and create new issues for separate problems.

@vladsl A debug log might help diagnose the problem. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by amennini** [comment] 2016-03-31 10:44
Hi. @cketti I've reproduced the crash. Here is the log
[k9-log.txt](https://github.com/k9mail/k-9/files/197434/k9-log.txt)

**Comment by philipwhiuk** [comment] 2016-03-31 11:08
I've opened separate issues for the issues in the log that we don't handle - #1240 , #1241
Please keep this one about data usage.

**Comment by cketti** [comment] 2019-02-28 19:06
Closed due to age. Please create a new issue with a recent debug log if this is still a problem.

**Closed by cketti** 2019-02-28 19:06 UTC
Labels: needs info, performance
