### ISSUE TITLE
Notifications: content inconsistent (locked vs. unlocked)

### ISSUE THREAD

**Issue by dennisguse** [k9mail/k-9#2514] opened 2017-04-27 21:18 UTC
My setting for  "Lock Screen Notifications" used to be "Same as when screen unlocked".

### Expected behavior
Show a notification presenting sender, subjects, and content of incoming mails.
The notification should be the SAMe independent if screen is
A) locked or
B) unlocked.

### Actual behavior
Depending on the current state (locked vs. unlocked), the notification _is different_.
In addition, it remains unchanged if unlocking the locked device or vice versa.
A) locked: "Content hidden"
B) unlocked: preview of the actual e-Mail.

Case A) is unexpected.
In addition, if A) happened (content hidden) and the screen is unlocked, a newly incoming mail leads to a change of the notification presenting a preview of the content.
Locking the device will then show "XXX new messages.

### Steps to reproduce
1. Lock screen
2. Receive e-Mail (notification: "content hidden")
3. Unlock 
-> notification still "content hidden"

### Environment
K-9 Mail version: 5.207 (Fdroid)

Android version: Lineageos 14.1-20170413

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2017-04-29 11:13
There's a setting that controls this I think.

Settings -> Global -> Privacy -> Show subject

I'm not quite sure why it's still hidden after unlocking - that seems like a bug but it could be an issue with LineageOS.

**Comment by dennisguse** [comment] 2017-04-29 20:10
_IMPORTANT:_ My Android is configured to "Android Settings -> Configure Notifications -> On the lock screen: hide sensitive content on lock".

Just tested it and you are right.
Thanks for pointing me to this setting!
It is producing the behavior that was confusing me.

Seemingly K9Mails "Settings -> Global -> Privacy -> Show subject"  TO When device is locked", decides on creation of a notification if the subject should be shown.
If locked: no
If unlocked: yes
Thus, changing the lock state does not change the notification anymore - this is kind of unexpected to me.
Additionally (I think), the created notification is _not flagged to contain sensitive information_.
Therefore, the Android lock screens shows the actual content (depending on the lock state it was created) of the notification instead of "Content hidden".

So,  it is not a bug - just too complex settings for me ;)
Thanks again!

**Comment by philipwhiuk** [comment] 2017-05-04 15:39
The settings organisation is going to change due to the design project anyway. Closing this as, for now, it works as intended.

**Closed by philipwhiuk** 2017-05-04 15:39 UTC
