### ISSUE TITLE
K-9 Mail is crashing upon launch on Android 10

### ISSUE THREAD

**Issue by a1exus** [k9mail/k-9#4122] opened 2019-07-23 20:57 UTC
### Expected behavior
not crash?

### Actual behavior
crash (I don't even see anything)

### Steps to reproduce
1. on Android 10, start app
2. start again
3. start again...

### Environment
K-9 Mail version: 5.600

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by njeyaakili** [comment] 2019-07-23 21:09
This was happening to me on an Essential ph-1 with 10-beta3. 

I looked for permission issues but didn't see anything.

I ended up removing and reinstalling K-9 and it has worked since (currently at 10-beta5).

**Comment by cketti** [comment] 2019-08-03 20:25
Duplicate of #4042

**Closed by cketti** 2019-08-03 20:25 UTC
