### ISSUE TITLE
Email subject is not encrypted

### ISSUE THREAD

**Issue by zekooooo** [k9mail/k-9#3913] opened 2019-02-11 14:39 UTC
### Expected behavior
The subject should be replaced with a placeholder text, which is replaced by the real subject upon decryption. For example, Thunderbird replaces the subject with "Encrypted Message" (unlike Thunderbird and KMail, K9 doesn't replace it with the real subject upon decryption, but that's a matter for another issue).

### Actual behavior
The subject is sent in plaintext.

### Steps to reproduce
Send a new PGP encrypted mail from K9. Send an email from Thunderbird+Enigmail/pEp for Windows for comparison.

### Environment
K-9 Mail version: 5.600 (latest on F-Droid)

OpenKeychain 5.2 (also latest on F-Droid)

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: Sorry, I don't connect my phone to my Windows PC for security reasons.

**Comment by philipwhiuk** [comment] 2019-02-22 15:00
Duplicate of #2277

**Closed by philipwhiuk** 2019-02-22 15:00 UTC
