### ISSUE TITLE
Change resolution of attached images

### ISSUE THREAD

**Issue by muessjoeh** [k9mail/k-9#4782] opened 2020-05-25 16:26 UTC
When an image is attached, there is no way to set or change its resolution.

### Expected behavior

When an image is attached, there should be a simple way to set or change its resolution.

### Environment
K-9 Mail version:
5.600

Android version:
10

**Comment by cketti** [comment] 2020-05-25 16:27
Duplicate of #1758

**Closed by cketti** 2020-05-25 16:27 UTC

**Comment by francwalter** [comment] 2020-06-04 10:38
> When an image is attached, there should be a simple way to set or change its resolution.

Have a look to #3845 where there is [a k9 version](https://github.com/bebbo/k-9/releases/download/image-resize-bp/) with image resize implemented, it is a 5.600 version, stable and even still with the push feature not disabled.
I used it a while, but switched to FairEmail, where the image resize is available too (among many other features).
