### ISSUE TITLE
App crashed by typing address in the address field when composing a message

### ISSUE THREAD

**Issue by dingolino** [k9mail/k-9#1253] opened 2016-04-03 14:06 UTC
### Expected behaviour
Creating new email or answer to an email. Normaly I can look for my contacts by typing the letter one by one to find the desierd contact

### Actual behaviour
in 5.108 K9 is crashing every time I am typing the 2nd letter. Let´s assume i am looking for a contact namend "Claus"
I type "c" than I type "l" and K9 is crashing
If the name is "Hugo"
I type "h" than I type "u" and K9 is crashing.

To overcome this problem I have uninstalled 5.108 and reinstalled it but no change.
Went back to 5.107 and it is working.

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.108

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (web.de and gmail)

**Comment by philipwhiuk** [comment] 2016-04-03 14:17
What keyboard are you using? Were you given the option of sending a crash report?

**Comment by dingolino** [comment] 2016-04-03 17:22
I am using the Swype Keyboard
And I had no chance to send a crash report

**Comment by dingolino** [comment] 2016-04-03 17:27
Hi

I am using the Swype Keyboard.

I had no chance to send a crash report.

K9 was not closing completely just closes the new e-mail and than I was back in the inbox or the folder I was starting from

Best regards
Claus



Am 3. April 2016 16:18:08 MESZ, schrieb Philip <notifications@github.com>:
>What keyboard are you using? Were you given the option of sending a
>crash report?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1253#issuecomment-204984541

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by philipwhiuk** [comment] 2016-04-03 17:30
Hmm. Can you try enabling debug logging in the preferences and then provide the contents of any new "e-mail" created in the K9mail-errors folder after trying again?

I downloaded the trial Swype keyboard and it seems to work fine on my device (but it's a later OS and different device).

**Comment by dingolino** [comment] 2016-04-03 17:35
Ok, I will give it a try

I can also use a different keyboard just to see.

Best regards
Claus

Am 3. April 2016 19:30:50 MESZ, schrieb Philip <notifications@github.com>:
>Hmm. Can you try enabling debug logging in the preferences and then
>provide the contents of any new "e-mail" created in the K9mail-errors
>folder after trying again?
>
>I downloaded the trial Swype keyboard and it seems to work fine on my
>device (but it's a later OS and different device).
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1253#issuecomment-205018262

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by dingolino** [comment] 2016-04-03 18:12
Hi,

I have now updated - again to 5.108.

Guess what?

No crash when typing a contact.

Problem is that the contacts are now in a inverted type and the bar is white
and the letter are grey (not black), so it is not easy to read 

But now I cannot send emails at all.

I have now a number of error meassages in the k9 error folder but how can I
get those over to you?

Best regards,

Claus




Am 03.04.2016 um 19:30 schrieb Philip <notifications@github.com>: 
Hmm. Can you try enabling debug logging in the preferences and then provide
the contents of any new "e-mail" created in the K9mail-errors folder after
trying again?
I downloaded the trial Swype keyboard and it seems to work fine on my device
(but it's a later OS and different device).

**Comment by philipwhiuk** [comment] 2016-04-03 18:14
Either paste them here / a GitHub gist / http://pastie.org/

**Comment by dingolino** [comment] 2016-04-03 18:18
copied 2 error messages 




K9-Mail version: 5.108
Device make: samsung
Device model: SM-N910F
Android version: 4.4.4

java.lang.Exception: Message count 0 for folder Entwürfe
at
com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:931)
at
com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:99)
at
com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:754)
at
com.fsck.k9.controller.MessagingController.run(MessagingController.java:257)
at java.lang.Thread.run(Thread.java:841)



K9-Mail version: 5.108
Device make: samsung
Device model: SM-N910F
Android version: 4.4.4

javax.net.ssl.SSLException: Read error: ssl=0x7aeb5db0: I/O error during
system call, Connection timed out
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at
com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:746)
at java.io.InputStream.read(InputStream.java:162)
at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
at
com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
at
com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:38)
at
com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:30)
at
com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:88)
at
com.fsck.k9.mail.store.imap.ImapConnection.readStatusResponse(ImapConnection.java:626)
at
com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.sendIdle(ImapFolderPusher.java:294)
at
com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:187)
at java.lang.Thread.run(Thread.java:841)





Am 03.04.2016 um 19:30 schrieb Philip <notifications@github.com>: 
Hmm. Can you try enabling debug logging in the preferences and then provide
the contents of any new "e-mail" created in the K9mail-errors folder after
trying again?
I downloaded the trial Swype keyboard and it seems to work fine on my device
(but it's a later OS and different device).

**Comment by philipwhiuk** [comment] 2016-04-03 18:22
Ok neither of those are related. Looks like we aren't going to get a stacktrace for this.

I might try and see if I can reproduce it on an emulator...

**Comment by dingolino** [comment] 2016-04-03 18:25
Related to what?

to the not sending problem?

or

to the crash while typing the 2nd letter of a contact?

Is there anything I can do further?

If not I would switch back to 5.107

Best regards,

Claus





Am 03.04.2016 um 20:23 schrieb Philip <notifications@github.com>: 
Ok neither of those are related. Looks like we aren't going to get a
stacktrace for this.
I might try and see if I can reproduce it on an emulator...

**Comment by dingolino** [comment] 2016-04-03 18:26
by the way:

I can receive the email you are sending with my Note





Am 03.04.2016 um 20:23 schrieb Philip <notifications@github.com>: 
Ok neither of those are related. Looks like we aren't going to get a
stacktrace for this.
I might try and see if I can reproduce it on an emulator...

**Comment by philipwhiuk** [comment] 2016-04-03 18:27
To either - the first is #1174 , the second is a simple network error while trying to connect for push e-mail.

**Comment by dingolino** [comment] 2016-04-03 18:29
ok,

could I do something against the simple network error?   ;-)

It came after updating from 5.107 to 5.108







Am 03.04.2016 um 20:27 schrieb Philip <notifications@github.com>: 
To either - the first is #1174 , the second is a simple network error while
trying to connect for push e-mail.

**Comment by philipwhiuk** [comment] 2016-04-03 18:38
The network error just says the connection timed out. Can you create a separate issue for this - assuming you can get the e-mail on another device. I'm going to close this one as we have two open ( #1251 ) for the same thing

**Closed by philipwhiuk** 2016-04-03 18:38 UTC

**Comment by wweich** [comment] 2016-05-08 08:40
I have the same error. When typing a second character in the recipient field, I get `"K-9 Mail" was closed` with no option to send crash log.
K-9 Mail 5.108 on Android 6.0.1 on Moto X Style.

**Comment by philipwhiuk** [comment] 2016-05-08 12:28
See #1251 wweich
