### ISSUE TITLE
Answer button in landscape view

### ISSUE THREAD

**Issue by rudisten1** [k9mail/k-9#4226] opened 2019-10-23 06:06 UTC
### Expected behavior
I shoukd see the answer button in landscape mode (top or bottom)

### Actual behavior
The answer command is somewhere under a third level menu

### Steps to reproduce
1. Try to answer to email in landscape mode on a smartphone with 5.5 inch screen or less
2.
3.

### Environment
K-9 Mail version:
5.600
Android version:
7.01

Account type (IMAP, POP3, WebDAV/Exchange):
Imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2019-10-23 11:52
Duplicate of #727

**Closed by cketti** 2019-10-23 11:52 UTC

**Comment by rudisten1** [comment] 2019-10-23 18:21
So? Still a bug since a long time? And btw closed?
