### ISSUE TITLE
Entire message corrupted at transmission time when TO: list of recipient gets too large

### ISSUE THREAD

**Issue by michaelof** [k9mail/k-9#4609] opened 2020-03-14 22:40 UTC
### Expected behavior
K9 should be able to handle large lists of recipient in TO list. I e.g. wanted to send an email to ~30 parents of the class of my little son

### Actual behavior
TO line  "breaks" after appr. 1000 characters:
- rest of TO line is getting part of BODY
- FROM and SUBJECT are getting cut off completely!!
- result was a SMTP 5.5.0-5.7.1 as e.g. Gmail (of course) does not accept mails without a FROM.
- reproducible!

### Root cause analysis:
As K9 runs against my own OpenSuse VPS, with postfix / dovecot etc. running on it, I was able to compare:
- the K9-"sent" email, stored in ...<sender>/Maildir/.Sent/cur folder, 
- and a directly after the unsuccesful K9-transmission sent by Thuinderbird, same Sent folder 

Differences:
- K9 mail's sequence is FROM, TO, ..., vs. Thunderbird TO, FROM
- K9 puts complete TO into a single line, while Thinderbird adds a line break after each adress and idents every adress starting with the second adress by on whitespace.

These are the only differences I can see.

### Environment
K-9 Mail version:
5.600

Android version:
6.00

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment] 2020-03-15 00:09
Duplicate of #822

**Closed by cketti** 2020-03-15 00:09 UTC
