### ISSUE TITLE
Serious slowdown

### ISSUE THREAD

**Issue by pcav** [k9mail/k-9#3181] opened 2018-02-13 12:07 UTC
Unsure whether this is a k9 problem.
Since a few days most operations are very slow, several seconds to select a message etc.
Thanks for hints.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by chrisvdb** [comment] 2018-02-14 10:44
I have the same issue on MIUI 9.2.4.0 (Android 7.1.2). It's so slow that Android proposes to kill the app regularly as it's not responding (but waiting a few seconds always helps). Started happening a few days ago and I didn't have this issue before.

**Comment by atrent** [comment] 2018-02-14 11:07
In my case it's just slow in opening the imap connection

**Comment by atrent** [comment] 2018-02-14 11:08
Version 5.403

**Comment by Vachha** [comment] 2018-02-14 11:14
I am having the same issue even if the connection is over local wifi within the same LAN. The connection is so slow it can even present as a black screen that persists for a few seconds when changing IMAP folders.

Tested on:
  LG V30+  running Android V7.1.2 - K9 V5.403
  LG V20    running Android V7.0 - K9 V5.403
  LG V10   running Android V6.0 - also tested with K9 V5.5 Build #530 (10-Feb-2018 13:50:07)

The IMAP server is Dovecot V 2.2.31 running on Linux, all other IMAP clients are running smoothly, including Thunderbird and Roundcube. Nothing untoward seen in the IMAP server logs. I can forward server logs if necessary.

**Comment by pcav** [comment] 2018-02-14 17:51
Thanks, glad to see it's not only my problem. LG G6 here.

**Comment by pcav** [comment] 2018-02-14 17:53
I confirm: black screen, And wanting to kill app, etc.
Not always though, unclear what triggers it.

**Comment by matt-matt2** [comment] 2018-02-17 08:27
Never had the black screen and app not responding, but I do have serious sluggishness when swiping to select messages in a mailbox. 
Oneplus 3T here, doesn't do anything slow so this is a surprise. This started happening recently, around the time the icon changed.

**Comment by chrisvdb** [comment] 2018-02-17 08:54
On one occasion I have submitted a report to Google Play on my phone when I was prompted with 'ok/wait/report'. I hope that will help you debug the issue.

**Comment by 98c71be8** [comment] 2018-02-22 20:09
I confirm the slowdown behavior:
1. Opening a new e-mail takes dozens of seconds: sometime Android ask me to kill the unresponsive K9
2. Erasing an e-mail takes even longer - until the window gets back to the list of e-mails I see a blank screen
3. Rotating the screen while an e-mail is displayed - this really ends up with Android telling me that K9 stopped responding!

This is outrageous!

how can I go back to previous version? That one had no slowdown problems!

**Comment by chrisvdb** [comment] 2018-02-26 03:37
We don't seem to get any love from the dev team regarding this issue. I wonder how many people are affected. For me K-9 is currently not usable, so I (hopefully) temporarily switched to the built-in mail app. I will monitor this bug report in the hope to switch back to K-9 when the issue is fixed.

**Comment by Vachha** [comment] 2018-02-26 04:02
Folks,

After my last post I also noticed that my contacts and dialer were slow, and getting worse. K9 has to read contacts to display human readable names. I only use Google contacts so I deleted my contact storage data and re-synced my contacts. Presto! contacts got dramatically faster (It used to be better) and so did K9. While K9 and Dailer and Contacts are not back to their usual snappy speed but they are very useable again. Google are well known for releasing unpolished code into the wild to "see how it goes" and I have a suspicion that the K9 speed problems may well be related to contacts, especially as like me you have a large address book of approx 2,000 contacts.

**If you can safely do so**, please try to flush and reload your contacts and report your results back here. Only do it if you your contacts are synced, I do not use SIM or Phone contact storage so can't comment on that. It may shed light on this issue for the developers. 

To flush and reload your contacts :
1. In setting go to Contact Storage and delete data
2. Go to Accounts and sync and toggle Contact storage off and back on again

**Comment by cketti** [comment] 2018-02-26 04:04
The difference between 5.402 and 5.403 is super small and can't really cause any change in performance. It's much more likely that reinstalling the app "fixed" the performance issue.

**Comment by Vachha** [comment] 2018-02-26 04:09
FYI I was having the issue with 5.402 also, and had the same with K9 V5.5 Build #530, which is why I wonder if it is related to contact retrieval. I did not reinstall any app when flushing my contacts.

**Comment by Valodim** [comment] 2018-02-26 07:25
Can you check if unchecking the "show contact names" option under settings / display helps the situation?

**Comment by Vachha** [comment] 2018-02-26 07:39
Just checked the improvement was good with show "show contact names" unchecked and the improvement was dramatic with "show correspondents names" unchecked!

**Comment by pcav** [comment] 2018-02-26 07:44
In my case, `Show contact names` was unchecked. Unselecting `Show contact pictures` apparently brought back speed to normal.

**Comment by Valodim** [comment] 2018-02-26 07:58
Ugh, yeah. It appears that part of the codebase goes back to the time where pull requests were merged rather hastily. We really need to revise that, especially around the [bindView](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/fragment/MessageListAdapter.java#L142) method. As is, both of those settings are liabilities more than features.

Anyone feeling up for this? Maybe @philipwhiuk you like to rewrite things? :)

**Comment by philipwhiuk** [comment] 2018-02-26 09:11
I guess it's probably querying way too often (e.g. every render rather than every keypress or something). My phone is pretty snappy so I haven't seen a slowdown but I guess I can look at what's going on and optimise it.

**Comment by 98c71be8** [comment] 2018-02-26 12:10
Status Update  for 5.402: after activating and deactivating the bellow features a couple of times, my K9 really got frozen and had to kill the app when Android proposed:
1. Show correspondend names: ON/OF (if Off it also disable the Show Contact names option)
2. Show correspondend names: ON, and then Show Contact names Off/On
3. Show contact Pictures ON/OFF
5. Show account size ON/OFF
6. Count Search results ON/OFF


After playing a bit with variants of all above, and putting in the end all to OFF, when exiting the Display screen (where changes where performed) I ended up with a totally frozen client and had to kill the app.

Now, although I was hoping that 5.402 solved my problem, I am in the same situation like 5 days ago: app freeze when scrolling list of e-mails, or rotating screen, or opening an e-mail.

Hope it helps.

**Comment by matt-matt2** [comment] 2018-02-26 19:31
For me at least, unticking both of "show contact names" or "show contact pictures" results in a dramatic speedup. These defaults never slowed my session down until the new version came out.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by matt-matt2** [comment] 2018-03-13 19:45
I think we need to change the title of this report so that it gets more attention. It seems to me that the issue is in contacts code and that this was a bug introduced in the facelift. It's serious enough that I won't consider reenabling the folder view contacts interface until it's resolved, makes k9 run like, well, a shot dog frankly.

**Comment by matt-matt2** [comment] 2018-03-13 19:57
Fwiw I do not have a large contacts list and have no issues with performance in any other app that interacts with my contacts list. I've cleared k9 caches but can't find a method to clear down the contacts storage itself..

**Comment by chrisvdb** [comment] 2018-03-14 05:28
Yes, currently completely unusable without putting "show contact names" and "show contact pictures" off. I'm surprised this does not get more attention from the devs.

**Comment by Barkole** [comment] 2018-05-28 18:07
Sometimes K9 does not response at all. most of the time, it took several seconds for a simple UI interaction.

**Comment by Barkole** [comment] 2018-05-28 18:09
For me at least, unticking both of "show contact names" or "show contact pictures" results in a dramatic speedup. These defaults never slowed my session down until the new version came out.

**Comment by madduck** [comment] 2018-07-21 00:04
I have both unchecked on 5.403, and performance is dreadful regardless. It's generally become faster for me to open my laptop, download the message, and read it there, than to wait for K9 to display an email. And I'm not even talking about search, local or server-side.

**Comment by cketti** [comment] 2019-03-01 05:22
This should be fixed in `master`.

**Closed by cketti** 2019-03-01 05:22 UTC

**Comment by matt-matt2** [comment] 2019-03-01 15:49
Fixed by what checkin?
