### ISSUE TITLE
STARTTLS does not work after update to Android 7.0 (K9 tries to use SSLv3)

### ISSUE THREAD

**Issue by countii** [k9mail/k-9#1618] opened 2016-09-18 17:24 UTC
### Expected behavior
Fetch mail via IMAP

### Actual behavior
Connection fails with "Connection Refused"

### Details
After updating to Android 7.0, K-9 does not connect to my IMAP server anymore. It seems that K9 is trying to use SSLv3.

#### Logcat:
http://hastebin.com/nisoniwalu.hb

#### Server-Log:
http://hastebin.com/axidinefij.hb

#### Dovecot settings:
`ssl_cipher_list = ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5:!DSS`

### Environment
K-9 Mail version: 5.111 as well as latest release.

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please notice that this works in both thunderbird and gmail.

**Comment by philipwhiuk** [comment] 2016-09-19 12:55
What's the account's security setting (Settings -> Account settings -> Fetching email -> Incoming server -> Security) set to?

**Comment by countii** [comment] 2016-09-19 14:35
The error persists on both STARTTLS and SSL/TLS, I usually use STARTTLS tho

**Comment by philipwhiuk** [comment] 2016-09-19 16:21
If it's SSL/TLS then I expect the error - if you select the secure encrypted method we shouldn't try the upgrade method. So definitely STARTTLS is the one you need to use.

I don't know whether Nougat does anything to disable STARTTLS - if it does we may have to code around it to maintain this feature.

**Comment by cketti** [comment] 2016-09-20 22:10
You most likely disabled too many ciphers, so that Android and your servers couldn't find any in common and the handshake fails.

Closing this as it's most likely not a bug in K-9 Mail.
We already have issue #893 to add better error reporting on TLS errors.

**Closed by cketti** 2016-09-20 22:10 UTC

**Comment by countii** [comment] 2016-09-20 22:21
So what you're saying is K9 does (all of the sudden) not support TLSv1.X ECDHE_ECDSA?

**Comment by cketti** [comment] 2016-09-20 22:41
K-9 Mail only blacklists some ciphers but otherwise uses the TLS implementation of the OS.

Just because the log contains the string "ssl3" doesn't mean anyone is actually attempting to use the SSLv3 protocol. See e.g. http://security.stackexchange.com/questions/101965/ssl3-error-when-requesting-connection-using-tls-1-2

**Comment by cketti** [comment] 2016-09-20 22:44
Some ciphers that have been enabled before have been disabled by default on Android 7.0. See https://developer.android.com/reference/javax/net/ssl/SSLEngine.html

**Comment by countii** [comment] 2016-09-20 22:53
I don't have any disabled ciphers in my cipherlist:
`└─> nmap --script ssl-cert,ssl-enum-ciphers -p 993 [host]
[...]
993/tcp open  imaps
[...]
| ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (secp256k1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (secp256k1) - A
|     compressors: 
|       NULL
|     cipher preference: client
|     warnings: 
|       Key exchange parameters of lower strength than certificate key
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (secp256k1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (secp256k1) - A
|     compressors: 
|       NULL
|     cipher preference: client
|     warnings: 
|       Key exchange parameters of lower strength than certificate key
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (secp256k1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (secp256k1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (secp256k1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (secp256k1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (secp256k1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (secp256k1) - A
|     compressors: 
|       NULL
|     cipher preference: client
|     warnings: 
|       Key exchange parameters of lower strength than certificate key
|_  least strength: A
`
