### ISSUE TITLE
Can't choose a OpenKeychain key in account's end-to-end encryption

### ISSUE THREAD

**Issue by mlee734** [k9mail/k-9#4547] opened 2020-02-18 10:28 UTC
After some of updates I've noticed that any of my e-mails can't be decrypted even though I never had any issues before. K-9 and OpenKeychain work just fine on a standalone basis.

### Problem
I expect K-9 to let me choose my key in settings under "End-to-end encryption", but nothing happens after I tap "Configure end-to-end key". However OpenKeychain is connected under "Enable OpenPGP support".

### Steps to reproduce
1. Open K-9
2. Go to settings and choose one of accounts
3. Under "End-to-end encryption" tab try to choose one of your keys

### Environment
K-9 Mail version: 5.705 (also tried 5.502, 5.600 and 5.700)

OpenKeychain version: 5.5

Android version: Xiaomi Mi6, 9 PKQ1.190118.001

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2020-02-18 13:14
Duplicate of #3420

**Closed by cketti** 2020-02-18 13:14 UTC
