### ISSUE TITLE
Choose which folders affect unread number

### ISSUE THREAD

**Issue by ikeeki320** [k9mail/k-9#1841] opened 2016-12-07 21:11 UTC
I'm using Nova Launcher and Tesla Unread in conjuction with K9. I have folders these folders set up via Rackspace email and they are in K9 on my phone. A, B, C, and D are just folders I created and use to organize my emails, but sometimes I like to leave them unread for later viewing. However, I would like those emails in those particular four folders to not impact the unread message count. I have tried changing the folder settings so that they were 2nd Class or none in the display, sync, push, and notification class as well as changing the notification setting to 1st class folders only, but that did not help. An unread message in the Spam folder does not affect the unread badge count. Does anyone know how I can get the unread count to reflect just the unread messages in the Inbox?
Inbox
Sent
Deleted Messages
Drafts
Spam
Folder A
Folder B
Folder C
Folder D

K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP via Rackspace

**Comment by rasos** [comment] 2018-05-26 19:07
I would even go further: I would like to be able to define, which folder is triggering a notification. 

May use case is that I have one folder which is collecting messages from a chat channel, and I want only that one showing numbers of unread messages and blinking.

**Comment by cketti** [comment] 2019-02-28 21:34
Duplicate of #1266

**Closed by cketti** 2019-02-28 21:34 UTC
Labels: enhancement
