### ISSUE TITLE
Failure to receive emails

### ISSUE THREAD

**Issue by Gypsy2GS** [k9mail/k-9#2045] opened 2017-01-12 17:47 UTC
### Expected behavior
Receive emails

### Actual behavior
INBOX in FOLDERS shows message:- SSLProtocolException: SSL h
No emails loaded

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.202

Android version: 6.0.1

Account type POP3

**Comment by philipwhiuk** [comment] 2017-01-12 18:12
It's probably a sign that your mailserver either only supports SSLv3 or only supports old protocols.

**Comment by Gypsy2GS** [comment] 2017-01-12 19:58
Which means...?

**Comment by philipwhiuk** [comment] 2017-01-15 21:13
It means your email server is not supported by K-9 because it's insecure.

**Comment by Gypsy2GS** [comment] 2017-01-15 22:36
Well, that's Tiscali (TalkTalk) ... A bit difficult to believe.

**Comment by philipwhiuk** [comment] 2017-01-15 22:50
Nope, TalkTalk is actually terrible:

https://www.htbridge.com/ssl/?id=389cc9da63df8ebce8b6c9dd8673722b2ae670fb5f9a0e97305a328e78e076e1

See the list of protocols is limited to mostly limited to RSA with RC4 (very broken) and RCA with DES40 (very broken). Of the two slightly better ones I suspect your device doesn't actually implement them.

All we have done recently is to blacklist the RC4 ciphers, which is what I suspect your device was using prior to the update.

**Comment by philipwhiuk** [comment] 2017-01-15 22:51
Duplicate of #1994 (same email server too)

**Closed by philipwhiuk** 2017-01-15 22:51 UTC

**Comment by Gypsy2GS** [comment] 2017-01-16 09:04
OK, thanks for the info. Seems that NTL is alive and well. It's back to
webmail, I guess.

**Comment by philipwhiuk** [comment] 2017-01-16 10:00
I'm considering long-term the possibility of re-allowing downgrade to these insecure protocols given appropriate UI feedback. But that will only happen when I/we have implemented fixes for #1789 and #893 as part of #1818 (where I've started to concept it). I want the user to know that their email server is insecure rather than pretending all is fine.

**Comment by cketti** [comment] 2017-01-16 11:05
I'm against supporting broken servers. However, we need to get better at letting users know who's to blame.
