### ISSUE TITLE
K9 Mail lost all user configuration (again)

### ISSUE THREAD

**Issue by BitBernd** [k9mail/k-9#4088] opened 2019-06-20 07:12 UTC
### Expected behavior
K9 Mail should keep my accounts data.

### Actual behavior
K9 randomly deletes my account data.
This happened 5 times now, on a Motarola(2x), on a Nexus 5X(2x) and yesterday on my Xperia XZ1 Compact(1x).
I opened K9 and got the welcome screen, all my accounts are gone.
I suspect the data is still there, because the app still uses the same amount of memory as before.
But i cannot get the accounts back in K9.

I really like K9 but this is so annoying that I made an GitHub Account to report this.

### Steps to reproduce
1. Get K9
2. Wait long enough
3. Swuuup, your data is gone.

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type: Multiple IMAP accounts

**Comment by stephankn** [comment] 2019-06-24 06:48
I got a similar effect today with K9 5.600 on Android 9 with an imap/smtp account. The account itself was still there, but sending mail failed due to a wrong password. I did not change my password for quite long. Re-entering the password in K9 settings fixed the issue. 
But why did K9 forget about the password details in the first place?

**Comment by cketti** [comment] 2019-06-29 14:30
Duplicate of #750

**Closed by cketti** 2019-06-29 14:30 UTC

**Comment by ByteJuggler** [comment] 2019-10-01 22:40
This happened to me recently too.  Opened up K9Mail and like "wat, where's my accounts dude..."
