### ISSUE TITLE
Sign into Gmail (or other provider) browser dialogue box when adding @gmail or domain account associated with a gmail account.

### ISSUE THREAD

**Issue by Goldmaster** [k9mail/k-9#5803] opened 2021-12-02 23:30 UTC
**Is your feature request related to a problem? Please describe.**
I would really love to have the ability to sign into gmail just as easily as signing into gmail from the gmail app or how mailbox or boxer did it. Currently for those with 2fa, you have to go a create an app password then sign in that way.

Also some domain names such as those associated with google, are quite a pain to setup as you often have a different domain ending, which can cause k9 to think the email is a different provider when infact is gmail.

**Describe the solution you'd like**
A simple solution will be to load up a browser signin page, that allows the user to authenticate k9 mail with gmail or any other email provider. This will make k9 mail much easier to set up and use and reduce errors.

**Describe alternatives you've considered**
I have considered sticking to Gmail as I'm already setup and can have a sign in with gmail option.

**Additional context**
No

**Comment by cketti** [comment] 2022-01-09 07:54
Duplicate of #655

**Closed by cketti** 2022-01-09 07:54 UTC
Labels: enhancement
