### ISSUE TITLE
Text overlapped b2box on Galaxy Note 8 

### ISSUE THREAD

**Issue by Canonshooter** [k9mail/k-9#3046] opened 2018-01-05 17:16 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
The text should be visible 

### Actual behavior
Tell us what happens instead
The text is overlaid by box below the text

### Steps to reproduce
1. Open any folder 
2. Error is beside the k9 mail icon on top of screen 
3.

### Environment
K-9 Mail version:
5.402
Android version:
7.1.1
Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment] 2018-01-05 17:21
Duplicate of #3047

**Closed by cketti** 2018-01-05 17:21 UTC
