### ISSUE TITLE
Long lines are wrapped hard when a draft is opened for editing

### ISSUE THREAD

**Issue by Chris78** [k9mail/k-9#5723] opened 2021-10-06 12:03 UTC
Steps to reproduce:
* Create a new draft and enter a long line (150 characters or so)
* Save the draft and verify (for example with thunderbird) that the line is still one line, without any line-break
* Open the draft again for editing in k9mail, append another word to that line and save the draft.
* The line will have (unwanted) line-breaks now

And after a few edits+save you will have a draft with several lines, although you never entered any line-break. This is quite a mess and annoying to correct.

I also noticed, that some lines were indented by one blank after editing a draft with thunderbird. Not sure yet, how to cleanly reproduce it. Looked to me like \n\r maybe becomes \n<blank> or something like this. What contradicts this thesis is that I even saw the first line being prepended by a blank.

**Comment by cketti** [comment] 2021-10-07 12:02
Duplicate of #5702

The fix is included in [K-9 Mail 5.904](https://github.com/k9mail/k-9/releases/tag/5.904).

**Closed by cketti** 2021-10-07 12:02 UTC
