### ISSUE TITLE
Dark Mode Widget Message List

### ISSUE THREAD

**Issue by flimtag101** [k9mail/k-9#7297] opened 2023-10-26 14:36 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

Hi,
When using the Widget "K-9 Message List" to display my inbox on Android, I can only get it to display in light mode. My Android system is globally set to dark mode. Other Previous GitHub threads on this issue have been closed and linked to this thread [https://github.com/thundernest/k-9/issues/3728](https://github.com/thundernest/k-9/issues/3728). Despite this, I cannot configure Message List to be in dark mode, or find any information online on how to do this. I would prefer to use a dark mode widget since it's nicer on my eyes.

### Suggested solution

Is it possible to have a dark mode version of the K-9 Message List widget?

**Comment by cketti** [comment] 2023-10-26 17:14
> Other Previous GitHub threads on this issue have been closed and linked to this thread https://github.com/thundernest/k-9/issues/3728. Despite this, I cannot configure Message List to be in dark mode, or find any information online on how to do this.

That's because there's no point in having multiple open issues each requesting the same feature. Issue #3728 is still open. That means this functionality hasn't been implemented yet.

Duplicate of #3728

**Closed as completed by cketti** 2023-10-26 17:14 UTC
Labels: type: enhancement
