### ISSUE TITLE
Same as issue - Syncing Disabled #2135

### ISSUE THREAD

**Issue by OpenIaaS** [k9mail/k-9#3418] opened 2018-05-29 11:07 UTC
But you closes the thread and it is 2018 one year later (Issue exist on latest MUI 9.5.9 Android 7 based) ...

this make app totally unusable, and can be low tech solved by adding a timer which to push check mail button on 1-5-10-15.... minutes

**Comment by OpenIaaS** [comment] 2018-05-29 11:18
Sorry about that it works when App is set to autostart 

I got hard time when i found that stock app is moved to gmail and searching for replacement

**Comment by OpenIaaS** [comment] 2018-05-30 17:12
App do not as it do not shows in Settings > Sync menu (maybe it is incompatible with) any other app I tried and work shows there (i tired BlueMail) it shows there and works ... I'm posting this to know where to search the issue

**Comment by tvlovers** [comment] 2018-06-08 22:14
I'm using Note8 on Android 7, but your device should be similar

Try the following:
settings ->device maintenance -> battery and then:

    unmonitored apps -> add K-9 -> go back to battery sub menu
    battery usage -> 3 dots -> optimize battery usage -> change "apps not optimized" to "all apps" view -> turn K-9 off
    restart your phone

**Comment by cketti** [comment] 2019-03-08 02:23
Duplicate of #3950

**Closed by cketti** 2019-03-08 02:23 UTC
