### ISSUE TITLE
5.7 interface requests 

### ISSUE THREAD

**Issue by dannyauble** [k9mail/k-9#4300] opened 2019-11-28 01:24 UTC
Is there any way to get some features from the old version?

In particular the main screen giving you access to all your accounts instead of having to have a drop down to pick each account.

Also I miss the buttons at the bottom while reading. On bigger phones going to the top to delete is much more cumbersome.

Not having a reply all is also less than optimal. I know you can get to it through the drop down, but that is much more involved than just hitting the button as before.
Thanks!

**Comment by oni303** [comment] 2019-11-28 05:55
Most important for me would be a way to select multiple mails fast. Long press and then select is not an option. Swipe right like in the last 6+ years would be gteate.

In general a good UI design is easy and fast to work with, adding at least one press/click for each action is step in the wrong direction.
An other characteristic are short distances between ui elements often used consecutively. The upper left corner is too far for most users to reach easy. Therefore changing mail accounts became a job for both hands.

To add a positive point, the design looks a lot more modern.

**Comment by FAUguy** [comment] 2019-11-28 07:37
I've been using the 5.7 update for the past day, and there are many features from the K-9 Mail that I use.
This includes the main screen showing all the E-Mail accounts in a list, now you have to use the left tab to select E-Mail accounts (takes more time). The icon shortcuts that were on the bottom of the screen are gone, and now have to stretch to the top of the screen to get the functions. Each account no longer has its own dedicated LED Notification Color, they are all now default Blue.
Because of this, I have to remove 5.7 and go back to using 5.6 despite it keeps saying Sync Disabled for my IMAP accounts (even with 15 min Polling selected).

**Comment by nadmaga** [comment] 2019-11-28 08:46
I agree with the other posts. I like the new design better then the old one, but the usibility is not better.

One point I want to add is, that the attachments of a mail is showing only at the end of a mail. So you always have to scroll to the end of the mail to see and save the attachments. I would prefer to have a icon in the header to see that there are attachments in this mail and if you click on it you will see all attachments. Also the icon for the attachments it self is always the green andriod logo and not a document type specific logo like PDF, JPG, Word, Excel etc

**Comment by Hustensirup** [comment] 2019-11-28 11:40
In software engineering there is a rule that you must not break: usability over design!
I will also go back to the old version, if this is going to the production version I must quit using k-9.
I thought k-9 ks for professional users only, but now I think it's the opposite. I know it took many time but for what?
Sorry if it sounds rude, but I think this is the wrong way...

**Comment by ANEast** [comment] 2019-11-28 22:07
> 
> 
> I agree with the other posts. I like the new design better then the old one, but the usibility is not better.
> 
> One point I want to add is, that the attachments of a mail is showing only at the end of a mail. So you always have to scroll to the end of the mail to see and save the attachments. I would prefer to have a icon in the header to see that there are attachments in this mail and if you click on it you will see all attachments. Also the icon for the attachments it self is always the green andriod logo and not a document type specific logo like PDF, JPG, Word, Excel etc

Sadly the attachments at the bottom has been a request for years, but seems to generate hot debate.  I agree that having it at the bottom is wrong, but this thread https://github.com/k9mail/k-9/issues/2067#issuecomment-559381643 has not been commented on for a long time.  I would do this myself, but don't have the coding knowledge.

**Comment by artoriosrex** [comment] 2019-11-29 01:52
When replying, the new message window pane is only 3 lines long. 
There is over 5x as much space devoted to the quoted text pane as there is to the composition pane, which does not Auto-expand as you enter text into it (pushing the quoted text down)

**Comment by bio12** [comment] 2019-11-29 19:15
I second the "buttons at the bottom went up"-issue. This is not really meaningful, if you have a huge display.

**Comment by DavidWiesner** [comment] 2019-12-02 18:25
- I agree with @Hustensirup in his main point. UX before design. With the new release you removed more than one the half of the user stories you supported in the old version. Only some examples: Missing the unified inbox by default. Overview over all accounts in one place. Swipe gestures in list and many more details.

**Comment by FredericLeroy** [comment] 2019-12-04 07:23
I can't use the new interface. I liked to select quickly mesages and see all my mailboxes at once.
I can't see if I have new mail with the new ui. And I don't want to use unified mailbox neither.
I reverted to old version.

Do you plan to improve the new ui to have feature of the old ?

**Comment by PCigales** [comment] 2019-12-10 16:29
As I wrote in another issue report, I like the new UI and am grateful to the devs for their work, but there a few features missing in this new version:
- time remaining before next sync and sync errors are no longer shown
- the size of the local file for each account is no longer shown
- the names of the folders are no longer translated nor exapnded (for example "outbox" -> "messages envoyés" or "sent items"), there was an option for that in setting but it has been removed
- please bring back the possibility to store the local files in sdcard (the fake internal one) for backup puroposes
- for manual update outside automatic sync, one has to scroll down each folder, there should be a command to run update per account, as it was before
- it would be great to be able to select mails by scrolling them horizontally as before (switching to right to left not to interfere with the drawer, for example)
- the top right arrow when composing a mail is to close to the send icon, there is a risk that trying to save a mail as a draft, you accidentally send it while it is not finished

Thanks in advance, I think the app is on the right track.

**Comment by PCigales** [comment] 2019-12-11 09:25
I found two other issues:
- in any folder (inbox, outbox...), pressing the three dots at the top right corner opens a menu where there is a "delete" command at the bottom, but this does nothing
- the counter of unread messages of the outbox folder (not the one containing the already sent elements but the the one where mails being sent are temporarily stored) is not reset to zero after a mail is manually sent from this folder (to reproduce this bug, disconnect the phone from network, send a mail, it will remain in this outbox folder and an error notification will be shown, then reconnect the phone to the network, go to the outbox folder, press the three dots menu and then the send command: the counter of unread messages in the drawer in front of the outbox folder will remain at one until you close and reopen K9-mail, although there is no more mail in the folder).

**Comment by dannyauble** [comment] 2020-01-14 17:02
I am guessing we will not receive any traction here sadly.

**Comment by FAUguy** [comment] 2020-01-14 17:06
I'm staying with 5.6
Just wish I could get Play Store to stop showing there is an update available.

**Comment by FredericLeroy** [comment] 2020-01-14 17:10
Indeed it seems :( I saw users on french forums abandoning k9. And the day I will loose the apk, if the ui hadn't adressed these issues, I will drop it too.

Could a developer inform us on their intention for the ui ? Will they address issues or continue with this reduced ui experience ?

It is cumbersome to switch between versions to test if k9 improves.

**Comment by madduck** [comment] 2020-01-14 23:02
> I'm staying with 5.6
> Just wish I could get Play Store to stop showing there is an update available.

You could get it from F-Droid, where you can disable updates per-app.

**Comment by madduck** [comment] 2020-01-14 23:02
It looks like this will result in a fork, which is a real shame, but it's what happens if you throw your community off the boat.

**Comment by PCigales** [comment] 2020-01-14 23:28
> I'm staying with 5.6
> Just wish I could get Play Store to stop showing there is an update available.

Just unsuscribe to the beta program, I guess, as 5.7 is a pre-release, and as far as I am concerned, I don't see all related updates in Google Play Store.

> It looks like this will result in a fork, which is a real shame, but it's what happens if you throw your community off the boat.

Maybe we should not get too impatient, after all, the devs are aware that there are too many issues and regressions to release the app in its current state. Interface aside, the bugs with mails saves as draft and with the scrolling of the answer to a mail during edition are just incompatible with a everyday use of the present version.
Like you, I just hope that K9 mail will never become a project between buddies for the buddies, as K9 mail has some uncommon very useful features, such as deletion sync settings, and also because the situation is not great with alternative apps and the state of mind of their authors (just read posts on XDA about F---E---- !). So, for the time being, I just prefer to tell my gratitude to the devs of K9 mail who work for free on this project and wish everything would be back to a satisfactory condition before the public release.

**Comment by cketti** [comment] 2020-02-07 17:13
Thank you all for your feedback. The comments in this issue address a lot of different parts of the app. That makes it very hard to have a constructive discussion on how to improve the app to make it work for you (or telling you that particular use case won't be supported in the future).

We're still quite a bit away from a new stable release. Some of the features that have been removed are coming back in different forms. The open issues for the 5.800 milestone can be found here: https://github.com/k9mail/k-9/milestone/24

Most of the problems mentioned here have already been discussed in more focused issues. Please use the issue search to find them (be sure to include closed issues) and learn how they will be addressed in the future.

I'm closing this issue because it's not focused enough so we could use for planning development work.

**Closed by cketti** 2020-02-07 17:13 UTC
