### ISSUE TITLE
[Feature Request]  Ability to edit from addresses

### ISSUE THREAD

**Issue by clijunky** [k9mail/k-9#3655] opened 2018-10-09 15:36 UTC
I use many email addresses on a given domain and would like to be able to edit the from address on the fly.  

Example:  email comes in to pizzashop@mydomain.com, and is delivered to a single user (not pizzashop), but sorted by the from address.  In replying I'd like to be able to override the account from address and type my own.  

As a reference, similar functionality is available on the Thunderbird desktop mail client.

An outlier case I'm sure, but a nice feature.

Thank you.

**Comment by cketti** [comment] 2018-10-12 00:17
Duplicate of #935

**Closed by cketti** 2018-10-12 00:17 UTC
