### ISSUE TITLE
Timestamp = Sync-Time?

### ISSUE THREAD

**Issue by PunchIng** [k9mail/k-9#2638] opened 2017-07-23 09:22 UTC
Did not find an exicting issue...

### Expected behavior
On syncing mails all mails should have the date and time they were send / delivered to the server. A mail I recieve on a PC with Thunderbird has its timestamp and keeps it. That should be the same on K9: timestamps should not be altered by the client or the divice's system.

### Actual behavior
In K9 once in a while an old (and read) email - received and read a couple of days or weeks ago - pops up on top of the list sorted by date / time. It now shows the date / time of the last sync! On the PC (Thunderbird) the previous timestamp is not altered. 

### Steps to reproduce
1. No idea - cannot reproduce it
2.
3.

### Environment
K-9 Mail version: 5.206

Android version: 6.01

Account type (IMAP, POP3, WebDAV/Exchange): IMAP on strato.de

**Comment by philipwhiuk** [comment] 2017-07-25 11:13
This is generally because the format of the received time on the email is invalid.

Please provide the source of an email that is incorrectly ordered.

**Comment by mcost** [comment] 2017-07-25 14:20
I have a problem which I am not sure it is related. It has happened suddenly after upgrading K9mail a couple of releases back.

The behaviour is extremely annoying and it is putting me off K9mail altogether as it is making it unusable at least for me.

What happens is the following:

a) I send an email
b) I go into the sent folder (which hasn't been syncronized for a while)
c) The email I just sent is at the top of the sent folder (rightly so)
d) I click on the email, but I get a completely different email that was sent perhaps a few days back
e) Even if I force refresh the folder, the problem stays there, the emails are all mixed up.

**Comment by AEaut** [comment] 2017-07-30 13:13
Hello Punching,

> On the PC (Thunderbird) the previous timestamp is not altered.

But there you use POP3, right? So, that copy should be quite "conserved".

It would be interesting to know which timestamp parameter(s) of a specific, exemplarily selected affected message got overwritten by K-9.

Can you provide both the header from your pop3 downloaded copy + the header from the 'original (but suspected to be modified by k-9) copy' which is still on the server?

Perhaps one can make sharper conclusions after comparing them.

**Comment by AEaut** [comment] 2017-07-30 13:57
Hello mcost,

Does a different imap client open the same wrong messages like k-9 does?

**Comment by PunchIng** [comment] 2017-07-30 15:34
Hello AEaut,

no, it's IMAP for both clients. So the headers should be the same, altered or not, right?

I just synced the mails in K9. Here is the header of another mail that appears with the date and time of the sync (attached image: see date and time top right!).

![screenshot_20170730-162344-2](https://user-images.githubusercontent.com/30384727/28754796-3f75cf7a-754d-11e7-9db1-2547689afa5a.jpg)

In Thunderbird (IMAP) it's listed (and stays) 'correctly' with the date and time listed in the first line of the header. Following is the source code of the same mail in the PC / Thunderbird...

Any more ideas?


X-Envelope-From: <kautzsch@dommerdich-bestattungen.de>
X-Envelope-To: <a.kern@paulus-buchholz.de>
X-Delivery-Time: 1499860307
X-UID: 1960
Return-Path: <kautzsch@dommerdich-bestattungen.de>
Authentication-Results: strato.com 1;
    spf=pass
        smtp.mailfrom="kautzsch@dommerdich-bestattungen.de";
    dkim=none;
    domainkeys=none;
    dkim-adsp=none
        header.from="kautzsch@dommerdich-bestattungen.de"
X-Strato-MessageType: email
X-RZG-CLASS-ID: mi00
Received-SPF: pass
    (strato.com: domain dommerdich-bestattungen.de designates 80.67.31.27 as permitted sender)
    mechanism=ip4;
    client-ip=80.67.31.27;
    helo="smtprelay04.ispgateway.de";
    envelope-from="kautzsch@dommerdich-bestattungen.de";
    receiver=smtp.rzone.de;
    identity=mailfrom;
Received: from smtprelay04.ispgateway.de ([80.67.31.27])
    by smtp.rzone.de (RZmta 41.1 OK)
    with ESMTPS id R041c0t6CBplQMo
    (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (curve secp521r1 with 521 ECDH bits, eq. 15360 bits RSA))
    (Client did not present a certificate)
    for <a.kern@paulus-buchholz.de>;
    Wed, 12 Jul 2017 13:51:47 +0200 (CEST)
Received: from [80.147.130.127] (helo=Admin-PC)
    by smtprelay04.ispgateway.de with esmtpa (Exim 4.89)
    (envelope-from <kautzsch@dommerdich-bestattungen.de>)
    id 1dVGBG-0008O8-Px; Wed, 12 Jul 2017 13:51:47 +0200
Date: 12 Jul 2017 13:51:49
From: Denny Kautzsch | Dommerdich Bestattungen <kautzsch@dommerdich-bestattungen.de>
X-Mailer: CodeProject CSmtp/Rapid Data PowerOrdo (U), Version 2016-Nov-11
Reply-To: kautzsch@dommerdich-bestattungen.de
Disposition-Notification-To: kautzsch@dommerdich-bestattungen.de
X-Priority: 3 (Normal)
To: <a.kern@paulus-buchholz.de>
Bcc:
Subject: Trauerfallmeldung, Renate von Tschirschnitz
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="__MESSAGE__ID__54yg6f6h6y456345"
Message-Id: <E1dVGBG-0008O8-Px@smtprelay04.ispgateway.de>
X-Df-Sender: a2F1dHpzY2hAZG9tbWVyZGljaC1iZXN0YXR0dW5nZW4uZGU=

--__MESSAGE__ID__54yg6f6h6y456345
Content-type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

...

**Comment by mcost** [comment] 2017-07-30 16:04
Yes it's IMAP. 

I will try to dig out the headers. 



On 30 July 2017 16:34:56 BST, PunchIng <notifications@github.com> wrote:
>Hello AEaut,
>
>no, it's IMAP for both clients. So the headers should be the same,
>altered or not, right?
>
>I just synced the mails in K9. Here is the header of another mail that
>appears with the date and time of the sync (attached image: see date
>and time top right!).
>
>![screenshot_20170730-162344-2](https://user-images.githubusercontent.com/30384727/28754796-3f75cf7a-754d-11e7-9db1-2547689afa5a.jpg)
>
>In Thunderbird (IMAP) it's listed (and stays) 'correctly' with the date
>and time listed in the first line of the header. Following is the
>source code of the same mail in the PC / Thunderbird...
>
>Any more ideas?
>
>
>X-Envelope-From: <kautzsch@dommerdich-bestattungen.de>
>X-Envelope-To: <a.kern@paulus-buchholz.de>
>X-Delivery-Time: 1499860307
>X-UID: 1960
>Return-Path: <kautzsch@dommerdich-bestattungen.de>
>Authentication-Results: strato.com 1;
>    spf=pass
>        smtp.mailfrom="kautzsch@dommerdich-bestattungen.de";
>    dkim=none;
>    domainkeys=none;
>    dkim-adsp=none
>        header.from="kautzsch@dommerdich-bestattungen.de"
>X-Strato-MessageType: email
>X-RZG-CLASS-ID: mi00
>Received-SPF: pass
>(strato.com: domain dommerdich-bestattungen.de designates 80.67.31.27
>as permitted sender)
>    mechanism=ip4;
>    client-ip=80.67.31.27;
>    helo="smtprelay04.ispgateway.de";
>    envelope-from="kautzsch@dommerdich-bestattungen.de";
>    receiver=smtp.rzone.de;
>    identity=mailfrom;
>Received: from smtprelay04.ispgateway.de ([80.67.31.27])
>    by smtp.rzone.de (RZmta 41.1 OK)
>    with ESMTPS id R041c0t6CBplQMo
>(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (curve secp521r1
>with 521 ECDH bits, eq. 15360 bits RSA))
>    (Client did not present a certificate)
>    for <a.kern@paulus-buchholz.de>;
>    Wed, 12 Jul 2017 13:51:47 +0200 (CEST)
>Received: from [80.147.130.127] (helo=Admin-PC)
>    by smtprelay04.ispgateway.de with esmtpa (Exim 4.89)
>    (envelope-from <kautzsch@dommerdich-bestattungen.de>)
>    id 1dVGBG-0008O8-Px; Wed, 12 Jul 2017 13:51:47 +0200
>Date: 12 Jul 2017 13:51:49
>From: Denny Kautzsch | Dommerdich Bestattungen
><kautzsch@dommerdich-bestattungen.de>
>X-Mailer: CodeProject CSmtp/Rapid Data PowerOrdo (U), Version
>2016-Nov-11
>Reply-To: kautzsch@dommerdich-bestattungen.de
>Disposition-Notification-To: kautzsch@dommerdich-bestattungen.de
>X-Priority: 3 (Normal)
>To: <a.kern@paulus-buchholz.de>
>Bcc:
>Subject: Trauerfallmeldung, Renate von Tschirschnitz
>MIME-Version: 1.0
>Content-Type: multipart/mixed;
>boundary="__MESSAGE__ID__54yg6f6h6y456345"
>Message-Id: <E1dVGBG-0008O8-Px@smtprelay04.ispgateway.de>
>X-Df-Sender: a2F1dHpzY2hAZG9tbWVyZGljaC1iZXN0YXR0dW5nZW4uZGU=
>
>--__MESSAGE__ID__54yg6f6h6y456345
>Content-type: text/plain; charset=UTF-8
>Content-Transfer-Encoding: base64
>
>... 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2638#issuecomment-318909571

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AEaut** [comment] 2017-07-30 19:39
Good evening Punching,

ok, I try to order my findings in a logic way:

1) The date and time shown on the right top in each full message view is "normally" based on the data contained in the "Date:" header.

2) k-9 did not rewrite the header "Date:" in the original mail source on synchronisation, as that is still different (originally old) compared to the (recent) synchro date&time.

3) So, there must be an 'internal' copy of this header's content. Probably (to be verified by k-9 staff) this copy is already written on first contact of the client with each particular message, and used from the beginning - but in some cases re-written on syme sync events, at least on your device.

4) Sometimes, there is no "Date:" header contained in a message. In such cases, k-9 processes the Date/Time contained in the (probably newest?) "Received:" header instead.

5) It would be interesting to know, if k-9 also writes an internal copy of the (newest) "Received:" date/time on first contact with a message.

5.1) If yes, there would be 2 identical copies in case of 4).]

5.2) If yes, then it would be interesting to know, whether the re-writing-on-sync-problem also affects the received-header date/time copy, or the date-header date/time copy. You can check this by selecting "Arrival" ("Ankunftsdatum") instead of "Date" ("Datum") in the "Sort by..." menu. I would even recommend you to do so _however_, because the "Date:" header is fully controlled by the sender (his client, respectively), and this may, more likely than on your mail server, be misconfigured, which would lead to a wrong integration of the message in the chronology on your/the recipient's side.

6) As touched in 5.2), and referring to philipwhiuk's statement

> This is generally because the format of the received time on the email is invalid.

not only the date/time information may be wrong due to a misconfiguration in the sender's client, but also the syntax/format may be different. I sighted a numer of messages from various clients, and as long as the date: header (and/or the newest received: header) contained a value like

> Tue, 25 Jul 2017 20:02:42 +0000
[sometimes with "(UTC)" or "(CEST)" etc. suffix]

everything seems to work fine for my k-9, especially even on synchro events.

While I found one sample, where the date: header was missing completely, and which was no problem for k-9 as described in 4), I did not yet find a sample within my currently available messages with a date: syntax like the one provided with your sample, which was:

> 12 Jul 2017 13:51:49

Perhaps THIS was, what caused k-9 to destroy the date-header date/time copy when synchronising (needs verification by k-9 staff)? (If yes, then k-9 staff should be able to harmonise the code: since such irregular format is obviously no problem on the first contact with a message, why should it suddenly become a problem on later synchronisation events?)

7) On my kitkat, the date/time output on the right top (regardless of the source field) was in this syntax:

> 20. Juli 2017 09:30

while your sample shows a comma-character after the number of the year:

> 30. Juli 2017, 16:11

This slight difference might be a result of our different Android versions, and in that case probably irrelevant for the problem we discuss. But perhaps there is an undeniable context? To better judge it, I suggest you to compare on your k-9, if that comma appears with _all_ messages on top right, or only with those that are affected by the sync-rewriting problem.

**Comment by AEaut** [comment] 2017-07-30 19:59
Hello mcost,

the more I think about PunchIng's issue, the more I think that your issue is very different (although both issues might have to do with data overwriting in k-9's internal database, in your case perhaps affecting some message identifier or so).

But you can still check with a different imap client, if this too open the same wrong messages like your (initial) k-9 does.

At this point now, you don't need to dig out headers like PunchIng did.

**Comment by mcost** [comment] 2017-07-30 21:49
Thank you I will try and let you know. 

Much appreciated.

By the way I use kopano as the backend. 

Not sure you ever came across it (www.kopano.com). It's excellent though. It worked with K-9 mail for many many years till this year when I started experiencing these issues. 

Marco

On 30 July 2017 21:00:03 BST, AEaut <notifications@github.com> wrote:
>Hello mcost,
>
>the more I think about PunchIng's issue, the more I think that your
>issue is very different (although both issues might have to do with
>data overwriting in k-9's internal database, in your case perhaps
>affecting some message identifier or so).
>
>But you can still check with a different imap client, if this too open
>the same wrong messages like your (initial) k-9 does.
>
>At this point now, you don't need to dig out headers like PunchIng did.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2638#issuecomment-318925552

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PunchIng** [comment] 2017-07-31 07:07
Good morning AEaut,

wow, that's a lot of stuff! Thank you for explaining! So here is what I see:

In K9 ALL messages show the comma-character in the date / time line the top-right position, also in other email accounts. That should be depending on the Android version, right?

It's very confusing that the incriminated mail was NOT shown this morning BUT turned up again - with the date and time of the sync - when I had the K9 syncing the "next up to 25 mails" ("Bis zu 25 weitere abrufen"). 

In K9 the incriminated mail does not (!) show the "Received:" in the header and shows the "Date:" as "12 Jul 2017 13:61:49". Here is the same mail after the last sync:
![screenshot_20170731-085106-2](https://user-images.githubusercontent.com/30384727/28766111-4b9ec654-75ce-11e7-9389-106387cbec66.jpg)

In Thunderbird the header is showing all lines as listed in my last post. 

No more ideas on my side, I'm afraid...

Thanks anyway!

**Comment by AEaut** [comment] 2017-07-31 09:33
Hello PunchIng.

> In K9 the incriminated mail does not (!) show the "Received:" in the header 
> In Thunderbird the header is showing all lines

Well ... of course I had seen that your screenshot looked incomplete. I explained that to myself with you had snipped away some items for privacy reasons or so. And since the Date: header was there, and since the rest was contained in the full text version, I thought it was not worth discussing this. In the light of your now added information, I feel somehow ... uncertain. My personal and "user" viewpoint is, that mail headers should remain, and also shown, intact/complete at all times. Perhaps K-9 people can explain why they show (in that specific case at least) what looks like a locally cached "simplified" header instead of the full one in the message on the server.

> It's very confusing that the incriminated mail was NOT shown this morning BUT turned up again - with the date and time of the sync

So, even after K-9 had set a new (internal) timestamp on the sync yesterday (supposedly because the syntax of the date: header content string was (then) not processable (anymore) for k-9), k-9 rewrote it again?! If anybody from k-9 is reading, please clarify this.

> ALL messages show the comma-character in the date / time line the top-right position
> That should be depending on the Android version, right?

I guess so.

Could you try whether the change of "Sort by..." solve at least the inconsistent chronologic list view problem? (Acknowledging that this would, if it works so, only be a cosmetic measure to the supposed repeated internal timestamp and header and who-knows-what-else rewriting issues).

Do these problems also occur with mails sent by senders with different mainstream client products as well, or is there perhaps some "consistency" in regard to

X-Mailer: CodeProject CSmtp/Rapid Data PowerOrdo (U), Version 2016-Nov-11

(taken from the full header of your first sample)

**Comment by AEaut** [comment] 2017-07-31 21:13
welcome!

say ... the "simplified" header issue ... does that occur with all 3 identified messages visible in the last screenshot? or just with the one you have already responded (fall renate v. t.)?

**Comment by PunchIng** [comment] 2017-08-01 06:33
@philipwhiuk: Thanks, your hint helped to find the complete headers!

@AEaut: I attach a screenshot of another message from the same sender. It's probably the incorrect format of the received time on the email, as philipwhiuk wrote 7 days ago. I guess the bug is in that "Rapid Data" Software. Thats an undertakers ("Bestatter") software made in Kiel, Germany. I'll send them an email!

Thanks to you both for seeing to my problem - not many people are getting emails from undertakers, I suppose...

![screenshot_20170801-082236](https://user-images.githubusercontent.com/30384727/28812213-f40834b8-7693-11e7-88c8-fdf405ebacff.jpg)

**Comment by AEaut** [comment] 2017-08-01 06:58
@philipwhiuk 

> You won't see all the headers unless you download the complete message.

ok, this explains the particular question, while i find it pretty intransparent. if there is, say, a MB of embedded imagery, what is the point in downloading that all, while i want k-9 only to download and show the headers only. especially when i want to view the headers, then it is mostly to check the source of a message - it might contain malware or such - and JUST THEN k-9 would force me to download the complete message?

@PunchIng + @philipwhiuk 
the received: date is fine, the trigger is the date: header's content syntax. it's irregular compared to the usual syntax, but is it violating a standard? is k-9 the only client that cant't handle this syntax? even if it were a standards violation, then, why does k-9 produce a date: replacement on each sync? once would be enough, on the first contact. is it not possible to keep the first replacement?

**Comment by mcost** [comment] 2017-08-01 08:15
@ AEaut

I checked with Thunderbird and the issue isn't there...

**Comment by PunchIng** [comment] 2017-08-01 15:06
@AEaut 

The  "Rapid Data" software company looked into the issue and replaced some dll files at the sender's email software. So far the test mails show up correctly. Let's see if that closes the issue! I'll keep you posted! 

Thanks everyone for helping!

**Comment by AEaut** [comment] 2017-08-01 15:20
@PunchIng
wow. they react fast!

lets hope their product was the only one using a different date syntax than the mainstream products.

**Comment by mcost** [comment] 2017-08-01 15:52
@AEaut 

Hi, I am glad this fixes @PunchIng problems... But it won't fix mines :(

**Comment by AEaut** [comment] 2017-08-01 15:54
@mcost 

does the order of messages in the list view seem okay, and "only" the single message view that is opened after tapping one list item does not match, or is, as your last statement implies, the list order itself already out of control?

**Comment by mcost** [comment] 2017-08-01 15:56
@AEaut 

The list is OK except when I click on a message I get back another one which is also in the list but perhaps well down or that has been there for a few days.

If I force a refresh then I get messages sometimes repeated in the list (i.e. the same message appearing more than once) and the random message being brought back still occurs perhaps with a different message being brougth back.

**Comment by AEaut** [comment] 2017-08-01 16:38
> I get messages sometimes repeated in the list (i.e. the same message appearing more than once)
> The list is OK except when I click on a message

just a side note, this would definitely not be okay if i had this^^

basically,

> I click on the email, but I get a completely different email that was sent perhaps a few days back
> If I force a refresh then ... the random message being brought back still occurs perhaps with a different message being brougth back.

sounds like that the items in the lists "link" to other messages. 

unfortunately i don't know anything about how k-9 creates message identifiers on sync/refresh events, and how it gets and processes the identifier of a chosen/tapped list item.

@philipwhiuk 
any idea what @mcost can or should do? get a debuglog? or "recreate data (last resort!)"?

**Comment by mcost** [comment] 2017-08-01 16:47
Recreate data works. 

Except the problem then instantly occurs next time you append a message to that folder. 

One thing I am not sure i made clear is that the issue happens in folders where you move or append a message. 

Say you move a message from inbox to another folder which had pre existing messages, that folder will now be messed up. 

That's why the sent folder is always messed up. 

Recreate data will work only temporarily until the first message you add to that folder.. 

Thanks a lot! 

On 1 August 2017 17:38:14 BST, AEaut <notifications@github.com> wrote:
>> I get messages sometimes repeated in the list (i.e. the same message
>appearing more than once)
>> The list is OK except when I click on a message
>
>just a side note, this would definitely not be okay if i had this^^
>
>basically,
>
>> I click on the email, but I get a completely different email that was
>sent perhaps a few days back
>> If I force a refresh then ... the random message being brought back
>still occurs perhaps with a different message being brougth back.
>
>sounds like that the items in the lists "link" to other messages. 
>
>unfortunately i don't know anything about how k-9 creates message
>identifiers on sync/refresh events, and how it gets and processes the
>identifier of a chosen/tapped list item.
>
>@philipwhiuk 
>any idea what @mcost can or should do? get a debuglog? or "recreate
>data (last resort!)"?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2638#issuecomment-319426294

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AEaut** [comment] 2017-08-01 17:24
i found out already, that it is a fatal idea to put non-draft-messages into the folder for drafts. have created an issue for that, but yet no response.

i can only speculate: perhaps there's something special with sent messages, too, say, with their identifiers, so that the problem may occur once in a while (i just tried it with two regular sent messages being in the sent folder + 1 added/moved received message: can't reproduce the behaviour which u describe, even after sync. but perhaps just too few data?)


-------- Original Message --------

**Comment by mcost** [comment] 2017-08-01 17:30
What I do is the following:


a) I receive some emails in Inbox.

b) I have a folder say called "keep" which is synced with the server already

c) I move some of the inbox messages into the "keep" folder (not draft)

d) I go into the "keep" folder, and press on the messages, and the order is all messed up...



This problem did not used to occur whatsoever until a few releases of K9 mail at all. I then had a K9 mail update, say in March this year and the problem started.



Thanks!





-----Original message-----

**Comment by mcost** [comment] 2017-08-02 15:03
@AEaut 

Any help much appreciated... I am stuck.

**Comment by AEaut** [comment] 2017-08-02 17:21
@mcost 
hello marco, i have no idea by now. (no better idea than uninstalling and re-installing the app; und not using any saved configuration after re-installing.) sorry, man.

**Comment by mcost** [comment] 2017-08-02 17:24
I have done that many times already.... 

On 2 August 2017 18:21:41 BST, AEaut <notifications@github.com> wrote:
>@mcost 
>hello marco, i have no idea by now. (no better idea than uninstalling
>and re-installing the app; und not using any saved configuration after
>re-installing.) sorry, man.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/2638#issuecomment-319740018

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pgera** [comment] 2018-11-22 11:48
I'm not sure if this is the same issue or not, but I noticed something similar. I have a simple reproducer and divergence from AOSP's email client.

Test case:

- Use k-9 for a gmail account. 
- In the gmail account, import another gmail account's mails by setting up pop3. (Settings->Accounts & Imports->Check mail from other accounts)
- Once gmail starts importing the mail, all the imported mail will start appearing at the top in k-9 although the mail may be really old
- AOSP's mail client, gmail website, gmail android client, or thunderbird don't do this. They maintain the real chronological order of the mail.

**Comment by philipwhiuk** [comment] 2018-11-22 21:30
@pgera - it would be useful to get some examples of raw emails to debug this

**Comment by cketti** [comment] 2019-03-01 00:33
See #1356

**Closed by cketti** 2019-03-01 00:33 UTC
Labels: needs info

**Comment by nekohayo** [comment] 2023-09-26 17:25
I don't have a problem with the mails' timestamps "in the inbox / folder view", but I the timestamps of the _notifications_ are wrong under certain conditions; see #7200 for that.

**Comment by spacelama** [comment] 2023-12-01 01:50
One specific old email has just appeared when I imported a server into my new phone:

```
Return-path: <noreply@communityrequest.evidence.com>
Envelope-to: tim@me.org
Delivery-date: Sun, 02 Jul 2023 01:38:12 +1000
Received: from tim by fs.me.org with local (Exim 4.94.2)
    (envelope-from <noreply@communityrequest.evidence.com>)
    id 1qFcfs-00EGWP-AB
    for tim@fs.me.org; Sun, 02 Jul 2023 01:38:12 +1000
Delivered-To: me@me.org
Received: from imap.gmail.com [74.125.200.108]
    by fs.me.org with IMAP (fetchmail-6.4.16 polling imap.gmail.com account tim@me.com folder INBOX)
    for <tim@localhost> (single-drop); Sun, 02 Jul 2023 01:38:12 +1000 (AEST)
Received: by 2002:a05:7300:b389:b0:d9:bf:5e6c with SMTP id dz9csp5113537dyb;
 Sat, 1 Jul 2023 08:38:04 -0700 (PDT)
X-Google-Smtp-Source: APBJJlF5txwLNzS82iu5qJofmmVN1YTnucne5RspLkxqsCOIKRl7o1ShvtsjjR4k6SYMw96JHTqF
X-Received: by 2002:a17:902:7c82:b0:1b5:2fdf:5bd8 with SMTP id
 y2-20020a1709027c8200b001b52fdf5bd8mr4989144pll.8.1688225884432; Sat, 01 Jul
 2023 08:38:04 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1688225884; cv=none; d=google.com;
 ...
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com;
 ...
ARC-Authentication-Results: i=1; mx.google.com; dkim=pass
 ...
Received: from proxy.au.evidence.com ([20.213.232.233]) by mx.google.com with
 ESMTPS id
 k1-20020a170902760100b001b3ac2cdacasi13749880pll.553.2023.07.01.08.38.03 for
 <tim@me.com> (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384
 bits=256/256); Sat, 01 Jul 2023 08:38:04 -0700 (PDT)
Received-SPF: pass (google.com: domain of
 noreply@communityrequest.evidence.com designates 20.213.232.233 as permitted
 sender) client-ip=20.213.232.233;
Authentication-Results: mx.google.com; dkim=pass
 header.i=@communityrequest.evidence.com header.s=au1-dk-2023-04
 header.b=TcUM0zj9; spf=pass (google.com: domain of
 noreply@communityrequest.evidence.com designates 20.213.232.233 as permitted
 sender) smtp.mailfrom=noreply@communityrequest.evidence.com; dmarc=pass
 (p=NONE sp=NONE dis=NONE) header.from=evidence.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple;
Received: from zippy-worker-deploy-d4cdb877d-8trwh
 (10-60-73-50.jmx-service.utilities.svc.cluster.local [10.60.73.50]) by
 proxy.au.evidence.com (Postfix) with ESMTPS id 68E008005A for
 <tim@me.com>; Sat,  1 Jul 2023 15:38:01 +0000 (UTC)
Date: Sat, 01 Jul 2023 15:38:01 (UTC)
From: Axon <noreply@communityrequest.evidence.com>
To: tim@me.com
Message-ID: <406080264.37595.1688225881383.JavaMail.root@zippy-worker-deploy-d4cdb877d-8trwh>
Subject: Evidence share request XRD veh
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="----=_Part_37594_2036696144.1688225881383"
```

vs an email that was sorted correctly:

```
Return-Path: <someone@gmail.com>
X-Original-To: tim
Delivered-To: tim@me.org
Received: by smtp.me.org (Postfix, from userid 738)
    id 122CE20726; Tue, 28 Nov 2023 12:49:27 +1100 (AEDT)
Delivered-To: tim@me.com
Received: from imap.gmail.com [74.125.68.108]
    by smtp.rather.puzzling.org with IMAP (fetchmail-6.4.37 polling imap.gmail.com account tim@me.com folder INBOX)
    for <tim@localhost> (single-drop); Tue, 28 Nov 2023 12:49:26 +1100 (AEDT)
Received: by 2002:a05:7301:c09:b0:fb:d229:b938 with SMTP id nd9csp633357dyc;
 Mon, 27 Nov 2023 17:49:20 -0800 (PST)
X-Received: by 2002:a2e:988d:0:b0:2c7:fa6:718c with SMTP id
 b13-20020a2e988d000000b002c70fa6718cmr9263412ljj.9.1701136159884; Mon, 27 Nov
 2023 17:49:19 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1701136159; cv=none; d=google.com;
 ...
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com;
 s=arc-20160816;
 ...
ARC-Authentication-Results: i=1; mx.google.com; dkim=pass header.i=@gmail.com
 ...
Received: from mail-sor-f41.google.com (mail-sor-f41.google.com.
 [209.85.220.41]) by mx.google.com with SMTPS id
 20-20020a170906015400b00a01d4b65ad6sor3110624ejh.11.2023.11.27.17.49.19 for
 <tim.w.connors@gmail.com> (Google Transport Security); Mon, 27 Nov 2023
 17:49:19 -0800 (PST)
Received-SPF: pass (google.com: domain of rhosie81@gmail.com designates
 209.85.220.41 as permitted sender) client-ip=209.85.220.41;
Authentication-Results: mx.google.com; dkim=pass header.i=@gmail.com
 header.s=20230601 header.b=YmC0FuBy; spf=pass (google.com: domain of
 ...
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=20230601;
 ...
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=1e100.net;
 s=20230601; t=1701136159; x=1701740959;
X-Gm-Message-State: AOJu0YxwVflAvGq007ZnYzy2kbZHLkqOowolVf+WX2c1xbBKpC3N/Vrp
 ...
X-Google-Smtp-Source: AGHT+IEXDgIBiZO+CgA2va1/oimbsWZEci4yqRV4qN5jSBkYM2BY9Fc4VXYho...
X-Received: by 2002:a17:906:10ca:b0:a10:fde9:5160 with SMTP id
 ...
MIME-Version: 1.0
From: Someone <someone@gmail.com>
Date: Tue, 28 Nov 2023 12:49:06 +1100
Message-ID: <CABgQ5bhVC23XiTxin5xJzXDfsenuC3C7W1ObP4sQz_41_g+bOA@mail.gmail.com>
Subject: CHRISTMAS PARTY
To: tim@me.com
Content-Type: text/plain; charset="UTF-8"
```
