### ISSUE TITLE
Force selection of a certain alias before sending

### ISSUE THREAD

**Issue by Etim-Orb** [k9mail/k-9#5847] opened 2022-01-03 12:02 UTC
**Is your feature request related to a problem? Please describe.**

I use aliases when sending emails. If I were to forget I'm sending the email from the default alias meanwhile I want to send it from another, that could introduce some big problems like cross comtamination of adresses, confusing the recipent and sending problems.

**Describe the solution you'd like**

Create a setting that while enabled, the default or any alias for that matter would not be selected when creating an email, and the user would have to manually select the alias before sending the email.

**Describe alternatives you've considered**

**Additional context**

**Comment by cketti** [comment] 2022-01-04 00:10
Duplicate of #5782

**Closed by cketti** 2022-01-04 00:10 UTC
