### ISSUE TITLE
Notifications disappearing for new mail

### ISSUE THREAD

**Issue by evitalis** [k9mail/k-9#3809] opened 2018-12-09 16:35 UTC
### Expected behavior
Notifications should remain in the notification area and lock screen until dismissed, or mail is read.

### Actual behavior
As soon as the phone screen is turned on the lock screen notification disappears. When the phone is unlocked no notification for new mail is present in the top notification area.

I have my settings to only show the application name on the lock screen, and show notifications for new mail. Perhaps I am just missing another setting somewhere.

### Steps to reproduce
1. Receive new mail while phone screen is locked and off
2. Press power to turn on display, lock screen notification disappears
3. Unlock phone, no notification is displayed

### Environment
K-9 Mail version: 5.600

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2019-01-03 14:09
The intention is that they are currently dismissed when you open the folder the email is in I think.

We probably want to properly spec the notifications system to ensure it acts how we want.

**Comment by mhoran** [comment] 2019-01-03 14:42
I have experienced this with the app in the foreground (which seems to be a feature). However, I have also experienced this when the app is *not* in the foreground, suggesting that something else is happening. I believe I've seen this when on the home screen or some other app.

Unfortunately this isn't very easy to reproduce, and I don't have any logs to back up my experience. I have used the recent notifications widget to verify that K9 did indeed display a notification, despite clearing it before I've acknowledged it.

**Comment by tualatin** [comment] 2019-01-31 08:12
Here the same, see my command: #3890

**Comment by evitalis** [comment] 2019-02-13 12:28
Is there any chance of a workaround for this? I have now missed a handful of important emails due to the lack of proper notification.

**Comment by evitalis** [comment] 2019-02-28 19:32
#3205

**Comment by cketti** [comment] 2019-03-01 05:31
Duplicate of #3205

**Closed by cketti** 2019-03-01 05:31 UTC
Labels: enhancement
