### ISSUE TITLE
Sending messages in outbox does it twice

### ISSUE THREAD

**Issue by xuhdev** [k9mail/k-9#4527] opened 2020-02-11 01:49 UTC
### Expected behavior

The mail should be sent once after requesting sending a failed mail in the outbox.

### Actual behavior
The mail is sent twice.

### Steps to reproduce
A failed message sending due to authorization failure is put the mail in outbox. Fix the authorization issue, long press the message, tap "send again", and send. 

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment] 2020-02-11 02:01
Duplicate of #4491

**Closed by cketti** 2020-02-11 02:01 UTC
