### ISSUE TITLE
Import is unrecoverable broken

### ISSUE THREAD

**Issue by hannesa2** [k9mail/k-9#4698] opened 2020-04-26 08:46 UTC
When I import and don't specify passwords, I run into this

<img width="840" alt="image" src="https://user-images.githubusercontent.com/3314607/80302486-ad4e4780-87aa-11ea-9057-a9257815580f.png">

Then the app is unrecoverable broken

**Comment by szotsaki** [comment] 2020-04-27 09:47
Possibly a duplicate of https://github.com/k9mail/k-9/issues/4676

**Comment by cketti** [comment] 2020-05-05 13:26
Duplicate of #3691

**Closed by cketti** 2020-05-05 13:26 UTC
