### ISSUE TITLE
k9 should catch bug in OpenGLRenderer

### ISSUE THREAD

**Issue by traumschule** [k9mail/k-9#4681] opened 2020-04-21 17:09 UTC
Another instance of #4665, this time with the fresh beta. Nice layout btw!

## Expected behavior
k9 should not crash when child process bails out.

### Actual behavior
k9 crashes when mail fails to render.

### Steps to reproduce
1. Click through mails until k9 crashes

### Environment
K-9 Mail version: 5.709
Android version: 9
Account type: IMAP

```
04-21 17:34:47.041  1266  1581 I InputDispatcher: Delivering touch to (4480): action: 0x0, displayId: 0, '133cb9b', toolType: 1
04-21 17:34:47.041  4480  4480 D ViewRootImpl@36243a7[MessageList]: ViewPostIme pointer 0
04-21 17:34:47.370  1266  1581 I clp-JNI : Add pinfo) 133cb9b com.fsck.k9/com.fsck.k9.activity.MessageList (server) : AppWindowToken{5005819 token=Token{e8a5b60 ActivityRecord{34ed363 u0 com.fsck.k9/.activity.MessageList t9977}}} : 4480 : 
10186 : 1
04-21 17:34:47.371  1266  1581 I InputDispatcher: Delivering touch to (4480): action: 0x1, displayId: 0, '133cb9b', toolType: 1
04-21 17:34:47.371  4480  4480 D ViewRootImpl@36243a7[MessageList]: ViewPostIme pointer 1
04-21 17:34:48.191  1266  1581 I InputDispatcher: Delivering touch to (4480): action: 0x0, displayId: 0, '133cb9b', toolType: 1
04-21 17:34:48.191  4480  4480 D ViewRootImpl@36243a7[MessageList]: ViewPostIme pointer 0
04-21 17:34:48.258  1266  1581 I clp-JNI : Add pinfo) 133cb9b com.fsck.k9/com.fsck.k9.activity.MessageList (server) : AppWindowToken{5005819 token=Token{e8a5b60 ActivityRecord{34ed363 u0 com.fsck.k9/.activity.MessageList t9977}}} : 4480 : 
10186 : 1
04-21 17:34:48.258  1266  1581 I InputDispatcher: Delivering touch to (4480): action: 0x1, displayId: 0, '133cb9b', toolType: 1
04-21 17:34:48.258  4480  4480 D ViewRootImpl@36243a7[MessageList]: ViewPostIme pointer 1
04-21 17:34:48.316  4480  4480 D InputMethodManager: HSIFW - flag : 0 Pid : 4480
04-21 17:34:48.324  4480  4480 D ScrollView: initGoToTop
04-21 17:34:48.382  4480  4480 D MessageViewFragment: MessageView displaying message MessageReference{accountUuid='740abd79-f9a8-46b6-9428-93595d70e367', folderServerId='INBOX', uid='153473', flag=null}
04-21 17:34:48.383  4480  4480 D MessageLoaderHelper: Creating new local message loader
04-21 17:34:48.406  4480  4480 D ScrollView:  onsize change changed 
04-21 17:34:48.422  4480  4480 D InputMethodManager: prepareNavigationBarInfo() DecorView@5610d70[MessageList]
04-21 17:34:48.423  4480  4480 D InputMethodManager: getNavigationBarColor() -16777216
04-21 17:34:48.423  4480  4480 V InputMethodManager: Starting input: tba=com.fsck.k9 ic=null mNaviBarColor -16777216 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
04-21 17:34:48.423  4480  4480 D InputMethodManager: startInputInner - Id : 0
04-21 17:34:48.423  4480  4480 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-21 17:34:48.425  4480  4480 D InputTransport: Input channel constructed: fd=83
04-21 17:34:48.425  4480  4480 D InputTransport: Input channel destroyed: fd=153
04-21 17:34:48.710  4480  4480 D MessageLoaderHelper: Creating new decode message loader
04-21 17:34:48.717  4480  5605 V LockableDatabase: LockableDatabase: Transaction ended, took 10 ms / com.fsck.k9.mailstore.LocalStore.doBatchSetSelection(LocalStore.java:1030)
04-21 17:34:48.799  4480  4480 D InputMethodManager: HSIFW - flag : 0 Pid : 4480
04-21 17:34:48.833  4480  4480 D Utility : No external images.
04-21 17:34:48.948  4480  4507 E OpenGLRenderer: Font Cache (CPU):
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:   Size: 210.72 kB 
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:   Glyph Count: 52 
04-21 17:34:48.948  4480  4507 E OpenGLRenderer: CPU Caches:
04-21 17:34:48.948  4480  4507 E OpenGLRenderer: GPU Caches:
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:   Other:
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:     Buffer Object: 63.00 KB (2 entries)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:   Image:
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:     Texture: 39.22 KB (3 entries)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:          Texture( 1):       19600 Byte (count:2)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:          Texture( 2):         960 Byte (count:1)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:   Scratch:
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:     RenderTarget: 192.94 KB (28 entries)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:     Texture: 512.00 KB (1 entry)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:     Buffer Object: 64.03 KB (3 entries)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer: Other Caches:
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:                          Current / Maximum
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:   VectorDrawableAtlas    0.00 kB /   0.00 KB (entries = 0)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:   Layers Total           0.00 KB (numLayers = 0)
04-21 17:34:48.948  4480  4507 E OpenGLRenderer: Total GPU memory usage (Max: 48 MB):
04-21 17:34:48.948  4480  4507 E OpenGLRenderer:   892096 bytes, 871.19 KB (166.22 KB is purgeable)
04-21 17:34:48.949  4480  4480 W System.err: java.lang.IllegalStateException: Unable to create layer for FrameLayout, size 768x6528 max size 8192 color type 4 has context 1
04-21 17:34:48.949  4480  4480 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)
04-21 17:34:48.949  4480  4480 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:326)
04-21 17:34:48.949  4480  4480 W System.err:    at android.os.Looper.loop(Looper.java:181)
04-21 17:34:48.949  4480  4480 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7094)
04-21 17:34:48.949  4480  4480 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-21 17:34:48.949  4480  4480 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-21 17:34:48.949  4480  4480 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
04-21 17:34:48.955  4480  4480 F chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
04-21 17:34:48.956  4480  4480 F libc    : Fatal signal 5 (SIGTRAP), code 4 (TRAP_HWBKPT), fault addr 0x90f97696 in tid 4480 (com.fsck.k9), pid 4480 (com.fsck.k9)
```

Usually rendered messages appear in the log as
```
MessageLoaderHelper: Creating new decode message loader
Utility : No external images.
```
hinting where error handling could be added

**Comment by cketti** [comment] 2020-04-23 18:15
There's no need to open another issue. Duplicate of #4665

**Closed by cketti** 2020-04-23 18:15 UTC
