### ISSUE TITLE
Reordering Accounts Leaves Duplicate Entries

### ISSUE THREAD

**Issue by r4taw2mg** [k9mail/k-9#1420] opened 2016-05-31 09:01 UTC
### Expected behaviour
Reordering e-mail accounts by moving an entry up or down in the list of all account.

### Actual behaviour
An additonal entry in the list is created at the place where the account was assumed to be moved to. The very same account is also listed at its old place. Seems like both entries in the list refer to the same account because removing one also removes the other.

### Steps to reproduce
1. got to account list
2. choose "move up" or "move down" via popup menu
3.

### Environment
K-9 Mail version:
5.007

Android version:
4.2.2 (3.0.64-CM-g9c2e2bc)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment] 2016-05-31 10:28
Duplicate of #615, fixed in master and in latest unstable release.

**Closed by philipwhiuk** 2016-05-31 10:28 UTC

**Comment by r4taw2mg** [comment] 2016-06-01 08:29
Sorry, I just couldn't find out which release includes the bugfix. I just updated to K-9 v5.010 that still includes the bug (with a newly created account).

**Comment by philipwhiuk** [comment] 2016-06-01 09:05
There's no stable release for it. I'm not sure quite how @cketti determines what gets picked onto stable and what doesn't (except that obviously large features will wait for a proper major stable release)
