### ISSUE TITLE
Feature request: more folder buttons

### ISSUE THREAD

**Issue by hadmut** [k9mail/k-9#2635] opened 2017-07-20 14:44 UTC
Hi, 

K-9 has a pretty good feature, it can offer buttons in the mail message and list views to directly move a mail into the archive or spam folder. It also allows to move a mail into an arbitrary folder, but that's slow, compilacated, error prone, and annoying, if there's a long list of folders. 

Would be really useful if K-9 would offer to use more buttons like the archive button, just with different folders, to move mails immediately into the configured folders (e.g. archive, todo, office).

**Comment by steelman** [comment] 2018-01-24 20:38
Most of the time I use K-9 to read incoming mail. The most common operations I perform after selecting several messages are:
1. Mark as read (I could archive as well)
1. Delete
1. Spam
1. Leave as unread or flag to handle a message

Out of the first three Spam requires two taps in the folder view, whereas the other two are easily accessible. I don't Move nor Copy messages with K-9, I use desktop clients to do that. So there are two buttons I never use, while the two I use (Spam, Star) are hidden in the menu.

My suggestion is to make the order of the operations in the folder view fully configurable.

**Comment by cketti** [comment] 2019-03-01 00:31
Duplicate of #2406

**Closed by cketti** 2019-03-01 00:31 UTC
Labels: enhancement
