### ISSUE TITLE
Unable to connect to IMAP via SSL/TLS

### ISSUE THREAD

**Issue by miskovics** [k9mail/k-9#3280] opened 2018-03-25 08:57 UTC
### Expected behavior
During incoming mail settings validation k9mail connects to IMAP server via SSL/TLS, requests user to accept unmatching certificate, and accepts incoming mail settings.

### Actual behavior
Validation of incoming mail settings fails with "unable to connect", unclear what the problem is, no possibility to accept unmatching certificate.

### Steps to reproduce
1. Add new account
2. Configure incoming mail with SSL/TLS
3. Hit <kbd>Next</kbd>

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### Note
The same procedure DOES work using "no encryption".
The same procedure DOES work for outgoing mail using SMTP: when validating settings, confirmation dialog popped up, I accepted the certificate, and the validation succeeded.
I also imported the server's certificate into Android's personal certificate storage, did not help either.
The problem happened after the certificate was renewed on the server.
The certificate (*.domain.com) does not exactly match to the server name (mail.domain.com) in k9mail.

**Comment by philipwhiuk** [comment] 2018-04-15 23:05
Closing as duplicate of #1789

**Closed by philipwhiuk** 2018-04-15 23:05 UTC

**Comment by miskovics** [comment] 2018-04-24 17:39
This is the answer I received from the server support, might be useful, so I add it here.

> server ... no longer accept SMTP connections except if they are over TLS1.2 (TLS1.1, TLS1.0 as well as any version of SSL are no longer supported; SSL itself is obsolete and insecure and has been superseded by its replacement, TLS, which is an improvement of and development upon SSL - which should no longer be used for security reasons) and use one of the following encryption cypher / hashing algorithm sets :
> 
> ECDHE-ECDSA-AES256-GCM-SHA384
> ECDHE-RSA-AES256-GCM-SHA384
> ECDHE-ECDSA-CHACHA20-POLY1305
> ECDHE-RSA-CHACHA20-POLY1305
> ECDHE-ECDSA-AES128-GCM-SHA256
> ECDHE-RSA-AES128-GCM-SHA256
> ECDHE-ECDSA-AES256-SHA384
> ECDHE-RSA-AES256-SHA384
> ECDHE-ECDSA-AES128-SHA256
> ECDHE-RSA-AES128-SHA256
> 
> Versions of TLS older than 1.2 as well as all versions of SSL are obsolete and should no longer be considered secure or be used.
> 
> If your phone or device is running Android Nougat then the issue is with your device's operating system and whatever mail app you try to use will most likely not be able to connect to our server. This is due to Android Nougat not support elliptic curve encryption or only supporting obsolete methods of elliptic curve encryption or something along those lines.
> 
> More information on the issue with Android Nougat that's at the heart of this situation can be found at :
> 
> https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0
> 
> and
> 
> https://code.google.com/p/android/issues/detail?id=224438 .
>
