### ISSUE TITLE
Read window jumps to top when screen is rotated

### ISSUE THREAD

**Issue by koendra** [k9mail/k-9#2774] opened 2017-09-16 22:01 UTC
Hi,

When reading a mail, it happens (accidentally or not) that the phone is rotated. Ideally, the current reading position within the text should not change when changing from portrait to landscape mode or vice versa. For example, when while reading the 10th paragraph the phone is rotated, this paragraph should still be displayed after the rotation.

Unfortunately, K9 mail jumps all the way back to the top when the screen is rotated (and the display mode is changed from portrait to landscape or vice versa).
This behaviour is rather annoying because one needs to scroll down again to continue reading.

### Environment
K-9 Mail version: 5.208

**Comment by cketti** [comment] 2017-09-16 22:06
Duplicate of #1720

**Closed by cketti** 2017-09-16 22:06 UTC

**Comment by koendra** [comment] 2017-10-07 19:44
Oeps, I had searched in the issues for 'rotat', hoping it would find rotate and rotation...
