### ISSUE TITLE
Crash when no permission to attachment

### ISSUE THREAD

**Issue by gjedeer** [k9mail/k-9#1737] opened 2016-10-20 09:05 UTC
### Expected behavior
K9 displays a toast message that it can't read the attachment

### Actual behavior
K9 crashes

### Steps to reproduce
1. Try sharing a GPX track in OSMAnd
2. Pick k-9
3. Crash

This is due to a [bug in OSMAnd](https://groups.google.com/forum/#!topic/osmand/iIbByH5zUFY), but it wouldn't hurt if k-9 handled this more gracefully

### Environment
K-9 Mail version:
5.010

Android version:
4.4.4

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Crash log:
```
10-20 10:50:24.665 I/k9      (25481): Committing preference changes
10-20 10:50:24.690 I/k9      (25481): Preferences commit took 28ms
10-20 10:50:24.710 I/k9      (25481): Committing preference changes
10-20 10:50:24.715 I/k9      (25481): Preferences commit took 8ms
10-20 10:51:28.510 I/PackageManager(2311): Adding preferred activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.MessageCompose} for user 0 :
10-20 10:51:28.555 I/Timeline(27016): Timeline: Activity_launch_request id:com.fsck.k9 time:253834704
10-20 10:51:28.560 I/ActivityManager(2311): START u0 {act=android.intent.action.SEND typ=application/gpx+xml flg=0x3000001 cmp=com.fsck.k9/.activity.MessageCompose (has clip) (has extras)} from pid 27016
10-20 10:51:28.915 V/k9      (25481): /storage/sdcard1/osmand/tracks/rec/2016-02-06_17-52_sob..gpx
10-20 10:51:28.915 V/k9      (25481): new attachment.size: 692
10-20 10:51:29.125 E/AndroidRuntime(25481): Process: com.fsck.k9, PID: 25481
10-20 10:51:29.125 E/AndroidRuntime(25481): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load os-compat from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fsck.k9-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.fsck.k9-1, /vendor/lib, /system/lib]]]: findLibrary returned null
10-20 10:51:29.125 E/AndroidRuntime(25481): 	at com.fsck.k9.activity.loader.AttachmentContentLoader.loadInBackground(AttachmentContentLoader.java:58)
10-20 10:51:29.125 E/AndroidRuntime(25481): 	at com.fsck.k9.activity.loader.AttachmentContentLoader.loadInBackground(AttachmentContentLoader.java:24)
10-20 10:51:29.335 W/ActivityManager(2311):   Force finishing activity com.fsck.k9/.activity.MessageCompose
10-20 10:51:30.885 I/ActivityManager(2311): Process com.fsck.k9 (pid 25481) has died.
10-20 10:51:30.885 W/ActivityManager(2311): Scheduling restart of crashed service com.fsck.k9/.service.PushService in 1000ms
```

**Comment by philipwhiuk** [comment] 2016-10-20 09:16
This is actually caused by failing to load the os-compat library for SafeContentResolver.

Fixed in #1545

**Closed** 2016-10-20 09:17 UTC
Labels: duplicate
