### ISSUE TITLE
Failure to connect Exchange 2003 OWA

### ISSUE THREAD

**Issue by cmcarrizo** [k9mail/k-9#892] opened 2015-11-11 14:04 UTC
j7 from Samsung with 5.1 lollipop via WebDAV not think it's a customer's problem , nor OWA , from my old smartphone with android 4.4 can connect and try other WebDAV clients with the same result . From the browser I can also connect . The error is as follows:

MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit
Subject: SSLHandshakeException: Connection closed by peer
Date: Sun, 08 Nov 2015 08:07:19 -0300
From: K9mail internal 
Message-ID: 

K9-Mail version: 5.107
Device make: samsung
Device model: SM-J700M
Android version: 5.1.1

com.fsck.k9.mail.CertificateValidationException: Connection closed by peer
at com.fsck.k9.mail.store.WebDavStore.doInitialConnection(WebDavStore.java:792)
at com.fsck.k9.mail.store.WebDavStore.authenticate(WebDavStore.java:694)
at com.fsck.k9.mail.store.WebDavStore.sendRequest(WebDavStore.java:1065)
at com.fsck.k9.mail.store.WebDavStore.processRequest(WebDavStore.java:1143)
at com.fsck.k9.mail.store.WebDavStore.processRequest(WebDavStore.java:1118)
at com.fsck.k9.mail.store.WebDavStore.access$500(WebDavStore.java:58)
at com.fsck.k9.mail.store.WebDavStore$WebDavFolder.getMessageCount(WebDavStore.java:1332)
at com.fsck.k9.mail.store.WebDavStore$WebDavFolder.getMessageCount(WebDavStore.java:1346)
at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1038)
at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:113)
at com.fsck.k9.controller.MessagingController$35.run(MessagingController.java:4493)
at com.fsck.k9.controller.MessagingController.run(MessagingController.java:423)
at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLHandshakeException: Connection closed by peer
at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:623)
at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:585)
at org.apache.http.impl.io.SocketInputBuffer.(SocketInputBuffer.java:75)
at org.apache.http.impl.SocketHttpClientConnection.createSessionInputBuffer(SocketHttpClientConnection.java:88)
at org.apache.http.impl.conn.DefaultClientConnection.createSessionInputBuffer(DefaultClientConnection.java:175)
at org.apache.http.impl.SocketHttpClientConnection.bind(SocketHttpClientConnection.java:111)
at org.apache.http.impl.conn.DefaultClientConnection.openCompleted(DefaultClientConnection.java:134)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:226)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:172)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:130)
at org.apache.http.impl.client.DefaultRequestDirector.executeOriginal(DefaultRequestDirector.java:1317)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:707)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:696)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:519)
at com.fsck.k9.mail.store.WebDavStore$WebDavHttpClient.executeOverride(WebDavStore.java:2453)
at com.fsck.k9.mail.store.WebDavStore.doInitialConnection(WebDavStore.java:757)
... 12 more

**Comment by ocdtrekkie** [comment] 2015-11-11 14:11
This sounds to me like something you might see if your Exchange server still wants a very insecure connection method like SSL2/3.

**Comment by cmcarrizo** [comment] 2015-11-11 14:31
surely , it is Exchange 2003

**Comment by ocdtrekkie** [comment] 2015-11-11 15:01
@cmcarrizo Fundamentally, you shouldn't be using it.

However, if you need to make K-9 Mail work with it, you'll need to fork the app and re-enable some methods.

https://github.com/k9mail/k-9/blob/e76c489941d9bb0164541ed53425662c31e2a7bb/k9mail-library/src/main/java/com/fsck/k9/mail/ssl/DefaultTrustedSocketFactory.java

Is where you'll find the blacklisted ciphers and blacklisted protocols.

**Comment by cmcarrizo** [comment] 2015-11-11 15:13
Protocols enabled:
TLS1.0

**Comment by cmcarrizo** [comment] 2015-11-11 15:42
This would solve the problem? the server where I connect is mailsrv.provincanje.com.ar

**Comment by ocdtrekkie** [comment] 2015-11-11 18:29
A great way to see how your Exchange server is configured is to use SSLLabs, here: https://www.ssllabs.com/ssltest/analyze.html?d=mailsrv.provincanje.com.ar&hideResults=on&latest (I took the liberty of telling it not to publicly list your results.)

It looks like you can use TLS 1.0 on both your device and your server, but it looks like Android 5.x has disabled 3DES, which is what your server selects as the best choice to work with Android 5.x. So it may not be possible, even with a K-9 modification, to use Exchange Server 2003 with Android 5.x and up.

**Comment by ocdtrekkie** [comment] 2015-11-11 18:30
Also, FYI, cketti is gonna close this when he sees it because it's not a bug/issue with K-9. It's that your server is too old for your client device.

**Comment by cmcarrizo** [comment] 2015-11-11 18:34
It is what I feared , to use other clients, and previous version of android it works. Thank you very much , for confirmation . Then we will have to upgrade. He was very kind . thank you

**Comment by cketti** [comment] 2015-11-11 20:15
@ocdtrekkie: Thanks for the research.

Closing this issue because it's probably not a bug in K-9 Mail. I created issue #893 to remind us to improve the error reporting so users get a better idea of why the app is not working.

**Closed by cketti** 2015-11-11 20:15 UTC
