### ISSUE TITLE
Is this a bug of k-9 ?

### ISSUE THREAD

**Issue by Lucnsy** [k9mail/k-9#3379] opened 2018-05-09 23:50 UTC
I can't input mail address because of the bug.

[https://www.youtube.com/watch?v=fgDV0yHar4A](https://www.youtube.com/watch?v=fgDV0yHar4A)

**Comment by cketti** [comment] 2018-05-10 15:20
Duplicate of #2829

**Closed by cketti** 2018-05-10 15:20 UTC

**Comment by Lucnsy** [comment] 2018-05-10 17:58
Thanks
