### ISSUE TITLE
Support for authorization via oauth2

### ISSUE THREAD

**Issue by saber716rus** [k9mail/k-9#5948] opened 2022-03-07 20:46 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.807

### Problem you are trying to solve

Hello. The topic about authorization via the oauth2 token was raised at the forum. When will it be implemented?

### Suggested solution

If you add it, then simplify the authorization procedure.

**Comment by cketti** [comment] 2022-03-07 20:51
Duplicate of #655

**Closed by cketti** 2022-03-07 20:51 UTC
Labels: enhancement
