### ISSUE TITLE
Feature Request: Adding multiple comma separated addresses to the TO/CC/BCC-Field

### ISSUE THREAD

**Issue by francwalter** [k9mail/k-9#3680] opened 2018-10-24 08:46 UTC
Hello

at the moment I need often to add many addresses (about 40) to the TO-Field. It seems not possible to add them in one line by copy and paste. If I try to put into the TO-Field e.g.:

`<email-1@example.org>,<email-2@example.org>,...<email-n@example.org>`

I get errors that some addresses are not recognized. Seems to be too many addresses at once.
I tried also without the <>, e.g. `email-1@example.org, email-2@example.org, ...` or `"name-1" <email-1@example.org>, "name-2" <email-2@example.org>, ...` without luck.

I would appreciate a feature to add a lot of mail-addresses just by copy and paste to the TO/CC/BCC fields.
I cannot use email-groups, because most of the email-addresses are not in my addressbook.

Is this planned or could it be?
Thanks.

frank

Android 7.0 on Cubot Note Plus and k-9 Mail v5.600 using only IMAP/SMTP

**Comment by cketti** [comment] 2019-03-08 04:26
Duplicate of #2961

**Closed by cketti** 2019-03-08 04:26 UTC
