### ISSUE TITLE
Unable to view/read MIME attached forwarded emails

### ISSUE THREAD

**Issue by CapitalF** [k9mail/k-9#1264] opened 2016-04-06 03:35 UTC
Today I forwarded myself an email as an attachment, but K9Mail isn't capable of reading it.

That's right, K9Mail is an email application that can't read emails.

The email itself is just a MIME attachment. I can download the file, but the only option available to open it is gmail. Yep, I have to open the attachment with gmail because I can't read it with K9Mail, which doesn't seem to register itself as a mail application with the system.

K-9 Mail version: 5.008

Android version: Cyanogenmod 12.1

**Comment by philipwhiuk** [comment] 2016-04-06 09:07
K-9 definitely registers itself with the system for e-mail. It may not be registering itself for the specific attachment type.

And this actually seems to crash the application in the current code (with the eml file I tried), when it hits this line:

https://github.com/k9mail/k-9/blob/9ebf411d95a9cb1f6918016d982d8ca6467d1a8a/k9mail/src/main/java/com/fsck/k9/mailstore/LocalMessageExtractor.java#L529

But the bug is likely before this in the message parsing phase.

**Comment by CapitalF** [comment] 2016-04-06 09:33
Could it be that the Application/Viewer is selective in that it does not allow a file/object to be opened from the application whence the request came from?

Otherwise maybe I need a reinstall.

**Comment by philipwhiuk** [comment] 2016-04-06 22:33
Removed my comment about the crash.

We register to read and send emails. We don't register to receive files. When we handle an attachment we treat (correctly) as a file.

The MIME type of a EML file is (from an example I created) text/plain. So in order to handle this we'd have to look for all text/plain content, then try and convert into a MimeMessage and then display it.

This is an enhancement.

The bug I found is a separate issue and was because I'd encrypted the email with the attachment.

On a semi-related note K-9 doesn't support forwarding emails as attachments right now either,

**Comment by CapitalF** [comment] 2016-04-06 22:55
The system recognizes the forwarded attachment file as an email, as the two possible options to open it with are gmail and the built-in Cyanogen "mail" application. It would seem reasonable for K9Mail to also be on this list, but it isn't. Could this be changed?

I imagine that the best solution would be for K9 to display, or give the option to download/display the attached forwarded mail, but just adding K9 to the list of applications which could open the file would probably be appropriate.

I agree this is an enhancement, but given how many mails I get which are forwarded as attachments these days, it's a pretty important one for me.

**Comment by CapitalF** [comment] 2016-04-06 23:05
One final thought: Imagine my frustration as I forwarded myself an important email that I needed out in the field. Once I got to where I was going and needed to read that email, I was unable to do so using K9mail. I had to install/use another mail application to do it.

**Comment by philipwhiuk** [comment] 2016-04-06 23:07
"just adding K9 to the list of applications which could open the file would probably be appropriate."

means adding Android handling intents. It also means making the display class work with a file rather than an email from the DB.

I agree it's frustrating. None of what I've put means it won't get done and depending on how many contributors and how they prioritize stuff it'll likely get done sooner or later.

**Comment by cketti** [comment] 2016-04-06 23:55
Duplicate of #733

**Closed by cketti** 2016-04-06 23:55 UTC
Labels: enhancement
