### ISSUE TITLE
Application's crash after Gmail login

### ISSUE THREAD

**Issue by ema-pe** [k9mail/k-9#3602] opened 2018-09-08 09:54 UTC
### Expected behavior
After I entered my email and my custom generated password from Google, I should click "Next" and continue the account configuration.

### Actual behavior
When I click to "Next", the program crashes.

### Steps to reproduce
1. I suggest to use your Google account. Add new account to K9 Mail and enter email and custom password.
2. Click "Next".
3. Boom! Crash!

### Environment
K-9 Mail version: 5.403 from F-Droid

Android version: 7.1.2 (LineageOS 14.1)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

I attached the [logs](https://github.com/k9mail/k-9/files/2363204/k9-log.txt). Personal informations were removed.

UPDATE: Now the Gmail account is created and the account's box appeared on the home screen. It works now, but the crash is anyway strange.

**Comment by cketti** [comment] 2018-09-10 14:27
Looks like `Activity` crashes when restoring instance state (before any of our state restoring code runs). I checked the source code and don't see an obvious reason for why this happens. It might be a bug in the Android version you're using.

```
09-08 11:45:01.313 15089 15089 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.setup.AccountSetupBasics}: java.lang.RuntimeException: Parcel android.os.Parcel@e02e57: Unmarshalling unknown type code 2131492881 at offset 1596
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@e02e57: Unmarshalling unknown type code 2131492881 at offset 1596
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.Parcel.readValue(Parcel.java:2444)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.Parcel.readSparseArray(Parcel.java:2068)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.Parcel.readValue(Parcel.java:2422)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.BaseBundle.unparcel(BaseBundle.java:271)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2104)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.Activity.onRestoreInstanceState(Activity.java:1048)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at com.fsck.k9.activity.setup.AccountSetupBasics.onRestoreInstanceState(AccountSetupBasics.java:124)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.Activity.performRestoreInstanceState(Activity.java:1003)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1175)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2657)
09-08 11:45:01.313 15089 15089 E AndroidRuntime: 	... 9 more
```

I'm closing this issue because I can't reproduce it and it doesn't seem to be an immediate problem for the issue reporter anymore.

**Closed by cketti** 2018-09-10 14:27 UTC
