### ISSUE TITLE
Support IMAP using Outh2

### ISSUE THREAD

**Issue by elhennig** [k9mail/k-9#5071] opened 2020-12-16 10:29 UTC
Microsoft will disable basic authentication for IMAP for Office365 soon. 
In order to be able to use an Office365 account with K9 it would be great if the app could support Oauth2 as authentication type. Currently it only support Basic, Encrypted and Certificate. This would be needed for SMTP and IMAP and if possible also for POP3.
Since version 78 Thunderbird supports this feature for IMAP/POP3/SMTP

**Comment by cketti** [comment] 2020-12-16 14:37
Duplicate of #1753

**Closed by cketti** 2020-12-16 14:37 UTC
Labels: enhancement
