### ISSUE TITLE
Recipient headers (To, CC, BCC) can exceed maximum line length

### ISSUE THREAD

**Issue by evilMouse** [k9mail/k-9#2538] opened 2017-05-16 20:33 UTC
It seems that for long CC most servers do not accept messages created by K9. 

I've found two bug reports that probably pertain to the same problem - both closed without solution:
https://github.com/k9mail/k-9/issues/2153 , https://github.com/k9mail/k-9/issues/2090

Gmail returns:
209.85.233.26 failed after I sent the message.
Remote host said: 550-5.7.1 [212.77.101.11      11] Our system has detected that this message is
550-5.7.1 not RFC 5322 compliant:
550-5.7.1 'From' header is missing.

Yahoo:
98.136.216.25 failed after I sent the message.
Remote host said: 554 Message not allowed - [299]

Below is a sample header taken from mailer daemon reply. In addresses I've replaced small letters and numbers with *.
````
Return-Path: <********@**.**>
Received: (wp-smtpd smtp.wp.pl 21731 invoked from network); 9 May 2017 12:39:35 +0200
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=wp.pl; s=1024a;
          t=1494326375; bh=GxJNyNAIze0/sLcmzs809CUhriVEk0kSCgvT6Q6V+pY=;
          h=Subject:To:CC:From;
          b=ch4amAgjxkXn+UESSOnoSNjZZoFrKztgbsFVUhGx0RtrtCzePS4z124n+tBz3sgP9
           iBIlARMAKDTf7y4a3eZjBzkB/FDC2X0lPn169X1x9NWvGZwAxjTBJBVPWdVajlSD+D
           j0Ruc3Gug6pCPDfXGT+WIxpP+G6AR/VTrYjJETl4=
Received: from ******-**********.*********.** (HELO [**.***.***.*]) (********@**.**@[**.***.***.***])
          (envelope-sender <********@**.**>)
          by smtp.wp.pl (WP-SMTPD) with ECDHE-RSA-AES256-GCM-SHA384 encrypted SMTP
          for <*******@****************.**>; 9 May 2017 12:39:35 +0200
Date: Tue, 09 May 2017 12:39:23 +0200
User-Agent: K-9 Mail for Android
In-Reply-To: <********-****-****-****-************@****************.**>
References: <**************.********@**.**> <********-****-****-****-************@****************.**>
MIME-Version: 1.0
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable
Subject: =?UTF-8?Q?R*=3A_4*_-_20_***_*=C3=B3=C5=BA****_-?= =?UTF-8?Q?_****_***_*****_**=C4=99***=3A-=29?=
To: A***** <*******@****************.**>,A********* R******** <****-*****@**.**>
CC: Z***** C********** <******.***********@*****.***>,P**** G******** <*.*********@******.***>,=?UTF-8?Q?T*****_=C5=81****?= <******.****@**.**>,J**** M******* <*.********@*********.***.**>,=?UTF-8?Q?D******_=C5=BB*******?= <***@*******.***>,I**** W*********** <*****@**************.**>,******** <********@******.**>,"********.*******" <********.*******@******.**>,****** <******@****.**>,"*****.*****" <*****.*****@*******.***>,******* <*******@******.****.**>,"*.******" <*.******@***.********.**>,**** <****@*****.***.**>,************** <**************@****.**>,M***** G**** <******.*****.****@*****.***>,"******.**********" <******.**********@*****.***>,"********.*******" <********.*******@*****.***>,******** <********@*****.***>,*** <***@******.**>,"*.******" <*.******@*******.**>,***** <*****@**************.***.**>,************** <**************@*****.***>,**** <****@**.**>,************** <**************@*****.***>,********** <**********@*****.***>,"*.*********"
<*.*********@*****.***>
From: K******** G**** <********@**.**>
Message-ID: <********-****-****-****-************@**.**>
X-WP-MailID: ********************************
X-WP-AV: skaner antywirusowy Poczty Wirtualnej Polski
X-WP-SPAM: NO 000000A [ceOE]    
````
### Environment
K-9 Mail version:
5.206

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment] 2017-05-16 22:20
My guess is this is because we aren't implementing `MimeUtility.foldAndEncode` and so aren't wrapping the CC: header line properly.

**Comment by evilMouse** [comment] 2017-05-17 06:40
Can I do anything to help?

**Comment by evilMouse** [comment] 2017-05-31 22:24
Bump

**Comment by philipwhiuk** [comment] 2017-05-31 23:20
You could implement `MimeUtility.foldAndEncode`

**Comment by cketti** [comment] 2017-08-24 15:33
Duplicate of #822

**Closed by cketti** 2017-08-24 15:33 UTC
Labels: bug

**Comment by tukoz** [comment] 2018-07-20 07:41
I may be wrong but shouldn't this issue stays open while valid?

Android v 7.1.1
K-9 Mail v 5.403

```
This is the mail system at host relay2-d.mail.gandi.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<XXX@gmail.com>: host gmail-smtp-in.l.google.com[74.125.140.XXX] said:
    550-5.7.1 [217.70.183.XXX      11] Our system has detected that this
    message is 550-5.7.1 not RFC 5322 compliant: 550-5.7.1 'From' header is
    missing. 550-5.7.1 To reduce the amount of spam sent to Gmail, this message
    has been 550-5.7.1 blocked. Please visit 550-5.7.1
    https://support.google.com/mail/?p=RfcMessageNonCompliant 550 5.7.1 and
    review RFC 5322 specifications for more information. m15-v6si2847075wma.158
    - gsmtp (in reply to end of DATA command)

   [x4 gmail recipients]
```
It seems non gmail recipients accepted my email though.
