### ISSUE TITLE
Syncing disabled on Samsung Galaxy s9

### ISSUE THREAD

**Issue by madfmy** [k9mail/k-9#3547] opened 2018-08-09 13:16 UTC
My K-9 email app keeps going into a syncing disabled state.  This was not happening on my old S5 phone.  

It seemed as though if I go into App manager, K9 app, Storage and clear cache it starts up again for a little while.  However, the last time I did this it did not.  I also went into the Phone Settings Device Maintenance, Memory and hit clean now.  That also seems to get the syncing disabled removed for a little while.  

### Expected behavior
Email syncing should occur according to the settings - push and poll every 1/2 hour
Not to be required to clear cache every few hours.

### Actual behavior
Polling will occur for a while then all accounts go into a syncing disabled state. 

### Steps to reproduce
1. open K9
2. leave on for a while
3. syncing disabled
This happens frequently though I have not noticed exact time it takes to get into this state. 

### Environment
K-9 Mail version:
5.403

Android version:
8.0.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by mat-m** [comment] 2018-08-10 06:18
If you enabled data saving or battery saving, global syncing may be hung by Samsung Experience. Can you check those settings ?

**Comment by madfmy** [comment] 2018-08-14 16:01
Yes I have battery saving on.  It seems whenever I get the syncing disabled if I go into device maintenance and clean it works.  I shouldn't have to do that all the time should I?
Do you know (other than disabling the batter savings) that would fix this?

**Comment by madfmy** [comment] 2018-08-14 16:09
I looked at 3430 and yes I guess this is a duplicate - sorry, new to this kind of support.  I did try to follow the instructions there however, I cannot find the #2 instruction battery usage -> 3 dots -> optimize battery usage -> change "apps not optimized" to "all apps" view -> turn K-9 off  
I do have an option called unmonitored apps and I have K-9 in there - to stop S9 from putting K-9 to sleep.  Is that the same thing?

**Comment by madfmy** [comment] 2018-08-14 16:28
I found an option that says app power monitor, not sure if this is similar and also not sure if I should have that option turned on (it then says monitoring 33 apps to prevent excess battery usage I think this is related to the apps I marked as ok to put to sleep) or do I turn that off and then it says monitor the power usage of your apps to extend batter life.

**Comment by Mastiffen** [comment] 2018-08-27 09:45
I have a similar issue, which is why I don't open an issue myself: My S9 syncs, but it doesn't seem to obey the sync time. I have it set to sync every minute (time is very important in my job), but it doesn't sync non-push accounts like that. They are always 2-3 minutes after the mail has hit my PC. I have turned off battery optimization on my phone for K9, and as far as I know I have no data optimization.

**Comment by mat-m** [comment] 2018-09-20 22:07
@madfmy your 2nd comment of Aug, 14: Yes it is the same thing. You can't have both.
When you disable battery saver, you may need to launch the sync once in K-9 to reinitialize its state.

**Comment by mat-m** [comment] 2018-09-20 22:08
@Mastiffen  POP or IMAP account ?

**Comment by Mastiffen** [comment] 2018-09-21 06:51
I'm using POP. But I will try IMAP. Weird, because that has never been a problem before. I have had the same settings on K9 for my last 3 phones, at least, so 5-6 years.

**Comment by Mastiffen** [comment] 2018-09-23 10:03
I have tried IMAP for two days now, and it doesn't seem to matter. I still often get mail to my phone 2-3 minutes after it comes into the PC. "Always" in my first post about this was probably not accurate, I'm guessing 2/3 of the mail is later on the phone.

**Comment by mat-m** [comment] 2018-11-28 09:53
OK, so 2-3 minutes for a disconnected protocol is not crazy. If you take that your mobile provider may have a longer path to reach you and may have more security elements to go through, the delay seams reasonable to me and not related to k-9.
You can test by defining your account in the default email program and see if it is better (I guess not).

**Comment by Mastiffen** [comment] 2018-11-28 10:02
The thing is that my previous Sony Xperia X Performance synced every minute to the second, like all phones before that. This phone is almost always 2-3 minutes late. I have a job where I need to be fast to get the assignments, and this means that I am less free than before, because 2 minutes can be the difference betwen me getting the job and one of my competitors/colleagues getting it. As for trying another mail client, no thank you! ;) Oh, and it seems like GMail (which is regular imap, I believe) is getting synced every minute. So I don't understand why my other accounts (job account and two others) aren't.

**Comment by cketti** [comment] 2019-03-08 03:21
Duplicate of #3950

**Closed by cketti** 2019-03-08 03:21 UTC
