### ISSUE TITLE
Collate notifications for new mesages

### ISSUE THREAD

**Issue by sphh** [k9mail/k-9#4559] opened 2020-02-24 11:15 UTC
When I open K-9 or manually update the message list, I get a notification for every new message. This constant beeping can get quite annoying, if there are many messages. It would be great, if K-9 could just audibly notify once after the update; either one notification for each account or one notification after checking all accounts.

### Environment
K-9 Mail version: 5.705

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by lotth** [comment] 2020-05-26 20:42
I agree on that, multiple sound notification is pretty annoying. Playing the notification once whatever the number of new messages from last message check is enough.
This behavior is new in version 5.7xx. In version 5.6 I only had sound notification once.

**Comment by rezazarchi** [comment] 2021-05-22 10:27
i tested `setOnlyAlertOnce(true)` in notification builder but it still doesn't seem to work

**Comment by rezazarchi** [comment] 2021-05-24 05:36
Finally I found the cause of this issue. [setOnlyAlertOnce](https://developer.android.com/training/notify-user/build-notification#Updating) only works when update notification. we need same notificationId when show notification to update that notification. i changed notification id [here](https://github.com/k9mail/k-9/blob/18e8b31f1cc18fea778fb43aabfc0e0a622340e0/app/core/src/main/java/com/fsck/k9/notification/NewMailNotifications.java#L146) and [here](https://github.com/k9mail/k-9/blob/18e8b31f1cc18fea778fb43aabfc0e0a622340e0/app/core/src/main/java/com/fsck/k9/notification/NewMailNotifications.java#L157) to a constant number and this issue fixed. show all unread messages together grouped in one notification. (tested on Android 9 Samsung device)
but I think it had reason to set different ids for each newMail notifications. was that right solution? @cketti

**Comment by cketti** [comment] 2021-08-07 14:52
Should be fixed in 5.802.

**Closed by cketti** 2021-08-07 14:52 UTC
