### ISSUE TITLE
K9 App No Sound when email arrives

### ISSUE THREAD

**Issue by lheasycall** [k9mail/k-9#2610] opened 2017-06-29 14:49 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When email arrives, there is no sound notifications to notify the email has arrived. 

### Actual behavior
When an email arrives, it will produce the sound notification once and than any additional emails will continue to arrive but there is no more sound. 

### Steps to reproduce
1. Add a POP3 email account
2. Set Poll to Every minute
3. Go to Account Settings>New mail ringtone>set new mail ringtone
4. Settings>Global Settings>Network>Background Sync>Always

### Environment
K-9 Mail version:

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by chris-y** [comment] 2017-10-06 11:02
This appears to be affecting all notification alerts other then the visual one on screen.
Sounds, vibrate and LED alerts do not work here (well, they do but intermittently).

**Comment by nathanzachary** [comment] 2018-01-03 20:56
Not sure why, but I just started experiencing this problem recently (after the update to K-9 Mail version 5.400).  Android version 7.1.1, and IMAP accounts.

The first email will trigger the notification (sound, vibrate, LED, and on-screen), but any subsequent ones only trigger the on-screen (no sound, vibration, or LED).

**Comment by nathanzachary** [comment] 2018-01-04 03:25
It does seem to be related to Quiet Time settings (as mentioned in #2999).  I just had another example of it.  The first email that I received after Quiet Time started produced a notification.  Subsequent ones have not, though.  The same thing happened this morning when Quiet Time ended: first email caused a notification, but all others failed to trigger the notifications (except on-screen).

**Comment by cketti** [comment] 2019-03-01 00:23
Duplicate of #2999

**Closed by cketti** 2019-03-01 00:23 UTC
