### ISSUE TITLE
K9 Widget Dark Mode

### ISSUE THREAD

**Issue by semperridens** [k9mail/k-9#4409] opened 2019-12-26 20:58 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Feature: I would wish a dark mode for the K9 Mail Widget
### Actual behavior
No Dark Mode
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: current

Android version: 10

Account type (IMAP):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2020-01-02 18:30
Duplicate of #3728

**Closed by cketti** 2020-01-02 18:30 UTC
