### ISSUE TITLE
lost in trash

### ISSUE THREAD

**Issue by ajay-gh** [k9mail/k-9#4084] opened 2019-06-17 11:24 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior

I should be able to move a deleted message in the trash back to another folder or the inbox. Cannot figure out how. Neither context menu nor other commands seem to provide this feature.

### Actual behavior

feature not available

### Steps to reproduce
1. n/a
2.
3.

### Environment
K-9 Mail version: 5.600

Android version: 7.1

Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
no logs

**Comment by cketti** [comment] 2019-06-29 16:17
Duplicate of #1796

**Closed by cketti** 2019-06-29 16:17 UTC
