### ISSUE TITLE
Feature Request : Show and browse folders tree in the same way a file manager does

### ISSUE THREAD

**Issue by sebma** [k9mail/k-9#3190] opened 2018-02-19 18:39 UTC
Hi,

This is not an issue, it's a feature request.

It would be really great if we could see and browse the IMAP folders in the same way a file manager does with an UP folder to go back to the parent folder (in each subfolder).

Can you please consider this idea ?

Thanks for this application, you have done a great job so far.

**Comment by cketti** [comment] 2018-02-20 01:23
Duplicate of #630

**Closed by cketti** 2018-02-20 01:23 UTC
