### ISSUE TITLE
Bug since 5.200: Can no longer pinch-zoom in message

### ISSUE THREAD

**Issue by jmlobert** [k9mail/k-9#2029] opened 2017-01-10 16:53 UTC
### Expected behavior
Inside message that are larger than the screen, pinch-zoom in and out was easy until last update 

### Actual behavior
Pinch-zoom is no longer possible in most, but not all emails. 

### Steps to reproduce
1. Open message that is wider than screen
2. Try to pinch-zoom out
This is almost consistent, not 100%, some messages still zoom, most do not.

### Environment
K-9 Mail version: 5.200

Android version:
6.0.1, Google Nexus 5

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by KNejad** [comment] 2017-01-10 17:09
I can confirm this is also effecting me (Moto G4 Android 6.0.1) and from what i read in the ratings page of the app it is also affecting many otger people

**Comment by Valodim** [comment] 2017-01-10 17:10
Duplicate of #1908. Please do check if an issue already exists before reporting.

**Closed by Valodim** 2017-01-10 17:10 UTC
