### ISSUE TITLE
Yahoo folders produced 2 Trash folders on completed set up.

### ISSUE THREAD

**Issue by vanisle** [k9mail/k-9#2667] opened 2017-08-06 20:09 UTC
I set up K9
All 4 email populated fine except the 2 - yahoo.ca has 2 Trash folders. Both will show deleted email counts and both will in time clear trash..one at a time.
How do I remove second folder as it does glitch when emptying trash.

**Comment by Petrovic555** [comment] 2017-08-08 10:10
Same problem here!
I was making a new issue with this title "Importing 6 accounts with settings.k9s result in one having 2 Trash Folders", but than I read in the template "check for an existing issue". So here I am!

I changed phones; so exporting settings on the old one and importing on the new one.
The settings.k9s contained 6 mail accounts. After import all six seem to be in working order, but one has 2 trashboxes!

![screenshot_20170808-111234](https://user-images.githubusercontent.com/18037598/29066217-d5201552-7c2e-11e7-87be-9b5b35331a82.png)

I've noticed this behaviour also on my old phone (some time ago after a factory reset and importing the k9s-settings-file).

To check if there was a fault in the settings.k9s file, this is what I did:
1) I've extracted each of the six account.
2) And compared the whole lot.
The differences did not explain (at least to me they did not) the 2 trashboxes.
The differences were few and "expainable". Like lines with:  "account uuid", "<name>", "<username>", "chipColor", "ledColor" and "<email>". So nothing strange here.

Because the double-trashfolders were in the first/upper account, I editted the settings.k9s file and re-arranged the order of the mail accounts in it (<account through </account>).
Much to my surprise (after re-installing k9 and importing again) it's again the first/upper account. By the way, the order of accounts is still the same. I think k9 does a sort; there was a confirmation popup with all 6 accounts and - if I remember correctly - this popup was the same in both my import-runs.
The only "strange" thing (and perhaps worthwhile mentioning) about the first/upper account is that it contains an underscore ("<name>firstname_lastname"</name>.

I hope I've supplied enough information for the programmers to debug&solve this issue.
Please contact me personally to get the mentioned settings.k9s file (it's full of personal-info, so I won't be uploading it).

Kinds regards,
Peter, a happy K9 user.

**Comment by cketti** [comment] 2017-08-08 12:10
Duplicate of #1220

**Closed by cketti** 2017-08-08 12:10 UTC
