### ISSUE TITLE
Server Autoconfiguration like Thunderbird

### ISSUE THREAD

**Issue by EpeR1** [k9mail/k-9#5705] opened 2021-09-29 15:15 UTC
Please add XML/http based autoconfiguration feature for incoming and outgoing server.
Like Thunderbird autoconfiguration, or Outlook autodiscover protocol.

Mostly I'm interest in self hosted mode autoconfiguration requests for example:
 http://autoconfig.example.com/mail/config-v1.1.xml?emailaddress=fred@example.com

More info on:
https://wiki.mozilla.org/Thunderbird:Autoconfiguration
https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat
https://autoconfig.thunderbird.net/v1.1/

**Comment by cketti** [comment] 2021-09-29 15:17
Duplicate of #865

**Closed by cketti** 2021-09-29 15:17 UTC
Labels: enhancement

**Comment by EpeR1** [comment] 2021-09-29 18:32
Okay, duplicated, 
but Is the "self hosted" version of XML configuration file  planned to implement/support?

**Comment by cketti** [comment] 2021-09-30 11:48
> Is the "self hosted" version of XML configuration file planned to implement/support?

Sure, I consider this to be part of #865
