### ISSUE TITLE
Filter of incoming messages

### ISSUE THREAD

**Issue by hitam4450** [k9mail/k-9#1763] opened 2016-10-29 11:08 UTC
Hi, 

as recommended by a close friend, being a longtime user of k9mail, I installed the app and currently I am exploring all the possibilities! However, I did not find any option to create filter for incoming messages, being routed into different folders. Is this option missing or hidden somewhere ??

Regards, hitam4450

**Comment by philipwhiuk** [comment] 2016-11-01 11:43
Not currently supported - K-9 like most mobile clients assumes server side filtering currently.

Duplicate of #908

**Closed by philipwhiuk** 2016-11-01 11:43 UTC

**Comment by wwp** [comment] 2016-11-01 11:53
Server-side filtering might be popular for some IMAP servers, they're not at all (or almost? I know no example) used for POP or mixed POP-IMAP ones. Here in France at least, I know no provider who allows server-side filtering but spam filtering (and they're not good at it, the service is definitely not reliable).
Anyway, all major MUA allow filtering, and it's not for fun.

**Comment by philipwhiuk** [comment] 2016-11-01 12:15
> Anyway, all major MUA allow filtering

Desktop applications implementing filtering is a very different case to mobile applications. 

Filtering can be quite processor intensive if you're talking about running a long list of rules against each message. This isn't conducive to good battery life. So it's never been a priority for mobile apps.

In addition, using a mobile client has always been in addition to a desktop client. So maintaining two sets of filters has never been appealing to most people.

Certainly the major mobile MUAs do not implement filters except where they are modifying server side filters.

But you are right, server side filtering is not any better.

POP doesn't support folders so can't support much in the way of filters.

Server side filters are not standardised at all:

* My server uses maildrop filter rules on receiving mail. Hand editing a text file on the server is not an amazing UX though :(
* SIEVE exists but isn't widely deployed.
* Gmail implements an IMAP extension, X-GM-LABELS to orgaise messages. The Gmail app can't create filters for them though.
* Yahoo's filters are [only modifiable via a desktop client](https://help.yahoo.com/kb/SLN26408.html)
* Microsoft's EWS API supports [creating Inbox rules](https://msdn.microsoft.com/en-us/library/office/ff597938(v=exchg.80).aspx) via the EWS API. We don't yet implement EWS at all though.

**Comment by Sobuj53** [comment] 2017-03-27 14:57
It may be a battery hog but I think it's a necessary evil. For me, I'd love to waste some battery for this option. Also most of the smart phone are now shiped with high capacity battery that's why I think the developer may rethink this opinion. The filter doesn't have to as much extensive like MS Outlook but only sender base filtering will do the trick. To be honest I think this option can make this app much more user friendly. But that's just me and I'm sure there are other user who'll agree with me.
