### ISSUE TITLE
How to create a message filter ?

### ISSUE THREAD

**Issue by stemy2** [k9mail/k-9#3126] opened 2018-01-23 11:20 UTC
Hello,

I'm using my own mail server, and the main disavantage is that my mailbox is permanently saturated by messages from cron. I'd like to create a filter to move those messages to other folder, but the app seems not have this functionality, i searched for 5 minutes without finding anything like that.

So here is my question: is it possible to create message filters ? If it is, how ?

Thanks.

**Comment by violoncelloch** [comment] 2018-01-23 12:52
If you use your own server the best solution is to create filter rules on there...

**Comment by njeyaakili** [comment] 2018-01-23 13:12
I agree, all automated mail filtering (spam, delivery changes etc.) is best done on the MDA/LDA - that way all MUAs get a consistent view automatically, and without the potential costs of doing this through a mobile device's client.

And ... if you own the server a quick and dirty solution is to set up a special account for all "root-type" messages and adjust the scripts/aliases file entry to get everything delivered there rather than your personal inbox. Then set up the new account in your MUAs (K-9, etc.) so you can get them easily.

**Comment by philipwhiuk** [comment] 2018-01-23 13:33
Closing as duplicate of #908

**Closed by philipwhiuk** 2018-01-23 13:33 UTC
