### ISSUE TITLE
Emails to be delivered as signed & encrypted aren't shown as being signed when received

### ISSUE THREAD

**Issue by JasperWeiss** [k9mail/k-9#1230] opened 2016-03-30 08:35 UTC
### Expected behaviour
Mails sent by K-9 as signed and encrypted should be marked as signed and encrypted when received.

### Actual behaviour
E-mail is only marked as encrypted.

### Steps to reproduce
1. Set-up OpenKeychain
2. Send email from account to the same account with Sign & Encrypt set 
3. Open email received in Inbox

### Environment
K-9 Mail version: 5.108

Android version: 
* ??
* 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
* ??
* IMAP

**Comment by philipwhiuk** [comment] 2016-03-30 09:08
Yup :(

**Comment by adqm** [comment] 2016-03-30 11:15
To me, this looks like an issue with the _detection_ of whether the mail is signed or not.  Looking at the same message in K-9 and Mutt (sent from the latest alpha build of K-9), Mutt recognizes it as signed with a valid signature, but K-9 says it isn't signed.

So to me it looks like the signing is actually happening fine, but K-9 just isn't recognizing that the e-mail is signed.

**Comment by Valodim** [comment] 2016-03-30 12:39
The simple issue here is that receiving pgp/mime support does not yet recognize rfc 1847 encapsulated format ([click](https://tools.ietf.org/html/rfc3156#section-6.1)). This is not a bug, it's simply not implemented yet.

For the future: "Doesn't work" with zero extra information is not a useful bug report. We have the template for a reason.

**Comment by JasperWeiss** [comment] 2016-03-30 15:06
Android version: Cyanogenmod 13.0 Nightly, Android 6.0.1

**Comment by Valodim** [comment] 2016-04-18 14:55
closing as duplicate of #576

**Closed by Valodim** 2016-04-18 14:55 UTC
Labels: enhancement
