### ISSUE TITLE
Add the possibility to set a BBC Address to send the mails when unsing an Identity

### ISSUE THREAD

**Issue by agaengel** [k9mail/k-9#4365] opened 2019-12-13 11:44 UTC
When sending an emails via an Identity I want so set an BCC adress that recives all Mails send via this identity

**Comment by cketti** [comment] 2019-12-13 11:56
Duplicate of #1648

**Closed by cketti** 2019-12-13 11:56 UTC

**Comment by agaengel** [comment] 2019-12-13 11:58
sorry I missed this when searching for open issues
