### ISSUE TITLE
please do NOT use 'translated' folder names

### ISSUE THREAD

**Issue by computersalat** [k9mail/k-9#3449] opened 2018-06-16 09:55 UTC
### Expected behavior
The default folder names for important folders should be
 - Drafts
 - Sent
 - Junk
 - Trash

when you add a new IMAP postbox.

### Actual behavior
Currently you are using the **translated** name, which is e.g. for **German**
 - Entwürfe
 - Gesendet
 - Spam
 - Papierkorb

am pretty sure that when you are using a different language than DE or EN, e.g. FR than the folder names would be used in the French translation.
This is annoying to change those folder names every time when adding a IMAP account ...
It is OK to use the **translation** in the **Description** of the folder name usage, e.g.
```
Ordner für Entwürfe
Drafts
```

### Steps to reproduce
1. setup K-9 with different language (Do NOT use English)
2. setup IMAP account
3. check folder names

### Environment
K-9 Mail version: any version

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2019-03-08 02:49
Fixed in `master`

**Closed by cketti** 2019-03-08 02:49 UTC

**Comment by computersalat** [comment] 2020-02-26 21:21
obviously the `fix` is `broken` again cause translation are still used
K-9 Mail: 5.600

**Comment by cketti** [comment] 2020-02-26 21:46
There hasn't been a stable release since my comment. You can check out recent beta versions ("pre-release"), though. https://github.com/k9mail/k-9/releases

**Comment by PCigales** [comment] 2021-02-18 11:05
Good afternoon,

In the latest release of K9-mail (v5.730), folder names are no longer translated, as in v5.76, even when associated.
For example, "outbox" remains as it is after it has been tied with the folder containing sent mails in the account settings. In French, it should be translated to "envoyés" or as in v5.76, be followed by "(envoyés)".

Thanks.

**Comment by cketti** [comment] 2021-02-18 11:18
K-9 Mail uses the names of the folders on the server. The only exception is the Inbox, which will be translated. "Outbox" is a special local folder that contains emails that still need to be sent by K-9 Mail. That folder name is translated as well.

All other folder names are displayed as they are named on the server. If you don't like the name, you'll have to rename the folder on the server. K-9 Mail currently doesn't support renaming folders, so you'll have to do it using another client and then refresh the folder list in K-9 Mail.

**Comment by PCigales** [comment] 2021-02-18 11:52
Thank you for your answer, and your work. A lot of progress has been made since last time I tried the beta release, and the app is now functional in production usage.
Turning off associated folder name translation a bit of regression compared to v5.76, but nothing too disturbing.
If I rename folders on the imap server, it will break other clients, like Outlook on Windows and the webmail of the service provider, and some of them cannot be customized in the same way K9-mail does.
"Outbox" refers to already sent mails on the imap server, and is not translated. The mails still to be sent are in "boîte d'envoi" that could be translated to "sending box".
