### ISSUE TITLE
Impossible to edit recipient addresses

### ISSUE THREAD

**Issue by gwollman** [k9mail/k-9#2162] opened 2017-02-01 00:16 UTC
### Expected behavior
There should be some way to edit the recipient email address short of deleting and retyping the entire thing.

### Actual behavior
There is no obvious touch or sequence of touches to make the address editable.  The delete button on the softkeyboard is active but deletes the entire address (and in any case there is no way to move point to the position where deletion or insertion is required).

### Steps to reproduce
1. Reply to a message from an RT queue.
2. Try to figure out how to append or remove "-comment" from the local-part of the queue's address.
3. Get frustrated and give up on responding to that ticket in K-9.

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2017-02-06 03:46
Duplicate of #1925

**Closed by cketti** 2017-02-06 03:46 UTC
