### ISSUE TITLE
"Delete" button notification issue

### ISSUE THREAD

**Issue by carbsk** [k9mail/k-9#1001] opened 2016-01-06 15:52 UTC
Hi,

I'm using your email app and it's great, but now I'm having an issue with it, I just change my cell phone importing settings from old one (moto g 3) to this new (galaxy note 5), the issue is that in notifications some times show the "delete" button and some times not, when appear is with some email account and with others no.

I'm sending a couple of screen shots so you can see issue, I don't know, probably I'm doing something wrong. 

Thanks.
Greetings

**Comment by lbdroid** [comment] 2016-01-06 16:01
This appears to be a duplicate of https://github.com/k9mail/k-9/issues/943

**Comment by carbsk** [comment] 2016-01-06 16:17
Hi, yes it's the same issue.

Thanks.

**Closed** 2016-01-07 02:31 UTC
