### ISSUE TITLE
Full mail source view

### ISSUE THREAD

**Issue by ViggiMarco** [k9mail/k-9#5007] opened 2020-10-14 06:31 UTC
Hi, to sunbmit spam to services like spamcop, it is necessary to provide full source of spam message, all message, not only headres. Could be possibile to make an option to show it? Thank you.

**Comment by cketti** [comment] 2020-10-14 14:09
Duplicate of #1018

For your particular use case you could maybe use the "forward as attachment" action. This will include the original message as `message/rfc822` part in the forwarded message.

**Closed by cketti** 2020-10-14 14:09 UTC
Labels: enhancement

**Comment by ViggiMarco** [comment] 2020-10-17 06:28
But, forwarding many spam message results impossible because the mail... contains spam. There would be a system to download the message, to change its extension or compress it with password, and also to examinate the content fully.
I can't even forward it to myself...
