### ISSUE TITLE
add ability to compose html messages

### ISSUE THREAD

**Issue by alexanderdd** [k9mail/k-9#3560] opened 2018-08-17 21:30 UTC
### Expected behavior
I want to send a message with a numbered list and a few words in bold. I tap "new message" and find a bar with some basic formatting options. In settings, compose mode can be set to text or html. (Just like it already is with read mode)

### Actual behavior
I can only compose text mail, not html mail.

### Comments
I am surprised that nobody already asked for this (or did I not find it?). I found this https://github.com/k9mail/k-9/issues/1397 but it's a different topic.

I am trying to move away from gmail, and for me this is a necessary feature. Anybody else?

### Environment
K-9 Mail version: 5.403

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): irrelevant

**Comment by cketti** [comment] 2019-03-08 03:27
Duplicate of #1745

**Closed by cketti** 2019-03-08 03:27 UTC
