### ISSUE TITLE
All settings deleted without warning

### ISSUE THREAD

**Issue by ygoe** [k9mail/k-9#4136] opened 2019-07-31 08:16 UTC
Today I found K-9 mail with no accounts at all on my device. There were 3 accounts set up for the past few years. Never had any issues with that. I was wondering why I'm not getting any notifications on my smartwatch anymore so I opened the app on the phone. It suggested me to import settings or continue creating an account.

This thing has just forgotten **everything**! How can that be? Was there a broken update recently that just messed everything up? How can I get my settings back? It will take a lot of time to set it up again properly.

### Environment
K-9 Mail version: Unknown, the information is currently not accessible. Latest version from Google Play store.

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): 3x IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
Inaccessible, also does not apply because the error is not reproducible.

**Comment by cketti** [comment] 2019-08-03 20:00
Duplicate of #750

**Closed by cketti** 2019-08-03 20:00 UTC
