### ISSUE TITLE
no longer stretches/shrinks email

### ISSUE THREAD

**Issue by naturat** [k9mail/k-9#1975] opened 2017-01-05 04:16 UTC
### Expected behavior
when using 2 fingers I should be able to zoom in/out of emails or being able to pan around an email in order to read it better

### Actual behavior
Nothing happens.  This was working fine and yesterday new k9 patch was installed which broke it.

### Steps to reproduce
1. Open email
2. use finger on screen to pan - nothing happens.
3. use 2 fingers on screen to zoom in/out - nothing happens.

### Environment
K-9 Mail version:
5.201

Android version: 
6.0.1
Samsung S6 (SM-G920V)

Account type (IMAP, POP3, WebDAV/Exchange):
pop3

**Comment by N-ik05** [comment] 2017-01-05 08:40
I think this is a duplicate of https://github.com/k9mail/k-9/issues/1908
, although I don't see any problems with panning.

**Closed** 2017-01-05 08:50 UTC
