### ISSUE TITLE
ability to move messages stored locally.

### ISSUE THREAD

**Issue by ericblack44** [k9mail/k-9#2631] opened 2017-07-19 00:47 UTC
Would love to be able to move messages between the trash and other folders.

I've been using k9 for as long as I can remember but tired of having to constantly look in the trash for messages that get deleted (ALL TOO EASILY...RELOCATE BUTTONS)

**Comment by Zero3K** [comment] 2017-07-19 14:43
I agree with your suggestion.

**Comment by Zero3K** [comment] 2017-07-20 14:37
To move a message, press and hold your thumb on it until the actions box pops up. Then tap Move and choose the destination folder.

**Comment by scherr1** [comment] 2017-07-29 15:39
I can't even add folders so I tried to move something as suggested in this thread. Long press doez not bring up move as an option.  So, 2 things. How do I add a folder and why is my long press not bringing up move. 
Also why does email disappear after several days?

**Comment by shaolinux** [comment] 2018-06-25 01:54
Hi,

First thing, thanks for developing such a great app!
I know this feature has been requested a number of times already.

Here's what I'd like to be able to do:
I use POP to fetch my email.
I choose not to delete an email on the server when I delete it from the app.
(But I would like the feature implemented even if it was deleted on the server)
Could there please be a feature to undelete _locally_, or even better, to move _locally_ (within K-9 Mail only) any email I want to any folder I want ?

I'm sure many people would appreciate to do so, as it is possible in numerous email clients.
Cheers!

**Comment by cketti** [comment] 2019-03-01 00:30
Duplicate of #1796

**Closed by cketti** 2019-03-01 00:30 UTC
